import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";
import { parseLenderAsk } from "../ask-lender/parse";
import { normalizedPublishedStatePath } from "../seo/published-state-path";
import { NEW_MEXICO_SNAPSHOT as nm } from "./snapshot";

function dataRows(path: string): string[] {
  return readFileSync(path, "utf8").trim().split(/\r?\n/).slice(1);
}

test("New Mexico slice rows stay unsummed and are not a license census", () => {
  const counties = dataRows(nm.hmda.countyMarketSource);
  const bernalillo = counties.map((line) => line.split(",")).find((cols) => cols[3] === "Bernalillo");
  assert.equal(counties.length, 18);
  assert.equal(new Set(counties.map((line) => line.split(",")[2])).size, 18);
  assert.equal(Number(bernalillo?.[5]), 14288);
  assert.equal(nm.hmda.countyMarketRows, 18);
  assert.equal(nm.hmda.allNewMexicoCounties, 33);
  assert.equal(nm.hmda.countyMarketRowsAreAllCounties, false);
  assert.equal(nm.hmda.majorMarketSliceIsStatewide, false);
  assert.equal(dataRows(nm.hmda.lenderCountyActivitySource).length, 2556);
  assert.equal(dataRows(nm.hmda.leiSummarySource).length, 513);
  assert.equal(dataRows(nm.hmda.highConfidenceMappingSource).length, 146);
  assert.equal(nm.hmda.leiRowsAreLicenses, false);
  assert.equal(nm.hmda.mappingsAreLicenses, false);
  assert.equal(nm.hmda.largestPrintedCountyOriginations, 14288);
  assert.equal(nm.hmda.countyOriginationsAddedToStatewide, false);
  assert.equal(nm.hmda.statewideAcceptedAggregate, "NOT_ACQUIRED");
  assert.equal(nm.hmda.sliceSubstitutedForStatewide, false);
  assert.equal(nm.mortgage.companyRoster, "NOT_ACQUIRED");
  assert.equal(nm.mortgage.branchRoster, "NOT_ACQUIRED");
  assert.equal(nm.mortgage.originatorRoster, "NOT_ACQUIRED");
  assert.equal(nm.mortgage.lenderBrokerServicerSplit, "NOT_ACQUIRED");
  assert.equal(nm.mortgage.missingBulkIsZero, false);
  assert.equal(nm.mortgage.misspelledHostIsCensus, false);
  assert.equal(nm.otherFidRosters.blendedIntoMortgageCounts, false);
  assert.equal(nm.notAcquired.fdicInstitutionRecount, "NOT_RECOUNTED");
  assert.equal(nm.banksAreMortgageLicenses, false);
  assert.equal(nm.complaintIsViolation, false);
  assert.equal(nm.notAcquired.enforcementOrders, "NOT_ACQUIRED");
  assert.equal(nm.notAcquired.complaints, "NOT_ACQUIRED");
  assert.equal(nm.nameOnlyAdverseJoins, 0);
  assert.equal(nm.newCanonicalOrganizations, 0);
  assert.equal(nm.graphWrites, 0);
  assert.equal(existsSync(nm.fdicFile), true);
  assert.equal(nm.sources.strategicPlanSha256, "f9c46a8c7933ebcda106de2059cddf6c40c76d8c7310d0ed4293f969d33242b1");
});

test("New Mexico page does not invent a statewide total or a city route", () => {
  const page = readFileSync("app/new-mexico/page.tsx", "utf8");
  const sitemap = readFileSync("app/sitemap.ts", "utf8");
  assert.match(page, /NOT_ACQUIRED/);
  assert.match(page, /NOT_RECOUNTED/);
  assert.match(page, /14,288/);
  assert.match(page, /Bernalillo/);
  assert.match(page, /2,556/);
  assert.match(page, /nmlsconsumeracess\.org/);
  assert.match(page, /https:\/\/www\.nmlsconsumeraccess\.org\//);
  assert.match(page, /NMSA 58-21B/);
  assert.match(page, /does not rank/);
  assert.match(page, /not a substitute/);
  assert.doesNotMatch(page, /href="https?:\/\/(?:www\.)?nmlsconsumeracess\.org/);
  assert.doesNotMatch(page, /71,931|71931|16,000|16000/);
  assert.doesNotMatch(page, /AggregateRating|Trust Score|ratingValue/);
  assert.equal(existsSync("app/new-mexico/albuquerque"), false);
  assert.equal(existsSync("app/new-mexico/santa-fe"), false);
  assert.equal((sitemap.match(/path: '\/new-mexico'/g) ?? []).length, 1);
  assert.equal(normalizedPublishedStatePath("/New-Mexico"), "/new-mexico");
  assert.equal(normalizedPublishedStatePath("/new-mexico/albuquerque"), null);
});

test("New Mexico Ask keeps rankings ahead of a name search and does not read bare nm", () => {
  const rank = parseLenderAsk("best Rocket Mortgage company in New Mexico");
  assert.equal(rank.mode, "fail_closed");
  assert.equal(rank.failClosedKind, "nm-ranking");
  assert.equal("identityQuery" in rank ? rank.identityQuery : undefined, undefined);
  assert.equal(parseLenderAsk("best mortgage lender in nm").failClosedKind, "nm-ranking");
  const companies = parseLenderAsk("how many mortgage loan companies in New Mexico");
  assert.match(companies.failReason ?? "", /NOT_ACQUIRED/);
  assert.match(companies.failReason ?? "", /not zero/);
  const originators = parseLenderAsk("mortgage loan originators in New Mexico");
  assert.match(originators.failReason ?? "", /NOT_ACQUIRED/);
  assert.match(originators.failReason ?? "", /person/);
  const branches = parseLenderAsk("mortgage company branches in nm");
  assert.equal(branches.failClosedKind, "nm-branches");
  const split = parseLenderAsk("how many mortgage brokers versus servicers in New Mexico");
  assert.match(split.failReason ?? "", /NOT_ACQUIRED/);
  const smallLoan = parseLenderAsk("small loan companies in New Mexico");
  assert.match(smallLoan.failReason ?? "", /not mortgage/);
  const banks = parseLenderAsk("how many FDIC banks in New Mexico");
  assert.match(banks.failReason ?? "", /NOT_RECOUNTED/);
  const complaints = parseLenderAsk("complaints in New Mexico");
  assert.match(complaints.failReason ?? "", /not a violation/);
  const orders = parseLenderAsk("enforcement orders in New Mexico");
  assert.match(orders.failReason ?? "", /NOT_ACQUIRED/);
  const city = parseLenderAsk("how many licensed mortgage lenders in Albuquerque");
  assert.match(city.failReason ?? "", /geography only/);
  const discovery = parseLenderAsk("mortgage companies Albuquerque New Mexico");
  assert.equal(discovery.mode, "entity");
  assert.equal(discovery.geography?.state, "NM");
  const inNm = parseLenderAsk("mortgage companies in nm");
  assert.equal(inNm.mode, "entity");
  assert.equal(inNm.geography?.state, "NM");
  const bare = parseLenderAsk("mortgage companies nm");
  assert.notEqual(bare.geography?.state, "NM");
  assert.equal(String(bare.failClosedKind ?? "").startsWith("nm-"), false);
  const bareUpper = parseLenderAsk("mortgage companies NM");
  assert.notEqual(bareUpper.geography?.state, "NM");
  const apps = parseLenderAsk("How many mortgage applications in New Mexico?");
  assert.equal(apps.mode, "count");
  assert.equal(String(apps.failClosedKind ?? "").startsWith("nm-"), false);
  const utah = parseLenderAsk("mortgage lenders in Utah");
  assert.equal(String(utah.failClosedKind ?? "").startsWith("nm-"), false);
  const oklahoma = parseLenderAsk("mortgage companies in ok");
  assert.equal(oklahoma.failClosedKind, "ok-mortgage-not-acquired");
});
