/** NM-LEND-001. Mortgage bulk rosters were not acquired. The owned HMDA file is an 18-county slice, not a statewide census. */
export const NEW_MEXICO_SNAPSHOT = {
  contract: "lender-nm-state-intel-v1",
  path: "/new-mexico",
  generatedAt: "2026-10-06T18:40:00Z",
  retrievedAt: "2026-10-06",
  regulator: "New Mexico Regulation and Licensing Department, Financial Institutions Division",
  sources: {
    division: "https://www.rld.nm.gov/financial-institutions/",
    mortgageIndustry: "https://www.rld.nm.gov/financial-institutions/who-we-regulate/mortgage-industry/",
    onlineServices: "https://www.rld.nm.gov/about-us/public-information-hub/online-services-old-page/",
    observedMisspelledHost: "nmlsconsumeracess.org",
    nmlsConsumerAccess: "https://www.nmlsconsumeraccess.org/",
    strategicPlan: "https://www.rld.nm.gov/wp-content/uploads/2025/12/NMRLD-2026-StrategicPlan-Final.pdf",
    strategicPlanSha256: "f9c46a8c7933ebcda106de2059cddf6c40c76d8c7310d0ed4293f969d33242b1",
    strategicPlanRetrieved: "2026-10-06",
    mortgageLoanCompanyAct: "NMSA 58-21",
    mortgageLoanOriginatorLicensingAct: "NMSA 58-21B",
  },
  mortgage: {
    companyRoster: "NOT_ACQUIRED",
    branchRoster: "NOT_ACQUIRED",
    originatorRoster: "NOT_ACQUIRED",
    lenderBrokerServicerSplit: "NOT_ACQUIRED",
    nmlsBulkRoster: "NOT_ACQUIRED",
    bulkPath: "NMLS Consumer Access search only",
    missingBulkIsZero: false,
    misspelledHostIsCensus: false,
  },
  otherFidRosters: {
    stateCharteredBanks: "NOT_ACQUIRED",
    creditUnions: "NOT_ACQUIRED",
    smallLoanCompanies: "NOT_ACQUIRED",
    collectionAgencies: "NOT_ACQUIRED",
    escrowCompanies: "NOT_ACQUIRED",
    endowedCareCemeteries: "NOT_ACQUIRED",
    moneyServices: "NOT_ACQUIRED",
    blendedIntoMortgageCounts: false,
  },
  hmda: {
    year: 2025,
    ownedSlice: "data/hmda/new-mexico/",
    countyMarketSource: "data/hmda/new-mexico/county_market_summary_nm.csv",
    countyMarketRows: 18,
    allNewMexicoCounties: 33,
    countyMarketRowsAreAllCounties: false,
    majorMarketSliceIsStatewide: false,
    lenderCountyActivitySource: "data/hmda/new-mexico/lender_activity_by_county_nm.csv",
    lenderCountyActivityRows: 2556,
    leiSummarySource: "data/hmda/new-mexico/lender_state_summary_nm.csv",
    leiSummaryRows: 513,
    leiRowsAreLicenses: false,
    highConfidenceMappingSource: "data/hmda/new-mexico/lei_to_nmls_mapping.csv",
    highConfidenceMappings: 146,
    mappingsAreLicenses: false,
    largestPrintedCounty: "Bernalillo",
    largestPrintedCountyOriginations: 14288,
    countyOriginationsAddedToStatewide: false,
    statewideAcceptedAggregate: "NOT_ACQUIRED",
    sliceSubstitutedForStatewide: false,
  },
  notAcquired: {
    enforcementOrders: "NOT_ACQUIRED",
    complaints: "NOT_ACQUIRED",
    fdicInstitutionRecount: "NOT_RECOUNTED",
  },
  fdicFile: "lib/fdic/data/new-mexico.json",
  banksAreMortgageLicenses: false,
  complaintIsViolation: false,
  newCanonicalOrganizations: 0,
  graphWrites: 0,
  claimEligibilityChanges: 0,
  nameOnlyAdverseJoins: 0,
} as const;
