export const WEST_VIRGINIA_LENDER_SNAPSHOT = {
  regulator: "West Virginia Division of Financial Institutions",
  commissionerNamedOnReport: "Dawn E. Holstein",
  reportTitle: "124th Annual Report of Financial Institutions",
  reportUrl: "https://dfi.wv.gov/media/15/download?inline",
  indexUrl: "https://dfi.wv.gov/about-us/annual-report-summary",
  filename: "WVDFI Annual Report FY25 FINAL notarized.pdf",
  authority: "W. Va. Code §31A-2-12",
  fiscalYearEnding: "2025-06-30",
  httpLastModified: "Thu, 03 Sep 2026 14:44:11 GMT",
  httpDate: "Tue, 06 Oct 2026 19:06:40 GMT",
  retrievedAt: "2026-10-06",
  bytes: 6124848,
  sha256: "A64CA096D1919E9836DF3579B03905D49F6E92359E012013BEB5A7B7FE22AE87",
  textLayer: "NONE_SCANNED",
  licensedMortgageCompanies: {
    heading: "WEST VIRGINIA LICENSED MORTGAGE COMPANIES",
    printedPages: "20-31",
    namedRows: 475,
    sourcePrintedTotal: null,
    rowCountIsPageObservation: true,
    lenderBrokerServicerSplit: "NOT_SEPARATED",
    listedOfficeStateIsASeparatePopulation: false,
    nmlsIdPrinted: false,
  },
  examinations: {
    label: "Mortgage Lender/Broker/Servicer Examinations & Visitations",
    fy2024: 15,
    fy2025: 11,
    isLicenseCount: false,
    allClassTotalFy2024: 70,
    allClassTotalFy2025: 67,
    allClassTotalIsMortgageLicenses: false,
  },
  notAcquired: {
    mortgageLoanOriginatorRoster: "NOT_ACQUIRED",
    separateBrokerRoster: "NOT_ACQUIRED",
    separateServicerRoster: "NOT_ACQUIRED",
    branchRoster: "NOT_ACQUIRED",
    nmlsConsumerAccessBulkRoster: "NOT_ACQUIRED",
    stateCharteredBankRowCount: "NOT_ACQUIRED",
    moneyTransmitterRoster: "NOT_ACQUIRED",
    regulatedConsumerLenderRoster: "NOT_ACQUIRED",
    fdicInstitutionRecount: "NOT_RECOUNTED",
  },
  hmda: {
    productSlice: "data/hmda/west-virginia/",
    vintage: 2025,
    countyMarketRows: 21,
    lenderCountyActivity: 2081,
    leiStateSummaries: 470,
    highConfidenceLeiMaps: 141,
    majorMarketsWithNames: 18,
    reloaded: false,
    isLicensing: false,
    acceptedStatewideAggregate: "NOT_ACQUIRED",
    countyMarketSource: "data/hmda/west-virginia/county_market_summary_wv.csv",
    lenderCountyActivitySource: "data/hmda/west-virginia/lender_activity_by_county_wv.csv",
    leiSummarySource: "data/hmda/west-virginia/lender_state_summary_wv.csv",
    highConfidenceMappingSource: "data/hmda/west-virginia/lei_to_nmls_mapping.csv",
  },
  fdicFile: "lib/fdic/data/west-virginia.json",
  graphWrites: 0,
  nameOnlyAdverseJoins: 0,
  newCanonicalOrganizations: 0,
  aggregateRating: null,
  trustScore: null,
} as const;
