import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";
import { executeAskQuery } from "../ask-lender/execute-query";
import { parseLenderAsk } from "../ask-lender/parse";
import { AR_COMPANY_LICENSES, AR_MLO_STATUSES, ARKANSAS_SNAPSHOT as ar } from "./snapshot";
import { normalizedPublishedStatePath } from "../seo/published-state-path";

test("Arkansas company, branch, person, and HMDA grains stay separate", () => {
  const csv = readFileSync(ar.hmda.source, "utf8").trim().split(/\r?\n/);
  const keys = csv[0]!.split(",");
  const records = csv.slice(1).map((line) => Object.fromEntries(line.split(",").map((value, index) => [keys[index], value])));
  const sum = (key: string) => records.reduce((total, row) => total + Number(row[key]), 0);
  assert.equal(records.length, 75);
  assert.equal(new Set(records.map((row) => row.county_fips)).size, 75);
  assert.equal(sum("total_applications"), ar.hmda.applications);
  assert.equal(sum("total_originations"), ar.hmda.originations);
  assert.equal(sum("denial_count"), ar.hmda.denials);
  assert.equal(sum("purchase_count"), ar.hmda.purchase);
  assert.equal(sum("refinance_count"), ar.hmda.refinance);
  assert.equal(sum("purpose_other_count"), ar.hmda.otherPurpose);
  assert.equal(sum("apps_conventional"), ar.hmda.conventional);
  assert.equal(sum("apps_fha"), ar.hmda.fha);
  assert.equal(sum("apps_va"), ar.hmda.va);
  assert.equal(sum("apps_usda_other"), ar.hmda.usdaOther);
  assert.equal(ar.hmda.purchase + ar.hmda.refinance + ar.hmda.otherPurpose, ar.hmda.applications);
  assert.equal(ar.hmda.conventional + ar.hmda.fha + ar.hmda.va + ar.hmda.usdaOther + ar.hmda.otherLoanType, ar.hmda.applications);
  assert.equal(Math.round((ar.hmda.denials / ar.hmda.applications) * 10000) / 100, ar.hmda.denialApplicationPct);
  assert.equal(readFileSync(ar.hmda.leiSummarySource, "utf8").trim().split(/\r?\n/).length - 1, 674);
  assert.equal(readFileSync(ar.hmda.majorMarketSliceSource, "utf8").trim().split(/\r?\n/).length - 1, 19);
  assert.equal(ar.hmda.leiRowsAreLicenses, false);
  assert.equal(ar.hmda.majorMarketSliceIsStatewide, false);
  assert.equal(AR_COMPANY_LICENSES.reduce((total, row) => total + row.rows, 0), ar.companies.rows);
  assert.equal(ar.companies.rows, ar.companies.companyIds);
  assert.equal(ar.companies.licenseStatusApproved, 683);
  assert.equal(ar.companies.officeStateIsLicenseCount, false);
  assert.equal(ar.branches.rows, 1536);
  assert.equal(ar.branches.areCompanies, false);
  assert.equal(ar.branches.licenseStatusColumn, null);
  assert.equal(AR_MLO_STATUSES.reduce((total, row) => total + row.persons, 0), ar.mortgageLoanOfficers.rows);
  assert.equal(ar.mortgageLoanOfficers.areCompanies, false);
  assert.equal(ar.mortgageLoanOfficers.sponsoringCompanyIdsAreCompanyCensus, false);
  assert.equal(ar.populationsAreAdded, false);
  assert.equal(ar.companies.rows + ar.branches.rows + ar.mortgageLoanOfficers.rows === 13458, true);
  assert.equal(ar.notAcquired.enforcementOrders, "NOT_ACQUIRED");
  assert.equal(ar.notAcquired.controlPersons, "NOT_ACQUIRED");
  assert.equal(ar.notAcquired.stateBankCharters, "NOT_ACQUIRED");
  assert.equal(ar.nameOnlyAdverseJoins, 0);
  assert.equal(ar.newCanonicalOrganizations, 0);
  assert.equal(ar.graphWrites, 0);
});

test("Arkansas page does not add the three populations or invent a city route", () => {
  const page = readFileSync("app/arkansas/page.tsx", "utf8");
  const sitemap = readFileSync("app/sitemap.ts", "utf8");
  assert.match(page, /683/);
  assert.match(page, /1,536/);
  assert.match(page, /11,239/);
  assert.match(page, /116,797/);
  assert.match(page, /NOT_ACQUIRED/);
  assert.match(page, /does not rank/);
  assert.match(page, /not a company/);
  assert.doesNotMatch(page, /13,458|13458/);
  assert.doesNotMatch(page, /AggregateRating|Trust Score|ratingValue/);
  assert.equal(existsSync("app/arkansas/little-rock"), false);
  assert.equal(existsSync("app/arkansas/fayetteville"), false);
  assert.equal(existsSync("app/arkansas/pulaski"), false);
  assert.equal((sitemap.match(/path: '\/arkansas'/g) ?? []).length, 1);
});

test("Arkansas Ask keeps classes, persons, branches, and HMDA apart", () => {
  const hmda = executeAskQuery({ q: "How many mortgage applications in Arkansas?" });
  assert.equal(hmda.countEvidence?.value, 116797);
  const companies = parseLenderAsk("how many mortgage companies in Arkansas");
  assert.match(companies.failReason ?? "", /683/);
  assert.match(companies.failReason ?? "", /not added/);
  assert.equal(companies.count ?? null, null);
  const brokers = parseLenderAsk("Arkansas mortgage broker license");
  assert.match(brokers.failReason ?? "", /188/);
  assert.match(brokers.failReason ?? "", /Combination/);
  const bankers = parseLenderAsk("Arkansas mortgage banker license");
  assert.match(bankers.failReason ?? "", /7/);
  const servicers = parseLenderAsk("Arkansas mortgage servicer license");
  assert.match(servicers.failReason ?? "", /44/);
  const combination = parseLenderAsk("Arkansas combination mortgage banker-broker-servicer");
  assert.match(combination.failReason ?? "", /444/);
  const branches = parseLenderAsk("mortgage branches in Arkansas");
  assert.match(branches.failReason ?? "", /1,536/);
  assert.match(branches.failReason ?? "", /not a company/);
  const officers = parseLenderAsk("mortgage loan officers in Arkansas");
  assert.match(officers.failReason ?? "", /11,239/);
  assert.match(officers.failReason ?? "", /Persons/);
  const rank = parseLenderAsk("best mortgage lender in Arkansas");
  assert.match(rank.failReason ?? "", /does not rank/);
  const city = parseLenderAsk("mortgage lender Little Rock");
  assert.match(city.failReason ?? "", /geography only/);
  const token = parseLenderAsk("mortgage companies in ar");
  assert.equal(token.failClosedKind, "ar-companies");
  const arizona = parseLenderAsk("mortgage companies in Arizona");
  assert.equal(String(arizona.failClosedKind ?? "").startsWith("ar-"), false);
  const missouri = parseLenderAsk("mortgage brokers in Missouri");
  assert.equal(String(missouri.failClosedKind ?? "").startsWith("ar-"), false);
  const mississippi = parseLenderAsk("how many mortgage lenders in Mississippi");
  assert.equal(mississippi.failClosedKind, "ms-mortgage-mixed");
  assert.equal(normalizedPublishedStatePath("/Arkansas"), "/arkansas");
  assert.equal(normalizedPublishedStatePath("/arkansas/little-rock"), null);
});
