/** AR-LEND-001. Company, branch, and mortgage-loan-officer sheets stay separate. */
export const AR_COMPANY_LICENSES = [
  { licenseName: "AR Combination Mortgage Banker-Broker-Servicer License", rows: 444 },
  { licenseName: "AR Mortgage Broker License", rows: 188 },
  { licenseName: "AR Mortgage Servicer License", rows: 44 },
  { licenseName: "AR Mortgage Banker License", rows: 7 },
] as const;

export const AR_MLO_STATUSES = [
  { status: "Approved", persons: 9888 },
  { status: "Approved - Inactive", persons: 1350 },
  { status: "Approved - Conditional", persons: 1 },
] as const;

export const ARKANSAS_SNAPSHOT = {
  contract: "lender-ar-state-intel-v1",
  path: "/arkansas",
  generatedAt: "2026-10-06T16:30:00Z",
  retrievedAt: "2026-10-06",
  regulator: "Arkansas Securities Department",
  sources: {
    nmlsPage: "https://securities.arkansas.gov/loans/nmls/",
    workbook: "https://securities.arkansas.gov/wp-content/uploads/2026/09/Licensed-Mortgage-Companies-Branches-MLOs.xls",
    workbookSha256: "65f05e45cb9436dc4dac155eb7cc0c16bb8a56047ee690dcb30379cd6b65358e",
    workbookBytes: 2062336,
    workbookLastModified: "2026-09-29T21:32:44Z",
    pageLabel: "as of September 1, 2026",
    pageModified: "2026-09-29T21:41:29Z",
    nmlsConsumerAccess: "https://nmlsconsumeraccess.org/",
    statute: "Arkansas Fair Mortgage Lending Act",
  },
  companies: {
    clock: "2026-09-01",
    rows: 683,
    companyIds: 683,
    licenseStatusApproved: 683,
    otherStatuses: 0,
    officeStateArkansas: 33,
    officeStateIsLicenseCount: false,
    classesAreOneLenderCensus: false,
  },
  branches: {
    clock: "2026-09-01",
    rows: 1536,
    branchIds: 1536,
    companyIds: 268,
    streetStateArkansas: 120,
    streetStateIsBranchCount: false,
    licenseNameRepeatsCompanyClass: true,
    licenseStatusColumn: null,
    areCompanies: false,
  },
  mortgageLoanOfficers: {
    clock: "2026-09-01",
    rows: 11239,
    individualIds: 11239,
    licenseName: "AR Mortgage Loan Officer License",
    sponsoringCompanyIds: 619,
    sponsoringCompanyIdsAreCompanyCensus: false,
    areCompanies: false,
    namesPublished: false,
  },
  notAcquired: {
    controlPersons: "NOT_ACQUIRED",
    enforcementOrders: "NOT_ACQUIRED",
    complaints: "NOT_ACQUIRED",
    stateBankCharters: "NOT_ACQUIRED",
    moneyServices: "NOT_ACQUIRED",
  },
  hmda: {
    year: 2025,
    acceptedSource: "lib/home-intel/accepted-snapshot.json",
    acceptedGrain: "2025 jurisdiction aggregate already used by Ask",
    applications: 114072,
    originations: 66394,
    denials: 20091,
    denialApplicationPct: 17.61,
    countyFile: "data/hmda/by-state/AR/county_market_summary.csv",
    countyFileApplications: 116797,
    countyFileOriginations: 66394,
    countyFileDenials: 21095,
    countyFileReplacesAccepted: false,
    counties: 75,
    leiSummarySource: "data/hmda/by-state/AR/lender_state_summary.csv",
    leiSummaryRows: 674,
    leiRowsAreLicenses: false,
    majorMarketSliceSource: "data/hmda/arkansas/county_market_summary_ar.csv",
    majorMarketSliceRows: 19,
    majorMarketSliceIsStatewide: false,
  },
  populationsAreAdded: false,
  newCanonicalOrganizations: 0,
  graphWrites: 0,
  claimEligibilityChanges: 0,
  exactCanonicalAttachments: 0,
  nameOnlyAdverseJoins: 0,
} as const;
