import assert from "node:assert/strict";
import test from "node:test";
import { existsSync, readFileSync } from "node:fs";
import { SC_LENDER_SNAPSHOT as sc, SC_MORTGAGE_ROSTER } from "./snapshot";
import { parseLenderAsk } from "@/lib/ask-lender/parse";
import { normalizedPublishedStatePath } from "@/lib/seo/published-state-path";

test("South Carolina lender/servicer rows stay one license class", () => {
  assert.equal(SC_MORTGAGE_ROSTER.length, 564);
  assert.equal(sc.licensing.licenseRows, 564);
  assert.equal(sc.licensing.distinctCompanyIds, 564);
  assert.equal(sc.licensing.approvedRows, 562);
  assert.equal(sc.licensing.approvedDeficientRows, 2);
  assert.equal(sc.licensing.lenderCount, null);
  assert.equal(sc.licensing.servicerCount, null);
  assert.equal(sc.licensing.brokerRows, null);
  assert.equal(sc.licensing.originatorPersons, null);
  assert.equal(sc.hmda.statewideApplications, null);
  assert.equal(sc.hmda.countyMarketRows, 30);
  assert.equal(sc.hmda.leiSummaryRows, 1009);
  assert.equal(sc.hmda.countyMarketRowsAreAllCounties, false);
  assert.equal(sc.graphWrites, 0);
  const movement = SC_MORTGAGE_ROSTER.find((row) => row.companyId === "39179");
  assert.equal(movement?.companyName, "Movement Mortgage, LLC");
  assert.equal(movement?.licenseStatus, "Approved");
  assert.equal(movement?.officeState, "SC");
  const deficient = SC_MORTGAGE_ROSTER.filter((row) => row.licenseStatus === "Approved - Deficient").map((row) => row.companyId).sort();
  assert.deepEqual(deficient, ["1462", "34384"]);
  const green = SC_MORTGAGE_ROSTER.find((row) => row.companyId === "2598612");
  assert.equal(green?.companyName, "Green Lending LLC");
  assert.match(green?.street ?? "", /Ste\. 25/);
  assert.equal(new Set(SC_MORTGAGE_ROSTER.map((row) => row.licenseName)).size, 1);
});

test("South Carolina lender page and Ask do not invent a census or a city route", () => {
  const page = readFileSync("app/south-carolina/page.tsx", "utf8");
  assert.match(page, /does not publish one South Carolina lender total/);
  assert.match(page, /Approved - Deficient/);
  assert.match(page, /Approved as of 09\/03\/2026/);
  assert.doesNotMatch(page, /AggregateRating|Trust Score|ratingValue/);
  assert.equal(existsSync("app/south-carolina/charleston"), false);
  assert.equal(existsSync("app/south-carolina/columbia"), false);
  assert.equal(existsSync("app/south-carolina/greenville"), false);
  assert.equal(normalizedPublishedStatePath("/South-Carolina"), "/south-carolina");
  assert.equal(normalizedPublishedStatePath("/south-carolina/charleston"), null);
  const many = parseLenderAsk("how many mortgage lenders in South Carolina");
  assert.equal(many.mode, "fail_closed");
  assert.match(many.failReason ?? "", /564/);
  assert.match(many.failReason ?? "", /not a broker count/);
  assert.doesNotMatch(many.failReason ?? "", /statewide application/);
  const brokers = parseLenderAsk("South Carolina mortgage brokers");
  assert.match(brokers.failReason ?? "", /NOT_ACQUIRED/);
  const hmda = parseLenderAsk("South Carolina HMDA applications");
  assert.match(hmda.failReason ?? "", /30/);
  assert.match(hmda.failReason ?? "", /1,009/);
  assert.equal(parseLenderAsk("best mortgage lender in South Carolina").failClosedKind, "sc-ranking");
  assert.match(parseLenderAsk("mortgage lender Charleston South Carolina").failReason ?? "", /geography only/);
  assert.equal(parseLenderAsk("how many Kentucky mortgage lenders").failClosedKind, "ky-dfi-licensing");
  assert.notEqual(parseLenderAsk("mortgage lender Charleston").failClosedKind, "sc-city-context");
});
