/** ID-LEND-001. Department of Finance fiscal year 2025 license lines stay on their own grains. HMDA is the owned slice, not a license census. */
export const IDAHO_LENDER_SNAPSHOT = {
  contract: "lender-id-state-intel-v1",
  path: "/idaho",
  generatedAt: "2026-10-06T18:20:00Z",
  regulator: "Idaho Department of Finance",
  sources: {
    annualReport: "https://www.finance.idaho.gov/wp-content/uploads/2026/02/FY2025-Annual-Report.pdf",
    annualReportTitle: "120th Annual Report",
    annualReportBytes: 9976715,
    annualReportSha256: "aa60c854f7dc161e685019d78804d7648680621b19f5051ba527aa136b6a84da",
    letterDate: "2025-10-06",
    fiscalYearLabel: "fiscal year 2025",
    fiscalPeriod: "July 1, 2024 through June 30, 2025",
    populationClock: "2025-06-30",
    nmlsConsumerAccess: "https://www.nmlsconsumeraccess.org/",
    nmlsIsBulkCensus: false,
  },
  allDepartmentFilings: {
    prior: 241211,
    current: 244862,
    isMortgageCount: false,
  },
  mortgage: {
    statute: "Idaho Residential Mortgage Practices Act",
    sourceSentence: "licensed mortgage brokers/lenders and servicing companies",
    prior: 2488,
    current: 2584,
    companyVersusBranch: "NOT_SEPARATED",
    servicingInsideSourceSentence: true,
    servicingSplitFromBrokersAndLenders: false,
    nmlsIds: "NOT_ACQUIRED",
    namedRoster: "NOT_ACQUIRED",
  },
  mortgageLoanOriginators: {
    prior: 7743,
    current: 8641,
    grain: "individual licensees",
    addedToCompanyCount: false,
    namedRoster: "NOT_ACQUIRED",
  },
  regulatedLenders: {
    statute: "Idaho Credit Code",
    label: "Regulated Lender licensees",
    prior: 822,
    current: 817,
    addedToMortgageCount: false,
  },
  collectionAgencyAct: {
    collectionAgencies: { prior: 1340, current: 1323 },
    debtBuyers: { prior: 89, current: 83 },
    creditRepair: { prior: 7, current: 5 },
    creditCounselorsEnding: 22,
    creditCounselorPriorClean: false,
    debtSettlement: { prior: 22, current: 24 },
    individualsRegistered: { prior: 49578, current: 44962 },
    addedToMortgageCount: false,
    debtBeingCollectedIsMortgage: false,
  },
  banks: {
    asOf: "2025-06-30",
    stateCharteredUnderDirectSupervision: 9,
    hostStateBanksCharteredElsewhere: 11,
    idahoBasedBanks: 10,
    idahoBasedBanksComposition: "9 state-chartered banks and 1 federal savings bank",
    addedToMortgageCount: false,
  },
  creditUnions: {
    stateCharteredAsOf: "2025-06-30",
    stateCharteredUnderDirectSupervision: 16,
    hostStateCreditUnions: 13,
    idahoBasedAsOf: "2024-06-30",
    idahoBasedCreditUnions: 26,
    idahoBasedComposition: "16 state-chartered credit unions and 10 federal credit unions",
    clocksAreTheSame: false,
    addedToMortgageCount: false,
  },
  hmda: {
    year: 2025,
    ownedSlice: "data/hmda/idaho/",
    countyMarketSource: "data/hmda/idaho/county_market_summary_id.csv",
    countyMarketRows: 24,
    allIdahoCounties: 44,
    countyMarketRowsAreAllCounties: false,
    namedMajorMarkets: 14,
    lenderCountyActivitySource: "data/hmda/idaho/lender_activity_by_county_id.csv",
    lenderCountyActivityRows: 2356,
    leiSummarySource: "data/hmda/idaho/lender_state_summary_id.csv",
    leiSummaryRows: 529,
    leiRowsAreLicenses: false,
    highConfidenceMappingSource: "data/hmda/idaho/lei_to_nmls_mapping.csv",
    highConfidenceMappings: 144,
    mappingsAreLicenses: false,
    largestPrintedCounty: "Ada",
    largestPrintedCountyFips: "16001",
    largestPrintedCountyOriginations: 16030,
    countyOriginationsAddedToStatewide: false,
    statewideAcceptedAggregate: "NOT_ACQUIRED",
    sliceRebuilt: false,
  },
  notAcquired: {
    enforcementOrderCorpus: "NOT_ACQUIRED",
    complaintCount: "NOT_ACQUIRED",
    exemptEntityRegistrationRoster: "NOT_ACQUIRED",
    mortgageProcessorUnderwriterRoster: "NOT_ACQUIRED",
    fdicInstitutionRecount: "NOT_RECOUNTED",
  },
  fdicFile: "lib/fdic/data/idaho.json",
  banksAreMortgageLicenses: false,
  complaintIsViolation: false,
  restitutionUsd: 2248216,
  restitutionIsLicenseCount: false,
  complaintRecoveryUsdMoreThan: 203584,
  complaintRecoveryIsComplaintCount: false,
  unpublishedLayoutFigures: ["9252", "93500611962"],
  newCanonicalOrganizations: 0,
  graphWrites: 0,
  claimEligibilityChanges: 0,
  nameOnlyAdverseJoins: 0,
} as const;
