/** AL-LEND-001: Banking Department class counts stay separate. HMDA is market activity. */
export const ALABAMA_SNAPSHOT = {
  path: '/alabama',
  generatedAt: '2026-10-05T14:05:00Z',
  retrievedAt: '2026-10-05',
  regulator: 'Alabama State Banking Department',
  sources: {
    annualReport: 'https://banking.alabama.gov/wp-content/uploads/2026/04/FY-2025-Annual-Report-1.pdf',
    annualReportSha256: '3ca1f2226b49ce6849181116fc5282acc934afeef48d2dbb3ccc2231f3b5f2fb',
    annualReportLetterDate: '2025-12-31',
    statute: '§ 5-2A-13, Code of Alabama 1975',
    verifyServiceProviders: 'https://banking.alabama.gov/verify-service-providers/',
    nmlsResourceCenter: 'https://banking.alabama.gov/nmls-resource-center/',
    nmls: 'https://nmlsconsumeraccess.org/',
    complaints: 'https://banking.alabama.gov/con_affairs/file-a-complaint/',
  },
  bureauOfBanks: {
    clock: 'fiscal year-end 2025',
    commercialBanksSupervised: 88,
    totalAssetsPhrase: 'exceeding $224 billion',
    branchesInAlabamaAndHostStates: 1786,
    hostStates: 16,
    independentTrustCompanies: 2,
    bankManagedTrustDepartments: 6,
    assetsUnderAdministrationPhrase: 'exceeding $148 billion in 2025',
  },
  bureauOfLoans: {
    compositionClock: '2025-06-30',
    classTableClock: '2024-12-31',
    compositionLicensees: 19619,
    compositionIsMortgageCensus: false,
    smallLoanAct: 669,
    consumerCreditAct: 2720,
    pawnShopAct: 586,
    mortgageBrokersLicensingAct: 518,
    safeActOriginatorLicensees: 14836,
    deferredPresentmentServicesAct: 290,
    mortgageBrokerGrain: 'ACTIVE_LICENSEES',
    mortgageBrokerBusinessOrPerson: 'NOT_LABELED',
    safeActGrain: 'MORTGAGE_LOAN_ORIGINATOR_LICENSEES',
    mortgageLenderCount: null,
    servicerCount: null,
    combinedMortgageTotal: null,
    nmlsBulkRoster: 'NOT_ACQUIRED',
    licenseeRows: null,
  },
  mortgageBrokerFinancials2024: {
    clock: '2024 calendar year',
    adoptedAsCensus: false,
    totalAssets: 12700493,
    totalNetWorth: 5560116,
    totalLoansClosedCount: 3095,
    totalLoansClosedAmount: 796401026,
    netProfit: 1490201,
  },
  hmda: {
    year: 2025,
    source: 'data/hmda/by-state/AL/county_market_summary.csv',
    applications: 206604,
    originations: 114635,
    denials: 40443,
    denialApplicationPct: 19.58,
    distinctLeis: 885,
    counties: 67,
    purchase: 103757,
    refinance: 64992,
    otherPurpose: 37855,
    conventional: 140783,
    fha: 36860,
    va: 26204,
    usdaOther: 2757,
  },
  enforcement: {
    corpus: 'NOT_ACQUIRED',
    exactCanonicalAttachments: 0,
    nameOnlyAdverseJoins: 0,
    scope: 'No bounded Alabama State Banking Department mortgage enforcement corpus was acquired. Missing orders are not zero orders.',
  },
  complaints: {
    intake: 'KNOWN',
    providerRows: 'NOT_ACQUIRED',
    outcomes: 'NOT_ACQUIRED',
    bankIntake: 'Consumer.Banking@banking.alabama.gov',
    lendingIntake: 'Consumer.Lending@banking.alabama.gov',
  },
  newCanonicalOrganizations: 0,
  graphWrites: 0,
  claimEligibilityChanges: 0,
} as const;
