export type GoldenOutcome = 'PASS' | 'PARTIAL' | 'UNSUPPORTED_SAFE' | 'FAIL';
export type LenderGoldenQuestion = { query: string; expected: GoldenOutcome };

export const LENDER_GOLDEN_QUESTIONS: LenderGoldenQuestion[] = [
  { query: 'NMLS 3030', expected: 'PASS' }, { query: 'Find NMLS 3030', expected: 'PASS' },
  { query: 'NMLS ID 3030', expected: 'PASS' }, { query: 'NMLS institution ID 3030', expected: 'PASS' },
  { query: 'Rocket Mortgage', expected: 'PASS' }, { query: 'find Rocket Mortgage', expected: 'PASS' },
  { query: 'Bank of America', expected: 'PASS' }, { query: 'United Wholesale Mortgage', expected: 'PASS' },
  { query: 'LEI 549300HW662MN1WU8550', expected: 'PASS' }, { query: 'what is an NMLS ID', expected: 'PASS' },
  { query: 'what is an LEI', expected: 'PASS' }, { query: 'what is HMDA', expected: 'PASS' },
  { query: 'which lenders reported the most applications in Florida', expected: 'PASS' },
  { query: 'which lenders originated the most mortgages in Florida', expected: 'PASS' },
  { query: 'mortgage originations in Broward County', expected: 'PASS' },
  { query: 'FHA originations in Broward County', expected: 'PASS' },
  { query: 'VA mortgage activity in Florida', expected: 'PASS' },
  { query: 'conventional mortgage activity in New Jersey', expected: 'PASS' },
  { query: 'purchase mortgages in Palm Beach County', expected: 'PASS' },
  { query: 'refinance activity in Broward County', expected: 'PASS' },
  { query: 'mortgage denials in Florida', expected: 'PASS' },
  { query: 'compare applications and originations in Florida', expected: 'PARTIAL' },
  { query: 'compare FHA and conventional in Broward County', expected: 'PARTIAL' },
  { query: 'compare Florida and New Jersey originations', expected: 'PARTIAL' },
  { query: 'CFPB complaints for Rocket Mortgage', expected: 'PARTIAL' },
  { query: 'lenders with CFPB mortgage complaints', expected: 'PASS' },
  { query: 'lenders with federal enforcement records', expected: 'PARTIAL' },
  { query: 'Florida OFR lenders', expected: 'PARTIAL' },
  { query: 'licensed mortgage lenders in New Jersey', expected: 'PARTIAL' },
  { query: 'New Jersey RMLA lenders', expected: 'PARTIAL' },
  { query: 'California CRMLA lenders', expected: 'PARTIAL' },
  { query: 'Arizona mortgage lenders', expected: 'PARTIAL' },
  { query: 'Colorado mortgage lenders', expected: 'PARTIAL' },
  { query: 'licensed mortgage lenders in Colorado', expected: 'PARTIAL' },
  { query: 'licensed mortgage lenders in Virginia', expected: 'PARTIAL' },
  { query: 'Is Rocket licensed in Virginia?', expected: 'PARTIAL' },
  { query: 'How many mortgage lenders are in Virginia?', expected: 'PARTIAL' },
  { query: 'Mortgage brokers in Virginia', expected: 'PARTIAL' },
  { query: 'mortgage applications in Virginia', expected: 'PASS' },
  { query: 'Virginia first-time buyer assistance', expected: 'PARTIAL' },
  { query: 'Complaints against a Virginia lender', expected: 'PARTIAL' },
  { query: 'mortgage lenders in New York', expected: 'PARTIAL' },
  { query: 'licensed mortgage bankers in New York', expected: 'PARTIAL' },
  { query: 'mortgage brokers in New York', expected: 'PARTIAL' },
  { query: 'mortgage loan servicers in New York', expected: 'PARTIAL' },
  { query: 'mortgage loan officers in New York', expected: 'PARTIAL' },
  { query: 'how many lenders are in New York?', expected: 'PARTIAL' },
  { query: 'best mortgage lender in New York', expected: 'UNSUPPORTED_SAFE' },
  { query: 'mortgage applications in New York', expected: 'PASS' },
  { query: 'complaints against lender X in New York', expected: 'PARTIAL' },
  { query: 'mortgage lenders in Illinois', expected: 'PARTIAL' },
  { query: 'licensed mortgage lenders in Illinois', expected: 'PARTIAL' },
  { query: 'how many lenders are in Illinois?', expected: 'PARTIAL' },
  { query: 'best mortgage lender in Illinois', expected: 'UNSUPPORTED_SAFE' },
  { query: 'mortgage applications in Illinois', expected: 'PASS' },
  { query: 'complaints against a lender in Illinois', expected: 'PARTIAL' },
  { query: 'lenders headquartered in Broward County', expected: 'UNSUPPORTED_SAFE' },
  { query: 'lenders serving Broward County', expected: 'UNSUPPORTED_SAFE' },
  { query: 'lenders doing business in Broward County', expected: 'UNSUPPORTED_SAFE' },
  { query: 'I am buying a house in Broward County', expected: 'PARTIAL' },
  { query: 'who is making the most home loans in my county', expected: 'UNSUPPORTED_SAFE' },
  { query: 'who approves the most mortgage applications', expected: 'UNSUPPORTED_SAFE' },
  { query: 'which lender has the best approval odds', expected: 'UNSUPPORTED_SAFE' },
  { query: 'best mortgage lender in Florida', expected: 'UNSUPPORTED_SAFE' },
  { query: 'safest mortgage lender', expected: 'UNSUPPORTED_SAFE' },
  { query: 'cheapest mortgage lender', expected: 'UNSUPPORTED_SAFE' },
  { query: 'lender with no complaints', expected: 'UNSUPPORTED_SAFE' },
  { query: 'lender with no enforcement', expected: 'UNSUPPORTED_SAFE' },
  { query: 'is this lender trustworthy', expected: 'UNSUPPORTED_SAFE' },
  { query: 'I want to verify the lender that gave me a loan estimate', expected: 'PARTIAL' },
  { query: 'how do I check if a mortgage company is licensed', expected: 'UNSUPPORTED_SAFE' },
  { query: 'is Rocket Mortgage a bank', expected: 'PASS' }, { query: 'bank vs mortgage company', expected: 'PASS' },
  { query: 'NMLS person 123456', expected: 'UNSUPPORTED_SAFE' }, { query: 'mortgage loan officer NMLS 123456', expected: 'UNSUPPORTED_SAFE' },
  { query: 'branch NMLS 123456', expected: 'UNSUPPORTED_SAFE' },
  { query: 'how many lender institutions are there', expected: 'PASS' },
  { query: 'how many HMDA applications were reported', expected: 'PASS' },
  { query: 'how many Florida applications', expected: 'PASS' }, { query: 'how many Broward originations', expected: 'PASS' },
  { query: 'how many CFPB complaint observations', expected: 'PASS' },
  { query: 'mortgage companies near me', expected: 'UNSUPPORTED_SAFE' }, { query: 'lender at my address', expected: 'UNSUPPORTED_SAFE' },
  { query: 'does this lender lend in my ZIP code', expected: 'UNSUPPORTED_SAFE' }, { query: 'can this lender approve me', expected: 'UNSUPPORTED_SAFE' },
  { query: 'what interest rate will this lender give me', expected: 'UNSUPPORTED_SAFE' },
  { query: 'lender with highest approval rate', expected: 'UNSUPPORTED_SAFE' }, { query: 'lender with lowest denial rate', expected: 'UNSUPPORTED_SAFE' },
  { query: 'mortgage lenders for bad credit', expected: 'UNSUPPORTED_SAFE' }, { query: 'lender for first time homebuyers', expected: 'UNSUPPORTED_SAFE' },
  { query: 'what is an application in HMDA', expected: 'PASS' }, { query: 'what is an origination in HMDA', expected: 'PASS' },
  { query: 'what is a denial in HMDA', expected: 'PASS' }, { query: 'what is a CFPB complaint observation', expected: 'PARTIAL' },
  { query: 'Rocket Mortg', expected: 'PASS' }, { query: 'Rocket Mortgag', expected: 'UNSUPPORTED_SAFE' }, { query: '3030', expected: 'UNSUPPORTED_SAFE' },
  { query: '<script>alert(1)</script>', expected: 'UNSUPPORTED_SAFE' }, { query: "' OR 1=1 --", expected: 'UNSUPPORTED_SAFE' },
  { query: '', expected: 'UNSUPPORTED_SAFE' }, { query: 'x'.repeat(500), expected: 'UNSUPPORTED_SAFE' },
];
