import test, {type TestContext} from 'node:test';
import assert from 'node:assert/strict';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import snapshot from '../home-intel/accepted-snapshot.json';
import {ILLINOIS_SNAPSHOT} from '../illinois-intelligence/snapshot';
import {OREGON_SNAPSHOT} from '../oregon-intelligence/snapshot';
import {PENNSYLVANIA_SNAPSHOT} from '../pennsylvania-intelligence/snapshot';
import {NORTH_CAROLINA_SNAPSHOT} from '../north-carolina-intelligence/snapshot';
import {OHIO_SNAPSHOT} from '../ohio-intelligence/snapshot';import {MASSACHUSETTS_SNAPSHOT} from '../massachusetts-intelligence/snapshot';import {TENNESSEE_SNAPSHOT} from '../tennessee-intelligence/snapshot';
import {STATE_NAMES} from '../home-intel/states';
import {executeAskQuery} from './execute-query';
import {countSources} from './scalar-count';
import {AskResultView} from '../../components/ask-lender/ask-result-view';
import {AskTrustHubSearch} from '../../components/home-intel/ask-trust-hub-search';
import AskPage from '../../app/ask/page';
import {GET} from '../../app/api/ask/route';
import type {AskExecution} from './types';
Object.assign(globalThis,{React});
const actions=['application','origination','denial'] as const;
const fixture=()=>({...snapshot,applications:99991,originations:99992,denials:99993,geography:Object.keys(STATE_NAMES).map((state,i)=>({state,applications:i*100+1,originations:i*100+2,denials:i*100+3}))});
function source(t:TestContext){const data=fixture();t.mock.method(countSources,'snapshot',()=>data);t.mock.method(countSources,'publishedStateHmda',()=>null);return data;}
const run=(q:string,overrides={})=>executeAskQuery({q,overrides});
const value=(r:AskExecution)=>r.countEvidence?.value;
function noValue(r:AskExecution){assert.equal(value(r),null);assert.notEqual(r.countEvidence?.availability,'AVAILABLE');assert.equal(r.facts?.length,0);}
function findResult(node:unknown):AskExecution|undefined { if(!node||typeof node!=='object')return; if(Array.isArray(node))return node.map(findResult).find(Boolean);const props=(node as {props?:{result?:AskExecution;children?:unknown}}).props;return props?.result??findResult(props?.children);}
test('01-04 every jurisdiction/name/code and all three independent fields',t=>{const data=source(t);for(const row of data.geography)for(const action of actions)for(const place of [row.state,STATE_NAMES[row.state]]){const r=run(`How many mortgage ${action}s in ${place}?`);assert.equal(value(r),row[`${action}s`],`${place}/${action}: ${r.body}`);assert.equal(r.query.geography?.state,row.state);assert.equal(r.countEvidence?.field,`${action}s`);assert.ok(r.headline.includes(STATE_NAMES[row.state]));}});
test('05 national measures are separate fields, explicit default',t=>{const data=source(t);for(const action of actions){const r=run(`How many mortgage ${action}s nationally?`);assert.equal(value(r),data[`${action}s`]);assert.equal(r.countEvidence?.scope,'US');}assert.equal(value(run('How many mortgage denials?')),data.denials);});
test('06 sourced zero is successful',t=>{const data=source(t);data.geography.find(r=>r.state==='NJ')!.denials=0;const r=run('How many denials in NJ?');assert.equal(value(r),0);assert.equal(r.countEvidence?.availability,'AVAILABLE');assert.equal(r.facts?.[0].value,'0');});
test('07 missing and malformed selected values never coerce or substitute',t=>{const data=source(t);const row=data.geography.find(r=>r.state==='NJ')!;for(const bad of [null,undefined,'',-1,1.5,NaN,Infinity,Number.MAX_SAFE_INTEGER+1,'177325']){Object.assign(row,{originations:bad});noValue(run('How many originations in NJ?'));}data.geography=data.geography.filter(r=>r.state!=='NJ');noValue(run('How many originations in NJ?'));});
test('08 year mismatch and multiple years remain unresolved',t=>{source(t);for(const year of ['2024','2026','2024 and 2025']){const r=run(`How many originations in New Jersey in ${year}?`);noValue(r);assert.ok(r.query.reportingYears?.length);}assert.notEqual(value(run('How many originations in NJ in 2025?')),null);});
test('09 duplicate and mixed-grain aggregate keys rejected',t=>{const data=source(t);data.geography.push({...data.geography[0]});noValue(run('How many originations in NJ?'));data.geography.pop();Object.assign(data.geography[0],{county_fips:'00001'});noValue(run('How many originations in NJ?'));});
test('10 state/action override updates number, interpretation, trace and URL',t=>{const data=source(t);const r=run('How many originations in New Jersey?',{geo:'CA',action:'denial'});assert.equal(value(r),data.geography.find(r=>r.state==='CA')!.denials);assert.equal(r.query.geography?.state,'CA');assert.equal(r.query.actionTaken?.[0],'denial');assert.equal(r.countEvidence?.scope,'CA');assert.ok(r.trace?.method.includes('state=CA].denials'));assert.ok(r.headline.includes('California denials'));});
test('11 filter links preserve state/action and structured form values',t=>{source(t);const r=run('How many originations in New Jersey?');for(const chip of r.filters??[]){const url=new URL(chip.href,'https://fixture.test');if(['apps','den','fha'].includes(chip.id))assert.equal(url.searchParams.get('geo'),'NJ');}const html=renderToStaticMarkup(React.createElement(AskTrustHubSearch,{initialQuery:'How many originations in New Jersey?',overrides:{geo:'NJ',action:'denial'}}));assert.match(html,/value="NJ" selected/);assert.match(html,/value="denial" selected/);});
test('12 filtered counts use actual field and unsupported split stays unavailable',t=>{source(t);t.mock.method(countSources,'state',()=>[{state:'NJ',year:'2025',lei:'a',orig_fha:'7'},{state:'NJ',year:'2025',lei:'b',orig_fha:'11'},{state:'FL',year:'2025',lei:'a',orig_fha:'900'}]);assert.equal(value(run('How many FHA originations in New Jersey?')),18);noValue(run('How many FHA applications in New Jersey?'));noValue(run('How many FHA denials in Florida?'));noValue(run('How many purchase originations in NJ?'));noValue(run('How many purchase applications in NJ?'));});
test('13 unknown/local geography never national; ordinary in/or are not state codes',t=>{source(t);for(const place of ['Atlantis','Newark, NJ','Orange County, New Jersey'])noValue(run(`How many originations in ${place}?`));assert.equal(run('How many mortgage originations?').countEvidence?.scope,'US');});
test('14 two states require clarification',t=>{source(t);noValue(run('How many originations in New Jersey and Florida?'));});
test('15 pagination/publication cannot affect market count',t=>{source(t);const q='How many originations in NJ?';assert.equal(value(executeAskQuery({q,page:200,pageSize:1})),value(executeAskQuery({q,page:1,pageSize:50})));});
test('16 actual page/API share same source-backed result',async t=>{source(t);const params={q:'How many originations in NJ?',geo:'TX',action:'application'};const page=findResult(await AskPage({searchParams:Promise.resolve(params)}))!;const response=await GET(new Request('https://fixture.test/api/ask?'+new URLSearchParams(params)));const api=await response.json();assert.deepEqual(page.countEvidence,api.countEvidence);assert.deepEqual(JSON.parse(JSON.stringify(page.query)),api.query);assert.deepEqual(page.facts,api.facts);});
test('17 rendered number and trace derive from same source and clock',t=>{source(t);const r=run('How many originations in NJ?');const html=renderToStaticMarkup(React.createElement(AskResultView,{result:r,question:'How many originations in NJ?'}));assert.ok(html.includes(r.facts![0].value));assert.ok(html.includes(r.countEvidence!.sourceFingerprint!));assert.deepEqual(r.trace?.sourceFiles,['lib/home-intel/accepted-snapshot.json']);assert.equal(r.countEvidence?.sourceGrain,'county observations aggregated by jurisdiction');assert.equal(r.countEvidence?.reportingYear,'2025');});
test('18 changing only NJ source changes only NJ answer',t=>{const data=source(t);const before=value(run('How many originations in FL?'));data.geography.find(r=>r.state==='NJ')!.originations=717171;assert.equal(value(run('How many originations in NJ?')),717171);assert.equal(value(run('How many originations in FL?')),before);});
test('19 NMLS grouping and LEI regressions remain exact',()=>{for(const q of ['NMLS 3030','NMLS 30 30','LEI 549300FGXN1K3HLB1R50'])assert.equal(run(q).rows?.[0]?.nmls,'3030');assert.equal(run('nmls 32 51').query.identifier?.value,'3251');});
test('20 county-volume and county comparison retained',()=>{const r=run('How many applications in Broward County?');assert.equal(value(r),67743);const cmp=run('Compare Broward and Palm Beach mortgage activity');assert.ok(cmp.facts?.some(f=>f.label==='Palm Beach applications'&&f.value==='56,484'));assert.ok(run('Which lenders received the most applications for properties in Broward County?').rows?.length);});
test('21 corrupt/throwing source finishes unavailable, not zero',t=>{t.mock.method(countSources,'snapshot',()=>{throw Error('Source unavailable.');});noValue(run('How many originations in NJ?'));});
test('22 accepted source oracle independent of executor for all fields/states',()=>{
  for(const row of snapshot.geography)for(const action of actions){
    const expected=row.state==='IL'?ILLINOIS_SNAPSHOT.hmda[`${action}s`]:row.state==='OR'?OREGON_SNAPSHOT.hmda[`${action}s`]:row.state==='PA'?PENNSYLVANIA_SNAPSHOT.hmda[`${action}s`]:row.state==='NC'?NORTH_CAROLINA_SNAPSHOT.hmda[`${action}s`]:row.state==='OH'?OHIO_SNAPSHOT.hmda[`${action}s`]:row.state==='MA'?MASSACHUSETTS_SNAPSHOT.hmda[`${action}s`]:row.state==='TN'?TENNESSEE_SNAPSHOT.hmda[`${action}s`]:row[`${action}s`];
    assert.equal(value(run(`How many ${action}s in ${row.state}?`)),expected,`${row.state}/${action}`);
  }
});
test('23 filtered duplicates, null and mixed years fail closed',t=>{source(t);const records=[{state:'NJ',year:'2025',lei:'a',orig_fha:'9'}];t.mock.method(countSources,'state',()=>records);records.push({...records[0]});noValue(run('How many FHA originations in NJ?'));records.pop();records[0].year='2024';noValue(run('How many FHA originations in NJ?'));records[0].year='2025';records[0].orig_fha='';noValue(run('How many FHA originations in NJ?'));});

test('24 unsupported conditions before place and structured years cannot disappear',t=>{source(t);for(const q of ['Atlantis mortgage originations','How many originations under $500000 in NJ?','How many originations in NJ and nationally?','How many applications and denials in NJ?'])noValue(run(q));const r=executeAskQuery({q:'How many originations in NJ in 2024?',structuredQuery:{mode:'count',geography:{grain:'state',state:'NJ',note:'fixture'},actionTaken:['origination']}});noValue(r);});
test('25 supported FL product and purpose fields remain independent',t=>{source(t);t.mock.method(countSources,'markets',()=>[{year:'2025',state:'FL',county_fips:'12011',total_applications:'100',total_originations:'90',denial_count:'10',purchase_count:'11',refinance_count:'12',apps_fha:'13',orig_fha:'14'}]);assert.equal(value(run('How many FHA applications in Broward County?')),13);assert.equal(value(run('How many FHA originations in Broward County?')),14);assert.equal(value(run('How many purchase applications in Broward County?')),11);assert.equal(value(run('How many refinance applications in Florida?')),12);noValue(run('How many FHA denials in Broward County?'));});

test('26 internal scalar adaptation preserves purpose and cannot lift a refusal',t=>{source(t);assert.equal(value(executeAskQuery({q:'How many denials in NJ?',structuredQuery:{mode:'count'}})),value(run('How many denials in NJ?')));const structuredQuery={mode:'count' as const,geography:{grain:'state' as const,state:'NJ',note:'fixture'},actionTaken:['origination']};noValue(executeAskQuery({q:'How many purchase originations in NJ?',structuredQuery}));const r=executeAskQuery({q:'Which are the best mortgage lenders in NJ?',structuredQuery});assert.equal(r.failClosed,true);assert.equal(r.countEvidence,undefined);});

test('27 scalar interpretation names counted observations, not institution grain',t=>{source(t);const r=run('How many applications in NJ?');assert.ok(!r.interpretation.some(line=>line.label==='Entity grain'));const grain=r.interpretation.find(line=>line.label==='Counted observations')!;assert.ok(grain.value.includes('applications, not institutions'));assert.ok(grain.value.includes(r.countEvidence!.sourceGrain!));assert.ok(grain.value.includes('output: state property geography'));});
