import {executeSpecialistV2} from '../specialist-execution/v2';
﻿import test, { type TestContext } from 'node:test';
import assert from 'node:assert/strict';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {executeAskQuery} from './execute-query';
import {volumeSources, selectInstitutionVolume} from './institution-volume';
import {AskResultView} from '../../components/ask-lender/ask-result-view';
import AskPage from '../../app/ask/page';
import {GET} from '../../app/api/ask/route';
import type {AskExecution,LenderResearchQuery} from './types';
import stateSource from './generated/state.csv.json';
import countySource from './generated/county.csv.json';
Object.assign(globalThis,{React});
const A='AAAAAAAAAAAAAAAAAAAA',B='BBBBBBBBBBBBBBBBBBBB';
const row=(state='NJ',lei=A,extra:Record<string,unknown>={})=>({year:'2025',state,lei,total_applications:'31',total_originations:'17',orig_fha:'5',orig_va:'2',orig_conventional:'9',orig_usda_other:'1',...extra});
const county=(county_fips='12011',lei=A,extra:Record<string,unknown>={})=>({year:'2025',state:'FL',county_fips,lei,applications:'41',originations:'23',denials:'11',apps_fha:'7',orig_fha:'3',...extra});
const originalLoaders={...volumeSources};
function source(t:TestContext){t.after(()=>Object.assign(volumeSources,originalLoaders));const state=[row(),row('NJ',B,{total_originations:'9'}),row('FL',A,{total_originations:'101'})];const counties=[county(),county('12099'),county('34001',A,{state:'NJ',denials:'9999'})];volumeSources.state=()=>state;volumeSources.county=()=>counties;return {state,counties};}
const run=(q:string,overrides={})=>executeAskQuery({q,overrides});
const q='Which lenders reported the most mortgage denials in New Jersey?';
const origins='Which lenders originated the most mortgages in New Jersey?';
function unavailable(r:AskExecution){assert.notEqual(r.volumeEvidence?.availability,'AVAILABLE');assert.equal(r.volumeEvidence?.observedSum,null);assert.equal(r.volumeEvidence?.positiveReporters,null);assert.equal(r.volumeEvidence?.completeWithinSource,false);assert.equal(r.denominator,undefined);assert.equal(r.totalRows,undefined);assert.deepEqual(r.rows,[]);assert.deepEqual(r.facts,[]);}
function findResult(node:unknown):AskExecution|undefined {if(!node||typeof node!=='object')return;if(Array.isArray(node))return node.map(findResult).find(Boolean);const p=(node as {props?:{result?:AskExecution;children?:unknown}}).props;return p?.result??findResult(p?.children);}
const html=(r:AskExecution)=>renderToStaticMarkup(React.createElement(AskResultView,{result:r,question:q}));
test('01 NJ institution denial absence is not market zero',t=>{source(t);const r=run(q);unavailable(r);assert.equal(r.volumeEvidence?.availability,'UNSUPPORTED');assert.match(r.body,/not a finding of zero denials/);assert.doesNotMatch(html(r),/New Jersey denials: 0|0 reporting institutions|Denominator:/);assert.match(r.trace!.method,/No ordering/);});
test('02 absent county/state product denial splits',t=>{source(t);for(const place of ['New Jersey','Florida','Broward County'])unavailable(run(`Which lenders reported the most FHA mortgage denials in ${place}?`));});
test('03 state product applications absent; FL compatible alternative retained',t=>{source(t);unavailable(run('Which lenders received the most FHA mortgage applications in New Jersey?'));const r=run('Which lenders received the most FHA mortgage applications in Florida?');assert.equal(r.volumeEvidence?.observedSum,14);assert.equal(r.volumeEvidence?.field,'apps_fha');});
test('04 positive NJ and FL originations and ordering',t=>{source(t);const r=run(origins);assert.deepEqual(r.rows?.map(r=>r.metric),[17,9]);assert.equal(r.volumeEvidence?.observedSum,26);assert.equal(run(origins,{geo:'FL'}).volumeEvidence?.observedSum,101);});
test('05 FHA originations and county applications use their own fields',t=>{source(t);const r=run(origins,{loanType:'FHA'});assert.equal(r.volumeEvidence?.observedSum,10);assert.equal(r.volumeEvidence?.field,'orig_fha');const c=run('Which lenders received the most applications in Broward County?');assert.equal(c.volumeEvidence?.observedSum,41);assert.equal(c.volumeEvidence?.field,'applications');});
test('06 selected numeric zero vs every missing/invalid representation',t=>{const d=source(t);d.state[0].total_originations='0';assert.equal(run(origins).volumeEvidence?.observedSum,9);for(const bad of [null,undefined,'',' ', 'suppressed',-1,1.5,NaN,Infinity,Number.MAX_SAFE_INTEGER+1,'1e3']){Object.assign(d.state[0],{total_originations:bad});unavailable(run(origins));}});
test('07 complete all-zero cohort is available and honest empty',t=>{const d=source(t);d.state.forEach(r=>r.total_originations='0');const r=run(origins);assert.equal(r.volumeEvidence?.availability,'AVAILABLE');assert.equal(r.volumeEvidence?.observedSum,0);assert.equal(r.totalRows,0);assert.equal(r.volumeEvidence?.eligibleInstitutions,2);assert.match(r.body,/no positive observations/);assert.match(r.body,/does not mean.*no lenders/);});
test('08 mixed missing selected values cannot create partial complete ranking',t=>{const d=source(t);Object.assign(d.state[1],{total_originations:null});unavailable(run(origins));});
test('09 missing secondary fields preserve selected table and null',t=>{const d=source(t);Object.assign(d.state[0],{total_applications:null});const r=run(origins);assert.equal(r.volumeEvidence?.availability,'AVAILABLE');assert.equal(r.rows?.[0].applications,null);assert.equal(r.rows?.[0].denials,null);assert.equal(r.rows?.[0].metric,17);});
test('10 FL county aggregation excludes NJ and preserves declared keys',t=>{source(t);const r=run('Which lenders reported the most denials in Florida?');assert.equal(r.volumeEvidence?.observedSum,22);assert.equal(r.rows?.length,1);assert.equal(r.volumeEvidence?.sourceGrain,'county-LEI-year');assert.equal(r.volumeEvidence?.scope,'FL');});
test('11 duplicate/overlapping/mixed-year rows rejected',t=>{const d=source(t);d.state.push({...d.state[0]});unavailable(run(origins));d.state.pop();Object.assign(d.state[0],{county_fips:'34001'});unavailable(run(origins));delete (d.state[0] as Record<string,unknown>).county_fips;d.state[0].year='2024';unavailable(run(origins));});
test('12 totals before pagination and publication enrichment',t=>{source(t);const a=executeAskQuery({q:origins,pageSize:1,page:2});const b=executeAskQuery({q:origins,pageSize:50});assert.equal(a.rows?.length,1);assert.equal(a.volumeEvidence?.observedSum,b.volumeEvidence?.observedSum);assert.equal(a.totalRows,2);assert.ok(b.rows?.every(r=>!r.href));assert.equal(a.volumeEvidence?.positiveReporters,2);});
test('13 row labels/Trace/summaries source-derived',t=>{source(t);const r=run(origins,{loanType:'FHA'});assert.match(r.rows![0].whyMatched[0],/orig_fha/);assert.match(r.trace!.method,/field orig_fha/);assert.equal(r.volumeEvidence?.observedSum,10);assert.equal(r.rows![0].metricLabel,'FHA originations');assert.ok(html(r).includes(r.volumeEvidence!.sourceFingerprint!));});
test('14 contextual all-loan values explicitly scoped, no product relabeling',t=>{source(t);const r=run(origins,{loanType:'FHA'});assert.equal(r.rows![0].applications,31);assert.match(html(r),/Secondary measures.*all-loan observations/);assert.equal(r.denominator,undefined);});
test('15 typed action/state/product overrides update capability and filters',t=>{source(t);const r=run(q,{geo:'FL',action:'origination',loanType:'FHA'});assert.equal(r.volumeEvidence?.observedSum,5);assert.equal(r.volumeEvidence?.scope,'FL');assert.equal(r.query.actionTaken?.[0],'origination');assert.equal(r.volumeEvidence?.field,'orig_fha');const r2=run(origins,{action:'denial'});unavailable(r2);assert.equal(new URL(r2.filters!.find(c=>c.id==='orig')!.href,'https://test').searchParams.get('geo'),'NJ');});
test('16 unsupported year/purpose/local/multi-value preserved',t=>{source(t);for(const s of ['in New Jersey 2024','in New Jersey 2024 and 2025','in Newark NJ','in New Jersey and Florida'])unavailable(run(`Which lenders originated the most mortgages ${s}?`));for(const s of ['purchase','FHA and VA'])unavailable(run(`Which lenders originated the most ${s} mortgages in New Jersey?`));unavailable(run('Which lenders received the most purchase applications in New Jersey?'));const r=run(origins+' 2024');assert.deepEqual(r.query.reportingYears,['2024']);});
test('17-18 recovery invokes protected scalar with NJ/action/vintage retained',t=>{source(t);const r=run(q);const url=new URL(r.href!,'https://test');assert.equal(url.searchParams.get('geo'),'NJ');assert.equal(url.searchParams.get('action'),'denial');const s=run(url.searchParams.get('q')!,{geo:'NJ',action:'denial'});assert.equal(s.countEvidence?.availability,'AVAILABLE');assert.equal(s.countEvidence?.scope,'NJ');assert.equal(s.countEvidence?.action,'denial');assert.equal(s.countEvidence?.reportingYear,'2025');assert.equal(s.countEvidence?.sourceFile,'lib/home-intel/accepted-snapshot.json');assert.equal(r.countEvidence,undefined);unavailable(r);});
test('19 actual page/API same fixture and null remains unavailable in HTML',async t=>{source(t);for(const question of [q,origins]){const page=findResult(await AskPage({searchParams:Promise.resolve({q:question})}))!;const api=await (await GET(new Request('https://test/api/ask?q='+encodeURIComponent(question)))).json();assert.deepEqual(page.volumeEvidence,api.volumeEvidence);assert.deepEqual(page.facts,api.facts);assert.deepEqual(JSON.parse(JSON.stringify(page.rows)),api.rows);if(question===q){assert.match(html(page),/Observed sum: unavailable/);assert.doesNotMatch(html(page),/Denominator:/);}}});
test('20 missing/corrupt source and loader failure are unavailable',t=>{source(t);for(const bad of [null,{},[],[null]]){volumeSources.state=()=>bad;unavailable(run(origins));}volumeSources.state=()=>{throw Error('private-stack-must-not-appear');};const r=run(origins);unavailable(r);assert.doesNotMatch(JSON.stringify(r),/private-stack/);});
test('21 independent raw-source controls; known-positive paths not blocked',()=>{for(const [question,raw,field,filter] of [[origins,stateSource,'total_originations',(r:Record<string,string>)=>r.state==='NJ'],['Which lenders originated the most FHA mortgages in Florida?',stateSource,'orig_fha',(r:Record<string,string>)=>r.state==='FL'],['Which lenders received the most applications in Broward County?',countySource,'applications',(r:Record<string,string>)=>r.state==='FL'&&r.county_fips==='12011']] as const){const expected=raw.filter(filter).reduce((n,r)=>n+Number((r as Record<string,string>)[field]),0);const r=run(question);assert.equal(r.volumeEvidence?.availability,'AVAILABLE');assert.equal(r.volumeEvidence?.observedSum,expected);assert.ok(r.rows?.length);}});
test('22 identity/scalar/compare preserved',()=>{assert.equal(run('NMLS 30 30').rows?.[0].nmls,'3030');assert.equal(run('nmls 32 51').query.identifier?.value,'3251');assert.equal(run('How many mortgage denials in New Jersey?').countEvidence?.availability,'AVAILABLE');assert.ok(run('Compare Broward and Palm Beach mortgage applications').facts?.length);});
test('23 structured multi-value input and unknown states do not select first/fallback',t=>{source(t);const plan:LenderResearchQuery={mode:'entity',geography:{grain:'state',state:'NJ',note:''},actionTaken:['origination','denial']};unavailable(executeAskQuery({q:origins,structuredQuery:plan}));assert.equal(selectInstitutionVolume({...plan,actionTaken:['origination'],geography:{grain:'state',state:'ZZ',note:''}}).evidence.availability,'NEEDS_CLARIFICATION');});
test('24 national partition sums independent institutions and no source-year coercion',t=>{const d=source(t);const r=run('Which lenders originated the most mortgages nationally?');assert.equal(r.volumeEvidence?.observedSum,127);assert.equal(r.totalRows,2);assert.match(r.headline,/acquired U.S. jurisdictions/);Object.assign(d.state[0],{year:null});unavailable(run(origins));});

test('25 specialist adapter preserves unavailable instead of zero-match',()=>{const r=executeSpecialistV2({query:'FHA mortgage denials in Broward County',geography:{stateCode:'FL',countyFips:'12011',county:'Broward'},action:'denial',loanType:'FHA'});assert.equal(r.body.resultState,'UNSUPPORTED_CAPABILITY');assert.equal(r.status,422);});

test('26 recovery for other supported counties never overrides county to FL',t=>{source(t);volumeSources.county=()=>null;const r=run('Which lenders reported the most mortgage denials in Orange County?');const url=new URL(r.href!,'https://test');assert.equal(url.searchParams.get('geo'),null);const result=run(url.searchParams.get('q')!,{action:'denial'});assert.equal(result.countEvidence?.scope,'12095');});
