/**
 * LEND-NAT-011 — profile intelligence metric dictionary.
 * Evidence presentation only. No Trust Score, ranking, or quality conversion.
 */

export type Confidence = 'confirmed' | 'high_confidence' | 'review_required' | 'unresolved';

export type MetricDefinition = {
  metric_key: string;
  display_concept: string;
  source: string;
  numerator: string;
  denominator: string;
  time_period: string;
  entity_attribution_rule: string;
  limitations: string;
  safe_for_future_public_display: boolean;
  available_in_current_vintage: boolean;
};

export const PROFILE_METRIC_DICTIONARY: MetricDefinition[] = [
  {
    metric_key: 'hmda_application_count',
    display_concept: 'HMDA applications',
    source: 'FFIEC HMDA 2025 LEI summaries (lender_hmda_observations, geo_grain=state)',
    numerator: 'sum(applications) at state grain',
    denominator: 'not a rate; count of applications',
    time_period: 'HMDA 2025 reporting vintage (not calendar-2026 activity)',
    entity_attribution_rule: 'observation.institution_id = canonical institution; LEI is the source key',
    limitations: 'No national grain. State grain is canonical for apps/orig. Not a quality signal.',
    safe_for_future_public_display: true,
    available_in_current_vintage: true,
  },
  {
    metric_key: 'hmda_origination_count',
    display_concept: 'HMDA originations',
    source: 'FFIEC HMDA 2025 LEI summaries (geo_grain=state)',
    numerator: 'sum(originations) at state grain',
    denominator: 'not a rate; count of originations',
    time_period: 'HMDA 2025 reporting vintage',
    entity_attribution_rule: 'observation.institution_id = canonical institution',
    limitations: 'Equals county-grain origination sum nationally; use state grain for institution totals.',
    safe_for_future_public_display: true,
    available_in_current_vintage: true,
  },
  {
    metric_key: 'hmda_origination_rate',
    display_concept: 'Originations / applications',
    source: 'FFIEC HMDA 2025 state grain',
    numerator: 'hmda_origination_count',
    denominator: 'hmda_application_count (state grain). Null if applications = 0.',
    time_period: 'HMDA 2025 reporting vintage',
    entity_attribution_rule: 'same institution_id on both sides',
    limitations: 'Not an approval rate. Withdrawn/incomplete/approved-not-accepted are not materialized. Not a quality score.',
    safe_for_future_public_display: true,
    available_in_current_vintage: true,
  },
  {
    metric_key: 'hmda_denial_count',
    display_concept: 'HMDA denials',
    source: 'FFIEC HMDA 2025 LEI summaries (geo_grain=county)',
    numerator: 'sum(denials) at county grain',
    denominator: 'count, not a rate',
    time_period: 'HMDA 2025 reporting vintage',
    entity_attribution_rule: 'observation.institution_id = canonical institution',
    limitations: 'State grain stores denials as 0/null. County grain is the denial source. Not a quality score.',
    safe_for_future_public_display: true,
    available_in_current_vintage: true,
  },
  {
    metric_key: 'hmda_denial_rate',
    display_concept: 'Denials / applications',
    source: 'FFIEC HMDA 2025',
    numerator: 'hmda_denial_count (county grain)',
    denominator: 'hmda_application_count (state grain). Never denials / observation-row-count.',
    time_period: 'HMDA 2025 reporting vintage',
    entity_attribution_rule: 'same institution_id; mixed grain disclosed',
    limitations:
      'Numerator is county-grain denials; denominator is state-grain applications. Full LAR action_taken distribution is not stored. Do not compare lenders without scale context. Not a quality score.',
    safe_for_future_public_display: true,
    available_in_current_vintage: true,
  },
  {
    metric_key: 'hmda_purchase_application_count',
    display_concept: 'Purchase-purpose applications',
    source: 'FFIEC HMDA 2025',
    numerator: 'sum(purchase_applications)',
    denominator: 'n/a',
    time_period: 'HMDA 2025',
    entity_attribution_rule: 'institution_id',
    limitations: 'Column exists but is NULL in the current LEI summaries. Not originations.',
    safe_for_future_public_display: false,
    available_in_current_vintage: false,
  },
  {
    metric_key: 'hmda_refinance_application_count',
    display_concept: 'Refinance-purpose applications',
    source: 'FFIEC HMDA 2025',
    numerator: 'sum(refinance_applications)',
    denominator: 'n/a',
    time_period: 'HMDA 2025',
    entity_attribution_rule: 'institution_id',
    limitations: 'NULL in current LEI summaries. Not originations.',
    safe_for_future_public_display: false,
    available_in_current_vintage: false,
  },
  {
    metric_key: 'hmda_conventional_application_count',
    display_concept: 'Conventional applications',
    source: 'FFIEC HMDA 2025',
    numerator: 'sum(apps_conventional)',
    denominator: 'n/a',
    time_period: 'HMDA 2025',
    entity_attribution_rule: 'institution_id',
    limitations: 'Not populated in current state/county summaries (all null/0).',
    safe_for_future_public_display: false,
    available_in_current_vintage: false,
  },
  {
    metric_key: 'hmda_fha_application_count',
    display_concept: 'FHA applications',
    source: 'FFIEC HMDA 2025',
    numerator: 'sum(apps_fha)',
    denominator: 'n/a',
    time_period: 'HMDA 2025',
    entity_attribution_rule: 'institution_id',
    limitations: 'Not populated in current summaries.',
    safe_for_future_public_display: false,
    available_in_current_vintage: false,
  },
  {
    metric_key: 'hmda_va_application_count',
    display_concept: 'VA applications',
    source: 'FFIEC HMDA 2025',
    numerator: 'sum(apps_va)',
    denominator: 'n/a',
    time_period: 'HMDA 2025',
    entity_attribution_rule: 'institution_id',
    limitations: 'Not populated in current summaries.',
    safe_for_future_public_display: false,
    available_in_current_vintage: false,
  },
  {
    metric_key: 'hmda_usda_application_count',
    display_concept: 'USDA/RHS applications',
    source: 'FFIEC HMDA 2025',
    numerator: 'sum(apps_usda_other)',
    denominator: 'n/a',
    time_period: 'HMDA 2025',
    entity_attribution_rule: 'institution_id',
    limitations: 'Not populated in current summaries.',
    safe_for_future_public_display: false,
    available_in_current_vintage: false,
  },
  {
    metric_key: 'states_with_hmda_activity',
    display_concept: 'States with HMDA activity observed',
    source: 'FFIEC HMDA 2025 state grain',
    numerator: 'count of distinct state_code with applications > 0',
    denominator: 'n/a',
    time_period: 'HMDA 2025',
    entity_attribution_rule: 'institution_id',
    limitations: 'Activity geography, not HQ and not “operates in” / licensed-in. One application is activity, not a branch.',
    safe_for_future_public_display: true,
    available_in_current_vintage: true,
  },
  {
    metric_key: 'counties_with_hmda_activity',
    display_concept: 'Counties with HMDA activity observed',
    source: 'FFIEC HMDA 2025 county grain',
    numerator: 'count of distinct county_fips with applications > 0',
    denominator: 'n/a',
    time_period: 'HMDA 2025',
    entity_attribution_rule: 'institution_id',
    limitations: 'Top counties stored; full county dump not in snapshot. Not a branch list.',
    safe_for_future_public_display: true,
    available_in_current_vintage: true,
  },
  {
    metric_key: 'cfpb_complaint_count',
    display_concept: 'Attributed CFPB mortgage complaints (all-time in graph)',
    source: 'CFPB Consumer Complaint Database',
    numerator: 'count of complaints where institution_id matches and attribution_confidence=confirmed',
    denominator: 'n/a',
    time_period: 'graph load (events 458,146); not a live CCDB pull',
    entity_attribution_rule: 'CONFIRMED company→institution bridge only',
    limitations: 'Unresolved source labels are excluded. Not a quality or risk score. Not enforcement.',
    safe_for_future_public_display: true,
    available_in_current_vintage: true,
  },
  {
    metric_key: 'cfpb_complaint_24m',
    display_concept: 'Attributed CFPB complaints in the 24-month window',
    source: 'CFPB CCDB',
    numerator: 'confirmed attributed complaints with date_received >= 2024-08-26',
    denominator: 'n/a',
    time_period: '2024-08-26 through graph load',
    entity_attribution_rule: 'CONFIRMED bridge only',
    limitations: 'Window matches LEND-NAT-006/010. Unresolved labels excluded. Not a score.',
    safe_for_future_public_display: true,
    available_in_current_vintage: true,
  },
  {
    metric_key: 'enforcement_event_count',
    display_concept: 'Authoritatively attributed federal enforcement events',
    source: 'OCC / FDIC ED&O / CFPB enforcement / Fed (as ingested)',
    numerator: 'distinct events joined to respondents with confidence=confirmed and institution_id set',
    denominator: 'n/a',
    time_period: 'source event dates; see issued_on',
    entity_attribution_rule: 'independent enforcement identifier (CERT/NMLS/LEI). CFPB complaint bridge is NOT sufficient.',
    limitations: 'NONE OBSERVED is not proof of no history. Name-only CFPB enforcement titles stay unattached.',
    safe_for_future_public_display: true,
    available_in_current_vintage: true,
  },
];

export const FORBIDDEN_PROFILE_KEYS = [
  'trustScore',
  'trust_score',
  'riskScore',
  'qualityScore',
  'complaintScore',
  'approvalScore',
  'grade',
  'ranking',
  'nationalVolumeRank',
  'bestLender',
  'worstLender',
] as const;
