import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";
import { executeAskQuery } from "../ask-lender/execute-query";
import { parseLenderAsk } from "../ask-lender/parse";
import { MS_BANK_FACILITIES, MS_CONSUMER_EXAMS, MISSISSIPPI_SNAPSHOT as ms } from "./snapshot";
import { normalizedPublishedStatePath } from "../seo/published-state-path";

test("Mississippi DBCF grains stay separate and match the HMDA county file", () => {
  const lic = ms.licensing;
  const csv = readFileSync(ms.hmda.source, "utf8").trim().split(/\r?\n/);
  const keys = csv[0]!.split(",");
  const records = csv.slice(1).map((line) => Object.fromEntries(line.split(",").map((value, index) => [keys[index], value])));
  const sum = (key: string) => records.reduce((total, row) => total + Number(row[key]), 0);
  assert.equal(records.length, 82);
  assert.equal(new Set(records.map((row) => row.county_fips)).size, 82);
  assert.equal(sum("total_applications"), ms.hmda.applications);
  assert.equal(sum("total_originations"), ms.hmda.originations);
  assert.equal(sum("denial_count"), ms.hmda.denials);
  assert.equal(sum("purchase_count"), ms.hmda.purchase);
  assert.equal(sum("refinance_count"), ms.hmda.refinance);
  assert.equal(sum("purpose_other_count"), ms.hmda.otherPurpose);
  assert.equal(sum("apps_conventional"), ms.hmda.conventional);
  assert.equal(sum("apps_fha"), ms.hmda.fha);
  assert.equal(sum("apps_va"), ms.hmda.va);
  assert.equal(sum("apps_usda_other"), ms.hmda.usdaOther);
  assert.equal(ms.hmda.purchase + ms.hmda.refinance + ms.hmda.otherPurpose, ms.hmda.applications);
  assert.equal(ms.hmda.conventional + ms.hmda.fha + ms.hmda.va + ms.hmda.usdaOther + ms.hmda.otherLoanType, ms.hmda.applications);
  assert.equal(Math.round((ms.hmda.denials / ms.hmda.applications) * 10000) / 100, ms.hmda.denialApplicationPct);
  assert.equal(readFileSync(ms.hmda.leiSummarySource, "utf8").trim().split(/\r?\n/).length - 1, 576);
  assert.equal(ms.hmda.leiRowsAreLicenses, false);
  assert.equal(ms.hmda.majorMarketSliceIsStatewide, false);
  assert.equal(lic.consumerFinanceCompanies + lic.mortgageLendersBranchesAndOriginators, lic.printedLicenseesElevenIndustries);
  assert.equal(lic.printedLicenseesIsMortgageCensus, false);
  assert.equal(lic.mortgageLenderCount, null);
  assert.equal(lic.mortgageBrokerCount, null);
  assert.equal(lic.mortgageServicerCount, null);
  assert.equal(lic.branchCount, null);
  assert.equal(lic.originatorCount, null);
  assert.equal(lic.nmlsBulkRoster, "NOT_ACQUIRED");
  assert.equal(ms.examinations.consumerFinanceExams + ms.examinations.mortgageExams, ms.examinations.printedCombinedExams);
  assert.equal(ms.examinations.mortgageFullExams + ms.examinations.mortgageLimitedExams, ms.examinations.mortgageExams);
  assert.equal(MS_CONSUMER_EXAMS.reduce((total, row) => total + row.exams, 0), ms.examinations.consumerFinanceExams);
  assert.equal(ms.examinations.findings, null);
  assert.equal(ms.penalties.actionCount, null);
  assert.equal(ms.penalties.nameOnlyAdverseJoins, 0);
  assert.equal(ms.banks.creditUnionCount, null);
  assert.equal(ms.banks.isMortgageLicense, false);
  for (const row of MS_BANK_FACILITIES) assert.equal(row.mississippiBranches + row.outOfStateBranches, row.branchSum);
  assert.equal(ms.newCanonicalOrganizations, 0);
  assert.equal(ms.graphWrites, 0);
  assert.equal(ms.claimEligibilityChanges, 0);
});

test("Mississippi page keeps the mixed mortgage sentence from banks and HMDA", () => {
  const page = readFileSync("app/mississippi/page.tsx", "utf8");
  const sitemap = readFileSync("app/sitemap.ts", "utf8");
  assert.match(page, /7,093/);
  assert.match(page, /2,092/);
  assert.match(page, /9,185/);
  assert.match(page, /102,491/);
  assert.match(page, /NOT_ACQUIRED/);
  assert.match(page, /not a company count/);
  assert.match(page, /not a DBCF license count/);
  assert.doesNotMatch(page, /AggregateRating|Trust Score|ratingValue/);
  assert.equal(existsSync("app/mississippi/jackson"), false);
  assert.equal(existsSync("app/mississippi/gulfport"), false);
  assert.equal(existsSync("app/mississippi/biloxi"), false);
  assert.equal((sitemap.match(/path: '\/mississippi'/g) ?? []).length, 1);
});

test("Mississippi Ask does not invent a lender, broker, or originator census", () => {
  const hmda = executeAskQuery({ q: "How many mortgage applications in Mississippi?" });
  assert.equal(hmda.countEvidence?.value, 102491);
  assert.match(JSON.stringify(hmda), /not institutions|applications/);
  const license = parseLenderAsk("HMDA applications in Mississippi");
  assert.equal(license.mode, "count");
  assert.equal(license.geography?.state, "MS");
  assert.equal(license.actionTaken?.[0], "application");
  assert.match(license.geography?.note ?? "", /not lender headquarters/);
  const mixed = parseLenderAsk("how many mortgage lenders in Mississippi");
  assert.match(mixed.failReason ?? "", /7,093/);
  assert.match(mixed.failReason ?? "", /not split/);
  assert.equal(mixed.count ?? null, null);
  const rank = parseLenderAsk("best mortgage lender in Mississippi");
  assert.match(rank.failReason ?? "", /does not rank/);
  const banks = parseLenderAsk("Mississippi state-chartered banks");
  assert.match(banks.failReason ?? "", /53/);
  assert.match(banks.failReason ?? "", /not a mortgage license/);
  const city = parseLenderAsk("mortgage lender Gulfport Mississippi");
  assert.match(city.failReason ?? "", /geography only/);
  const jackson = parseLenderAsk("mortgage lender Jackson");
  assert.equal(String(jackson.failClosedKind ?? "").startsWith("ms-"), false);
  const missouri = parseLenderAsk("mortgage brokers in Missouri");
  assert.equal(String(missouri.failClosedKind ?? "").startsWith("ms-"), false);
  const carolina = parseLenderAsk("mortgage lenders in South Carolina");
  assert.equal(carolina.failClosedKind, "sc-lender-servicer-license");
  assert.equal(normalizedPublishedStatePath("/Mississippi"), "/mississippi");
  assert.equal(normalizedPublishedStatePath("/mississippi/jackson"), null);
});
