/** MS-LEND-001. DBCF class sentences, examinations, and 2025 HMDA stay separate. */
export const MS_CONSUMER_EXAMS = [
  { industry: "Check casher", exams: 162 },
  { industry: "Credit availability", exams: 131 },
  { industry: "Motor vehicle sales finance", exams: 44 },
  { industry: "Pawnbroker", exams: 63 },
  { industry: "Small loan", exams: 182 },
  { industry: "Title pledge", exams: 38 },
  { industry: "Debt management", exams: 18 },
  { industry: "Money transmitter", exams: 8 },
] as const;

export const MS_BANK_FACILITIES = [
  { charter: "State banks", domiciles: 53, mississippiBranches: 655, outOfStateBranches: 721, branchSum: 1376, hostStateBranches: 206 },
  { charter: "State thrifts", domiciles: 0, mississippiBranches: 0, outOfStateBranches: 0, branchSum: 0, hostStateBranches: 0 },
  { charter: "Federal banks", domiciles: 4, mississippiBranches: 134, outOfStateBranches: 89, branchSum: 223, hostStateBranches: 79 },
  { charter: "Federal thrifts", domiciles: 2, mississippiBranches: 5, outOfStateBranches: 0, branchSum: 5, hostStateBranches: 0 },
] as const;

export const MISSISSIPPI_SNAPSHOT = {
  contract: "lender-ms-state-intel-v1",
  path: "/mississippi",
  generatedAt: "2026-10-05T18:45:00Z",
  retrievedAt: "2026-10-05",
  regulator: "Mississippi Department of Banking and Consumer Finance",
  sources: {
    annualReport: "https://dbcf.ms.gov/wp-content/uploads/2026/01/DBCF-Annual-Report-2025-Final-Draft-Alford-1-7.pdf",
    annualReportSha256: "e3ee862f5b090ac35a0fdab060c38eb7ba075984c4bd2a15175b6eb4ea57aec1",
    annualReportBytes: 8716329,
    annualReportPages: 26,
    mortgagePage: "https://dbcf.ms.gov/mortgage/",
    consumerFinancePage: "https://dbcf.ms.gov/consumer-finance/",
    nmls: "https://www.nmlsconsumeraccess.org/",
    statute: "Mississippi S.A.F.E. Mortgage Act, Miss. Code Ann. § 81-18-1 et seq.",
  },
  licensing: {
    clock: "2025-06-30",
    fiscalYear: "FY2025",
    consumerFinanceCompanies: 2092,
    consumerFinanceIndustries: 10,
    consumerFinanceClassesSplit: false,
    mortgageLendersBranchesAndOriginators: 7093,
    mortgageBucketMixesCompaniesBranchesAndPersons: true,
    mortgageLenderCount: null,
    mortgageBrokerCount: null,
    mortgageServicerCount: null,
    branchCount: null,
    originatorCount: null,
    printedLicenseesElevenIndustries: 9185,
    printedLicenseesIsMortgageCensus: false,
    nmlsBulkRoster: "NOT_ACQUIRED",
    licenseeRosterRows: null,
  },
  examinations: {
    clock: "FY2025",
    consumerFinanceExams: 646,
    mortgageExams: 167,
    mortgageFullExams: 98,
    mortgageLimitedExams: 69,
    printedCombinedExams: 813,
    findings: null,
  },
  penalties: {
    clock: "FY2025",
    consumerFinanceCivilMoneyPenaltiesCents: 166127628,
    consumerFinanceRefundsCents: 3071985,
    mortgageCivilMoneyPenaltiesCents: 1730000,
    mortgageRefundsCents: 185566,
    actionCount: null,
    exactCanonicalAttachments: 0,
    nameOnlyAdverseJoins: 0,
  },
  banks: {
    clock: "2025-06-30",
    stateCharteredCommercialBanks: 53,
    assetsThousands: 153498712,
    assetsPhrase: "over $153 billion",
    nonDepositoryTrustCompanies: 1,
    creditUnionCount: null,
    stateCharteredShareOfCharteredAssetsPhrase: "Approximately 88 percent",
    insolventOrLiquidatedBanks: 0,
    insolventWindow: "2024-07-01 through 2025-06-30",
    isMortgageLicense: false,
  },
  hmda: {
    year: 2025,
    source: "data/hmda/by-state/MS/county_market_summary.csv",
    leiSummarySource: "data/hmda/by-state/MS/lender_state_summary.csv",
    applications: 102491,
    originations: 54386,
    denials: 23222,
    denialApplicationPct: 22.66,
    counties: 82,
    leiSummaryRows: 576,
    leiRowsAreLicenses: false,
    purchase: 53447,
    refinance: 31082,
    otherPurpose: 17962,
    conventional: 72321,
    fha: 17405,
    va: 10848,
    usdaOther: 1917,
    otherLoanType: 0,
    majorMarketSliceRows: 18,
    majorMarketSliceIsStatewide: false,
  },
  newCanonicalOrganizations: 0,
  graphWrites: 0,
  claimEligibilityChanges: 0,
} as const;
