/** OK-LEND-001. ODCC consumer-credit classes, NMLS mortgage identities, and HMDA stay separate. */
export const OK_ODCC_CLASSES = [
  { id: "SL", label: "Supervised Lenders", inOklahoma: 781, allLocations: 1310 },
  { id: "OSL", label: "Oklahoma Small Lenders", inOklahoma: 89, allLocations: 103 },
  { id: "PB", label: "Pawn Brokers", inOklahoma: 218, allLocations: 218 },
  { id: "RTO", label: "Rent to Owns", inOklahoma: 176, allLocations: 216 },
  { id: "NOT", label: "Notifications", inOklahoma: 2274, allLocations: 2609 },
  { id: "SPA", label: "Health Spas", inOklahoma: 226, allLocations: 226 },
  { id: "PM", label: "Precious Metal and Gem Dealers", inOklahoma: 87, allLocations: 87 },
  { id: "CSO", label: "Credit Services Organizations", inOklahoma: 17, allLocations: 72 },
  { id: "CLF", label: "Consumer Litigation Funders", inOklahoma: 5, allLocations: 21 },
] as const;

export const OKLAHOMA_SNAPSHOT = {
  contract: "lender-ok-state-intel-v1",
  path: "/oklahoma",
  generatedAt: "2026-10-06T17:10:00Z",
  retrievedAt: "2026-10-06",
  regulator: "Oklahoma Department of Consumer Credit",
  sources: {
    rosterIndex: "https://oklahoma.gov/okdocc/licenses-we-regulate.html",
    printedAsOf: "2026-10-01",
    printedAsOfLabel: "Thursday, Oct 01, 2026",
    filenameClock: "2026-10-02",
    nmlsConsumerAccess: "http://www.nmlsconsumeraccess.org/",
  },
  mortgage: {
    brokerRoster: "NOT_ACQUIRED",
    lenderRoster: "NOT_ACQUIRED",
    companyRoster: "NOT_ACQUIRED",
    branchRoster: "NOT_ACQUIRED",
    originatorRoster: "NOT_ACQUIRED",
    nmlsBulkRoster: "NOT_ACQUIRED",
    bulkPath: "NMLS Consumer Access only",
  },
  odcc: {
    clock: "2026-10-01",
    classesAreMortgageLicenses: false,
    inStateAddedToAllLocations: false,
    classesAddedTogether: false,
  },
  hmda: {
    year: 2025,
    acceptedSource: "lib/home-intel/accepted-snapshot.json",
    acceptedGrain: "2025 jurisdiction aggregate already used by Ask",
    applications: 136810,
    originations: 78683,
    denials: 23493,
    denialApplicationPct: 17.17,
    countyFile: "data/hmda/by-state/OK/county_market_summary.csv",
    countyFileApplications: 139828,
    countyFileOriginations: 78683,
    countyFileDenials: 24704,
    countyFileCounties: 77,
    countyFileReplacesAccepted: false,
    leiSummarySource: "data/hmda/by-state/OK/lender_state_summary.csv",
    leiSummaryRows: 733,
    leiRowsAreLicenses: false,
    majorMarketSliceSource: "data/hmda/oklahoma/county_market_summary_ok.csv",
    majorMarketSliceRows: 26,
    majorMarketSliceIsStatewide: false,
  },
  notAcquired: {
    enforcementOrders: "NOT_ACQUIRED",
    complaints: "NOT_ACQUIRED",
    fdicInstitutionRecount: "NOT_RECOUNTED",
  },
  populationsAreAdded: false,
  newCanonicalOrganizations: 0,
  graphWrites: 0,
  claimEligibilityChanges: 0,
  exactCanonicalAttachments: 0,
  nameOnlyAdverseJoins: 0,
} as const;
