/** NE-LEND-001. Department counts are a 6/30/2024 annual-report clock, not a current NMLS roster. */
export const NEBRASKA_LENDER_SNAPSHOT = {
  regulator: 'Nebraska Department of Banking and Finance',
  reportUrl: 'https://ndbf.nebraska.gov/sites/default/files/reports/2024%20Annual%20Report_1.pdf',
  reportTitle: '2024 Nebraska Department of Banking and Finance Annual Report',
  httpLastModified: '2025-08-21T22:12:47Z',
  retrievedAt: '2026-10-06',
  sha256: '7787fe6654c2aadc9f3f56ba853ece3adec4ca646ab1af2d0b1c92a04cb2ba27',
  bytes: 10725018,
  clock: '2024-06-30',
  tableNote: 'Numbers include main offices only.',
  mortgageBankerCompanyLicenses: 499,
  mortgageLoanOriginators: 3954,
  stateCharteredBanks: 134,
  savingsAndLoanAssociations: 0,
  savingsAndLoanIsPrintedZero: true,
  creditUnions: 10,
  trustCompanies: 5,
  bankHoldingCompanies: 140,
  mortgageBrokerRoster: 'NOT_ACQUIRED',
  mortgageServicerRoster: 'NOT_ACQUIRED',
  branchRoster: 'NOT_ACQUIRED',
  nmlsIdentityRoster: 'NOT_ACQUIRED',
  mloPersonRoster: 'NOT_ACQUIRED',
  hmda: {
    vintage: 2025,
    acceptedStatewideAggregate: 'NOT_ACQUIRED',
    productSlice: 'data/hmda/nebraska',
    majorCountyMarkets: 14,
    leiStateSummaries: 491,
    highConfidenceLeiMaps: 117,
    hmdaIsLicensing: false,
  },
  graphWrites: 0,
  newCanonicalOrganizations: 0,
} as const;
