/** CT-LEND-001. Separate DOB license, NMLS identity, HMDA activity, and order grains. */
export const CONNECTICUT_SNAPSHOT = {
  contract_name: 'lender-ct-state-intel-v1',
  path: '/connecticut',
  generated_at: '2026-09-28T18:48:18Z',
  regulator: 'Connecticut Department of Banking',
  sources: {
    verification: 'https://portal.ct.gov/dob/consumer/consumer-complaints/nmls-consumer-access-instructions',
    licensing: 'https://portal.ct.gov/dob/about-dob/index-pages/verify-a-license',
    lender: 'https://portal.ct.gov/dob/consumer-credit-licenses/consumer-credit-licenses/mortgage-lenders-licensed-in-connecticut',
    broker: 'https://portal.ct.gov/dob/consumer-credit-licenses/consumer-credit-licenses/mortgage-brokers-licensed-in-connecticut',
    correspondent: 'https://portal.ct.gov/dob/consumer-credit-licenses/consumer-credit-licenses/mortgage-correspondent-lenders-licensed-in-connecticut',
    servicer: 'https://portal.ct.gov/dob/consumer-credit-licenses/consumer-credit-licenses/mortgage-servicers-licensed-in-connecticut',
    complaints: 'https://portal.ct.gov/dob/consumer/consumer-complaints/mortgage',
    ordersIndex: 'https://portal.ct.gov/dob/enforcement/administrative-orders-index-pages',
  },
  licensing: {
    roster: 'ACQUIRED',
    asOf: '2026-09-02',
    sourceStatus: 'LISTED_AS_LICENSED',
    liveVerification: 'KNOWN',
    nmlsPrintedRows: 0,
    exactRosterNmlsBridges: 0,
    note: 'Four DOB downloadable company-license lists also include branch-license rows. The workbooks print Connecticut license numbers but no NMLS ID field. Numeric license suffixes are not inferred to be NMLS IDs; confirm current status in NMLS Consumer Access.',
    mloPersonRoster: 'NOT_ACQUIRED',
    exemptEntityRoster: 'NOT_ACQUIRED',
  },
  hmda: {
    year: 2025, source: 'data/hmda/by-state/CT/county_market_summary.csv',
    applications: 123096, originations: 74032, denials: 21096, denialApplicationPct: 17.14,
    distinctLeis: 607, countyEquivalents: 9,
    purchase: 49415, refinance: 40771, otherPurpose: 32910,
    conventional: 104403, fha: 13392, va: 4890, usdaOther: 411,
    note: 'Connecticut-property HMDA activity across nine Census planning-region county-equivalents, not a Connecticut licensee census or quality measure.',
  },
  enforcement: {
    window: ['2022-01-01', '2026-09-28'],
    retrievedAt: '2026-09-28T18:48:18Z',
    scope: 'Selected DOB mortgage-related bulletin/order summaries; not a census of all 2022–2026 orders.',
    rows: [
      { date: '2022-03-24', respondent: 'Zenta Mortgage Services, LLC', grain: 'company', action: 'Consent Order; civil penalty', status: 'consent order; allegations resolved', nmls: '181658', stateLicense: null, bulletin: '3032', url: 'https://portal.ct.gov/DOB/Bulletin/2022/Bulletin-3032-April-1-2022', existingSlug: null },
      { date: '2023-06-05', respondent: 'FM Home Loans, LLC', grain: 'company', action: 'Consent Order; servicing-related resolution and civil penalty', status: 'consent order; allegations resolved', nmls: '2212', stateLicense: null, bulletin: '3094', url: 'https://portal.ct.gov/DOB/Bulletin/2023/Bulletin-3094-June-9-2023', existingSlug: 'fm-home-loans' },
      { date: '2023-10-27', respondent: 'Loan X Mortgage LLC', grain: 'company', action: 'Order revoking mortgage broker license, cease and desist, civil penalty', status: 'final order', nmls: '1879263', stateLicense: null, bulletin: '3116', url: 'https://portal.ct.gov/DOB/Bulletin/2023/Bulletin-3116-November-10-2023', existingSlug: null },
      { date: '2024-05-15', respondent: 'LoanSnap, Inc.', grain: 'company', action: 'Consent Order resolving prior notice', status: 'consent order; prior notice allegations not treated as findings', nmls: '76967', stateLicense: null, bulletin: '3143', url: 'https://portal.ct.gov/dob/bulletin/2024/bulletin-3143-may-17-2024', existingSlug: null },
      { date: '2025-09-15', respondent: 'Woodbridge Mortgage LLC', grain: 'company', action: 'Consent Order; mortgage broker license revoked', status: 'consent order with revocation', nmls: '72664', stateLicense: null, bulletin: '3213', url: 'https://portal.ct.gov/dob/bulletin/2025/bulletin-3213-september-19-2025', existingSlug: null },
      { date: '2025-09-15', respondent: 'Lionel Young Kim', grain: 'person/MLO', action: 'Consent Order; MLO license revoked', status: 'consent order with revocation', nmls: '229307', stateLicense: null, bulletin: '3213', url: 'https://portal.ct.gov/dob/bulletin/2025/bulletin-3213-september-19-2025', existingSlug: null },
      { date: '2025-09-15', respondent: 'George Guorong Wang', grain: 'person/MLO', action: 'Consent Order; MLO license revoked', status: 'consent order with revocation', nmls: '111145', stateLicense: null, bulletin: '3213', url: 'https://portal.ct.gov/dob/bulletin/2025/bulletin-3213-september-19-2025', existingSlug: null },
      { date: '2026-02-05', respondent: 'First Bank Mortgage, Inc. d/b/a Money Tree', grain: 'company', action: 'Joint Consent Order', status: 'consent order; alleged conduct described separately', nmls: '1291', stateLicense: null, bulletin: '3233', url: 'https://portal.ct.gov/dob/bulletin/2026/bulletin-3233-february-6-2026', existingSlug: null },
      { date: '2026-02-05', respondent: 'Meera Banta', grain: 'person/MLO', action: 'Joint Consent Order', status: 'consent order; alleged conduct described separately', nmls: '1582629', stateLicense: null, bulletin: '3233', url: 'https://portal.ct.gov/dob/bulletin/2026/bulletin-3233-february-6-2026', existingSlug: null },
      { date: '2026-08-12', respondent: 'NewRez LLC', grain: 'company', action: 'Multistate Settlement Agreement and Consent Order', status: 'consent order; regulator allegations distinguished', nmls: '3013', stateLicense: null, bulletin: '3262', url: 'https://portal.ct.gov/dob/bulletin/2026/bulletin-3262-august-28-2026', existingSlug: null },
      { date: '2026-08-27', respondent: 'Franklin Credit Management Corporation', grain: 'company', action: 'Consent Order; civil penalty and late-fee refunds', status: 'consent order', nmls: '2102', stateLicense: null, bulletin: '3262', url: 'https://portal.ct.gov/dob/bulletin/2026/bulletin-3262-august-28-2026', existingSlug: null },
    ],
    exactNmlsRespondentRows: 11,
    exactStateLicenseRespondentRows: 0,
    existingCanonicalAttachments: 1,
    nameOnlyAttachments: 0,
    note: 'Each printed NMLS number identifies its bulletin respondent, not a Connecticut license number. Only FM Home Loans has an independently exact NMLS match in the existing hub catalog; no adverse name match or graph write was made.',
  },
  complaints: { intake: 'KNOWN', providerRows: 'NOT_ACQUIRED', outcomes: 'REQUEST_ONLY' },
  graph: { netNewCanonicalOrganizations: 0, writes: 0, claimEligibilityChanged: false },
} as const;
