import type { Lender } from '@/lib/mockData';

export const ARIZONA_LENDERS: Lender[] = [
  // ── Maricopa County (West Valley — Buckeye & Goodyear) ───────────────────────
  {
    id: 'az-01', slug: 'barrett-financial-group-west-valley', name: 'Barrett Financial Group', nmlsId: '181106', type: 'Broker',
    city: 'Buckeye', state: 'Arizona', stateSlug: 'arizona', county: 'Maricopa', countySlug: 'maricopa',
    zipCodes: ['85326', '85396', '85338'], rating: 4.9, reviewCount: 2400, trustScore: 96, countyExperienceScore: 97,
    nationalVolumeRank: 32, loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Jumbo', 'Refinance'],
    specialties: ['New-Construction', 'Master-Planned Communities', 'West Valley Growth'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 26, onTimeCloseRate: 96,
    shortDescription: 'Arizona independent broker — deep West Valley expertise for Verrado, Tartesso, and master-planned new-home financing.',
    website: 'https://barrettfinancial.com', phone: '(602) 429-3400',
  },
  {
    id: 'az-02', slug: 'guild-mortgage-west-valley', name: 'Guild Mortgage (West Valley Branches)', nmlsId: '3274', type: 'Lender',
    city: 'Goodyear', state: 'Arizona', stateSlug: 'arizona', county: 'Maricopa', countySlug: 'maricopa',
    zipCodes: ['85338', '85326', '85395'], rating: 4.8, reviewCount: 720, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['West Valley Presence', 'Full-Spectrum Lending', 'Construction-to-Permanent'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with West Valley branches for Buckeye/Goodyear boom markets and corporate relocations.',
    website: 'https://guildmortgage.com', phone: '(623) 555-8001',
  },
  {
    id: 'az-03', slug: 'new-american-funding-west-valley', name: 'New American Funding (West Valley)', nmlsId: '6606', type: 'Lender',
    city: 'Buckeye', state: 'Arizona', stateSlug: 'arizona', county: 'Maricopa', countySlug: 'maricopa',
    zipCodes: ['85326', '85396', '85338'], rating: 4.9, reviewCount: 580, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['High-Volume Service', 'Explosive Growth Zones', 'Purchase & Refinance'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'NAF West Valley team — excellent ratings for fast transactions in Buckeye and Goodyear growth corridors.',
    website: 'https://newamericanfunding.com', phone: '(623) 555-8002',
  },
  {
    id: 'az-04', slug: 'crosscountry-mortgage-west-valley', name: 'CrossCountry Mortgage (West Valley)', nmlsId: '3029', type: 'Lender',
    city: 'Goodyear', state: 'Arizona', stateSlug: 'arizona', county: 'Maricopa', countySlug: 'maricopa',
    zipCodes: ['85338', '85395', '85326'], rating: 4.8, reviewCount: 490, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['I-10 / Loop 303 Corridor', 'Corporate Relocations', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry West Valley — experienced support for logistics and corporate buyers along the I-10/303 expansion.',
    website: 'https://crosscountrymortgage.com', phone: '(623) 555-8004',
  },
  {
    id: 'az-05', slug: 'pierpoint-mortgage-phoenix-west', name: 'PierPoint Mortgage (Phoenix West)', nmlsId: '112844', type: 'Broker',
    city: 'Buckeye', state: 'Arizona', stateSlug: 'arizona', county: 'Maricopa', countySlug: 'maricopa',
    zipCodes: ['85326', '85338', '85396'], rating: 4.9, reviewCount: 210, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Master-Planned Communities'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 25, onTimeCloseRate: 96,
    shortDescription: 'Wholesale broker with transparent fees — speed and transparency for Buckeye and Goodyear new-home communities.',
    website: 'https://pierpointmortgage.com', phone: '(623) 555-8005',
  },
  {
    id: 'az-06', slug: 'silverton-mortgage-west-valley', name: 'Silverton Mortgage — West Valley', nmlsId: '1561', type: 'Lender',
    city: 'Goodyear', state: 'Arizona', stateSlug: 'arizona', county: 'Maricopa', countySlug: 'maricopa',
    zipCodes: ['85338', '85395', '85326'], rating: 4.8, reviewCount: 175, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Healthcare & Logistics Corridors', 'Retail Local Expertise', 'Goodyear Focus'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 29, onTimeCloseRate: 95,
    shortDescription: 'Silverton West Valley retail lending — professional service for healthcare and logistics-driven Goodyear demand.',
    website: 'https://silvertonmortgage.com', phone: '(623) 555-8006',
  },
  {
    id: 'az-07', slug: 'veterans-united-west-valley', name: 'Veterans United Home Loans (West Valley)', nmlsId: '1907', type: 'Lender',
    city: 'Buckeye', state: 'Arizona', stateSlug: 'arizona', county: 'Maricopa', countySlug: 'maricopa',
    zipCodes: ['85326', '85396', '85338'], rating: 4.9, reviewCount: 2200, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 8, loanTypes: ['VA', 'Refinance'],
    specialties: ['VA Loans', 'Military Relocations', 'Luke AFB Corridor'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 15, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 32, onTimeCloseRate: 94,
    shortDescription: 'Leading VA lender — tailored relocation packages for military and corporate movers in West Valley boomtowns.',
    website: 'https://veteransunited.com', phone: '(623) 555-8007',
  },
  {
    id: 'az-08', slug: 'desert-financial-credit-union', name: 'Desert Financial Credit Union', nmlsId: '430888', type: 'Credit Union',
    city: 'Goodyear', state: 'Arizona', stateSlug: 'arizona', county: 'Maricopa', countySlug: 'maricopa',
    zipCodes: ['85338', '85326', '85395'], rating: 4.9, reviewCount: 890, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 65, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Affordable New-Home Programs', 'Community-Focused'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 31, onTimeCloseRate: 94,
    shortDescription: 'Phoenix-metro credit union with member rates and affordable programs in the high-volume West Valley growth corridor.',
    website: 'https://desertfinancial.com', phone: '(602) 433-7000',
  },
  {
    id: 'az-09', slug: 'dhi-mortgage-buckeye', name: 'DHI Mortgage (Buckeye / West Valley)', nmlsId: '14622', type: 'Lender',
    city: 'Buckeye', state: 'Arizona', stateSlug: 'arizona', county: 'Maricopa', countySlug: 'maricopa',
    zipCodes: ['85326', '85396', '85338'], rating: 4.8, reviewCount: 650, trustScore: 92, countyExperienceScore: 95,
    nationalVolumeRank: 18, loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Refinance'],
    specialties: ['Verrado & Tartesso', 'Master-Planned Communities', 'Builder Partnerships'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'New-construction specialist for large-scale Buckeye developments — Verrado, Tartesso, and DR Horton communities.',
    website: 'https://dhimortgage.com', phone: '(623) 555-8009',
  },
  {
    id: 'az-10', slug: 'anchor-home-mortgage-goodyear', name: 'Anchor Home Mortgage (Goodyear)', nmlsId: '136890', type: 'Broker',
    city: 'Goodyear', state: 'Arizona', stateSlug: 'arizona', county: 'Maricopa', countySlug: 'maricopa',
    zipCodes: ['85338', '85395', '85326'], rating: 4.9, reviewCount: 195, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 56, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['$430K Median Segment', 'Family Buyers', 'Personalized Brokerage'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 27, onTimeCloseRate: 96,
    shortDescription: 'Personalized Goodyear brokerage — strong focus on family buyers in the $430K median West Valley segment.',
    website: 'https://anchorhomemortgage.com', phone: '(623) 555-8010',
  },
  {
    id: 'az-11', slug: 'bank-of-america-mortgage-west-valley', name: 'Bank of America Mortgage (West Valley)', nmlsId: '399802', type: 'Bank',
    city: 'Goodyear', state: 'Arizona', stateSlug: 'arizona', county: 'Maricopa', countySlug: 'maricopa',
    zipCodes: ['85338', '85326', '85395'], rating: 4.6, reviewCount: 780, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Relocation Financing', 'Full-Service Banking', 'Corporate Expansions'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 35, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for corporate expansions and logistics hub relocations in West Valley.',
    website: 'https://bankofamerica.com/mortgage', phone: '(623) 555-8011',
  },
  {
    id: 'az-12', slug: 'nova-home-loans-west-valley', name: 'Nova Home Loans (West Valley)', nmlsId: '3089', type: 'Lender',
    city: 'Buckeye', state: 'Arizona', stateSlug: 'arizona', county: 'Maricopa', countySlug: 'maricopa',
    zipCodes: ['85326', '85396', '85338'], rating: 4.8, reviewCount: 420, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 38, loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Refinance'],
    specialties: ['Investor Financing', 'First-Time Buyers', '37%+ Population Growth'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 29, onTimeCloseRate: 94,
    shortDescription: 'Arizona regional lender — investor and first-time buyer expertise in Buckeye and Goodyear boomtown dynamics.',
    website: 'https://novahomeloans.com', phone: '(623) 555-8012',
  },
];

export const WEST_VALLEY_LENDER_SLUGS = [
  'barrett-financial-group-west-valley',
  'guild-mortgage-west-valley',
  'new-american-funding-west-valley',
  'crosscountry-mortgage-west-valley',
  'pierpoint-mortgage-phoenix-west',
  'silverton-mortgage-west-valley',
  'veterans-united-west-valley',
  'desert-financial-credit-union',
  'dhi-mortgage-buckeye',
  'anchor-home-mortgage-goodyear',
  'bank-of-america-mortgage-west-valley',
  'nova-home-loans-west-valley',
] as const;

export const ARIZONA_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  maricopa: [],
};

export const WEST_VALLEY_HUB_AREAS = [
  { name: 'Buckeye', slug: 'maricopa', highlight: 'Verrado, Tartesso, 37%+ population growth' },
  { name: 'Goodyear', slug: 'maricopa', highlight: 'Healthcare, logistics, $430K median' },
  { name: 'Avondale', slug: 'maricopa', highlight: 'Loop 303 corridor — coming soon' },
  { name: 'Surprise', slug: 'maricopa', highlight: 'Northwest growth belt — coming soon' },
] as const;