import type { Lender } from '@/lib/mockData';

export const CALIFORNIA_LENDERS: Lender[] = [
  // ── Santa Clara County (Silicon Valley Spine — San Jose & Cupertino) ─────────
  {
    id: 'ca-01', slug: 'c2-financial-silicon-valley', name: 'C2 Financial Corporation', nmlsId: '135622', type: 'Broker',
    city: 'San Jose', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95110', '95014', '95113'], rating: 4.9, reviewCount: 1850, trustScore: 97, countyExperienceScore: 98,
    nationalVolumeRank: 30, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'ARM', 'Refinance'],
    specialties: ['Jumbo & Cash-Heavy Deals', 'Tech Corridor Expertise', 'Multiple-Offer Strategy'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 97,
    shortDescription: 'California independent broker network — deep Silicon Valley expertise for ultra-competitive San Jose and Cupertino transactions.',
    website: 'https://c2financial.com', phone: '(408) 555-9001',
  },
  {
    id: 'ca-02', slug: 'guild-mortgage-silicon-valley', name: 'Guild Mortgage (Silicon Valley)', nmlsId: '3274', type: 'Lender',
    city: 'San Jose', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95110', '95014', '95125'], rating: 4.8, reviewCount: 640, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['High-Net-Worth Focus', 'Full Residential', 'Santa Clara Operations'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Silicon Valley presence — sophisticated jumbo and high-value financing for Santa Clara County.',
    website: 'https://guildmortgage.com', phone: '(408) 555-9002',
  },
  {
    id: 'ca-03', slug: 'new-american-funding-san-jose', name: 'New American Funding (San Jose)', nmlsId: '6606', type: 'Lender',
    city: 'San Jose', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95110', '95113', '95014'], rating: 4.9, reviewCount: 520, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Tech Professionals', 'Above-List Offers', 'High-Volume Service'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'NAF San Jose team — strong support for tech professionals in multiple-offer, above-list Silicon Valley transactions.',
    website: 'https://newamericanfunding.com', phone: '(408) 555-9003',
  },
  {
    id: 'ca-04', slug: 'crosscountry-mortgage-silicon-valley', name: 'CrossCountry Mortgage (Silicon Valley)', nmlsId: '3029', type: 'Lender',
    city: 'Cupertino', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95014', '95110', '95050'], rating: 4.8, reviewCount: 410, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['AI & Semiconductor Buyers', 'Stock-Liquidity Relocations', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Cupertino teams — experienced lending for AI and semiconductor professionals with RSU-driven income.',
    website: 'https://crosscountrymortgage.com', phone: '(408) 555-9004',
  },
  {
    id: 'ca-05', slug: 'pierpoint-mortgage-bay-area', name: 'PierPoint Mortgage (Bay Area)', nmlsId: '112844', type: 'Broker',
    city: 'San Jose', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95110', '95014', '95112'], rating: 4.9, reviewCount: 195, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['12–13 Day DOM Market', 'Fast Closings', 'Wholesale Access'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed-critical closings for Santa Clara\'s blistering 12–13 day on-market pace.',
    website: 'https://pierpointmortgage.com', phone: '(408) 555-9005',
  },
  {
    id: 'ca-06', slug: 'silverton-mortgage-san-jose', name: 'Silverton Mortgage — San Jose', nmlsId: '1561', type: 'Lender',
    city: 'San Jose', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95110', '95125', '95014'], rating: 4.8, reviewCount: 165, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Tech Expertise', 'Constrained Inventory', 'Retail Local Service'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton San Jose retail lending — professional service for constrained-inventory, cash-competitive deals.',
    website: 'https://silvertonmortgage.com', phone: '(408) 555-9006',
  },
  {
    id: 'ca-07', slug: 'city-national-bank-mortgage', name: 'City National Bank Mortgage', nmlsId: '5369', type: 'Bank',
    city: 'Cupertino', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95014', '95110', '95113'], rating: 4.8, reviewCount: 280, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 45, loanTypes: ['Jumbo', 'Conventional', 'ARM', 'Refinance'],
    specialties: ['Portfolio Loans', 'High-Net-Worth', 'Stock Compensation'],
    creditTiers: ['Excellent'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'Private bank mortgage arm — jumbo and portfolio lending tailored for generational wealth and stock-comp buyers.',
    website: 'https://cnb.com', phone: '(408) 555-9007',
  },
  {
    id: 'ca-08', slug: 'veterans-united-silicon-valley', name: 'Veterans United Home Loans (Silicon Valley)', nmlsId: '1907', type: 'Lender',
    city: 'San Jose', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95110', '95014', '95112'], rating: 4.9, reviewCount: 1100, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 8, loanTypes: ['VA', 'Refinance'],
    specialties: ['VA Loans', 'Executive Relocations', 'Military-Affiliated Tech'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 15, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 32, onTimeCloseRate: 94,
    shortDescription: 'VA and executive relocation programs — support for military-affiliated and high-earning tech migrants in Santa Clara.',
    website: 'https://veteransunited.com', phone: '(408) 555-9008',
  },
  {
    id: 'ca-09', slug: 'first-tech-federal-credit-union', name: 'First Tech Federal Credit Union', nmlsId: '732452', type: 'Credit Union',
    city: 'San Jose', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95110', '95014', '95125'], rating: 4.9, reviewCount: 720, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 68, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Tech-Employee CU', 'Member Rates', 'Constrained Supply Market'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Tech-employee credit union — competitive member rates for qualified professionals in ultra-tight Santa Clara inventory.',
    website: 'https://firsttechfed.com', phone: '(855) 855-8805',
  },
  {
    id: 'ca-10', slug: 'jvm-lending-cupertino', name: 'JVM Lending (Cupertino)', nmlsId: '310167', type: 'Lender',
    city: 'Cupertino', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95014', '95110', '95050'], rating: 4.9, reviewCount: 890, trustScore: 96, countyExperienceScore: 97,
    nationalVolumeRank: 40, loanTypes: ['Jumbo', 'Conventional', 'ARM', 'Refinance'],
    specialties: ['Premium Estates', 'Non-Contingent Contracts', 'Modern New Builds'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.9, avgCloseDays: 24, onTimeCloseRate: 96,
    shortDescription: 'Bay Area jumbo specialist — expertise in Cupertino luxury, multiple-offer, and non-contingent contract scenarios.',
    website: 'https://jvmlending.com', phone: '(408) 555-9010',
  },
  {
    id: 'ca-11', slug: 'bank-of-america-mortgage-silicon-valley', name: 'Bank of America Mortgage (Silicon Valley)', nmlsId: '399802', type: 'Bank',
    city: 'San Jose', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95110', '95014', '95113'], rating: 4.6, reviewCount: 920, trustScore: 89, countyExperienceScore: 91,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['High-Value Financing', 'Corporate Relocation', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 34, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages for corporate relocation packages and high-value San Jose/Cupertino purchases.',
    website: 'https://bankofamerica.com/mortgage', phone: '(408) 555-9011',
  },
  {
    id: 'ca-12', slug: 'bay-equity-home-loans-silicon-valley', name: 'Bay Equity Home Loans (Silicon Valley)', nmlsId: '76901', type: 'Lender',
    city: 'Cupertino', state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara',
    zipCodes: ['95014', '95110', '95112'], rating: 4.9, reviewCount: 540, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 36, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['65–68% Above-List Dynamics', 'Personalized Brokerage', 'Ultra-Competitive Deals'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'California-based lender — localized expertise in above-list, ultra-competitive Silicon Valley offer dynamics.',
    website: 'https://bayequityhomeloans.com', phone: '(408) 555-9012',
  },
];

export const SILICON_VALLEY_LENDER_SLUGS = [
  'c2-financial-silicon-valley',
  'guild-mortgage-silicon-valley',
  'new-american-funding-san-jose',
  'crosscountry-mortgage-silicon-valley',
  'pierpoint-mortgage-bay-area',
  'silverton-mortgage-san-jose',
  'city-national-bank-mortgage',
  'veterans-united-silicon-valley',
  'first-tech-federal-credit-union',
  'jvm-lending-cupertino',
  'bank-of-america-mortgage-silicon-valley',
  'bay-equity-home-loans-silicon-valley',
] as const;

export const CALIFORNIA_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  'santa-clara': [],
};

export const SILICON_VALLEY_HUB_AREAS = [
  { name: 'San Jose', slug: 'santa-clara', highlight: 'AI corridor, $1.5M+ medians, 12-day DOM' },
  { name: 'Cupertino', slug: 'santa-clara', highlight: 'Semiconductor hub, premium estates' },
  { name: 'Sunnyvale', slug: 'santa-clara', highlight: 'Tech campuses — coming soon' },
  { name: 'Palo Alto', slug: 'santa-clara', highlight: 'Venture capital corridor — coming soon' },
] as const;