import type { Lender } from '@/lib/mockData';

export const COLORADO_LENDERS: Lender[] = [
  // ── Denver Metro Outer Rings & North Suburbs (Adams, Boulder, Douglas) ───────
  {
    id: 'co-01', slug: 'american-financing-denver-north', name: 'American Financing (Denver North)', nmlsId: '227262', type: 'Broker',
    city: 'Erie', state: 'Colorado', stateSlug: 'colorado', county: 'Adams', countySlug: 'adams',
    zipCodes: ['80516', '80026', '80134'], rating: 4.9, reviewCount: 2100, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 32, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Master-Planned Communities', 'New Construction', 'Outer-Ring Growth'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Denver-area independent broker — deep expertise in Erie master-planned communities and north suburban new construction.',
    website: 'https://americanfinancing.net', phone: '(303) 555-9301',
  },
  {
    id: 'co-02', slug: 'guild-mortgage-denver-north', name: 'Guild Mortgage (Denver Metro North)', nmlsId: '3274', type: 'Lender',
    city: 'Erie', state: 'Colorado', stateSlug: 'colorado', county: 'Adams', countySlug: 'adams',
    zipCodes: ['80516', '80026', '80134'], rating: 4.8, reviewCount: 480, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'North Suburbs', 'Family Relocations'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Denver Metro North branches — comprehensive financing for Erie and Lafayette outer-ring growth.',
    website: 'https://guildmortgage.com', phone: '(303) 555-9302',
  },
  {
    id: 'co-03', slug: 'pierpoint-mortgage-denver-metro', name: 'PierPoint Mortgage (Denver Metro)', nmlsId: '112844', type: 'Broker',
    city: 'Erie', state: 'Colorado', stateSlug: 'colorado', county: 'Adams', countySlug: 'adams',
    zipCodes: ['80516', '80134', '80112'], rating: 4.9, reviewCount: 185, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Master-Planned Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to Erie and Parker master-planned new construction purchase timelines.',
    website: 'https://pierpointmortgage.com', phone: '(303) 555-9305',
  },
  {
    id: 'co-04', slug: 'lennar-mortgage-denver-outer-rings', name: 'Lennar Mortgage (Denver Outer Rings)', nmlsId: '1058', type: 'Lender',
    city: 'Erie', state: 'Colorado', stateSlug: 'colorado', county: 'Adams', countySlug: 'adams',
    zipCodes: ['80516', '80134', '80112'], rating: 4.7, reviewCount: 360, trustScore: 90, countyExperienceScore: 92,
    nationalVolumeRank: 35, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Master-Planned Financing', 'Modern Layouts', 'Steady Inventory Growth'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 8, bbbRating: 'A',
    googleRating: 4.7, trustpilotRating: 4.5, avgCloseDays: 30, onTimeCloseRate: 92,
    shortDescription: 'Builder-affiliated lender — expertise in Erie and Parker master-planned community financing.',
    website: 'https://lennar.com/mortgage', phone: '(303) 555-9309',
  },
  {
    id: 'co-05', slug: 'crosscountry-mortgage-north-suburbs', name: 'CrossCountry Mortgage (North Suburbs)', nmlsId: '3029', type: 'Lender',
    city: 'Louisville', state: 'Colorado', stateSlug: 'colorado', county: 'Boulder', countySlug: 'boulder',
    zipCodes: ['80027', '80026', '80516'], rating: 4.8, reviewCount: 390, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Tech Corridor Buyers', 'High-Earning Suburban Relocations', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Louisville teams — experienced support for Lafayette and Louisville tech-corridor suburban relocations.',
    website: 'https://crosscountrymortgage.com', phone: '(303) 555-9304',
  },
  {
    id: 'co-06', slug: 'elevations-credit-union', name: 'Elevations Credit Union', nmlsId: '400025', type: 'Credit Union',
    city: 'Lafayette', state: 'Colorado', stateSlug: 'colorado', county: 'Boulder', countySlug: 'boulder',
    zipCodes: ['80026', '80027', '80516'], rating: 4.9, reviewCount: 580, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 70, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Community Lender', 'Affordable Suburban Options'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Boulder-area credit union — community-focused member rates in high-growth north suburban corridors.',
    website: 'https://elevationscu.com', phone: '(800) 429-7626',
  },
  {
    id: 'co-07', slug: 'anchor-home-mortgage-louisville', name: 'Anchor Home Mortgage (Louisville)', nmlsId: '136890', type: 'Broker',
    city: 'Louisville', state: 'Colorado', stateSlug: 'colorado', county: 'Boulder', countySlug: 'boulder',
    zipCodes: ['80027', '80026', '80112'], rating: 4.9, reviewCount: 290, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Tech Corridor Demand', 'School-Driven Buyers', 'Personalized Brokerage'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on Lafayette and Louisville school-driven and tech-corridor demand.',
    website: 'https://anchorhomemortgage.com', phone: '(303) 555-9310',
  },
  {
    id: 'co-08', slug: 'veterans-united-denver-outer-rings', name: 'Veterans United Home Loans (Denver Outer Rings)', nmlsId: '1907', type: 'Lender',
    city: 'Lafayette', state: 'Colorado', stateSlug: 'colorado', county: 'Boulder', countySlug: 'boulder',
    zipCodes: ['80026', '80516', '80134'], rating: 4.9, reviewCount: 920, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 8, loanTypes: ['VA', 'FHA', 'Refinance'],
    specialties: ['VA Loans', 'Move-Up Family Programs', 'New Build Support'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 15, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'VA and family relocation programs — tailored for Erie and Parker families seeking new builds and excellent schools.',
    website: 'https://veteransunited.com', phone: '(303) 555-9307',
  },
  {
    id: 'co-09', slug: 'new-american-funding-denver-suburbs', name: 'New American Funding (Denver Suburbs)', nmlsId: '6606', type: 'Lender',
    city: 'Parker', state: 'Colorado', stateSlug: 'colorado', county: 'Douglas', countySlug: 'douglas',
    zipCodes: ['80134', '80112', '80516'], rating: 4.9, reviewCount: 440, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['New-Build Volume', 'Family Transactions', 'Purchase & Refinance'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'NAF Parker team — excellent ratings for new-build and family transactions in Douglas County suburbs.',
    website: 'https://newamericanfunding.com', phone: '(303) 555-9303',
  },
  {
    id: 'co-10', slug: 'silverton-mortgage-denver-suburbs', name: 'Silverton Mortgage — Denver Suburbs', nmlsId: '1561', type: 'Lender',
    city: 'Centennial', state: 'Colorado', stateSlug: 'colorado', county: 'Douglas', countySlug: 'douglas',
    zipCodes: ['80112', '80134', '80027'], rating: 4.8, reviewCount: 170, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Top-Tier School Districts', 'Suburban Retail Expertise', 'Family-Oriented Suburbs'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Centennial retail lending — professional service for Parker and Centennial school-district buyers.',
    website: 'https://silvertonmortgage.com', phone: '(303) 555-9306',
  },
  {
    id: 'co-11', slug: 'bank-of-america-mortgage-denver-suburbs', name: 'Bank of America Mortgage (Denver Suburbs)', nmlsId: '399802', type: 'Bank',
    city: 'Parker', state: 'Colorado', stateSlug: 'colorado', county: 'Douglas', countySlug: 'douglas',
    zipCodes: ['80134', '80112', '80026'], rating: 4.6, reviewCount: 710, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Relocation Financing', 'Full-Service Banking', 'Corporate Family Moves'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 32, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for corporate and family relocations to Parker and Centennial outer rings.',
    website: 'https://bankofamerica.com/mortgage', phone: '(303) 555-9311',
  },
  {
    id: 'co-12', slug: 'nova-home-loans-denver-outer-rings', name: 'Nova Home Loans (Denver Outer Rings)', nmlsId: '3089', type: 'Lender',
    city: 'Centennial', state: 'Colorado', stateSlug: 'colorado', county: 'Douglas', countySlug: 'douglas',
    zipCodes: ['80112', '80134', '80516'], rating: 4.8, reviewCount: 410, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Family Growth Suburbs', 'Bidding-War Avoidance'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'Colorado lender — localized knowledge of Erie and Centennial growth suburbs with new-build appeal beyond urban-core bidding wars.',
    website: 'https://novahomeloans.com', phone: '(303) 555-9312',
  },
];

export const DENVER_OUTER_RINGS_LENDER_SLUGS = [
  'american-financing-denver-north',
  'guild-mortgage-denver-north',
  'pierpoint-mortgage-denver-metro',
  'lennar-mortgage-denver-outer-rings',
  'crosscountry-mortgage-north-suburbs',
  'elevations-credit-union',
  'anchor-home-mortgage-louisville',
  'veterans-united-denver-outer-rings',
  'new-american-funding-denver-suburbs',
  'silverton-mortgage-denver-suburbs',
  'bank-of-america-mortgage-denver-suburbs',
  'nova-home-loans-denver-outer-rings',
] as const;

const ADAMS_SUPPLEMENTS = [
  'crosscountry-mortgage-north-suburbs',
  'elevations-credit-union',
  'anchor-home-mortgage-louisville',
  'veterans-united-denver-outer-rings',
  'new-american-funding-denver-suburbs',
  'silverton-mortgage-denver-suburbs',
  'bank-of-america-mortgage-denver-suburbs',
  'nova-home-loans-denver-outer-rings',
];

const BOULDER_SUPPLEMENTS = [
  'american-financing-denver-north',
  'guild-mortgage-denver-north',
  'pierpoint-mortgage-denver-metro',
  'lennar-mortgage-denver-outer-rings',
  'new-american-funding-denver-suburbs',
  'silverton-mortgage-denver-suburbs',
  'bank-of-america-mortgage-denver-suburbs',
  'nova-home-loans-denver-outer-rings',
];

const DOUGLAS_SUPPLEMENTS = [
  'american-financing-denver-north',
  'guild-mortgage-denver-north',
  'pierpoint-mortgage-denver-metro',
  'lennar-mortgage-denver-outer-rings',
  'crosscountry-mortgage-north-suburbs',
  'elevations-credit-union',
  'anchor-home-mortgage-louisville',
  'veterans-united-denver-outer-rings',
];

export const COLORADO_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  adams: ADAMS_SUPPLEMENTS,
  boulder: BOULDER_SUPPLEMENTS,
  douglas: DOUGLAS_SUPPLEMENTS,
};

export const DENVER_OUTER_RINGS_HUB_COUNTIES = [
  { name: 'Adams', slug: 'adams', highlight: 'Erie master-planned, north suburban growth' },
  { name: 'Boulder', slug: 'boulder', highlight: 'Lafayette & Louisville, tech corridor schools' },
  { name: 'Douglas', slug: 'douglas', highlight: 'Parker & Centennial, top-tier school districts' },
] as const;

export const DENVER_OUTER_RINGS_HUB_AREAS = [
  { name: 'Erie', slug: 'adams', highlight: 'Master-planned communities, new construction' },
  { name: 'Parker', slug: 'douglas', highlight: 'Family suburbs, move-up buyers' },
  { name: 'Centennial', slug: 'douglas', highlight: 'Top schools, bidding-war avoidance' },
  { name: 'Lafayette', slug: 'boulder', highlight: 'Tech corridor access, north suburbs' },
  { name: 'Louisville', slug: 'boulder', highlight: 'Elite schools, suburban exurban appeal' },
] as const;