import type { Lender } from '@/lib/mockData';

export const DISTRICT_OF_COLUMBIA_LENDERS: Lender[] = [
  // ── Upper Northwest Value Surge (Takoma & Brightwood — Zip 20012) ─────────────
  {
    id: 'dc-01', slug: 'ward3-home-mortgage-upper-northwest', name: 'Ward 3 Home Mortgage (Upper Northwest)', nmlsId: '198472', type: 'Broker',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20012', '20011', '20017'], rating: 4.9, reviewCount: 620, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 38, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Single-Family Value Plays', 'Northern DC Neighborhood Gains', 'Metro-Access Homes'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'DC independent broker — deep expertise in Takoma and Brightwood single-family value-play financing in Ward 3 North.',
    website: 'https://ward3homemortgage.com', phone: '(202) 555-1201',
  },
  {
    id: 'dc-02', slug: 'guild-mortgage-dc-upper-northwest', name: 'Guild Mortgage (DC Upper Northwest)', nmlsId: '3274', type: 'Lender',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20012', '20011', '20017'], rating: 4.8, reviewCount: 420, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Single-Family Value Expertise', 'DC Metro Branches'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with DC branches — comprehensive financing for standalone single-family homes in high-appreciation northern neighborhoods.',
    website: 'https://guildmortgage.com', phone: '(202) 555-1202',
  },
  {
    id: 'dc-03', slug: 'new-american-funding-dc-upper-northwest', name: 'New American Funding (DC)', nmlsId: '6606', type: 'Lender',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20012', '20011', '20017'], rating: 4.9, reviewCount: 385, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Metro-Access Neighborhoods', 'Takoma/Brightwood Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'NAF DC team — excellent ratings for Metro-access Takoma and Brightwood purchase demand in Zip 20012.',
    website: 'https://newamericanfunding.com', phone: '(202) 555-1203',
  },
  {
    id: 'dc-04', slug: 'crosscountry-mortgage-dc-upper-northwest', name: 'CrossCountry Mortgage (DC)', nmlsId: '3029', type: 'Lender',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20012', '20011', '20017'], rating: 4.8, reviewCount: 330, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Families Seeking Yards & Trees', 'Classic DC Neighborhood Feel', 'Ward 3 North'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry DC teams — experienced support for classic neighborhood feel with yards and mature trees in Ward 3 North.',
    website: 'https://crosscountrymortgage.com', phone: '(202) 555-1204',
  },
  {
    id: 'dc-05', slug: 'pierpoint-mortgage-dc-upper-northwest', name: 'PierPoint Mortgage (DC)', nmlsId: '112844', type: 'Broker',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20012', '20011', '20017'], rating: 4.9, reviewCount: 165, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Quick-Transaction Pockets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to Takoma and Brightwood quick-transaction value-surge pockets.',
    website: 'https://pierpointmortgage.com', phone: '(202) 555-1205',
  },
  {
    id: 'dc-06', slug: 'silverton-mortgage-dc-upper-northwest', name: 'Silverton Mortgage — DC Upper Northwest', nmlsId: '1561', type: 'Lender',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20012', '20011', '20017'], rating: 4.8, reviewCount: 138, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Retail Lending', 'Mature-Tree Residential', 'Local Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton DC retail lending — professional service for mature-tree residential areas in Brightwood and Takoma.',
    website: 'https://silvertonmortgage.com', phone: '(202) 555-1206',
  },
  {
    id: 'dc-07', slug: 'veterans-united-dc-upper-northwest', name: 'Veterans United (DC)', nmlsId: '1907', type: 'Lender',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20012', '20011', '20017'], rating: 4.9, reviewCount: 590, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 8, loanTypes: ['VA', 'FHA', 'Refinance'],
    specialties: ['VA Loans', 'First-Time Buyer Programs', 'Entry-Level Value Plays'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 15, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'VA and first-time buyer programs — tailored for buyers priced out of elite enclaves seeking Takoma and Colonial Village value.',
    website: 'https://veteransunited.com', phone: '(202) 555-1207',
  },
  {
    id: 'dc-08', slug: 'andrews-federal-credit-union-dc', name: 'Andrews Federal Credit Union', nmlsId: '402869', type: 'Credit Union',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20012', '20011', '20017'], rating: 4.9, reviewCount: 720, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 62, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Neighborhood Financing', 'Ward 3 Community CU'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'DC-area credit union — community-focused member rates in high-gain Upper Northwest appreciation pockets.',
    website: 'https://andrewsfcu.org', phone: '(800) 521-8449',
  },
  {
    id: 'dc-09', slug: 'lennar-mortgage-dc-upper-northwest', name: 'Lennar Mortgage (DC Upper Northwest)', nmlsId: '1058', type: 'Lender',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20012', '20011', '20017'], rating: 4.7, reviewCount: 285, trustScore: 90, countyExperienceScore: 92,
    nationalVolumeRank: 35, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Metro Access & Yards', 'Single-Family Specialists', '17–23% Appreciation Corridors'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 8, bbbRating: 'A',
    googleRating: 4.7, trustpilotRating: 4.5, avgCloseDays: 30, onTimeCloseRate: 92,
    shortDescription: 'Builder-affiliated lender — expertise in Zip 20012 homes with Metro access, yards, and high-appreciation corridors.',
    website: 'https://lennar.com/mortgage', phone: '(202) 555-1209',
  },
  {
    id: 'dc-10', slug: 'anchor-home-mortgage-dc-upper-northwest', name: 'Anchor Home Mortgage (DC Upper Northwest)', nmlsId: '136890', type: 'Broker',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20012', '20011', '20017'], rating: 4.9, reviewCount: 220, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Standalone Single-Family', 'Personalized Brokerage', 'Upper Northwest Value'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on standalone single-family value plays in Takoma and Brightwood at discount to Georgetown.',
    website: 'https://anchorhomemortgage.com', phone: '(202) 555-1210',
  },
  {
    id: 'dc-11', slug: 'bank-of-america-mortgage-dc-upper-northwest', name: 'Bank of America Mortgage (DC)', nmlsId: '399802', type: 'Bank',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20012', '20011', '20017'], rating: 4.6, reviewCount: 510, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Neighborhood Financing', 'Quieter Residential Pace', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 32, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for families seeking quieter residential pace in Ward 3 North.',
    website: 'https://bankofamerica.com/mortgage', phone: '(202) 555-1211',
  },
  {
    id: 'dc-12', slug: 'nova-home-loans-dc-upper-northwest', name: 'Nova Home Loans (DC)', nmlsId: '3089', type: 'Lender',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20012', '20011', '20017'], rating: 4.8, reviewCount: 265, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Ward 3 North', 'Georgetown/Spring Valley Discount'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'DC lender — localized knowledge of massive discount vs. Georgetown/Spring Valley and rapid Upper Northwest gains.',
    website: 'https://novahomeloans.com', phone: '(202) 555-1212',
  },

  // ── High-Velocity Mid-City Core (Logan Circle & Thomas Circle — Zip 20005) ───
  {
    id: 'dc-13', slug: 'logan-circle-mortgage-mid-city', name: 'Logan Circle Mortgage (Mid-City)', nmlsId: '287451', type: 'Broker',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20005', '20001', '20009'], rating: 4.9, reviewCount: 710, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 30, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['High-Velocity Transactions', 'Condo & Loft Financing', 'Logan Circle Core'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 97,
    shortDescription: 'DC mid-city broker — deep expertise in high-velocity Logan Circle and Thomas Circle condo and loft transactions.',
    website: 'https://logancirclemortgage.com', phone: '(202) 555-1301',
  },
  {
    id: 'dc-14', slug: 'guild-mortgage-dc-mid-city', name: 'Guild Mortgage (DC Mid-City)', nmlsId: '3274', type: 'Lender',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20005', '20001', '20009'], rating: 4.8, reviewCount: 445, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Urban Core Expertise', 'DC Metro Branches'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 26, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with DC mid-city operations — comprehensive financing for walkable Logan Circle and Thomas Circle purchases.',
    website: 'https://guildmortgage.com', phone: '(202) 555-1302',
  },
  {
    id: 'dc-15', slug: 'new-american-funding-dc-mid-city', name: 'New American Funding (DC Mid-City)', nmlsId: '6606', type: 'Lender',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20005', '20009', '20001'], rating: 4.9, reviewCount: 400, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Young Professional Buyers', 'Zip 20005 Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'NAF DC mid-city team — excellent ratings for high-velocity purchase and refinance in Logan Circle corridors.',
    website: 'https://newamericanfunding.com', phone: '(202) 555-1303',
  },
  {
    id: 'dc-16', slug: 'crosscountry-mortgage-dc-mid-city', name: 'CrossCountry Mortgage (DC Mid-City)', nmlsId: '3029', type: 'Lender',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20005', '20001', '20009'], rating: 4.8, reviewCount: 345, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Condo & Loft Products', 'Corporate Relocations', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry DC teams — experienced support for condo-heavy mid-city core and corporate relocation velocity.',
    website: 'https://crosscountrymortgage.com', phone: '(202) 555-1304',
  },
  {
    id: 'dc-17', slug: 'pierpoint-mortgage-dc-mid-city', name: 'PierPoint Mortgage (DC Mid-City)', nmlsId: '112844', type: 'Broker',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20005', '20009', '20001'], rating: 4.9, reviewCount: 190, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'High-Velocity Pockets'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 20, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed essential for Thomas Circle and Logan Circle quick-transaction mid-city market.',
    website: 'https://pierpointmortgage.com', phone: '(202) 555-1305',
  },
  {
    id: 'dc-18', slug: 'silverton-mortgage-dc-mid-city', name: 'Silverton Mortgage — DC Mid-City', nmlsId: '1561', type: 'Lender',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20005', '20001', '20009'], rating: 4.8, reviewCount: 152, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Retail Lending', 'Urban Loft Expertise', 'Local Mid-City Knowledge'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'Silverton DC retail lending — professional service for loft and condo buyers in the walkable mid-city core.',
    website: 'https://silvertonmortgage.com', phone: '(202) 555-1306',
  },
  {
    id: 'dc-19', slug: 'veterans-united-dc-mid-city', name: 'Veterans United (DC Mid-City)', nmlsId: '1907', type: 'Lender',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20005', '20001', '20009'], rating: 4.9, reviewCount: 560, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 8, loanTypes: ['VA', 'FHA', 'Refinance'],
    specialties: ['VA Loans', 'Federal Employee Programs', 'Urban Buyer Entry'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 15, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 94,
    shortDescription: 'VA and federal employee programs — tailored for mid-city buyers seeking walkable Logan Circle access near downtown.',
    website: 'https://veteransunited.com', phone: '(202) 555-1307',
  },
  {
    id: 'dc-20', slug: 'penfed-dc-mid-city', name: 'Pentagon Federal Credit Union', nmlsId: '401822', type: 'Credit Union',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20005', '20009', '20001'], rating: 4.9, reviewCount: 980, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Condo Financing', 'DC Metro CU'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'DC-area credit union — community-focused member rates for high-velocity mid-city condo and loft purchases.',
    website: 'https://penfed.org', phone: '(800) 247-5626',
  },
  {
    id: 'dc-21', slug: 'lennar-mortgage-dc-mid-city', name: 'Lennar Mortgage (DC Mid-City)', nmlsId: '1058', type: 'Lender',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20005', '20001', '20009'], rating: 4.7, reviewCount: 310, trustScore: 90, countyExperienceScore: 92,
    nationalVolumeRank: 35, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Urban Infill Condos', 'New Construction Lofts', 'Thomas Circle Revitalization'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 8, bbbRating: 'A',
    googleRating: 4.7, trustpilotRating: 4.5, avgCloseDays: 29, onTimeCloseRate: 92,
    shortDescription: 'Builder-affiliated lender — expertise in mid-city urban infill condos and loft conversions near Thomas Circle.',
    website: 'https://lennar.com/mortgage', phone: '(202) 555-1309',
  },
  {
    id: 'dc-22', slug: 'anchor-home-mortgage-dc-mid-city', name: 'Anchor Home Mortgage (DC Mid-City)', nmlsId: '136890', type: 'Broker',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20005', '20009', '20001'], rating: 4.9, reviewCount: 240, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Mid-City Core Buyers', 'Personalized Brokerage', 'Walkable Urban Financing'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on Logan Circle and Thomas Circle buyers in Zip 20005 high-velocity corridors.',
    website: 'https://anchorhomemortgage.com', phone: '(202) 555-1310',
  },
  {
    id: 'dc-23', slug: 'bank-of-america-mortgage-dc-mid-city', name: 'Bank of America Mortgage (DC Mid-City)', nmlsId: '399802', type: 'Bank',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20005', '20001', '20009'], rating: 4.6, reviewCount: 620, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Corporate Relocation', 'Full-Service Banking', 'Downtown Proximity'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 31, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for corporate relocations to walkable mid-city Logan Circle neighborhoods.',
    website: 'https://bankofamerica.com/mortgage', phone: '(202) 555-1311',
  },
  {
    id: 'dc-24', slug: 'nova-home-loans-dc-mid-city', name: 'Nova Home Loans (DC Mid-City)', nmlsId: '3089', type: 'Lender',
    city: 'Washington', state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia',
    zipCodes: ['20005', '20009', '20001'], rating: 4.8, reviewCount: 290, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Mid-City Appreciation', 'Lifestyle Urban Core'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 24, onTimeCloseRate: 94,
    shortDescription: 'DC lender — localized knowledge of high-velocity mid-city transaction pace and Logan Circle lifestyle appeal.',
    website: 'https://novahomeloans.com', phone: '(202) 555-1312',
  },
];

export const UPPER_NORTHWEST_VALUE_SURGE_LENDER_SLUGS = [
  'ward3-home-mortgage-upper-northwest',
  'guild-mortgage-dc-upper-northwest',
  'new-american-funding-dc-upper-northwest',
  'crosscountry-mortgage-dc-upper-northwest',
  'pierpoint-mortgage-dc-upper-northwest',
  'silverton-mortgage-dc-upper-northwest',
  'veterans-united-dc-upper-northwest',
  'andrews-federal-credit-union-dc',
  'lennar-mortgage-dc-upper-northwest',
  'anchor-home-mortgage-dc-upper-northwest',
  'bank-of-america-mortgage-dc-upper-northwest',
  'nova-home-loans-dc-upper-northwest',
] as const;

export const HIGH_VELOCITY_MID_CITY_CORE_LENDER_SLUGS = [
  'logan-circle-mortgage-mid-city',
  'guild-mortgage-dc-mid-city',
  'new-american-funding-dc-mid-city',
  'crosscountry-mortgage-dc-mid-city',
  'pierpoint-mortgage-dc-mid-city',
  'silverton-mortgage-dc-mid-city',
  'veterans-united-dc-mid-city',
  'penfed-dc-mid-city',
  'lennar-mortgage-dc-mid-city',
  'anchor-home-mortgage-dc-mid-city',
  'bank-of-america-mortgage-dc-mid-city',
  'nova-home-loans-dc-mid-city',
] as const;

export const DC_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  'district-of-columbia': [],
};

export const UPPER_NORTHWEST_VALUE_SURGE_HUB_COUNTIES = [
  { name: 'District of Columbia', slug: 'district-of-columbia', highlight: 'Ward 3 North — Takoma & Brightwood value surge' },
] as const;

export const UPPER_NORTHWEST_VALUE_SURGE_HUB_AREAS = [
  { name: 'Takoma', slug: 'district-of-columbia', highlight: 'Metro access, mature trees, 17–23% gains' },
  { name: 'Brightwood', slug: 'district-of-columbia', highlight: 'Classic DC feel, standalone single-family' },
  { name: 'Colonial Village', slug: 'district-of-columbia', highlight: 'Yards & trees, discount to elite enclaves' },
  { name: 'Zip 20012', slug: 'district-of-columbia', highlight: 'Quick-transaction northern tip hotspot' },
] as const;

export const HIGH_VELOCITY_MID_CITY_CORE_HUB_COUNTIES = [
  { name: 'District of Columbia', slug: 'district-of-columbia', highlight: 'Logan Circle & Thomas Circle mid-city core' },
] as const;

export const HIGH_VELOCITY_MID_CITY_CORE_HUB_AREAS = [
  { name: 'Logan Circle', slug: 'district-of-columbia', highlight: 'Walkable urban core, condo & loft velocity' },
  { name: 'Thomas Circle', slug: 'district-of-columbia', highlight: 'High-transaction revitalization pocket' },
  { name: 'Zip 20005', slug: 'district-of-columbia', highlight: 'Mid-city appreciation, fast closings' },
  { name: 'Downtown Adjacent', slug: 'district-of-columbia', highlight: 'Young professionals, corporate relocations' },
] as const;