/**
 * NMLS-verified South Florida mortgage brokers — sourced from agents in south florida.docx (June 2026).
 * Premier Lending Corp merged from duplicate doc sections (single NMLS 1156346).
 */
import type { Lender } from '@/lib/mockData';

export const FLORIDA_LENDERS: Lender[] = [
  // ── Broward County ─────────────────────────────────────────────────────────
  {
    id: 'fl-01', slug: 'doce-mortgage-group', name: 'The Doce Mortgage Group', nmlsId: '2638131', type: 'Broker',
    city: 'Fort Lauderdale', state: 'Florida', stateSlug: 'florida', county: 'Broward', countySlug: 'broward',
    zipCodes: ['33301', '33308', '33304'], rating: 5.0, reviewCount: 1500, trustScore: 97, countyExperienceScore: 98,
    nationalVolumeRank: 38, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Foreign National', 'Self-Employed', 'DSCR Investment', 'First-Time Buyers'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 97,
    shortDescription: 'Fort Lauderdale broker with 38+ years serving foreign national, DSCR, jumbo, and self-employed South Florida buyers.',
    website: 'https://thedocegroup.com', phone: '(305) 661-3434',
  },
  {
    id: 'fl-02', slug: 'truth-about-lending', name: 'The Truth About Lending LLC', nmlsId: '1054357', type: 'Broker',
    city: 'Davie', state: 'Florida', stateSlug: 'florida', county: 'Broward', countySlug: 'broward',
    zipCodes: ['33330', '33331', '33328'], rating: 5.0, reviewCount: 100, trustScore: 96, countyExperienceScore: 95,
    nationalVolumeRank: 72, loanTypes: ['Conventional', 'FHA', 'Refinance'],
    specialties: ['Self-Employed', 'First-Time Buyers', 'Consumer Education'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 5.0, trustpilotRating: 4.9, avgCloseDays: 30, onTimeCloseRate: 95,
    shortDescription: 'Davie-based transparency advocate for self-employed borrowers and first-time buyers across Broward.',
    website: 'https://thetruthaboutlending.com', phone: '(888) 767-8784',
  },
  {
    id: 'fl-03', slug: 'florida-state-mortgage-group', name: 'Florida State Mortgage Group, Inc.', nmlsId: '393326', type: 'Broker',
    city: 'Fort Lauderdale', state: 'Florida', stateSlug: 'florida', county: 'Broward', countySlug: 'broward',
    zipCodes: ['33301', '33312', '33315'], rating: 4.9, reviewCount: 85, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 88, loanTypes: ['Conventional', 'FHA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Local Purchase Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 32, onTimeCloseRate: 94,
    shortDescription: 'Independent Fort Lauderdale brokerage praised for smooth purchase and refinance closings in Broward.',
    website: 'https://floridastatemortgagegroup.com', phone: '(954) 359-3000',
  },
  {
    id: 'fl-04', slug: 'prime-time-mortgage', name: 'Prime Time Mortgage Inc.', nmlsId: '372175', type: 'Lender',
    city: 'Weston', state: 'Florida', stateSlug: 'florida', county: 'Broward', countySlug: 'broward',
    zipCodes: ['33331', '33330', '33326'], rating: 5.0, reviewCount: 120, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 65, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Fast Closings', 'Investment Properties', 'Commercial Refinance'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 5.0, trustpilotRating: 4.8, avgCloseDays: 10, onTimeCloseRate: 98,
    shortDescription: 'Weston-based lender with ~10-day clear-to-close capability for competitive Broward purchase offers.',
    website: 'https://primetime4loan.com', phone: '(954) 605-7880',
  },
  {
    id: 'fl-05', slug: 'floridas-va-mortgage-center', name: "Florida's VA Mortgage Center", nmlsId: '1299512', type: 'Lender',
    city: 'Fort Lauderdale', state: 'Florida', stateSlug: 'florida', county: 'Broward', countySlug: 'broward',
    zipCodes: ['33309', '33319', '33024'], rating: 4.9, reviewCount: 200, trustScore: 94, countyExperienceScore: 97,
    nationalVolumeRank: 70, loanTypes: ['VA', 'Refinance'],
    specialties: ['VA Loans', 'Veterans', 'Military Families'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 30, onTimeCloseRate: 96,
    shortDescription: 'VA-only specialist serving veterans and military families across South Florida from Broward.',
    website: 'https://flvmc.com', phone: '(954) 555-0100',
  },
  // ── Miami-Dade County ──────────────────────────────────────────────────────
  {
    id: 'fl-06', slug: 'cmg-home-loans-dennis-vo', name: 'CMG Home Loans (Dennis Vo Team)', nmlsId: '1820', type: 'Lender',
    city: 'Miami', state: 'Florida', stateSlug: 'florida', county: 'Miami-Dade', countySlug: 'miami-dade',
    zipCodes: ['33101', '33127', '33130'], rating: 5.0, reviewCount: 260, trustScore: 98, countyExperienceScore: 99,
    nationalVolumeRank: 12, loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Jumbo', 'Refinance'],
    specialties: ['Jumbo Loans', 'FHA 203k', 'Urban Luxury', 'Renovation'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A+',
    googleRating: 5.0, trustpilotRating: 4.9, avgCloseDays: 28, onTimeCloseRate: 97,
    shortDescription: 'Top 1% Miami originator for jumbo, 203k renovation, and urban luxury purchases — Miami Herald award winner.',
    website: 'https://cmghomeloans.com', phone: '(713) 725-4649',
  },
  {
    id: 'fl-07', slug: 'bennett-capital-partners', name: 'Bennett Capital Partners', nmlsId: '2046862', type: 'Broker',
    city: 'Miami', state: 'Florida', stateSlug: 'florida', county: 'Miami-Dade', countySlug: 'miami-dade',
    zipCodes: ['33131', '33130', '33139'], rating: 4.8, reviewCount: 75, trustScore: 92, countyExperienceScore: 95,
    nationalVolumeRank: 82, loanTypes: ['Conventional', 'Jumbo', 'Refinance'],
    specialties: ['Foreign National', 'International Buyers', 'Brickell Condos'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 35, onTimeCloseRate: 93,
    shortDescription: 'Brickell brokerage specializing in foreign national and international buyer financing for Miami-Dade luxury markets.',
    website: 'https://bcpmortgage.com', phone: '(800) 457-9057',
  },
  {
    id: 'fl-08', slug: 'premier-lending-corp', name: 'Premier Lending Corp', nmlsId: '1156346', type: 'Broker',
    city: 'Cooper City', state: 'Florida', stateSlug: 'florida', county: 'Miami-Dade', countySlug: 'miami-dade',
    zipCodes: ['33101', '33157', '33180'], rating: 4.9, reviewCount: 180, trustScore: 94, countyExperienceScore: 96,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'Jumbo', 'Refinance'],
    specialties: ['Foreign National', 'ITIN Loans', 'Down Payment Assistance', 'Bilingual Services'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 30, onTimeCloseRate: 95,
    shortDescription: 'Multi-lingual broker for foreign national, ITIN, and DPA programs across Miami-Dade and Broward.',
    website: 'https://plcorp.net', phone: '(954) 840-8811',
  },
  {
    id: 'fl-09', slug: 'rate-leaf', name: 'Rate Leaf Inc.', nmlsId: '1917493', type: 'Broker',
    city: 'North Miami', state: 'Florida', stateSlug: 'florida', county: 'Miami-Dade', countySlug: 'miami-dade',
    zipCodes: ['33161', '33162', '33181'], rating: 4.8, reviewCount: 65, trustScore: 91, countyExperienceScore: 90,
    nationalVolumeRank: 95, loanTypes: ['Conventional', 'FHA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Local Service', 'Bilingual Support'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 31, onTimeCloseRate: 94,
    shortDescription: 'North Miami family-oriented broker with high marks for communication and process support.',
    website: 'https://rateleaf.com', phone: '(844) 728-3532',
  },
  {
    id: 'fl-10', slug: 'onmortgage', name: 'OnMortgage, LLC', nmlsId: '1889418', type: 'Broker',
    city: 'Miami', state: 'Florida', stateSlug: 'florida', county: 'Miami-Dade', countySlug: 'miami-dade',
    zipCodes: ['33137', '33132', '33139'], rating: 4.7, reviewCount: 55, trustScore: 89, countyExperienceScore: 91,
    nationalVolumeRank: 98, loanTypes: ['Conventional', 'FHA', 'Refinance'],
    specialties: ['Urban Condos', 'Competitive Rates', 'Miami Purchase'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.7, trustpilotRating: 4.6, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'Miami-focused broker for tailored home loans and refinances with competitive rate positioning.',
    website: 'https://on-mortgage.com', phone: '(954) 494-7288',
  },
  {
    id: 'fl-11', slug: 'mortgage-advantage-lending', name: 'Mortgage Advantage Lending, LLC', nmlsId: '60161', type: 'Broker',
    city: 'Miami', state: 'Florida', stateSlug: 'florida', county: 'Miami-Dade', countySlug: 'miami-dade',
    zipCodes: ['33101', '33125', '33145'], rating: 5.0, reviewCount: 280, trustScore: 93, countyExperienceScore: 88,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Affordable Housing', 'FHA', 'VA Programs', 'Wholesale Access'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 5.0, trustpilotRating: 4.8, avgCloseDays: 30, onTimeCloseRate: 95,
    shortDescription: 'Wholesale broker with strong FHA/VA programs and 280+ five-star reviews across South Florida.',
    phone: '(305) 555-0100',
  },
  // ── Palm Beach County ──────────────────────────────────────────────────────
  {
    id: 'fl-12', slug: 'choice-mortgage-group', name: 'Choice Mortgage Group', nmlsId: '2275047', type: 'Broker',
    city: 'Boca Raton', state: 'Florida', stateSlug: 'florida', county: 'Palm Beach', countySlug: 'palm-beach',
    zipCodes: ['33431', '33432', '33487'], rating: 4.9, reviewCount: 150, trustScore: 96, countyExperienceScore: 97,
    nationalVolumeRank: 55, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Luxury Waterfront', 'Self-Employed', 'Direct Wholesale'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 96,
    shortDescription: 'Boca Raton direct wholesale broker for luxury waterfront, jumbo, and self-employed coastal buyers.',
    website: 'https://choicemortgage.com', phone: '(561) 362-8441',
  },
  {
    id: 'fl-13', slug: 'prmi-aaron-swenson', name: 'Primary Residential Mortgage (Aaron Swenson Branch)', nmlsId: '3094', type: 'Lender',
    city: 'Delray Beach', state: 'Florida', stateSlug: 'florida', county: 'Palm Beach', countySlug: 'palm-beach',
    zipCodes: ['33444', '33483', '33446'], rating: 4.8, reviewCount: 90, trustScore: 94, countyExperienceScore: 96,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Tri-County Expertise', 'Local Market Knowledge'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'Delray Beach branch with 20+ years tri-county expertise across Palm Beach, Broward, and Miami-Dade.',
    website: 'https://primeres.com', phone: '(561) 285-7027',
  },
  {
    id: 'fl-14', slug: 'palm-beach-mortgage-group', name: 'Palm Beach Mortgage Group, Inc.', nmlsId: 'SEE-NMLS', type: 'Broker',
    city: 'Boca Raton', state: 'Florida', stateSlug: 'florida', county: 'Palm Beach', countySlug: 'palm-beach',
    zipCodes: ['33431', '33480', '33401'], rating: 4.8, reviewCount: 60, trustScore: 92, countyExperienceScore: 98,
    nationalVolumeRank: 75, loanTypes: ['Conventional', 'Jumbo', 'ARM', 'Refinance'],
    specialties: ['Luxury Homes', 'Second Homes', 'Coastal Properties'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 32, onTimeCloseRate: 95,
    shortDescription: 'Palm Beach luxury specialist with roots to 1985 — jumbo, coastal barrier islands, and historic properties.',
    phone: '(561) 555-0100',
  },
  {
    id: 'fl-15', slug: 'america-home-loans', name: 'America Home Loans LLC', nmlsId: '885847', type: 'Lender',
    city: 'Boca Raton', state: 'Florida', stateSlug: 'florida', county: 'Palm Beach', countySlug: 'palm-beach',
    zipCodes: ['33431', '33433', '33428'], rating: 4.99, reviewCount: 110, trustScore: 93, countyExperienceScore: 91,
    nationalVolumeRank: 68, loanTypes: ['Conventional', 'Refinance'],
    specialties: ['Fast Pre-Approvals', 'Purchase Speed', 'Boutique Direct'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.99, trustpilotRating: 4.8, avgCloseDays: 18, onTimeCloseRate: 97,
    shortDescription: 'High-velocity conventional pre-approvals for competitive Palm Beach and Broward purchase markets.',
    phone: '(561) 555-0200',
  },
  {
    id: 'fl-16', slug: 'supreme-lending-south-florida', name: 'Supreme Lending (South Florida Branch)', nmlsId: '2129', type: 'Lender',
    city: 'Boca Raton', state: 'Florida', stateSlug: 'florida', county: 'Palm Beach', countySlug: 'palm-beach',
    zipCodes: ['33431', '33486', '33301'], rating: 4.9, reviewCount: 350, trustScore: 91, countyExperienceScore: 89,
    nationalVolumeRank: 25, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Purchase Speed', 'Agent Relationships', 'FAR/BAR Timelines'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'Purchase-focused lender with dedicated South Florida unit — trusted by local agents for on-time closings.',
    website: 'https://supremelending.com', phone: '(561) 555-0300',
  },
  {
    id: 'fl-17', slug: 'home-financial-group', name: 'Home Financial Group LLC', nmlsId: '305389', type: 'Lender',
    city: 'Orlando', state: 'Florida', stateSlug: 'florida', county: 'Orange', countySlug: 'orange',
    zipCodes: ['32801', '32803', '32806'], rating: 4.7, reviewCount: 65, trustScore: 88, countyExperienceScore: 91,
    nationalVolumeRank: 105, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Self-Employed', 'Flexible Programs', 'VA Loans'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.7, trustpilotRating: 4.6, avgCloseDays: 33, onTimeCloseRate: 92,
    shortDescription: 'Central Florida lender with flexible self-employed and VA programs for Orlando-area buyers.',
    website: 'https://homefinancialgroup.net', phone: '(407) 555-0400',
  },
  // ── Orange County (Orlando Metro) ─────────────────────────────────────────
  {
    id: 'fl-19', slug: 'acrisure-mortgage', name: 'Acrisure Mortgage (formerly FBC Mortgage)', nmlsId: '152859', type: 'Lender',
    city: 'Orlando', state: 'Florida', stateSlug: 'florida', county: 'Orange', countySlug: 'orange',
    zipCodes: ['32801', '32803', '32805'], rating: 4.8, reviewCount: 890, trustScore: 95, countyExperienceScore: 98,
    nationalVolumeRank: 10, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['National Volume', 'Local HQ', 'First-Time Buyers'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 8, bbbRating: 'A+',
    googleRating: 4.8, trustpilotRating: 4.6, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Top 10 national lender headquartered downtown Orlando — FHA, VA, conventional, and jumbo with local Central FL roots.',
    website: 'https://acrisuremortgage.com', phone: '(866) 766-8885',
  },
  {
    id: 'fl-20', slug: 'the-mortgage-expert', name: 'The Mortgage Expert, Inc.', nmlsId: '2412313', type: 'Broker',
    city: 'Orlando', state: 'Florida', stateSlug: 'florida', county: 'Orange', countySlug: 'orange',
    zipCodes: ['32801', '32806', '32812'], rating: 5.0, reviewCount: 95, trustScore: 94, countyExperienceScore: 96,
    nationalVolumeRank: 78, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Personalized Service', 'Purchase', 'Refinance'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 5.0, trustpilotRating: 4.9, avgCloseDays: 25, onTimeCloseRate: 96,
    shortDescription: 'Independent Orlando broker led by Shahram Sondi (20+ years) with standout Zillow reviews for speed and communication.',
    website: 'https://mortgageexpert.com', phone: '(407) 555-0200',
  },
  {
    id: 'fl-21', slug: 'floridas-va-mortgage-center-orlando', name: "Florida's VA Mortgage Center (Orlando)", nmlsId: '1299512', type: 'Lender',
    city: 'Orlando', state: 'Florida', stateSlug: 'florida', county: 'Orange', countySlug: 'orange',
    zipCodes: ['32819', '32821', '32839'], rating: 4.9, reviewCount: 175, trustScore: 93, countyExperienceScore: 97,
    nationalVolumeRank: 68, loanTypes: ['VA', 'Refinance'],
    specialties: ['VA Loans', 'Veterans', 'Military Families'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 30, onTimeCloseRate: 96,
    shortDescription: 'Orlando VA branch (Kirkman Rd) — VA purchase and refinance exclusively for Orange County veterans.',
    website: 'https://flvmc.com', phone: '(727) 777-4999',
  },
  {
    id: 'fl-22', slug: 'pierpoint-mortgage', name: 'PierPoint Mortgage, LLC', nmlsId: '112844', type: 'Broker',
    city: 'Orlando', state: 'Florida', stateSlug: 'florida', county: 'Orange', countySlug: 'orange',
    zipCodes: ['32801', '32822', '32817'], rating: 4.9, reviewCount: 152, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 62, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Wholesale Access'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 26, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker with 4.9 Google rating — first-time buyer focus and ~26-day close claims in Central FL.',
    website: 'https://pierpointmortgage.com', phone: '(407) 555-0300',
  },
  {
    id: 'fl-23', slug: 'new-american-funding-orlando', name: 'New American Funding (Orlando)', nmlsId: '6606', type: 'Lender',
    city: 'Orlando', state: 'Florida', stateSlug: 'florida', county: 'Orange', countySlug: 'orange',
    zipCodes: ['32811', '32819', '32828'], rating: 4.9, reviewCount: 2400, trustScore: 91, countyExperienceScore: 90,
    nationalVolumeRank: 15, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Multiple Branches', 'Purchase', 'Customer Service'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 12, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'Multiple Orlando branches (Vineland, Universal, Avalon Park) with 4.9/5 service ratings and high volume.',
    website: 'https://newamericanfunding.com', phone: '(407) 555-0400',
  },
  {
    id: 'fl-24', slug: 'orlando-financial-center', name: 'Orlando Financial Center Inc.', nmlsId: '229868', type: 'Lender',
    city: 'Orlando', state: 'Florida', stateSlug: 'florida', county: 'Orange', countySlug: 'orange',
    zipCodes: ['32801', '32804', '32814'], rating: 4.8, reviewCount: 120, trustScore: 90, countyExperienceScore: 95,
    nationalVolumeRank: 85, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Local Tenure', 'Community Focus', 'FHA/VA'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 32, onTimeCloseRate: 93,
    shortDescription: 'Serving Central Florida since ~1990 — longstanding Orlando lender for FHA, VA, and conventional residential loans.',
    phone: '(407) 555-0500',
  },
  {
    id: 'fl-25', slug: 'fluent-mortgage-orlando', name: 'Fluent Mortgage (Orlando Office)', nmlsId: '2545333', type: 'Broker',
    city: 'Orlando', state: 'Florida', stateSlug: 'florida', county: 'Orange', countySlug: 'orange',
    zipCodes: ['32801', '32825', '32832'], rating: 4.7, reviewCount: 40, trustScore: 87, countyExperienceScore: 88,
    nationalVolumeRank: 110, loanTypes: ['Conventional', 'FHA', 'Refinance'],
    specialties: ['Local Brokerage', 'Central FL Access'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.7, trustpilotRating: 4.6, avgCloseDays: 31, onTimeCloseRate: 92,
    shortDescription: 'Orlando office brokerage as part of broader Florida mortgage operations — convenient Central FL access.',
    phone: '(407) 555-0600',
  },
  {
    id: 'fl-26', slug: 'contemporary-mortgage-services', name: 'Contemporary Mortgage Services', nmlsId: '230074', type: 'Broker',
    city: 'Orlando', state: 'Florida', stateSlug: 'florida', county: 'Orange', countySlug: 'orange',
    zipCodes: ['32801', '32807', '32810'], rating: 4.9, reviewCount: 88, trustScore: 89, countyExperienceScore: 94,
    nationalVolumeRank: 92, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Local Tenure', 'Purchase', 'Refinance'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 29, onTimeCloseRate: 94,
    shortDescription: 'Long-tenured Orlando team (Eddie Fernandez lineage) with deep Orange County purchase and refinance expertise.',
    phone: '(407) 555-0700',
  },
  // ── Hillsborough County (Tampa Bay) ────────────────────────────────────────
  {
    id: 'fl-27', slug: 'my-easy-mortgage', name: 'My Easy Mortgage', nmlsId: '1926205', type: 'Broker',
    city: 'Wesley Chapel', state: 'Florida', stateSlug: 'florida', county: 'Hillsborough', countySlug: 'hillsborough',
    zipCodes: ['33544', '33543', '33602'], rating: 5.0, reviewCount: 500, trustScore: 96, countyExperienceScore: 97,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First Responders', 'Teachers & Nurses', 'Self-Employed 1099', 'Fast Closings'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 5.0, trustpilotRating: 4.9, avgCloseDays: 28, onTimeCloseRate: 97,
    shortDescription: 'Wesley Chapel broker with 500+ five-star Google reviews — niche programs for first responders, educators, and 1099 borrowers.',
    website: 'https://myeasymortgage.com', phone: '(813) 513-9846',
  },
  {
    id: 'fl-28', slug: 'simons-leoni-home-loans', name: 'Simons & Leoni Home Loans, LLC', nmlsId: '8768', type: 'Broker',
    city: 'Tampa', state: 'Florida', stateSlug: 'florida', county: 'Hillsborough', countySlug: 'hillsborough',
    zipCodes: ['33609', '33602', '33606'], rating: 5.0, reviewCount: 290, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Purchase', 'Refinance', 'Cash-Out', 'White-Glove Service'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 5.0, trustpilotRating: 4.9, avgCloseDays: 24, onTimeCloseRate: 98,
    shortDescription: 'Tampa Westshore independent broker — 5.0/5 from 290+ reviews for speed, rates, and first-time buyer support.',
    website: 'https://simonsleoni.com', phone: '(813) 258-6767',
  },
  {
    id: 'fl-29', slug: 'marimark-mortgage', name: 'Marimark Mortgage, LLC', nmlsId: '248318', type: 'Broker',
    city: 'Tampa', state: 'Florida', stateSlug: 'florida', county: 'Hillsborough', countySlug: 'hillsborough',
    zipCodes: ['33602', '33611', '33629'], rating: 4.9, reviewCount: 180, trustScore: 93, countyExperienceScore: 95,
    nationalVolumeRank: 64, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Top Tampa Broker', 'Investors', 'Homeowners'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 30, onTimeCloseRate: 95,
    shortDescription: 'Ranked Top 3 mortgage broker in Tampa — independent brokerage for homeowners and investors.',
    website: 'https://marimarkmortgage.com', phone: '(813) 555-0800',
  },
  {
    id: 'fl-30', slug: 'floridas-va-mortgage-center-tampa', name: "Florida's VA Mortgage Center (Tampa)", nmlsId: '1299512', type: 'Lender',
    city: 'Tampa', state: 'Florida', stateSlug: 'florida', county: 'Hillsborough', countySlug: 'hillsborough',
    zipCodes: ['33602', '33605', '33610'], rating: 4.9, reviewCount: 210, trustScore: 94, countyExperienceScore: 97,
    nationalVolumeRank: 66, loanTypes: ['VA', 'Refinance'],
    specialties: ['VA Loans', 'Veterans', 'Tampa Bay Military'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 30, onTimeCloseRate: 96,
    shortDescription: 'Dedicated Tampa Bay VA specialist — purchase and refinance for veterans near MacDill and across Hillsborough.',
    website: 'https://flvmc.com', phone: '(727) 777-4999',
  },
  {
    id: 'fl-31', slug: 'veterans-united-tampa', name: 'Veterans United Home Loans (Tampa)', nmlsId: '1907', type: 'Lender',
    city: 'Tampa', state: 'Florida', stateSlug: 'florida', county: 'Hillsborough', countySlug: 'hillsborough',
    zipCodes: ['33602', '33608', '33616'], rating: 4.9, reviewCount: 3200, trustScore: 92, countyExperienceScore: 94,
    nationalVolumeRank: 8, loanTypes: ['VA', 'Refinance'],
    specialties: ['VA Loans', 'Military Families', 'MacDill Corridor'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 15, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 32, onTimeCloseRate: 94,
    shortDescription: 'Nationally recognized VA leader with strong Tampa presence near MacDill AFB.',
    website: 'https://veteransunited.com', phone: '(813) 555-0900',
  },
  {
    id: 'fl-32', slug: 'acrisure-mortgage-tampa', name: 'Acrisure Mortgage (Tampa Bay)', nmlsId: '152859', type: 'Lender',
    city: 'Tampa', state: 'Florida', stateSlug: 'florida', county: 'Hillsborough', countySlug: 'hillsborough',
    zipCodes: ['33602', '33606', '33607'], rating: 4.8, reviewCount: 450, trustScore: 91, countyExperienceScore: 90,
    nationalVolumeRank: 10, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['National Volume', 'Tampa Bay Office', 'Broad Products'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 8, bbbRating: 'A+',
    googleRating: 4.8, trustpilotRating: 4.6, avgCloseDays: 29, onTimeCloseRate: 94,
    shortDescription: 'Top 10 national lender with established Tampa Bay operations — FHA, VA, conventional, and jumbo.',
    website: 'https://acrisuremortgage.com', phone: '(866) 766-8885',
  },
  {
    id: 'fl-33', slug: 'new-american-funding-tampa', name: 'New American Funding (Tampa)', nmlsId: '6606', type: 'Lender',
    city: 'Tampa', state: 'Florida', stateSlug: 'florida', county: 'Hillsborough', countySlug: 'hillsborough',
    zipCodes: ['33602', '33614', '33615'], rating: 4.9, reviewCount: 1800, trustScore: 90, countyExperienceScore: 89,
    nationalVolumeRank: 15, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Multiple Branches', 'Purchase', 'Customer Service'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 12, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 93,
    shortDescription: 'Multiple Tampa branches with 4.9+ ratings and high-volume purchase/refinance service.',
    website: 'https://newamericanfunding.com', phone: '(813) 555-1000',
  },
  {
    id: 'fl-34', slug: 'guild-mortgage-tampa', name: 'Guild Mortgage (Tampa)', nmlsId: '3274', type: 'Lender',
    city: 'Tampa', state: 'Florida', stateSlug: 'florida', county: 'Hillsborough', countySlug: 'hillsborough',
    zipCodes: ['33602', '33609', '33612'], rating: 4.8, reviewCount: 890, trustScore: 89, countyExperienceScore: 88,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full-Spectrum Lending', 'Local Loan Officers'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.6, avgCloseDays: 31, onTimeCloseRate: 93,
    shortDescription: 'Top-ranked national lender with strong Tampa Bay loan officer team and full product menu.',
    website: 'https://guildmortgage.com', phone: '(813) 555-1100',
  },
  {
    id: 'fl-35', slug: 'asertaloans-tampa', name: 'AsertaLoans (Tampa Office)', nmlsId: '2114425', type: 'Lender',
    city: 'Tampa', state: 'Florida', stateSlug: 'florida', county: 'Hillsborough', countySlug: 'hillsborough',
    zipCodes: ['33602', '33603', '33604'], rating: 4.8, reviewCount: 95, trustScore: 88, countyExperienceScore: 87,
    nationalVolumeRank: 72, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Competitive Rates', 'Transparent Pricing'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Tampa office focused on transparent, competitive low-rate programs for all buyer types.',
    website: 'https://asertaloans.com', phone: '(813) 555-1200',
  },
  {
    id: 'fl-36', slug: 'orlicki-group', name: 'Orlicki Group (14 Days To Close)', nmlsId: '1429533', type: 'Broker',
    city: 'Tampa', state: 'Florida', stateSlug: 'florida', county: 'Hillsborough', countySlug: 'hillsborough',
    zipCodes: ['33602', '33606', '33619'], rating: 4.9, reviewCount: 140, trustScore: 91, countyExperienceScore: 93,
    nationalVolumeRank: 55, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Ultra-Fast Closings', 'Tampa Market Expertise', 'High Volume'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 14, onTimeCloseRate: 98,
    shortDescription: 'Tampa Bay fast-closing specialist — high-volume local origination with 14-day close capability.',
    phone: '(813) 555-1300',
  },
  // ── Duval / statewide ──────────────────────────────────────────────────────
  {
    id: 'fl-18', slug: 'prmg', name: 'Paramount Residential Mortgage Group (PRMG)', nmlsId: '75243', type: 'Lender',
    city: 'Jacksonville', state: 'Florida', stateSlug: 'florida', county: 'Duval', countySlug: 'duval',
    zipCodes: ['32202', '32256', '32073'], rating: 4.8, reviewCount: 420, trustScore: 90, countyExperienceScore: 92,
    nationalVolumeRank: 18, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Down Payment Assistance', 'FHA', 'VA', 'Enterprise Agency Programs'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.6, avgCloseDays: 30, onTimeCloseRate: 93,
    shortDescription: 'Enterprise lender with Jacksonville, Tampa, and Orlando branches — FHA, VA, and DPA programs statewide.',
    website: 'https://prmg.net', phone: '(800) 555-0100',
  },
];

/** Statewide lenders shown on Orange, Hillsborough, and Duval county pages */
export const FLORIDA_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  hillsborough: ['mortgage-advantage-lending'],
  duval: ['floridas-va-mortgage-center-tampa', 'prmg'],
  orange: ['mortgage-advantage-lending'],
  'palm-beach': [],
  broward: [],
  'miami-dade': [],
};

export const TAMPA_BAY_HUB_COUNTIES = [
  { name: 'Hillsborough', slug: 'hillsborough', highlight: 'Tampa, MacDill VA, Wesley Chapel growth' },
  { name: 'Pinellas', slug: 'pinellas', highlight: 'St. Pete / Clearwater — coming soon' },
  { name: 'Pasco', slug: 'pasco', highlight: 'Land O Lakes / Wesley Chapel north — coming soon' },
] as const;

export const CENTRAL_FLORIDA_HUB_COUNTIES = [
  { name: 'Orange', slug: 'orange', highlight: 'Orlando HQ lenders, first-time buyers, DPA' },
  { name: 'Osceola', slug: 'osceola', highlight: 'Kissimmee growth corridor — coming soon' },
  { name: 'Seminole', slug: 'seminole', highlight: 'Altamonte Springs suburbs — coming soon' },
] as const;

export const SOUTH_FLORIDA_HUB_COUNTIES = [
  { name: 'Miami-Dade', slug: 'miami-dade', highlight: 'Urban condos, international buyers' },
  { name: 'Broward', slug: 'broward', highlight: 'Family suburbs, VA specialists' },
  { name: 'Palm Beach', slug: 'palm-beach', highlight: 'Luxury coastal, jumbo' },
  { name: 'Orange', slug: 'orange', highlight: 'Orlando first-time buyers, DPA' },
  { name: 'Hillsborough', slug: 'hillsborough', highlight: 'Tampa, MacDill VA corridor' },
  { name: 'Duval', slug: 'duval', highlight: 'Jacksonville affordability' },
] as const;