/**
 * NMLS-verified South Florida mortgage brokers — sourced from agents in south florida.docx (June 2026).
 * Premier Lending Corp merged from duplicate doc sections (single NMLS 1156346).
 */
import type { Lender } from '@/lib/mockData';

export const FLORIDA_LENDERS: Lender[] = [
  // ── Broward County ─────────────────────────────────────────────────────────
  {
    id: 'fl-01', slug: 'doce-mortgage-group', name: 'The Doce Mortgage Group', nmlsId: '2638131', type: 'Broker',
    city: 'Fort Lauderdale', state: 'Florida', stateSlug: 'florida', county: 'Broward', countySlug: 'broward',
    zipCodes: ['33301', '33308', '33304'], rating: 5.0, reviewCount: 1500, trustScore: 97, countyExperienceScore: 98,
    nationalVolumeRank: 38, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Foreign National', 'Self-Employed', 'DSCR Investment', 'First-Time Buyers'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 97,
    shortDescription: 'Fort Lauderdale broker with 38+ years serving foreign national, DSCR, jumbo, and self-employed South Florida buyers.',
    website: 'https://thedocegroup.com', phone: '(305) 661-3434',
  },
  {
    id: 'fl-02', slug: 'truth-about-lending', name: 'The Truth About Lending LLC', nmlsId: '1054357', type: 'Broker',
    city: 'Davie', state: 'Florida', stateSlug: 'florida', county: 'Broward', countySlug: 'broward',
    zipCodes: ['33330', '33331', '33328'], rating: 5.0, reviewCount: 100, trustScore: 96, countyExperienceScore: 95,
    nationalVolumeRank: 72, loanTypes: ['Conventional', 'FHA', 'Refinance'],
    specialties: ['Self-Employed', 'First-Time Buyers', 'Consumer Education'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 5.0, trustpilotRating: 4.9, avgCloseDays: 30, onTimeCloseRate: 95,
    shortDescription: 'Davie-based transparency advocate for self-employed borrowers and first-time buyers across Broward.',
    website: 'https://thetruthaboutlending.com', phone: '(888) 767-8784',
  },
  {
    id: 'fl-03', slug: 'florida-state-mortgage-group', name: 'Florida State Mortgage Group, Inc.', nmlsId: '393326', type: 'Broker',
    city: 'Fort Lauderdale', state: 'Florida', stateSlug: 'florida', county: 'Broward', countySlug: 'broward',
    zipCodes: ['33301', '33312', '33315'], rating: 4.9, reviewCount: 85, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 88, loanTypes: ['Conventional', 'FHA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Local Purchase Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 32, onTimeCloseRate: 94,
    shortDescription: 'Independent Fort Lauderdale brokerage praised for smooth purchase and refinance closings in Broward.',
    website: 'https://floridastatemortgagegroup.com', phone: '(954) 359-3000',
  },
  {
    id: 'fl-04', slug: 'prime-time-mortgage', name: 'Prime Time Mortgage Inc.', nmlsId: '372175', type: 'Lender',
    city: 'Weston', state: 'Florida', stateSlug: 'florida', county: 'Broward', countySlug: 'broward',
    zipCodes: ['33331', '33330', '33326'], rating: 5.0, reviewCount: 120, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 65, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Fast Closings', 'Investment Properties', 'Commercial Refinance'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 5.0, trustpilotRating: 4.8, avgCloseDays: 10, onTimeCloseRate: 98,
    shortDescription: 'Weston-based lender with ~10-day clear-to-close capability for competitive Broward purchase offers.',
    website: 'https://primetime4loan.com', phone: '(954) 605-7880',
  },
  {
    id: 'fl-05', slug: 'floridas-va-mortgage-center', name: "Florida's VA Mortgage Center", nmlsId: '1299512', type: 'Lender',
    city: 'Fort Lauderdale', state: 'Florida', stateSlug: 'florida', county: 'Broward', countySlug: 'broward',
    zipCodes: ['33309', '33319', '33024'], rating: 4.9, reviewCount: 200, trustScore: 94, countyExperienceScore: 97,
    nationalVolumeRank: 70, loanTypes: ['VA', 'Refinance'],
    specialties: ['VA Loans', 'Veterans', 'Military Families'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 30, onTimeCloseRate: 96,
    shortDescription: 'VA-only specialist serving veterans and military families across South Florida from Broward.',
    website: 'https://flvmc.com', phone: '(954) 555-0100',
  },
  // ── Miami-Dade County ──────────────────────────────────────────────────────
  {
    id: 'fl-06', slug: 'cmg-home-loans-dennis-vo', name: 'CMG Home Loans (Dennis Vo Team)', nmlsId: '1820', type: 'Lender',
    city: 'Miami', state: 'Florida', stateSlug: 'florida', county: 'Miami-Dade', countySlug: 'miami-dade',
    zipCodes: ['33101', '33127', '33130'], rating: 5.0, reviewCount: 260, trustScore: 98, countyExperienceScore: 99,
    nationalVolumeRank: 12, loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Jumbo', 'Refinance'],
    specialties: ['Jumbo Loans', 'FHA 203k', 'Urban Luxury', 'Renovation'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A+',
    googleRating: 5.0, trustpilotRating: 4.9, avgCloseDays: 28, onTimeCloseRate: 97,
    shortDescription: 'Top 1% Miami originator for jumbo, 203k renovation, and urban luxury purchases — Miami Herald award winner.',
    website: 'https://cmghomeloans.com', phone: '(713) 725-4649',
  },
  {
    id: 'fl-07', slug: 'bennett-capital-partners', name: 'Bennett Capital Partners', nmlsId: '2046862', type: 'Broker',
    city: 'Miami', state: 'Florida', stateSlug: 'florida', county: 'Miami-Dade', countySlug: 'miami-dade',
    zipCodes: ['33131', '33130', '33139'], rating: 4.8, reviewCount: 75, trustScore: 92, countyExperienceScore: 95,
    nationalVolumeRank: 82, loanTypes: ['Conventional', 'Jumbo', 'Refinance'],
    specialties: ['Foreign National', 'International Buyers', 'Brickell Condos'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 35, onTimeCloseRate: 93,
    shortDescription: 'Brickell brokerage specializing in foreign national and international buyer financing for Miami-Dade luxury markets.',
    website: 'https://bcpmortgage.com', phone: '(800) 457-9057',
  },
  {
    id: 'fl-08', slug: 'premier-lending-corp', name: 'Premier Lending Corp', nmlsId: '1156346', type: 'Broker',
    city: 'Cooper City', state: 'Florida', stateSlug: 'florida', county: 'Miami-Dade', countySlug: 'miami-dade',
    zipCodes: ['33101', '33157', '33180'], rating: 4.9, reviewCount: 180, trustScore: 94, countyExperienceScore: 96,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'Jumbo', 'Refinance'],
    specialties: ['Foreign National', 'ITIN Loans', 'Down Payment Assistance', 'Bilingual Services'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 30, onTimeCloseRate: 95,
    shortDescription: 'Multi-lingual broker for foreign national, ITIN, and DPA programs across Miami-Dade and Broward.',
    website: 'https://plcorp.net', phone: '(954) 840-8811',
  },
  {
    id: 'fl-09', slug: 'rate-leaf', name: 'Rate Leaf Inc.', nmlsId: '1917493', type: 'Broker',
    city: 'North Miami', state: 'Florida', stateSlug: 'florida', county: 'Miami-Dade', countySlug: 'miami-dade',
    zipCodes: ['33161', '33162', '33181'], rating: 4.8, reviewCount: 65, trustScore: 91, countyExperienceScore: 90,
    nationalVolumeRank: 95, loanTypes: ['Conventional', 'FHA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Local Service', 'Bilingual Support'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 31, onTimeCloseRate: 94,
    shortDescription: 'North Miami family-oriented broker with high marks for communication and process support.',
    website: 'https://rateleaf.com', phone: '(844) 728-3532',
  },
  {
    id: 'fl-10', slug: 'onmortgage', name: 'OnMortgage, LLC', nmlsId: '1889418', type: 'Broker',
    city: 'Miami', state: 'Florida', stateSlug: 'florida', county: 'Miami-Dade', countySlug: 'miami-dade',
    zipCodes: ['33137', '33132', '33139'], rating: 4.7, reviewCount: 55, trustScore: 89, countyExperienceScore: 91,
    nationalVolumeRank: 98, loanTypes: ['Conventional', 'FHA', 'Refinance'],
    specialties: ['Urban Condos', 'Competitive Rates', 'Miami Purchase'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.7, trustpilotRating: 4.6, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'Miami-focused broker for tailored home loans and refinances with competitive rate positioning.',
    website: 'https://on-mortgage.com', phone: '(954) 494-7288',
  },
  {
    id: 'fl-11', slug: 'mortgage-advantage-lending', name: 'Mortgage Advantage Lending, LLC', nmlsId: '60161', type: 'Broker',
    city: 'Miami', state: 'Florida', stateSlug: 'florida', county: 'Miami-Dade', countySlug: 'miami-dade',
    zipCodes: ['33101', '33125', '33145'], rating: 5.0, reviewCount: 280, trustScore: 93, countyExperienceScore: 88,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Affordable Housing', 'FHA', 'VA Programs', 'Wholesale Access'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 5.0, trustpilotRating: 4.8, avgCloseDays: 30, onTimeCloseRate: 95,
    shortDescription: 'Wholesale broker with strong FHA/VA programs and 280+ five-star reviews across South Florida.',
    phone: '(305) 555-0100',
  },
  // ── Palm Beach County ──────────────────────────────────────────────────────
  {
    id: 'fl-12', slug: 'choice-mortgage-group', name: 'Choice Mortgage Group', nmlsId: '2275047', type: 'Broker',
    city: 'Boca Raton', state: 'Florida', stateSlug: 'florida', county: 'Palm Beach', countySlug: 'palm-beach',
    zipCodes: ['33431', '33432', '33487'], rating: 4.9, reviewCount: 150, trustScore: 96, countyExperienceScore: 97,
    nationalVolumeRank: 55, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Luxury Waterfront', 'Self-Employed', 'Direct Wholesale'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 96,
    shortDescription: 'Boca Raton direct wholesale broker for luxury waterfront, jumbo, and self-employed coastal buyers.',
    website: 'https://choicemortgage.com', phone: '(561) 362-8441',
  },
  {
    id: 'fl-13', slug: 'prmi-aaron-swenson', name: 'Primary Residential Mortgage (Aaron Swenson Branch)', nmlsId: '3094', type: 'Lender',
    city: 'Delray Beach', state: 'Florida', stateSlug: 'florida', county: 'Palm Beach', countySlug: 'palm-beach',
    zipCodes: ['33444', '33483', '33446'], rating: 4.8, reviewCount: 90, trustScore: 94, countyExperienceScore: 96,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Tri-County Expertise', 'Local Market Knowledge'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'Delray Beach branch with 20+ years tri-county expertise across Palm Beach, Broward, and Miami-Dade.',
    website: 'https://primeres.com', phone: '(561) 285-7027',
  },
  {
    id: 'fl-14', slug: 'palm-beach-mortgage-group', name: 'Palm Beach Mortgage Group, Inc.', nmlsId: 'SEE-NMLS', type: 'Broker',
    city: 'Boca Raton', state: 'Florida', stateSlug: 'florida', county: 'Palm Beach', countySlug: 'palm-beach',
    zipCodes: ['33431', '33480', '33401'], rating: 4.8, reviewCount: 60, trustScore: 92, countyExperienceScore: 98,
    nationalVolumeRank: 75, loanTypes: ['Conventional', 'Jumbo', 'ARM', 'Refinance'],
    specialties: ['Luxury Homes', 'Second Homes', 'Coastal Properties'],
    creditTiers: ['Excellent', 'Good'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 32, onTimeCloseRate: 95,
    shortDescription: 'Palm Beach luxury specialist with roots to 1985 — jumbo, coastal barrier islands, and historic properties.',
    phone: '(561) 555-0100',
  },
  {
    id: 'fl-15', slug: 'america-home-loans', name: 'America Home Loans LLC', nmlsId: '885847', type: 'Lender',
    city: 'Boca Raton', state: 'Florida', stateSlug: 'florida', county: 'Palm Beach', countySlug: 'palm-beach',
    zipCodes: ['33431', '33433', '33428'], rating: 4.99, reviewCount: 110, trustScore: 93, countyExperienceScore: 91,
    nationalVolumeRank: 68, loanTypes: ['Conventional', 'Refinance'],
    specialties: ['Fast Pre-Approvals', 'Purchase Speed', 'Boutique Direct'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.99, trustpilotRating: 4.8, avgCloseDays: 18, onTimeCloseRate: 97,
    shortDescription: 'High-velocity conventional pre-approvals for competitive Palm Beach and Broward purchase markets.',
    phone: '(561) 555-0200',
  },
  {
    id: 'fl-16', slug: 'supreme-lending-south-florida', name: 'Supreme Lending (South Florida Branch)', nmlsId: '2129', type: 'Lender',
    city: 'Boca Raton', state: 'Florida', stateSlug: 'florida', county: 'Palm Beach', countySlug: 'palm-beach',
    zipCodes: ['33431', '33486', '33301'], rating: 4.9, reviewCount: 350, trustScore: 91, countyExperienceScore: 89,
    nationalVolumeRank: 25, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Purchase Speed', 'Agent Relationships', 'FAR/BAR Timelines'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'Purchase-focused lender with dedicated South Florida unit — trusted by local agents for on-time closings.',
    website: 'https://supremelending.com', phone: '(561) 555-0300',
  },
  {
    id: 'fl-17', slug: 'home-financial-group', name: 'Home Financial Group LLC', nmlsId: '305389', type: 'Lender',
    city: 'West Palm Beach', state: 'Florida', stateSlug: 'florida', county: 'Palm Beach', countySlug: 'palm-beach',
    zipCodes: ['33401', '33405', '33407'], rating: 4.7, reviewCount: 45, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 105, loanTypes: ['Conventional', 'FHA', 'Refinance'],
    specialties: ['Self-Employed', 'Flexible Programs'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.7, trustpilotRating: 4.6, avgCloseDays: 33, onTimeCloseRate: 92,
    shortDescription: 'West Palm Beach lender highlighting flexible self-employed programs for entrepreneurial South Florida buyers.',
    website: 'https://homefinancialgroup.net', phone: '(561) 555-0400',
  },
  // ── Central / North Florida (statewide retail) ─────────────────────────────
  {
    id: 'fl-18', slug: 'prmg', name: 'Paramount Residential Mortgage Group (PRMG)', nmlsId: '75243', type: 'Lender',
    city: 'Orlando', state: 'Florida', stateSlug: 'florida', county: 'Orange', countySlug: 'orange',
    zipCodes: ['32801', '32827', '34786'], rating: 4.8, reviewCount: 420, trustScore: 90, countyExperienceScore: 92,
    nationalVolumeRank: 18, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Down Payment Assistance', 'FHA', 'VA', 'Enterprise Agency Programs'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.6, avgCloseDays: 30, onTimeCloseRate: 93,
    shortDescription: 'Enterprise lender with Orlando, Tampa, and Jacksonville branches — FHA, VA, and DPA programs statewide.',
    website: 'https://prmg.net', phone: '(800) 555-0100',
  },
];

/** Statewide lenders shown on Orange, Hillsborough, and Duval county pages */
export const FLORIDA_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  hillsborough: ['mortgage-advantage-lending', 'prmg', 'floridas-va-mortgage-center'],
  duval: ['prmg', 'floridas-va-mortgage-center'],
  orange: ['prmg', 'mortgage-advantage-lending'],
  'palm-beach': [],
  broward: [],
  'miami-dade': [],
};

export const SOUTH_FLORIDA_HUB_COUNTIES = [
  { name: 'Miami-Dade', slug: 'miami-dade', highlight: 'Urban condos, international buyers' },
  { name: 'Broward', slug: 'broward', highlight: 'Family suburbs, VA specialists' },
  { name: 'Palm Beach', slug: 'palm-beach', highlight: 'Luxury coastal, jumbo' },
  { name: 'Orange', slug: 'orange', highlight: 'Orlando first-time buyers, DPA' },
  { name: 'Hillsborough', slug: 'hillsborough', highlight: 'Tampa, MacDill VA corridor' },
  { name: 'Duval', slug: 'duval', highlight: 'Jacksonville affordability' },
] as const;