import type { Lender } from '@/lib/mockData';

export const GEORGIA_LENDERS: Lender[] = [
  // ── Forsyth County (North Atlanta Suburbs) ───────────────────────────────────
  {
    id: 'ga-01', slug: 'johns-creek-mortgage', name: 'Johns Creek Mortgage LLC', nmlsId: '2320634', type: 'Broker',
    city: 'Johns Creek', state: 'Georgia', stateSlug: 'georgia', county: 'Forsyth', countySlug: 'forsyth',
    zipCodes: ['30097', '30024', '30041'], rating: 4.9, reviewCount: 220, trustScore: 96, countyExperienceScore: 97,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Refinance'],
    specialties: ['North 400 Corridor', 'Alpharetta & Suwanee', 'Multi-County Broker'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 25, onTimeCloseRate: 96,
    shortDescription: 'Johns Creek broker serving Alpharetta, Suwanee, and Cumming — personalized North Fulton and Forsyth expertise.',
    website: 'https://johnscreekmortgage.com', phone: '(678) 632-0080',
  },
  {
    id: 'ga-02', slug: 'northstar-mortgage-services', name: 'Northstar Mortgage Services', nmlsId: '158351', type: 'Broker',
    city: 'Alpharetta', state: 'Georgia', stateSlug: 'georgia', county: 'Forsyth', countySlug: 'forsyth',
    zipCodes: ['30009', '30004', '30041'], rating: 4.9, reviewCount: 310, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Jumbo', 'Refinance'],
    specialties: ['Since 1998', 'Avalon Alpharetta', 'Wholesale Direct Rates'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 97,
    shortDescription: 'Alpharetta broker since 1998 — A+ BBB, wholesale direct rates, and deep North Fulton suburban market knowledge.',
    website: 'https://northstarmortgageservices.com', phone: '(770) 995-8078',
  },
  {
    id: 'ga-03', slug: 'loanpro-mortgage-solutions', name: 'LoanPro Mortgage Solutions', nmlsId: '1229691', type: 'Broker',
    city: 'Cumming', state: 'Georgia', stateSlug: 'georgia', county: 'Forsyth', countySlug: 'forsyth',
    zipCodes: ['30041', '30040', '30028'], rating: 4.8, reviewCount: 145, trustScore: 92, countyExperienceScore: 94,
    nationalVolumeRank: 64, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Cumming HQ', 'Forsyth Families', 'Local Brokerage'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Cumming-headquartered brokerage focused on Forsyth County and North Atlanta family homebuyers.',
    website: 'https://loanproms.com', phone: '(770) 555-2500',
  },
  {
    id: 'ga-04', slug: 'pierpoint-mortgage-north-atlanta', name: 'PierPoint Mortgage (North Atlanta)', nmlsId: '112844', type: 'Broker',
    city: 'Alpharetta', state: 'Georgia', stateSlug: 'georgia', county: 'Forsyth', countySlug: 'forsyth',
    zipCodes: ['30004', '30041', '30097'], rating: 4.9, reviewCount: 152, trustScore: 93, countyExperienceScore: 92,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Wholesale Access'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 26, onTimeCloseRate: 96,
    shortDescription: 'Wholesale broker with transparent fees and ~26-day closes — suited to competitive North Atlanta offers.',
    website: 'https://pierpointmortgage.com', phone: '(770) 555-2600',
  },
  {
    id: 'ga-05', slug: 'guild-mortgage-north-atlanta', name: 'Guild Mortgage (Alpharetta / North Suburbs)', nmlsId: '3274', type: 'Lender',
    city: 'Alpharetta', state: 'Georgia', stateSlug: 'georgia', county: 'Forsyth', countySlug: 'forsyth',
    zipCodes: ['30004', '30041', '30097'], rating: 4.8, reviewCount: 680, trustScore: 91, countyExperienceScore: 90,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['North Atlanta Branches', 'Full-Spectrum Lending', 'Local Loan Officers'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.6, avgCloseDays: 31, onTimeCloseRate: 93,
    shortDescription: 'Top national lender with dedicated North Atlanta loan officers and full residential product menu.',
    website: 'https://guildmortgage.com', phone: '(770) 555-2700',
  },
  {
    id: 'ga-06', slug: 'capital-city-home-loans', name: 'Capital City Home Loans (Alpharetta)', nmlsId: '75615', type: 'Lender',
    city: 'Alpharetta', state: 'Georgia', stateSlug: 'georgia', county: 'Forsyth', countySlug: 'forsyth',
    zipCodes: ['30004', '30009', '30041'], rating: 4.8, reviewCount: 195, trustScore: 90, countyExperienceScore: 91,
    nationalVolumeRank: 55, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyer Programs', 'Alpharetta Based', 'Suburban Families'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'Alpharetta-based lender with broad home loan options and strong suburban family focus.',
    website: 'https://mortgage.ccbg.com', phone: '(770) 555-2800',
  },
  {
    id: 'ga-07', slug: 'victory-mortgage-north-atlanta', name: 'Victory Mortgage (North Atlanta)', nmlsId: '2140', type: 'Lender',
    city: 'Cumming', state: 'Georgia', stateSlug: 'georgia', county: 'Forsyth', countySlug: 'forsyth',
    zipCodes: ['30041', '30004', '30339'], rating: 4.8, reviewCount: 420, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 35, loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Refinance'],
    specialties: ['New Construction', 'Fischer Homes Partner', 'Cumming & Forsyth Growth'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'New construction specialist for Forsyth and Cherokee growth corridors — affiliated with Fischer Homes.',
    website: 'https://victorymortgage.com', phone: '(404) 355-0002',
  },
  {
    id: 'ga-08', slug: 'crosscountry-mortgage-alpharetta', name: 'CrossCountry Mortgage (Alpharetta)', nmlsId: '3029', type: 'Lender',
    city: 'Alpharetta', state: 'Georgia', stateSlug: 'georgia', county: 'Forsyth', countySlug: 'forsyth',
    zipCodes: ['30004', '30009', '30041'], rating: 4.8, reviewCount: 890, trustScore: 89, countyExperienceScore: 88,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['High-Volume Retail', 'Alpharetta Leadership', 'Premium Exurban'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 8, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.6, avgCloseDays: 30, onTimeCloseRate: 93,
    shortDescription: 'High-volume retail lender with experienced Alpharetta teams serving premium North Atlanta buyers.',
    website: 'https://crosscountrymortgage.com', phone: '(770) 555-2900',
  },
  {
    id: 'ga-09', slug: 'georgias-own-credit-union', name: "Georgia's Own Credit Union", nmlsId: '539379', type: 'Credit Union',
    city: 'Alpharetta', state: 'Georgia', stateSlug: 'georgia', county: 'Forsyth', countySlug: 'forsyth',
    zipCodes: ['30004', '30041', '30097'], rating: 4.8, reviewCount: 520, trustScore: 88, countyExperienceScore: 89,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Community Credit Union', 'Member Rates', 'First Responder Programs'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A+',
    googleRating: 4.8, trustpilotRating: 4.6, avgCloseDays: 32, onTimeCloseRate: 93,
    shortDescription: 'Regional credit union with competitive member rates for North Metro affluent families and professionals.',
    website: 'https://georgiasown.org', phone: '(800) 555-3000',
  },
  {
    id: 'ga-10', slug: 'anchor-home-mortgage', name: 'Anchor Home Mortgage, Inc.', nmlsId: '136890', type: 'Broker',
    city: 'Alpharetta', state: 'Georgia', stateSlug: 'georgia', county: 'Forsyth', countySlug: 'forsyth',
    zipCodes: ['30005', '30004', '30097'], rating: 4.9, reviewCount: 280, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 56, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Johns Creek & Alpharetta', 'Tech Professionals', 'Fast Funding'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 97,
    shortDescription: 'Alpharetta independent broker — personalized service for tech professionals and families in Johns Creek and Alpharetta.',
    website: 'https://theanchorteam.com', phone: '(678) 679-7000',
  },
];

/** Cross-county lenders shown on Forsyth and Fulton county pages */
export const GEORGIA_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  forsyth: ['peach-state-home-loans'],
  fulton: [],
};

export const NORTH_ATLANTA_HUB_COUNTIES = [
  { name: 'Forsyth', slug: 'forsyth', highlight: 'Cumming, schools, new construction growth' },
  { name: 'Fulton', slug: 'fulton', highlight: 'Alpharetta, Johns Creek, Suwanee border' },
  { name: 'Gwinnett', slug: 'gwinnett', highlight: 'Suwanee, Duluth reach — coming soon' },
] as const;