import type { Lender } from '@/lib/mockData';

export const MASSACHUSETTS_LENDERS: Lender[] = [
  // ── Undisputed Growth Leader (Worcester — Zip 01608) ─────────────────────────
  {
    id: 'ma-01', slug: 'central-mass-independent-mortgage-worcester', name: 'Central Mass Independent Mortgage (Worcester)', nmlsId: '284719', type: 'Broker',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.9, reviewCount: 640, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 36, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Three-Decker & Single-Family', 'Central Mass Growth', 'Worcester Value Plays'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Local Worcester independent — strong knowledge of Central Mass growth dynamics and three-decker single-family financing.',
    website: 'https://centralmassmortgage.com', phone: '(508) 555-2101',
  },
  {
    id: 'ma-02', slug: 'guild-mortgage-worcester', name: 'Guild Mortgage (Worcester)', nmlsId: '3274', type: 'Lender',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.8, reviewCount: 410, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Zip 01608 Focus', 'Full Residential Spectrum', 'Central Mass Operations'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Worcester branches — comprehensive financing for Worcester County growth and Boston spillover buyers.',
    website: 'https://guildmortgage.com', phone: '(508) 555-2102',
  },
  {
    id: 'ma-03', slug: 'new-american-funding-worcester', name: 'New American Funding (Worcester)', nmlsId: '6606', type: 'Lender',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.9, reviewCount: 375, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Worcester Growth Demand', 'Quick Transactions'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 25, onTimeCloseRate: 95,
    shortDescription: 'NAF Worcester team — excellent ratings for high-velocity purchase and refinance in Central Mass growth corridors.',
    website: 'https://newamericanfunding.com', phone: '(508) 555-2103',
  },
  {
    id: 'ma-04', slug: 'crosscountry-mortgage-worcester', name: 'CrossCountry Mortgage (Worcester)', nmlsId: '3029', type: 'Lender',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.8, reviewCount: 320, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Healthcare & Education Buyers', 'Broad Product Menu', 'Shrewsbury Suburbs'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Worcester teams — experienced support for healthcare, education, and young professional buyers in growth suburbs.',
    website: 'https://crosscountrymortgage.com', phone: '(508) 555-2104',
  },
  {
    id: 'ma-05', slug: 'pierpoint-mortgage-worcester', name: 'PierPoint Mortgage (Worcester)', nmlsId: '112844', type: 'Broker',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.9, reviewCount: 155, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Zip 01608 Focus', 'Fast Closings', 'High-Velocity Growth Market'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to Worcester\'s ironclad demand and quick transactions in a high-growth Central Mass pocket.',
    website: 'https://pierpointmortgage.com', phone: '(508) 555-2105',
  },
  {
    id: 'ma-06', slug: 'silverton-mortgage-worcester', name: 'Silverton Mortgage — Worcester', nmlsId: '1561', type: 'Lender',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.8, reviewCount: 142, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Retail Lending', 'Canal District & Urban Core', 'Local Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Worcester retail lending — professional service for urban core and revitalized neighborhood turn-key properties.',
    website: 'https://silvertonmortgage.com', phone: '(508) 555-2106',
  },
  {
    id: 'ma-07', slug: 'boston-spillover-mortgage-worcester', name: 'Boston Spillover Mortgage (Worcester)', nmlsId: '518392', type: 'Broker',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.9, reviewCount: 480, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Boston Metro Relocations', 'Biotech & Life Sciences', 'Condo & Rowhome Programs'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'Relocation specialist — tailored for Boston spillover transplants, biotech workers, and high-earning professionals priced out of Metro Boston.',
    website: 'https://bostonspillovermortgage.com', phone: '(508) 555-2107',
  },
  {
    id: 'ma-08', slug: 'dcu-worcester', name: 'Digital Federal Credit Union (Worcester)', nmlsId: '414078', type: 'Credit Union',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.9, reviewCount: 860, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 55, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Central Mass CU', 'Community-Focused Lending'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Massachusetts credit union — community-focused member rates for high-growth Worcester County buyers.',
    website: 'https://dcu.org', phone: '(800) 328-8797',
  },
  {
    id: 'ma-09', slug: 'growth-corridor-mortgage-worcester', name: 'Growth Corridor Mortgage (Worcester)', nmlsId: '367284', type: 'Broker',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.9, reviewCount: 295, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 40, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Undisputed Growth Leader', 'Boston Discount Financing', 'Appreciation Corridors'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'Growth corridor specialist — expertise in Worcester as Central Mass\' undisputed growth leader with massive discount vs. Boston pricing.',
    website: 'https://growthcorridormortgage.com', phone: '(508) 555-2109',
  },
  {
    id: 'ma-10', slug: 'anchor-home-mortgage-worcester', name: 'Anchor Home Mortgage (Worcester)', nmlsId: '136890', type: 'Broker',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.9, reviewCount: 230, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Personalized Brokerage', 'Worcester Urban Core', 'Family Growth Suburbs'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on Worcester urban revitalization and Shrewsbury family growth at Boston-spillover value.',
    website: 'https://anchorhomemortgage.com', phone: '(508) 555-2110',
  },
  {
    id: 'ma-11', slug: 'citizens-bank-mortgage-worcester', name: 'Citizens Bank Mortgage (Worcester)', nmlsId: '433960', type: 'Bank',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.7, reviewCount: 540, trustScore: 89, countyExperienceScore: 91,
    nationalVolumeRank: 12, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Regional Bank Financing', 'Boston Relocation Programs', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 12, bbbRating: 'A',
    googleRating: 4.7, trustpilotRating: 4.5, avgCloseDays: 31, onTimeCloseRate: 91,
    shortDescription: 'Full-service regional bank mortgages convenient for Boston metro relocations and young professionals moving to Worcester.',
    website: 'https://citizensbank.com/mortgage', phone: '(508) 555-2111',
  },
  {
    id: 'ma-12', slug: 'nova-home-loans-worcester', name: 'Nova Home Loans (Worcester Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.8, reviewCount: 255, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Worcester County Growth', 'Quick Sales Velocity'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'Worcester lender — localized knowledge of Central Mass appreciation, investor demand, and quick sales in growth corridors.',
    website: 'https://novahomeloans.com', phone: '(508) 555-2112',
  },
];

export const WORCESTER_UNDISPUTED_GROWTH_LEADER_LENDER_SLUGS = [
  'central-mass-independent-mortgage-worcester',
  'guild-mortgage-worcester',
  'new-american-funding-worcester',
  'crosscountry-mortgage-worcester',
  'pierpoint-mortgage-worcester',
  'silverton-mortgage-worcester',
  'boston-spillover-mortgage-worcester',
  'dcu-worcester',
  'growth-corridor-mortgage-worcester',
  'anchor-home-mortgage-worcester',
  'citizens-bank-mortgage-worcester',
  'nova-home-loans-worcester',
] as const;

export const MASSACHUSETTS_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  worcester: [],
};

export const WORCESTER_UNDISPUTED_GROWTH_LEADER_HUB_COUNTIES = [
  { name: 'Worcester', slug: 'worcester', highlight: 'Undisputed Central Mass growth leader' },
] as const;

export const WORCESTER_UNDISPUTED_GROWTH_LEADER_HUB_AREAS = [
  { name: 'Worcester', slug: 'worcester', highlight: 'Biotech hub, urban revitalization, growth leader' },
  { name: 'Shrewsbury', slug: 'worcester', highlight: 'Boston spillover suburbs, family demand' },
  { name: 'Canal District', slug: 'worcester', highlight: 'Revitalized urban core, quick transactions' },
  { name: 'Zip 01608', slug: 'worcester', highlight: 'Massive discount vs. Boston metro pricing' },
] as const;