import type { Lender } from '@/lib/mockData';

export const MASSACHUSETTS_LENDERS: Lender[] = [
  // ── Undisputed Growth Leader (Worcester — Zip 01608) ─────────────────────────
  {
    id: 'ma-01', slug: 'central-mass-independent-mortgage-worcester', name: 'Local Worcester Independent Mortgage', nmlsId: '284719', type: 'Broker',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.9, reviewCount: 640, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 36, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['First-Time Buyer Programs', 'Life Sciences Relocations', 'Zoom Town & Downtown Revitalization'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Local Worcester independent — strong knowledge of Zoom Town dynamics, downtown revitalization, and life sciences relocation financing.',
    website: 'https://centralmassmortgage.com', phone: '(508) 555-2101',
  },
  {
    id: 'ma-02', slug: 'guild-mortgage-worcester', name: 'Guild Mortgage (Worcester)', nmlsId: '3274', type: 'Lender',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.8, reviewCount: 410, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'First-Time & Investor Growth', 'Worcester County Operations'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Worcester branches — comprehensive financing for first-time buyers and investors in one of the country\'s hottest markets.',
    website: 'https://guildmortgage.com', phone: '(508) 555-2102',
  },
  {
    id: 'ma-03', slug: 'new-american-funding-worcester', name: 'New American Funding (Worcester)', nmlsId: '6606', type: 'Lender',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.9, reviewCount: 375, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Commuter Rail Corridor', 'Investor Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 25, onTimeCloseRate: 95,
    shortDescription: 'NAF Worcester team — excellent ratings for commuter rail corridor buyers and investor demand in fast-moving Worcester County.',
    website: 'https://newamericanfunding.com', phone: '(508) 555-2103',
  },
  {
    id: 'ma-04', slug: 'crosscountry-mortgage-worcester', name: 'CrossCountry Mortgage (Central MA)', nmlsId: '3029', type: 'Lender',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.8, reviewCount: 320, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Life Sciences Sector', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Central MA teams — experienced support for first-time buyers in Worcester\'s booming life sciences sector.',
    website: 'https://crosscountrymortgage.com', phone: '(508) 555-2104',
  },
  {
    id: 'ma-05', slug: 'pierpoint-mortgage-worcester', name: 'PierPoint Mortgage (Central MA)', nmlsId: '112844', type: 'Broker',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.9, reviewCount: 155, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Exceptionally Fast-Moving Market'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to Worcester\'s exceptionally fast-moving first-time buyer market.',
    website: 'https://pierpointmortgage.com', phone: '(508) 555-2105',
  },
  {
    id: 'ma-06', slug: 'silverton-mortgage-worcester', name: 'Silverton Mortgage — Worcester', nmlsId: '1561', type: 'Lender',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.8, reviewCount: 142, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Polar Park Corridor', 'Downtown Revitalization', 'Retail Local Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Worcester retail lending — professional service for Polar Park and downtown revitalization areas.',
    website: 'https://silvertonmortgage.com', phone: '(508) 555-2106',
  },
  {
    id: 'ma-07', slug: 'young-professional-investor-mortgage-worcester', name: 'Young Professional & Investor Specialists (Worcester)', nmlsId: '518392', type: 'Broker',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.9, reviewCount: 480, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Remote Worker Programs', 'Life Sciences Professionals', 'Zoom Town Affordability'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'Young professional and investor specialist — tailored for Zoom Town remote workers and life sciences professionals seeking Worcester affordability.',
    website: 'https://centralmayoungprofmortgage.com', phone: '(508) 555-2107',
  },
  {
    id: 'ma-08', slug: 'dcu-worcester', name: 'Digital Federal Credit Union (Worcester)', nmlsId: '414078', type: 'Credit Union',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.9, reviewCount: 860, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 55, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'First-Time Buyer Options', 'Worcester County CU'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Massachusetts credit union — community-focused member rates and first-time buyer options in high-growth Worcester County.',
    website: 'https://dcu.org', phone: '(800) 328-8797',
  },
  {
    id: 'ma-09', slug: 'downtown-new-construction-mortgage-worcester', name: 'New Construction & Downtown Specialists (Worcester)', nmlsId: '367284', type: 'Broker',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.9, reviewCount: 295, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 40, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Downtown Revitalization', 'New-Build Financing', 'Commuter Rail Access'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'New construction and downtown specialist — expertise in revitalization investments and commuter rail-access properties.',
    website: 'https://worcesterdowntownmortgage.com', phone: '(508) 555-2109',
  },
  {
    id: 'ma-10', slug: 'anchor-home-mortgage-worcester', name: 'Anchor Home Mortgage (Worcester)', nmlsId: '136890', type: 'Broker',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.9, reviewCount: 230, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Personalized Brokerage', 'Central MA Buyers', 'Greater Boston Affordability'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on relative affordability vs. Greater Boston for Central MA buyers.',
    website: 'https://anchorhomemortgage.com', phone: '(508) 555-2110',
  },
  {
    id: 'ma-11', slug: 'bank-of-america-mortgage-worcester', name: 'Bank of America Mortgage (Worcester)', nmlsId: '399802', type: 'Bank',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.6, reviewCount: 520, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Relocation Financing', 'Life Sciences Influx', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 32, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for life sciences and remote worker relocations to Worcester County.',
    website: 'https://bankofamerica.com/mortgage', phone: '(508) 555-2111',
  },
  {
    id: 'ma-12', slug: 'nova-home-loans-worcester', name: 'Nova Home Loans (Worcester Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.8, reviewCount: 255, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'First-Time Buyer Programs', 'Hottest Market Velocity'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'Worcester lender — localized knowledge of one of the country\'s hottest markets for investors and first-time buyers.',
    website: 'https://novahomeloans.com', phone: '(508) 555-2112',
  },

  // ── Transit-Oriented Urban Hotspots (Somerville & Cambridge — Middlesex) ──────
  {
    id: 'ma-13', slug: 'local-cambridge-somerville-independent-mortgage', name: 'Local Cambridge/Somerville Independent Mortgage', nmlsId: '392847', type: 'Broker',
    city: 'Cambridge', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02138', '02139', '02143', '02144'], rating: 4.9, reviewCount: 720, trustScore: 96, countyExperienceScore: 97,
    nationalVolumeRank: 34, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Tech/Biotech Financing', 'Transit-Oriented Urban', 'Green Line Extension Impact'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'Local Cambridge/Somerville independent — strong knowledge of Green Line extension impact and tech/biotech transit-oriented financing.',
    website: 'https://cambridgesomervillemortgage.com', phone: '(617) 555-2201',
  },
  {
    id: 'ma-14', slug: 'guild-mortgage-cambridge-somerville', name: 'Guild Mortgage (Cambridge/Somerville)', nmlsId: '3274', type: 'Lender',
    city: 'Cambridge', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02138', '02139', '02140', '02143'], rating: 4.8, reviewCount: 465, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Middlesex County Operations', 'Transit & Tech Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 26, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Cambridge and Somerville branches — comprehensive financing for tech/biotech professionals and transit-oriented urban properties.',
    website: 'https://guildmortgage.com', phone: '(617) 555-2202',
  },
  {
    id: 'ma-15', slug: 'new-american-funding-cambridge-somerville', name: 'New American Funding (Cambridge)', nmlsId: '6606', type: 'Lender',
    city: 'Cambridge', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02138', '02139', '02142', '02144'], rating: 4.9, reviewCount: 420, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Premium Urban Transactions', 'Cambridge/Somerville Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'NAF Cambridge team — excellent ratings for premium urban purchase and refinance in fierce-demand transit corridors.',
    website: 'https://newamericanfunding.com', phone: '(617) 555-2203',
  },
  {
    id: 'ma-16', slug: 'crosscountry-mortgage-cambridge-somerville', name: 'CrossCountry Mortgage (Greater Boston)', nmlsId: '3029', type: 'Lender',
    city: 'Somerville', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02143', '02144', '02145', '02139'], rating: 4.8, reviewCount: 380, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Tech/Biotech Professionals', 'Higher Education Corridors', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Greater Boston teams — experienced support for tech/biotech and higher education professionals in Somerville and Cambridge.',
    website: 'https://crosscountrymortgage.com', phone: '(617) 555-2204',
  },
  {
    id: 'ma-17', slug: 'pierpoint-mortgage-cambridge-somerville', name: 'PierPoint Mortgage (Boston Metro)', nmlsId: '112844', type: 'Broker',
    city: 'Cambridge', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02138', '02139', '02143', '02144'], rating: 4.9, reviewCount: 195, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Transit-Adjacent Properties', 'Fast Closings', 'Fierce Premium Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 19, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to fierce demand and premium pricing on transit-adjacent Cambridge and Somerville properties.',
    website: 'https://pierpointmortgage.com', phone: '(617) 555-2205',
  },
  {
    id: 'ma-18', slug: 'silverton-mortgage-cambridge-somerville', name: 'Silverton Mortgage — Somerville/Cambridge', nmlsId: '1561', type: 'Lender',
    city: 'Somerville', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02143', '02144', '02145', '02140'], rating: 4.8, reviewCount: 168, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Green Line Neighborhoods', 'Retail Local Expertise', 'Somerville Area'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'Silverton Somerville retail lending — professional service for neighborhoods near Green Line extension corridors.',
    website: 'https://silvertonmortgage.com', phone: '(617) 555-2206',
  },
  {
    id: 'ma-19', slug: 'young-professional-biotech-mortgage-cambridge', name: 'Young Professional & Biotech Specialists (Cambridge)', nmlsId: '528194', type: 'Broker',
    city: 'Cambridge', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02138', '02139', '02142', '02143'], rating: 4.9, reviewCount: 510, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 40, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Modern Condo Programs', 'Urban Rowhome Financing', 'High-Earning Tech Transplants'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Young professional and biotech specialist — tailored for high-earning tech/biotech transplants seeking Cambridge and Somerville urban cores.',
    website: 'https://biotechurbanmortgage.com', phone: '(617) 555-2207',
  },
  {
    id: 'ma-20', slug: 'dcu-cambridge-somerville', name: 'Digital Federal Credit Union (Cambridge/Somerville)', nmlsId: '414078', type: 'Credit Union',
    city: 'Somerville', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02143', '02144', '02138', '02139'], rating: 4.9, reviewCount: 920, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 55, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Member Rates', 'Urban Professional Programs', 'Middlesex County CU'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Massachusetts credit union — community-focused member rates for urban professionals in high-velocity Cambridge and Somerville hotspots.',
    website: 'https://dcu.org', phone: '(800) 328-8797',
  },
  {
    id: 'ma-21', slug: 'green-line-transit-mortgage-cambridge-somerville', name: 'Green Line Transit Specialists (Somerville/Cambridge)', nmlsId: '384721', type: 'Broker',
    city: 'Somerville', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02143', '02144', '02145', '02139'], rating: 4.9, reviewCount: 340, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 38, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Green Line Extension', 'Transit Station Proximity', 'Continuously Driven-Up Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 95,
    shortDescription: 'Transit-oriented specialist — expertise in properties near new Green Line stations and continuously driven-up demand areas.',
    website: 'https://greenlinetransitmortgage.com', phone: '(617) 555-2209',
  },
  {
    id: 'ma-22', slug: 'anchor-home-mortgage-cambridge-somerville', name: 'Anchor Home Mortgage (Cambridge/Somerville)', nmlsId: '136890', type: 'Broker',
    city: 'Cambridge', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02138', '02139', '02143', '02144'], rating: 4.9, reviewCount: 265, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Personalized Brokerage', '$930K+ Somerville Medians', '$1M+ Cambridge Medians'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on premium urban financing for $930K+ Somerville and $1M+ Cambridge median markets.',
    website: 'https://anchorhomemortgage.com', phone: '(617) 555-2210',
  },
  {
    id: 'ma-23', slug: 'bank-of-america-mortgage-cambridge-somerville', name: 'Bank of America Mortgage (Cambridge/Somerville)', nmlsId: '399802', type: 'Bank',
    city: 'Cambridge', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02138', '02139', '02142', '02143'], rating: 4.6, reviewCount: 680, trustScore: 89, countyExperienceScore: 91,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Professional Relocation Financing', 'Biotech Job Growth', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 30, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for biotech and higher education professional relocations to Cambridge and Somerville.',
    website: 'https://bankofamerica.com/mortgage', phone: '(617) 555-2211',
  },
  {
    id: 'ma-24', slug: 'nova-home-loans-cambridge-somerville', name: 'Nova Home Loans (Somerville/Cambridge Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Somerville', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex',
    zipCodes: ['02143', '02144', '02138', '02139'], rating: 4.8, reviewCount: 310, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Investor Financing', 'Premium Urban Properties', 'Transit-Oriented Hotspots'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 24, onTimeCloseRate: 94,
    shortDescription: 'Middlesex lender — localized knowledge of perennially hot transit-oriented Cambridge and Somerville investor markets.',
    website: 'https://novahomeloans.com', phone: '(617) 555-2212',
  },
];

export const WORCESTER_UNDISPUTED_GROWTH_LEADER_LENDER_SLUGS = [
  'central-mass-independent-mortgage-worcester',
  'guild-mortgage-worcester',
  'new-american-funding-worcester',
  'crosscountry-mortgage-worcester',
  'pierpoint-mortgage-worcester',
  'silverton-mortgage-worcester',
  'young-professional-investor-mortgage-worcester',
  'dcu-worcester',
  'downtown-new-construction-mortgage-worcester',
  'anchor-home-mortgage-worcester',
  'bank-of-america-mortgage-worcester',
  'nova-home-loans-worcester',
] as const;

export const TRANSIT_ORIENTED_URBAN_HOTSPOTS_LENDER_SLUGS = [
  'local-cambridge-somerville-independent-mortgage',
  'guild-mortgage-cambridge-somerville',
  'new-american-funding-cambridge-somerville',
  'crosscountry-mortgage-cambridge-somerville',
  'pierpoint-mortgage-cambridge-somerville',
  'silverton-mortgage-cambridge-somerville',
  'young-professional-biotech-mortgage-cambridge',
  'dcu-cambridge-somerville',
  'green-line-transit-mortgage-cambridge-somerville',
  'anchor-home-mortgage-cambridge-somerville',
  'bank-of-america-mortgage-cambridge-somerville',
  'nova-home-loans-cambridge-somerville',
] as const;

export const MASSACHUSETTS_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  worcester: [],
  middlesex: [],
};

export const TRANSIT_ORIENTED_URBAN_HOTSPOTS_HUB_COUNTIES = [
  { name: 'Middlesex', slug: 'middlesex', highlight: 'Cambridge & Somerville transit-oriented urban core' },
] as const;

export const TRANSIT_ORIENTED_URBAN_HOTSPOTS_HUB_AREAS = [
  { name: 'Cambridge', slug: 'middlesex', highlight: '$1M+ medians, Kendall Square biotech' },
  { name: 'Somerville', slug: 'middlesex', highlight: '$930K+ medians, Green Line extension' },
  { name: 'Union Square', slug: 'middlesex', highlight: 'New transit stations, fierce demand' },
  { name: 'Davis / Porter', slug: 'middlesex', highlight: 'Walkable T-access urban cores' },
] as const;

export const WORCESTER_UNDISPUTED_GROWTH_LEADER_HUB_COUNTIES = [
  { name: 'Worcester', slug: 'worcester', highlight: 'Undisputed Central Mass growth leader' },
] as const;

export const WORCESTER_UNDISPUTED_GROWTH_LEADER_HUB_AREAS = [
  { name: 'Downtown Worcester', slug: 'worcester', highlight: 'Zoom Town revitalization, life sciences boom' },
  { name: 'Polar Park Corridor', slug: 'worcester', highlight: 'Stadium district investment & new demand' },
  { name: 'Commuter Rail Hub', slug: 'worcester', highlight: 'Union Station access, Boston connectivity' },
  { name: 'Worcester County', slug: 'worcester', highlight: 'Relative affordability vs. Greater Boston' },
] as const;