import type { Lender } from '@/lib/mockData';

export const MASSACHUSETTS_LENDERS: Lender[] = [
  // ── Undisputed Growth Leader (Worcester — Zip 01608) ─────────────────────────
  {
    id: 'ma-01', slug: 'central-mass-independent-mortgage-worcester', name: 'Local Worcester Independent Mortgage', nmlsId: '284719', type: 'Broker',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.9, reviewCount: 640, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 36, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['First-Time Buyer Programs', 'Life Sciences Relocations', 'Zoom Town & Downtown Revitalization'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Local Worcester independent — strong knowledge of Zoom Town dynamics, downtown revitalization, and life sciences relocation financing.',
    website: 'https://centralmassmortgage.com', phone: '(508) 555-2101',
  },
  {
    id: 'ma-02', slug: 'guild-mortgage-worcester', name: 'Guild Mortgage (Worcester)', nmlsId: '3274', type: 'Lender',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.8, reviewCount: 410, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'First-Time & Investor Growth', 'Worcester County Operations'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Worcester branches — comprehensive financing for first-time buyers and investors in one of the country\'s hottest markets.',
    website: 'https://guildmortgage.com', phone: '(508) 555-2102',
  },
  {
    id: 'ma-03', slug: 'new-american-funding-worcester', name: 'New American Funding (Worcester)', nmlsId: '6606', type: 'Lender',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.9, reviewCount: 375, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Commuter Rail Corridor', 'Investor Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 25, onTimeCloseRate: 95,
    shortDescription: 'NAF Worcester team — excellent ratings for commuter rail corridor buyers and investor demand in fast-moving Worcester County.',
    website: 'https://newamericanfunding.com', phone: '(508) 555-2103',
  },
  {
    id: 'ma-04', slug: 'crosscountry-mortgage-worcester', name: 'CrossCountry Mortgage (Central MA)', nmlsId: '3029', type: 'Lender',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.8, reviewCount: 320, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Life Sciences Sector', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Central MA teams — experienced support for first-time buyers in Worcester\'s booming life sciences sector.',
    website: 'https://crosscountrymortgage.com', phone: '(508) 555-2104',
  },
  {
    id: 'ma-05', slug: 'pierpoint-mortgage-worcester', name: 'PierPoint Mortgage (Central MA)', nmlsId: '112844', type: 'Broker',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.9, reviewCount: 155, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Exceptionally Fast-Moving Market'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to Worcester\'s exceptionally fast-moving first-time buyer market.',
    website: 'https://pierpointmortgage.com', phone: '(508) 555-2105',
  },
  {
    id: 'ma-06', slug: 'silverton-mortgage-worcester', name: 'Silverton Mortgage — Worcester', nmlsId: '1561', type: 'Lender',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.8, reviewCount: 142, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Polar Park Corridor', 'Downtown Revitalization', 'Retail Local Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Worcester retail lending — professional service for Polar Park and downtown revitalization areas.',
    website: 'https://silvertonmortgage.com', phone: '(508) 555-2106',
  },
  {
    id: 'ma-07', slug: 'young-professional-investor-mortgage-worcester', name: 'Young Professional & Investor Specialists (Worcester)', nmlsId: '518392', type: 'Broker',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.9, reviewCount: 480, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Remote Worker Programs', 'Life Sciences Professionals', 'Zoom Town Affordability'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'Young professional and investor specialist — tailored for Zoom Town remote workers and life sciences professionals seeking Worcester affordability.',
    website: 'https://centralmayoungprofmortgage.com', phone: '(508) 555-2107',
  },
  {
    id: 'ma-08', slug: 'dcu-worcester', name: 'Digital Federal Credit Union (Worcester)', nmlsId: '414078', type: 'Credit Union',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.9, reviewCount: 860, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 55, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'First-Time Buyer Options', 'Worcester County CU'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Massachusetts credit union — community-focused member rates and first-time buyer options in high-growth Worcester County.',
    website: 'https://dcu.org', phone: '(800) 328-8797',
  },
  {
    id: 'ma-09', slug: 'downtown-new-construction-mortgage-worcester', name: 'New Construction & Downtown Specialists (Worcester)', nmlsId: '367284', type: 'Broker',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.9, reviewCount: 295, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 40, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Downtown Revitalization', 'New-Build Financing', 'Commuter Rail Access'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 24, onTimeCloseRate: 95,
    shortDescription: 'New construction and downtown specialist — expertise in revitalization investments and commuter rail-access properties.',
    website: 'https://worcesterdowntownmortgage.com', phone: '(508) 555-2109',
  },
  {
    id: 'ma-10', slug: 'anchor-home-mortgage-worcester', name: 'Anchor Home Mortgage (Worcester)', nmlsId: '136890', type: 'Broker',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.9, reviewCount: 230, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Personalized Brokerage', 'Central MA Buyers', 'Greater Boston Affordability'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on relative affordability vs. Greater Boston for Central MA buyers.',
    website: 'https://anchorhomemortgage.com', phone: '(508) 555-2110',
  },
  {
    id: 'ma-11', slug: 'bank-of-america-mortgage-worcester', name: 'Bank of America Mortgage (Worcester)', nmlsId: '399802', type: 'Bank',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01609', '01610'], rating: 4.6, reviewCount: 520, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Relocation Financing', 'Life Sciences Influx', 'Full-Service Banking'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 32, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for life sciences and remote worker relocations to Worcester County.',
    website: 'https://bankofamerica.com/mortgage', phone: '(508) 555-2111',
  },
  {
    id: 'ma-12', slug: 'nova-home-loans-worcester', name: 'Nova Home Loans (Worcester Independents)', nmlsId: '3089', type: 'Lender',
    city: 'Worcester', state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester',
    zipCodes: ['01608', '01602', '01604'], rating: 4.8, reviewCount: 255, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'First-Time Buyer Programs', 'Hottest Market Velocity'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'Worcester lender — localized knowledge of one of the country\'s hottest markets for investors and first-time buyers.',
    website: 'https://novahomeloans.com', phone: '(508) 555-2112',
  },
];

export const WORCESTER_UNDISPUTED_GROWTH_LEADER_LENDER_SLUGS = [
  'central-mass-independent-mortgage-worcester',
  'guild-mortgage-worcester',
  'new-american-funding-worcester',
  'crosscountry-mortgage-worcester',
  'pierpoint-mortgage-worcester',
  'silverton-mortgage-worcester',
  'young-professional-investor-mortgage-worcester',
  'dcu-worcester',
  'downtown-new-construction-mortgage-worcester',
  'anchor-home-mortgage-worcester',
  'bank-of-america-mortgage-worcester',
  'nova-home-loans-worcester',
] as const;

export const MASSACHUSETTS_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  worcester: [],
};

export const WORCESTER_UNDISPUTED_GROWTH_LEADER_HUB_COUNTIES = [
  { name: 'Worcester', slug: 'worcester', highlight: 'Undisputed Central Mass growth leader' },
] as const;

export const WORCESTER_UNDISPUTED_GROWTH_LEADER_HUB_AREAS = [
  { name: 'Downtown Worcester', slug: 'worcester', highlight: 'Zoom Town revitalization, life sciences boom' },
  { name: 'Polar Park Corridor', slug: 'worcester', highlight: 'Stadium district investment & new demand' },
  { name: 'Commuter Rail Hub', slug: 'worcester', highlight: 'Union Station access, Boston connectivity' },
  { name: 'Worcester County', slug: 'worcester', highlight: 'Relative affordability vs. Greater Boston' },
] as const;