import type { Lender } from '@/lib/mockData';

export const MICHIGAN_LENDERS: Lender[] = [
  // ── Greater Detroit Value Pockets (Dearborn, Lincoln Park & Howell) ──────────
  {
    id: 'mi-01', slug: 'local-greater-detroit-independent-mortgage', name: 'Local Greater Detroit Independent Mortgage', nmlsId: '502891', type: 'Broker',
    city: 'Dearborn', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48126', '48124', '48146'], rating: 4.9, reviewCount: 680, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 32, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Entry-Level Neighborhoods', 'Transitional Markets', 'Purchasing Power'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 21, onTimeCloseRate: 96,
    shortDescription: 'Local Greater Detroit independent — strong knowledge of entry-level and transitional neighborhood demand across Dearborn and Lincoln Park.',
    website: 'https://greaterdetroitindependentmortgage.com', phone: '(313) 555-5101',
  },
  {
    id: 'mi-02', slug: 'guild-mortgage-greater-detroit', name: 'Guild Mortgage (Greater Detroit)', nmlsId: '3274', type: 'Lender',
    city: 'Dearborn', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48126', '48124', '48120'], rating: 4.8, reviewCount: 470, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Wayne County Operations', 'Value Pocket Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 26, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Dearborn branches — comprehensive financing across Southeast Michigan value pockets.',
    website: 'https://guildmortgage.com', phone: '(313) 555-5102',
  },
  {
    id: 'mi-03', slug: 'new-american-funding-dearborn', name: 'New American Funding (Dearborn)', nmlsId: '6606', type: 'Lender',
    city: 'Dearborn', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48126', '48124', '48128'], rating: 4.9, reviewCount: 445, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Zillow Top 5 City', 'High-Volume Purchase/Refinance', 'Cultural Community Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 96,
    shortDescription: 'NAF Dearborn team — excellent ratings for one of Zillow\'s top 5 most popular US home shopping cities.',
    website: 'https://newamericanfunding.com', phone: '(313) 555-5103',
  },
  {
    id: 'mi-04', slug: 'crosscountry-mortgage-lincoln-park', name: 'CrossCountry Mortgage (Lincoln Park)', nmlsId: '3029', type: 'Lender',
    city: 'Lincoln Park', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48146', '48126', '48124'], rating: 4.8, reviewCount: 375, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Redfin Top 10 Neighborhood', '40% Over Asking', 'Affordable Price Point'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 24, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Lincoln Park — experienced support for Redfin\'s top 10 hottest neighborhood with 14% YoY sales jump.',
    website: 'https://crosscountrymortgage.com', phone: '(313) 555-5104',
  },
  {
    id: 'mi-05', slug: 'pierpoint-mortgage-greater-detroit', name: 'PierPoint Mortgage (Greater Detroit)', nmlsId: '112844', type: 'Broker',
    city: 'Lincoln Park', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48146', '48126', '48124'], rating: 4.9, reviewCount: 178, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Over-Asking Competition'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 18, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to nearly 40% over-asking sales in Lincoln Park\'s affordable hot market.',
    website: 'https://pierpointmortgage.com', phone: '(313) 555-5105',
  },
  {
    id: 'mi-06', slug: 'silverton-mortgage-greater-detroit', name: 'Silverton Mortgage — Greater Detroit', nmlsId: '1561', type: 'Lender',
    city: 'Dearborn', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48126', '48146', '48124'], rating: 4.8, reviewCount: 162, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Entry-Level Markets', 'Retail Local Expertise', 'Transitional Neighborhoods'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Dearborn retail lending — professional service for maximizing purchasing power in value pockets.',
    website: 'https://silvertonmortgage.com', phone: '(313) 555-5106',
  },
  {
    id: 'mi-07', slug: 'entry-level-transitional-mortgage-greater-detroit', name: 'Entry-Level & Transitional Neighborhood Specialists (Greater Detroit)', nmlsId: '513827', type: 'Broker',
    city: 'Lincoln Park', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48146', '48126', '48124'], rating: 4.9, reviewCount: 495, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 36, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Purchasing Power Maximization', 'Transitional Neighborhoods', '14% YoY Sales Growth'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 20, onTimeCloseRate: 96,
    shortDescription: 'Entry-level specialist — tailored for buyers maximizing value in Lincoln Park and Dearborn hot markets.',
    website: 'https://detroitentrylevelmortgage.com', phone: '(313) 555-5107',
  },
  {
    id: 'mi-08', slug: 'greater-detroit-community-credit-union', name: 'Greater Detroit Community Credit Union', nmlsId: '559102', type: 'Credit Union',
    city: 'Dearborn', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48126', '48124', '48146'], rating: 4.9, reviewCount: 820, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 54, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Affordable Options', 'Community-Focused Lending'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Community credit union — member rates for Southeast Michigan value pocket buyers.',
    website: 'https://greaterdetroitcu.org', phone: '(313) 555-5108',
  },
  {
    id: 'mi-09', slug: 'mshda-first-time-mortgage-greater-detroit', name: 'MSHDA & First-Time Buyer Specialists (Dearborn)', nmlsId: '521293', type: 'Broker',
    city: 'Dearborn', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48126', '48124', '48128'], rating: 4.9, reviewCount: 320, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 38, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Michigan MSHDA Programs', 'First-Time Buyers', 'Accessible Median Values'],
    creditTiers: ['Excellent', 'Good', 'Fair', 'Rebuilding'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 95,
    shortDescription: 'MSHDA specialist — expertise in Dearborn\'s accessible median values and Zillow top-5 buyer search explosion.',
    website: 'https://dearbornmshdamortgage.com', phone: '(313) 555-5109',
  },
  {
    id: 'mi-10', slug: 'anchor-home-mortgage-greater-detroit', name: 'Anchor Home Mortgage (Greater Detroit)', nmlsId: '136890', type: 'Broker',
    city: 'Lincoln Park', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48146', '48126', '48124'], rating: 4.9, reviewCount: 260, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['40% Over Asking', 'Personalized Brokerage', 'Value Pocket Buyers'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 19, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on Lincoln Park over-asking competition and affordable hot-market dynamics.',
    website: 'https://anchorhomemortgage.com', phone: '(313) 555-5110',
  },
  {
    id: 'mi-11', slug: 'bank-of-america-mortgage-greater-detroit', name: 'Bank of America Mortgage (Greater Detroit)', nmlsId: '399802', type: 'Bank',
    city: 'Dearborn', state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne',
    zipCodes: ['48126', '48124', '48146'], rating: 4.6, reviewCount: 590, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Relocation Financing', 'Full-Service Banking', 'Metro Detroit Value'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 31, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for buyers in Dearborn and Lincoln Park value pockets.',
    website: 'https://bankofamerica.com/mortgage', phone: '(313) 555-5111',
  },
  {
    id: 'mi-12', slug: 'nova-home-loans-howell-greater-detroit', name: 'Nova Home Loans (Howell / Greater Detroit)', nmlsId: '3089', type: 'Lender',
    city: 'Howell', state: 'Michigan', stateSlug: 'michigan', county: 'Livingston', countySlug: 'livingston',
    zipCodes: ['48843', '48855', '48146'], rating: 4.8, reviewCount: 270, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Redfin Top 10 Market', 'High-End Bidding Wars', 'Page View Surge'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 22, onTimeCloseRate: 94,
    shortDescription: 'Howell lender — localized knowledge of Redfin\'s national top 10 hottest market and rapid-fire bidding wars.',
    website: 'https://novahomeloans.com', phone: '(517) 555-5112',
  },
];

export const GREATER_DETROITS_VALUE_POCKETS_LENDER_SLUGS = [
  'local-greater-detroit-independent-mortgage',
  'guild-mortgage-greater-detroit',
  'new-american-funding-dearborn',
  'crosscountry-mortgage-lincoln-park',
  'pierpoint-mortgage-greater-detroit',
  'silverton-mortgage-greater-detroit',
  'entry-level-transitional-mortgage-greater-detroit',
  'greater-detroit-community-credit-union',
  'mshda-first-time-mortgage-greater-detroit',
  'anchor-home-mortgage-greater-detroit',
  'bank-of-america-mortgage-greater-detroit',
  'nova-home-loans-howell-greater-detroit',
] as const;

const GREATER_DETROIT_WAYNE_SUPPLEMENTS = [
  'nova-home-loans-howell-greater-detroit',
];

const GREATER_DETROIT_LIVINGSTON_SUPPLEMENTS = [
  'local-greater-detroit-independent-mortgage',
  'guild-mortgage-greater-detroit',
  'new-american-funding-dearborn',
  'crosscountry-mortgage-lincoln-park',
  'pierpoint-mortgage-greater-detroit',
  'silverton-mortgage-greater-detroit',
  'entry-level-transitional-mortgage-greater-detroit',
  'greater-detroit-community-credit-union',
  'mshda-first-time-mortgage-greater-detroit',
  'anchor-home-mortgage-greater-detroit',
  'bank-of-america-mortgage-greater-detroit',
];

export const MICHIGAN_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  wayne: GREATER_DETROIT_WAYNE_SUPPLEMENTS,
  livingston: GREATER_DETROIT_LIVINGSTON_SUPPLEMENTS,
};

export const GREATER_DETROITS_VALUE_POCKETS_HUB_AREAS = [
  { name: 'Dearborn', slug: 'wayne', highlight: 'Zillow top 5 US city, cultural community, accessible values' },
  { name: 'Lincoln Park', slug: 'wayne', highlight: 'Redfin top 10 neighborhood, 40% over asking, 14% YoY sales' },
  { name: 'Howell', slug: 'livingston', highlight: 'Redfin top 10 market, high-end bidding wars, page view surge' },
  { name: 'Wayne County', slug: 'wayne', highlight: 'Entry-level & transitional neighborhood demand' },
] as const;