/**
 * National / multi-state mortgage originators linked to Florida 2025 HMDA LEIs.
 *
 * Profiles prioritize verifiable identity (NMLS, legal name, HQ locality, website)
 * over reputation placeholders. Closing times and review ratings are omitted (0 / null)
 * so Research Score does not invent third-party performance claims.
 *
 * Volume figures for product UI come from HMDA evidence panels, not these rows.
 */
import type { Lender } from '@/lib/mockData';

/** Neutral catalog placeholders — sanitized / research scoring recomputes trustScore. */
const BASE = {
  rating: 0,
  reviewCount: 0,
  trustScore: 50,
  countyExperienceScore: 50,
  googleRating: 0,
  trustpilotRating: 0,
  /** No invented complaint census — score treats 0 as “clean”; prefer missing later */
  cfpbComplaints: 0,
  bbbRating: 'A' as const,
  nmlsVerified: true as const,
  creditTiers: ['Excellent', 'Good', 'Fair'] as Lender['creditTiers'],
};

export const NATIONAL_HMDA_LENDERS: Lender[] = [
  {
    ...BASE,
    id: 'nat-uwm',
    slug: 'united-wholesale-mortgage',
    name: 'United Wholesale Mortgage',
    nmlsId: '3038',
    type: 'Lender',
    city: 'Pontiac',
    state: 'Michigan',
    stateSlug: 'michigan',
    county: 'Oakland',
    countySlug: 'oakland',
    zipCodes: ['48341'],
    nationalVolumeRank: 1,
    loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Jumbo', 'Refinance'],
    specialties: [
      'Wholesale / broker channel',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'United Wholesale Mortgage (UWM), NMLS #3038, is a national wholesale mortgage lender headquartered in Pontiac, Michigan. It originates residential mortgages through independent brokers across the United States, including substantial Florida activity reported in public HMDA filings.',
    website: 'https://www.uwm.com',
  },
  {
    ...BASE,
    id: 'nat-rocket',
    slug: 'rocket-mortgage',
    name: 'Rocket Mortgage',
    nmlsId: '3030',
    type: 'Lender',
    city: 'Detroit',
    state: 'Michigan',
    stateSlug: 'michigan',
    county: 'Wayne',
    countySlug: 'wayne',
    zipCodes: ['48226'],
    nationalVolumeRank: 2,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: [
      'Direct-to-consumer digital origination',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'Rocket Mortgage, LLC (NMLS #3030), headquartered in Detroit, Michigan, is a national retail mortgage lender operating in all 50 states. Public HMDA data includes significant Florida originations for purchase and refinance products.',
    website: 'https://www.rocketmortgage.com',
  },
  {
    ...BASE,
    id: 'nat-freedom',
    slug: 'freedom-mortgage',
    name: 'Freedom Mortgage',
    nmlsId: '2767',
    type: 'Lender',
    city: 'Mount Laurel',
    state: 'New Jersey',
    stateSlug: 'new-jersey',
    county: 'Burlington',
    countySlug: 'burlington',
    zipCodes: ['08054'],
    nationalVolumeRank: 3,
    loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Refinance'],
    specialties: [
      'Retail and correspondent channels',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'Freedom Mortgage Corporation (NMLS #2767) is a national mortgage company based in Mount Laurel, New Jersey. It originates and services residential loans nationwide; Florida HMDA filings show high statewide volume among independent mortgage companies.',
    website: 'https://www.freedommortgage.com',
  },
  {
    ...BASE,
    id: 'nat-loandepot',
    slug: 'loandepot',
    name: 'loanDepot',
    nmlsId: '174457',
    type: 'Lender',
    city: 'Irvine',
    state: 'California',
    stateSlug: 'california',
    county: 'Orange',
    countySlug: 'orange',
    zipCodes: ['92612'],
    nationalVolumeRank: 4,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: [
      'Retail digital and branch origination',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'loanDepot.com, LLC (NMLS #174457) is a national retail mortgage lender headquartered in Irvine, California. It offers purchase and refinance mortgages across a multi-state footprint, including material Florida activity in 2025 HMDA data.',
    website: 'https://www.loandepot.com',
  },
  {
    ...BASE,
    id: 'nat-guaranteed-rate',
    slug: 'guaranteed-rate',
    name: 'Guaranteed Rate',
    nmlsId: '2611',
    type: 'Lender',
    city: 'Chicago',
    state: 'Illinois',
    stateSlug: 'illinois',
    county: 'Cook',
    countySlug: 'cook',
    zipCodes: ['60654'],
    nationalVolumeRank: 5,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: [
      'Retail mortgage banking',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'Guaranteed Rate, Inc. (NMLS #2611) is a national retail mortgage lender headquartered in Chicago, Illinois. It originates conventional and government loans across a multi-state network; Florida HMDA records show significant 2025 originations.',
    website: 'https://www.guaranteedrate.com',
  },
  {
    ...BASE,
    id: 'nat-pennymac',
    slug: 'pennymac',
    name: 'PennyMac Loan Services',
    nmlsId: '35953',
    type: 'Lender',
    city: 'Westlake Village',
    state: 'California',
    stateSlug: 'california',
    county: 'Los Angeles',
    countySlug: 'los-angeles',
    zipCodes: ['91362'],
    nationalVolumeRank: 6,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: [
      'Correspondent and retail channels',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'PennyMac Loan Services, LLC (NMLS #35953), based in Westlake Village, California, is a national mortgage originator and servicer. Public HMDA data for Florida includes substantial 2025 production under this institution.',
    website: 'https://www.pennymac.com',
  },
  {
    ...BASE,
    id: 'nat-chase',
    slug: 'jpmorgan-chase-bank',
    name: 'JPMorgan Chase Bank',
    nmlsId: '399798',
    type: 'Bank',
    city: 'Columbus',
    state: 'Ohio',
    stateSlug: 'ohio',
    county: 'Franklin',
    countySlug: 'franklin',
    zipCodes: ['43240'],
    nationalVolumeRank: 7,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: [
      'Bank-direct mortgage',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'JPMorgan Chase Bank, National Association (NMLS #399798) is a national bank offering consumer mortgage products under the Chase brand. Florida HMDA filings report multi-thousand originations statewide in 2025.',
    website: 'https://www.chase.com/personal/mortgage',
  },
  // ── Additional high-volume FL HMDA nationals (no prior directory slug) ──
  {
    ...BASE,
    id: 'nat-truist',
    slug: 'truist-bank',
    name: 'Truist Bank',
    nmlsId: '405457',
    type: 'Bank',
    city: 'Charlotte',
    state: 'North Carolina',
    stateSlug: 'north-carolina',
    county: 'Mecklenburg',
    countySlug: 'mecklenburg',
    zipCodes: ['28202'],
    nationalVolumeRank: 8,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Bank-direct mortgage', 'Southeast footprint', 'Florida HMDA activity'],
    shortDescription:
      'Truist Bank (NMLS #405457) is a large regional/national bank formed from BB&T and SunTrust, with mortgage operations across the Southeast and beyond. Florida HMDA data shows multi-thousand 2025 originations.',
    website: 'https://www.truist.com/home-ownership/mortgage',
  },
  {
    ...BASE,
    id: 'nat-regions',
    slug: 'regions-bank',
    name: 'Regions Bank',
    nmlsId: '467341',
    type: 'Bank',
    city: 'Birmingham',
    state: 'Alabama',
    stateSlug: 'alabama',
    county: 'Jefferson',
    countySlug: 'jefferson',
    zipCodes: ['35203'],
    nationalVolumeRank: 9,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Bank-direct mortgage', 'Southeast footprint', 'Florida HMDA activity'],
    shortDescription:
      'Regions Bank (NMLS #467341) is a Southeast-focused regional bank headquartered in Birmingham, Alabama, with residential mortgage lending across its footprint, including Florida.',
    website: 'https://www.regions.com/personal-banking/mortgage',
  },
  {
    ...BASE,
    id: 'nat-newrez',
    slug: 'newrez',
    name: 'Newrez',
    nmlsId: '2289',
    type: 'Lender',
    city: 'Fort Washington',
    state: 'Pennsylvania',
    stateSlug: 'pennsylvania',
    county: 'Montgomery',
    countySlug: 'montgomery',
    zipCodes: ['19034'],
    nationalVolumeRank: 10,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: [
      'Retail and wholesale channels',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'Newrez LLC (NMLS #2289) is a national mortgage company (Shellpoint / New Residential family) originating and servicing residential loans in multiple states, with material Florida HMDA volume in 2025.',
    website: 'https://www.newrez.com',
  },
  {
    ...BASE,
    id: 'nat-amerihome',
    slug: 'amerihome-mortgage',
    name: 'AmeriHome Mortgage',
    nmlsId: '1120271',
    type: 'Lender',
    city: 'Thousand Oaks',
    state: 'California',
    stateSlug: 'california',
    county: 'Ventura',
    countySlug: 'ventura',
    zipCodes: ['91362'],
    nationalVolumeRank: 11,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: [
      'Correspondent and wholesale channels',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'AmeriHome Mortgage Company, LLC (NMLS #1120271) is a national mortgage originator based in California. Florida HMDA filings place it among higher-volume independent originators statewide in 2025.',
    website: 'https://www.amerihome.com',
  },
  {
    ...BASE,
    id: 'nat-cardinal',
    slug: 'cardinal-financial',
    name: 'Cardinal Financial',
    nmlsId: '66247',
    type: 'Lender',
    city: 'Charlotte',
    state: 'North Carolina',
    stateSlug: 'north-carolina',
    county: 'Mecklenburg',
    countySlug: 'mecklenburg',
    zipCodes: ['28202'],
    nationalVolumeRank: 12,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: [
      'Retail mortgage banking',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'Cardinal Financial Company, Limited Partnership (NMLS #66247) is a national retail mortgage lender. Public HMDA data includes multi-thousand Florida originations in 2025.',
    website: 'https://www.cardinalfinancial.com',
  },
  {
    ...BASE,
    id: 'nat-naf',
    slug: 'new-american-funding',
    name: 'New American Funding',
    nmlsId: '6606',
    type: 'Lender',
    city: 'Tustin',
    state: 'California',
    stateSlug: 'california',
    county: 'Orange',
    countySlug: 'orange',
    zipCodes: ['92780'],
    nationalVolumeRank: 13,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: [
      'Retail multi-branch network',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'Broker Solutions, Inc., DBA New American Funding (NMLS #6606), is a national retail mortgage lender headquartered in Tustin, California, with Florida production reflected in 2025 HMDA data.',
    website: 'https://www.newamericanfunding.com',
  },
  {
    ...BASE,
    id: 'nat-mr-cooper',
    slug: 'mr-cooper',
    name: 'Mr. Cooper',
    nmlsId: '2104',
    type: 'Lender',
    city: 'Dallas',
    state: 'Texas',
    stateSlug: 'texas',
    county: 'Dallas',
    countySlug: 'dallas',
    zipCodes: ['75254'],
    nationalVolumeRank: 14,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: [
      'Retail origination and servicing',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'Nationstar Mortgage LLC, DBA Mr. Cooper (NMLS #2104), is a national mortgage originator and servicer headquartered in the Dallas area. Multiple Florida HMDA LEIs map to this company NMLS for 2025 activity.',
    website: 'https://www.mrcooper.com',
  },
  {
    ...BASE,
    id: 'nat-eagle',
    slug: 'eagle-home-mortgage',
    name: 'Eagle Home Mortgage',
    nmlsId: '2925',
    type: 'Lender',
    city: 'Miami',
    state: 'Florida',
    stateSlug: 'florida',
    county: 'Miami-Dade',
    countySlug: 'miami-dade',
    zipCodes: ['33126'],
    nationalVolumeRank: 15,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: [
      'Builder-affiliated / new construction',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'Eagle Home Mortgage, LLC (NMLS #2925) is a national lender affiliated with Lennar new-home communities. Florida HMDA data shows substantial 2025 originations, consistent with a large homebuilder-linked channel.',
    website: 'https://www.eaglehomemortgage.com',
  },
  {
    ...BASE,
    id: 'nat-pnc',
    slug: 'pnc-bank',
    name: 'PNC Bank',
    nmlsId: '446038',
    type: 'Bank',
    city: 'Pittsburgh',
    state: 'Pennsylvania',
    stateSlug: 'pennsylvania',
    county: 'Allegheny',
    countySlug: 'allegheny',
    zipCodes: ['15222'],
    nationalVolumeRank: 16,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Bank-direct mortgage', 'National multi-state originator', 'Florida HMDA activity'],
    shortDescription:
      'PNC Bank, National Association (NMLS #446038) is a national bank offering residential mortgage products. Florida HMDA filings include multi-thousand originations in 2025.',
    website: 'https://www.pnc.com/en/personal-banking/borrowing/home-lending.html',
  },
  {
    ...BASE,
    id: 'nat-wells-fargo',
    slug: 'wells-fargo-bank',
    name: 'Wells Fargo Bank',
    nmlsId: '399801',
    type: 'Bank',
    city: 'Sioux Falls',
    state: 'South Dakota',
    stateSlug: 'south-dakota',
    county: 'Minnehaha',
    countySlug: 'minnehaha',
    zipCodes: ['57104'],
    nationalVolumeRank: 17,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Bank-direct mortgage', 'National multi-state originator', 'Florida HMDA activity'],
    shortDescription:
      'Wells Fargo Bank, National Association (NMLS #399801) is a national bank with a large residential mortgage franchise. Florida HMDA data reports multi-thousand 2025 originations under this institution.',
    website: 'https://www.wellsfargo.com/mortgage/',
  },
  {
    ...BASE,
    id: 'nat-better',
    slug: 'better-mortgage',
    name: 'Better Mortgage',
    nmlsId: '330511',
    type: 'Lender',
    city: 'New York',
    state: 'New York',
    stateSlug: 'new-york',
    county: 'New York',
    countySlug: 'new-york',
    zipCodes: ['10003'],
    nationalVolumeRank: 18,
    loanTypes: ['Conventional', 'FHA', 'Jumbo', 'Refinance'],
    specialties: [
      'Digital direct-to-consumer',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'Better Mortgage Corporation (NMLS #330511) is a digital-first national mortgage lender. Florida HMDA filings show multi-thousand applications and originations across related LEIs in 2025.',
    website: 'https://better.com',
  },
  {
    ...BASE,
    id: 'nat-ally',
    slug: 'ally-bank',
    name: 'Ally Bank',
    nmlsId: '181005',
    type: 'Bank',
    city: 'Sandy',
    state: 'Utah',
    stateSlug: 'utah',
    county: 'Salt Lake',
    countySlug: 'salt-lake',
    zipCodes: ['84070'],
    nationalVolumeRank: 19,
    loanTypes: ['Conventional', 'Jumbo', 'Refinance'],
    specialties: ['Bank-direct digital mortgage', 'National multi-state originator', 'Florida HMDA activity'],
    shortDescription:
      'Ally Bank (NMLS #181005) is a national digital bank offering home loans under Ally Home. Florida HMDA activity appears among higher-volume bank originators in 2025.',
    website: 'https://www.ally.com/home-loans/',
  },
  {
    ...BASE,
    id: 'nat-td',
    slug: 'td-bank',
    name: 'TD Bank',
    nmlsId: '481428',
    type: 'Bank',
    city: 'Wilmington',
    state: 'Delaware',
    stateSlug: 'delaware',
    county: 'New Castle',
    countySlug: 'new-castle',
    zipCodes: ['19801'],
    nationalVolumeRank: 20,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Bank-direct mortgage', 'East Coast footprint', 'Florida HMDA activity'],
    shortDescription:
      'TD Bank, National Association (NMLS #481428) is a national bank with residential mortgage products along the East Coast, including Florida markets reflected in 2025 HMDA data.',
    website: 'https://www.td.com/us/en/personal-banking/mortgage',
  },
];
