/**
 * National / multi-state mortgage originators linked to Florida 2025 HMDA LEIs.
 *
 * Profiles prioritize verifiable identity (NMLS, legal name, HQ locality, website)
 * over reputation placeholders. Closing times and review ratings are omitted (0 / null)
 * so Research Score does not invent third-party performance claims.
 *
 * Volume figures for product UI come from HMDA evidence panels, not these rows.
 */
import type { Lender } from '@/lib/mockData';

/** Neutral catalog placeholders — sanitized / research scoring recomputes trustScore. */
const BASE = {
  rating: 0,
  reviewCount: 0,
  trustScore: 50,
  countyExperienceScore: 50,
  googleRating: 0,
  trustpilotRating: 0,
  /** No invented complaint census — score treats 0 as “clean”; prefer missing later */
  cfpbComplaints: 0,
  bbbRating: 'A' as const,
  nmlsVerified: true as const,
  creditTiers: ['Excellent', 'Good', 'Fair'] as Lender['creditTiers'],
};

export const NATIONAL_HMDA_LENDERS: Lender[] = [
  {
    ...BASE,
    id: 'nat-uwm',
    slug: 'united-wholesale-mortgage',
    name: 'United Wholesale Mortgage',
    nmlsId: '3038',
    type: 'Lender',
    city: 'Pontiac',
    state: 'Michigan',
    stateSlug: 'michigan',
    county: 'Oakland',
    countySlug: 'oakland',
    zipCodes: ['48341'],
    nationalVolumeRank: 1,
    loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Jumbo', 'Refinance'],
    specialties: [
      'Wholesale / broker channel',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'United Wholesale Mortgage (UWM), NMLS #3038, is a national wholesale mortgage lender headquartered in Pontiac, Michigan. It originates residential mortgages through independent brokers across the United States, including substantial Florida activity reported in public HMDA filings.',
    website: 'https://www.uwm.com',
  },
  {
    ...BASE,
    id: 'nat-rocket',
    slug: 'rocket-mortgage',
    name: 'Rocket Mortgage',
    nmlsId: '3030',
    type: 'Lender',
    city: 'Detroit',
    state: 'Michigan',
    stateSlug: 'michigan',
    county: 'Wayne',
    countySlug: 'wayne',
    zipCodes: ['48226'],
    nationalVolumeRank: 2,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: [
      'Direct-to-consumer digital origination',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'Rocket Mortgage, LLC (NMLS #3030), headquartered in Detroit, Michigan, is a national retail mortgage lender operating in all 50 states. Public HMDA data includes significant Florida originations for purchase and refinance products.',
    website: 'https://www.rocketmortgage.com',
  },
  {
    ...BASE,
    id: 'nat-freedom',
    slug: 'freedom-mortgage',
    name: 'Freedom Mortgage',
    nmlsId: '2767',
    type: 'Lender',
    city: 'Mount Laurel',
    state: 'New Jersey',
    stateSlug: 'new-jersey',
    county: 'Burlington',
    countySlug: 'burlington',
    zipCodes: ['08054'],
    nationalVolumeRank: 3,
    loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Refinance'],
    specialties: [
      'Retail and correspondent channels',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'Freedom Mortgage Corporation (NMLS #2767) is a national mortgage company based in Mount Laurel, New Jersey. It originates and services residential loans nationwide; Florida HMDA filings show high statewide volume among independent mortgage companies.',
    website: 'https://www.freedommortgage.com',
  },
  {
    ...BASE,
    id: 'nat-loandepot',
    slug: 'loandepot',
    name: 'loanDepot',
    nmlsId: '174457',
    type: 'Lender',
    city: 'Irvine',
    state: 'California',
    stateSlug: 'california',
    county: 'Orange',
    countySlug: 'orange',
    zipCodes: ['92612'],
    nationalVolumeRank: 4,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: [
      'Retail digital and branch origination',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'loanDepot.com, LLC (NMLS #174457) is a national retail mortgage lender headquartered in Irvine, California. It offers purchase and refinance mortgages across a multi-state footprint, including material Florida activity in 2025 HMDA data.',
    website: 'https://www.loandepot.com',
  },
  {
    ...BASE,
    id: 'nat-guaranteed-rate',
    slug: 'guaranteed-rate',
    name: 'Guaranteed Rate',
    nmlsId: '2611',
    type: 'Lender',
    city: 'Chicago',
    state: 'Illinois',
    stateSlug: 'illinois',
    county: 'Cook',
    countySlug: 'cook',
    zipCodes: ['60654'],
    nationalVolumeRank: 5,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: [
      'Retail mortgage banking',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'Guaranteed Rate, Inc. (NMLS #2611) is a national retail mortgage lender headquartered in Chicago, Illinois. It originates conventional and government loans across a multi-state network; Florida HMDA records show significant 2025 originations.',
    website: 'https://www.guaranteedrate.com',
  },
  {
    ...BASE,
    id: 'nat-pennymac',
    slug: 'pennymac',
    name: 'PennyMac Loan Services',
    nmlsId: '35953',
    type: 'Lender',
    city: 'Westlake Village',
    state: 'California',
    stateSlug: 'california',
    county: 'Los Angeles',
    countySlug: 'los-angeles',
    zipCodes: ['91362'],
    nationalVolumeRank: 6,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: [
      'Correspondent and retail channels',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'PennyMac Loan Services, LLC (NMLS #35953), based in Westlake Village, California, is a national mortgage originator and servicer. Public HMDA data for Florida includes substantial 2025 production under this institution.',
    website: 'https://www.pennymac.com',
  },
  {
    ...BASE,
    id: 'nat-chase',
    slug: 'jpmorgan-chase-bank',
    name: 'JPMorgan Chase Bank',
    nmlsId: '399798',
    type: 'Bank',
    city: 'Columbus',
    state: 'Ohio',
    stateSlug: 'ohio',
    county: 'Franklin',
    countySlug: 'franklin',
    zipCodes: ['43240'],
    nationalVolumeRank: 7,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: [
      'Bank-direct mortgage',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'JPMorgan Chase Bank, National Association (NMLS #399798) is a national bank offering consumer mortgage products under the Chase brand. Florida HMDA filings report multi-thousand originations statewide in 2025.',
    website: 'https://www.chase.com/personal/mortgage',
  },
  // ── Additional high-volume FL HMDA nationals (no prior directory slug) ──
  {
    ...BASE,
    id: 'nat-truist',
    slug: 'truist-bank',
    name: 'Truist Bank',
    nmlsId: '405457',
    type: 'Bank',
    city: 'Charlotte',
    state: 'North Carolina',
    stateSlug: 'north-carolina',
    county: 'Mecklenburg',
    countySlug: 'mecklenburg',
    zipCodes: ['28202'],
    nationalVolumeRank: 8,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Bank-direct mortgage', 'Southeast footprint', 'Florida HMDA activity'],
    shortDescription:
      'Truist Bank (NMLS #405457) is a large regional/national bank formed from BB&T and SunTrust, with mortgage operations across the Southeast and beyond. Florida HMDA data shows multi-thousand 2025 originations.',
    website: 'https://www.truist.com/home-ownership/mortgage',
  },
  {
    ...BASE,
    id: 'nat-regions',
    slug: 'regions-bank',
    name: 'Regions Bank',
    nmlsId: '467341',
    type: 'Bank',
    city: 'Birmingham',
    state: 'Alabama',
    stateSlug: 'alabama',
    county: 'Jefferson',
    countySlug: 'jefferson',
    zipCodes: ['35203'],
    nationalVolumeRank: 9,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Bank-direct mortgage', 'Southeast footprint', 'Florida HMDA activity'],
    shortDescription:
      'Regions Bank (NMLS #467341) is a Southeast-focused regional bank headquartered in Birmingham, Alabama, with residential mortgage lending across its footprint, including Florida.',
    website: 'https://www.regions.com/personal-banking/mortgage',
  },
  {
    ...BASE,
    id: 'nat-newrez',
    slug: 'newrez',
    name: 'Newrez',
    nmlsId: '2289',
    type: 'Lender',
    city: 'Fort Washington',
    state: 'Pennsylvania',
    stateSlug: 'pennsylvania',
    county: 'Montgomery',
    countySlug: 'montgomery',
    zipCodes: ['19034'],
    nationalVolumeRank: 10,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: [
      'Retail and wholesale channels',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'Newrez LLC (NMLS #2289) is a national mortgage company (Shellpoint / New Residential family) originating and servicing residential loans in multiple states, with material Florida HMDA volume in 2025.',
    website: 'https://www.newrez.com',
  },
  {
    ...BASE,
    id: 'nat-amerihome',
    slug: 'amerihome-mortgage',
    name: 'AmeriHome Mortgage',
    nmlsId: '1120271',
    type: 'Lender',
    city: 'Thousand Oaks',
    state: 'California',
    stateSlug: 'california',
    county: 'Ventura',
    countySlug: 'ventura',
    zipCodes: ['91362'],
    nationalVolumeRank: 11,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: [
      'Correspondent and wholesale channels',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'AmeriHome Mortgage Company, LLC (NMLS #1120271) is a national mortgage originator based in California. Florida HMDA filings place it among higher-volume independent originators statewide in 2025.',
    website: 'https://www.amerihome.com',
  },
  {
    ...BASE,
    id: 'nat-cardinal',
    slug: 'cardinal-financial',
    name: 'Cardinal Financial',
    nmlsId: '66247',
    type: 'Lender',
    city: 'Charlotte',
    state: 'North Carolina',
    stateSlug: 'north-carolina',
    county: 'Mecklenburg',
    countySlug: 'mecklenburg',
    zipCodes: ['28202'],
    nationalVolumeRank: 12,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: [
      'Retail mortgage banking',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'Cardinal Financial Company, Limited Partnership (NMLS #66247) is a national retail mortgage lender. Public HMDA data includes multi-thousand Florida originations in 2025.',
    website: 'https://www.cardinalfinancial.com',
  },
  {
    ...BASE,
    id: 'nat-naf',
    slug: 'new-american-funding',
    name: 'New American Funding',
    nmlsId: '6606',
    type: 'Lender',
    city: 'Tustin',
    state: 'California',
    stateSlug: 'california',
    county: 'Orange',
    countySlug: 'orange',
    zipCodes: ['92780'],
    nationalVolumeRank: 13,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: [
      'Retail multi-branch network',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'Broker Solutions, Inc., DBA New American Funding (NMLS #6606), is a national retail mortgage lender headquartered in Tustin, California, with Florida production reflected in 2025 HMDA data.',
    website: 'https://www.newamericanfunding.com',
  },
  {
    ...BASE,
    id: 'nat-mr-cooper',
    slug: 'mr-cooper',
    name: 'Mr. Cooper',
    nmlsId: '2104',
    type: 'Lender',
    city: 'Dallas',
    state: 'Texas',
    stateSlug: 'texas',
    county: 'Dallas',
    countySlug: 'dallas',
    zipCodes: ['75254'],
    nationalVolumeRank: 14,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: [
      'Retail origination and servicing',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'Nationstar Mortgage LLC, DBA Mr. Cooper (NMLS #2104), is a national mortgage originator and servicer headquartered in the Dallas area. Multiple Florida HMDA LEIs map to this company NMLS for 2025 activity.',
    website: 'https://www.mrcooper.com',
  },
  {
    ...BASE,
    id: 'nat-eagle',
    slug: 'eagle-home-mortgage',
    name: 'Eagle Home Mortgage',
    nmlsId: '2925',
    type: 'Lender',
    city: 'Miami',
    state: 'Florida',
    stateSlug: 'florida',
    county: 'Miami-Dade',
    countySlug: 'miami-dade',
    zipCodes: ['33126'],
    nationalVolumeRank: 15,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: [
      'Builder-affiliated / new construction',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'Eagle Home Mortgage, LLC (NMLS #2925) is a national lender affiliated with Lennar new-home communities. Florida HMDA data shows substantial 2025 originations, consistent with a large homebuilder-linked channel.',
    website: 'https://www.eaglehomemortgage.com',
  },
  {
    ...BASE,
    id: 'nat-pnc',
    slug: 'pnc-bank',
    name: 'PNC Bank',
    nmlsId: '446038',
    type: 'Bank',
    city: 'Pittsburgh',
    state: 'Pennsylvania',
    stateSlug: 'pennsylvania',
    county: 'Allegheny',
    countySlug: 'allegheny',
    zipCodes: ['15222'],
    nationalVolumeRank: 16,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Bank-direct mortgage', 'National multi-state originator', 'Florida HMDA activity'],
    shortDescription:
      'PNC Bank, National Association (NMLS #446038) is a national bank offering residential mortgage products. Florida HMDA filings include multi-thousand originations in 2025.',
    website: 'https://www.pnc.com/en/personal-banking/borrowing/home-lending.html',
  },
  {
    ...BASE,
    id: 'nat-wells-fargo',
    slug: 'wells-fargo-bank',
    name: 'Wells Fargo Bank',
    nmlsId: '399801',
    type: 'Bank',
    city: 'Sioux Falls',
    state: 'South Dakota',
    stateSlug: 'south-dakota',
    county: 'Minnehaha',
    countySlug: 'minnehaha',
    zipCodes: ['57104'],
    nationalVolumeRank: 17,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Bank-direct mortgage', 'National multi-state originator', 'Florida HMDA activity'],
    shortDescription:
      'Wells Fargo Bank, National Association (NMLS #399801) is a national bank with a large residential mortgage franchise. Florida HMDA data reports multi-thousand 2025 originations under this institution.',
    website: 'https://www.wellsfargo.com/mortgage/',
  },
  {
    ...BASE,
    id: 'nat-better',
    slug: 'better-mortgage',
    name: 'Better Mortgage',
    nmlsId: '330511',
    type: 'Lender',
    city: 'New York',
    state: 'New York',
    stateSlug: 'new-york',
    county: 'New York',
    countySlug: 'new-york',
    zipCodes: ['10003'],
    nationalVolumeRank: 18,
    loanTypes: ['Conventional', 'FHA', 'Jumbo', 'Refinance'],
    specialties: [
      'Digital direct-to-consumer',
      'National multi-state originator',
      'Florida HMDA activity',
    ],
    shortDescription:
      'Better Mortgage Corporation (NMLS #330511) is a digital-first national mortgage lender. Florida HMDA filings show multi-thousand applications and originations across related LEIs in 2025.',
    website: 'https://better.com',
  },
  {
    ...BASE,
    id: 'nat-ally',
    slug: 'ally-bank',
    name: 'Ally Bank',
    nmlsId: '181005',
    type: 'Bank',
    city: 'Sandy',
    state: 'Utah',
    stateSlug: 'utah',
    county: 'Salt Lake',
    countySlug: 'salt-lake',
    zipCodes: ['84070'],
    nationalVolumeRank: 19,
    loanTypes: ['Conventional', 'Jumbo', 'Refinance'],
    specialties: ['Bank-direct digital mortgage', 'National multi-state originator', 'Florida HMDA activity'],
    shortDescription:
      'Ally Bank (NMLS #181005) is a national digital bank offering home loans under Ally Home. Florida HMDA activity appears among higher-volume bank originators in 2025.',
    website: 'https://www.ally.com/home-loans/',
  },
  {
    ...BASE,
    id: 'nat-td',
    slug: 'td-bank',
    name: 'TD Bank',
    nmlsId: '481428',
    type: 'Bank',
    city: 'Wilmington',
    state: 'Delaware',
    stateSlug: 'delaware',
    county: 'New Castle',
    countySlug: 'new-castle',
    zipCodes: ['19801'],
    nationalVolumeRank: 20,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Bank-direct mortgage', 'East Coast footprint', 'Florida HMDA activity'],
    shortDescription:
      'TD Bank, National Association (NMLS #481428) is a national bank with residential mortgage products along the East Coast, including Florida markets reflected in 2025 HMDA data.',
    website: 'https://www.td.com/us/en/personal-banking/mortgage',
  },
  // ── Remaining high-priority mapping LEIs (empty slug) ──
  {
    ...BASE,
    id: 'nat-academy',
    slug: 'academy-mortgage',
    name: 'Academy Mortgage',
    nmlsId: '3113',
    type: 'Lender',
    city: 'Draper',
    state: 'Utah',
    stateSlug: 'utah',
    county: 'Salt Lake',
    countySlug: 'salt-lake',
    zipCodes: ['84020'],
    nationalVolumeRank: 21,
    loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Refinance'],
    specialties: ['Retail multi-branch network', 'National multi-state originator', 'Florida HMDA activity'],
    shortDescription:
      'Academy Mortgage Corporation (NMLS #3113) is a national retail mortgage lender headquartered in Draper, Utah, with multi-state branch production including material Florida HMDA originations in 2025.',
    website: 'https://www.academymortgage.com',
  },
  {
    ...BASE,
    id: 'nat-carrington',
    slug: 'carrington-mortgage',
    name: 'Carrington Mortgage Services',
    nmlsId: '2250',
    type: 'Lender',
    city: 'Anaheim',
    state: 'California',
    stateSlug: 'california',
    county: 'Orange',
    countySlug: 'orange',
    zipCodes: ['92806'],
    nationalVolumeRank: 22,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Retail and servicing channels', 'National multi-state originator', 'Florida HMDA activity'],
    shortDescription:
      'Carrington Mortgage Services, LLC (NMLS #2250) is a national mortgage company. Florida HMDA filings include multi-thousand originations under Carrington-related LEIs in 2025.',
    website: 'https://www.carringtonhomeloans.com',
  },
  {
    ...BASE,
    id: 'nat-southstate',
    slug: 'southstate-bank',
    name: 'SouthState Bank',
    nmlsId: '405461',
    type: 'Bank',
    city: 'Winter Haven',
    state: 'Florida',
    stateSlug: 'florida',
    county: 'Polk',
    countySlug: 'polk',
    zipCodes: ['33880'],
    nationalVolumeRank: 23,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Regional bank mortgage', 'Southeast footprint', 'Florida HMDA activity'],
    shortDescription:
      'SouthState Bank, National Association (NMLS #405461) is a Southeast regional bank with substantial Florida mortgage activity reflected in 2025 HMDA data.',
    website: 'https://www.southstatebank.com/personal/loans/mortgage',
  },
  {
    ...BASE,
    id: 'nat-citizens',
    slug: 'citizens-bank',
    name: 'Citizens Bank',
    nmlsId: '433960',
    type: 'Bank',
    city: 'Providence',
    state: 'Rhode Island',
    stateSlug: 'rhode-island',
    county: 'Providence',
    countySlug: 'providence',
    zipCodes: ['02903'],
    nationalVolumeRank: 24,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Bank-direct mortgage', 'National multi-state originator', 'Florida HMDA activity'],
    shortDescription:
      'Citizens Bank, National Association (NMLS #433960) is a national bank offering residential mortgage products. Florida HMDA data reports multi-thousand 2025 originations.',
    website: 'https://www.citizensbank.com/mortgage',
  },
  {
    ...BASE,
    id: 'nat-us-bank',
    slug: 'us-bank',
    name: 'U.S. Bank',
    nmlsId: '402216',
    type: 'Bank',
    city: 'Cincinnati',
    state: 'Ohio',
    stateSlug: 'ohio',
    county: 'Hamilton',
    countySlug: 'hamilton',
    zipCodes: ['45202'],
    nationalVolumeRank: 25,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Bank-direct mortgage', 'National multi-state originator', 'Florida HMDA activity'],
    shortDescription:
      'U.S. Bank National Association (NMLS #402216) is a national bank with a large home mortgage franchise. Florida HMDA filings show multi-thousand originations in 2025.',
    website: 'https://www.usbank.com/home-loans/mortgage.html',
  },
  {
    ...BASE,
    id: 'nat-ameris',
    slug: 'ameris-bank',
    name: 'Ameris Bank',
    nmlsId: '405455',
    type: 'Bank',
    city: 'Atlanta',
    state: 'Georgia',
    stateSlug: 'georgia',
    county: 'Fulton',
    countySlug: 'fulton',
    zipCodes: ['30309'],
    nationalVolumeRank: 26,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Regional bank mortgage', 'Southeast footprint', 'Florida HMDA activity'],
    shortDescription:
      'Ameris Bank (NMLS #405455) is a Southeast regional bank with mortgage lending across its footprint, including Florida production in 2025 HMDA data.',
    website: 'https://www.amerisbank.com/Personal/Borrow/Mortgage',
  },
  {
    ...BASE,
    id: 'nat-amerisave',
    slug: 'amerisave',
    name: 'AmeriSave Mortgage',
    nmlsId: '1168',
    type: 'Lender',
    city: 'Atlanta',
    state: 'Georgia',
    stateSlug: 'georgia',
    county: 'Fulton',
    countySlug: 'fulton',
    zipCodes: ['30328'],
    nationalVolumeRank: 27,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Direct-to-consumer retail', 'National multi-state originator', 'Florida HMDA activity'],
    shortDescription:
      'AmeriSave Mortgage Corporation (NMLS #1168) is a national direct-to-consumer mortgage lender. Florida HMDA data includes multi-thousand originations in 2025.',
    website: 'https://www.amerisave.com',
  },
  {
    ...BASE,
    id: 'nat-first-horizon',
    slug: 'first-horizon-bank',
    name: 'First Horizon Bank',
    nmlsId: '405456',
    type: 'Bank',
    city: 'Memphis',
    state: 'Tennessee',
    stateSlug: 'tennessee',
    county: 'Shelby',
    countySlug: 'shelby',
    zipCodes: ['38103'],
    nationalVolumeRank: 28,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Regional bank mortgage', 'Southeast footprint', 'Florida HMDA activity'],
    shortDescription:
      'First Horizon Bank (NMLS #405456) is a Southeast regional bank with residential mortgage products, including Florida activity in 2025 HMDA filings.',
    website: 'https://www.firsthorizon.com/Personal/Borrow/Mortgage',
  },
  {
    ...BASE,
    id: 'nat-sofi',
    slug: 'sofi-bank',
    name: 'SoFi Bank',
    nmlsId: '1121636',
    type: 'Bank',
    city: 'Cottonwood Heights',
    state: 'Utah',
    stateSlug: 'utah',
    county: 'Salt Lake',
    countySlug: 'salt-lake',
    zipCodes: ['84047'],
    nationalVolumeRank: 29,
    loanTypes: ['Conventional', 'Jumbo', 'Refinance'],
    specialties: ['Digital bank mortgage', 'National multi-state originator', 'Florida HMDA activity'],
    shortDescription:
      'SoFi Bank, National Association (NMLS #1121636) is a national digital bank offering home loans. Florida HMDA data reports multi-thousand originations in 2025.',
    website: 'https://www.sofi.com/mortgage/',
  },
  {
    ...BASE,
    id: 'nat-usaa',
    slug: 'usaa-federal-savings-bank',
    name: 'USAA Federal Savings Bank',
    nmlsId: '399809',
    type: 'Bank',
    city: 'San Antonio',
    state: 'Texas',
    stateSlug: 'texas',
    county: 'Bexar',
    countySlug: 'bexar',
    zipCodes: ['78288'],
    nationalVolumeRank: 30,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Military and veteran focus', 'National multi-state originator', 'Florida HMDA activity'],
    shortDescription:
      'USAA Federal Savings Bank (NMLS #399809) provides banking and mortgage products primarily for military members, veterans, and eligible families. Florida HMDA filings include material 2025 originations.',
    website: 'https://www.usaa.com/inet/wc/bank-home-loans-main',
  },
  {
    ...BASE,
    id: 'nat-flagstar',
    slug: 'flagstar-bank',
    name: 'Flagstar Bank',
    nmlsId: '399797',
    type: 'Bank',
    city: 'Hicksville',
    state: 'New York',
    stateSlug: 'new-york',
    county: 'Nassau',
    countySlug: 'nassau',
    zipCodes: ['11801'],
    nationalVolumeRank: 31,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Bank and wholesale mortgage channels', 'National multi-state originator', 'Florida HMDA activity'],
    shortDescription:
      'Flagstar Bank, National Association (NMLS #399797) is a national bank with significant mortgage origination operations. Florida HMDA data includes multi-hundred to multi-thousand originations in 2025.',
    website: 'https://www.flagstar.com/personal/loans/mortgage-loans.html',
  },
  // ── High-volume Florida credit unions & regionals (HMDA unmatched list) ──
  {
    ...BASE,
    id: 'nat-suncoast-cu',
    slug: 'suncoast-credit-union',
    name: 'Suncoast Credit Union',
    nmlsId: '417636',
    type: 'Credit Union',
    city: 'Tampa',
    state: 'Florida',
    stateSlug: 'florida',
    county: 'Hillsborough',
    countySlug: 'hillsborough',
    zipCodes: ['33610'],
    nationalVolumeRank: 32,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Florida credit union mortgage', 'Member lending', 'Florida HMDA activity'],
    shortDescription:
      'Suncoast Credit Union (NMLS #417636) is one of Florida’s largest credit unions, headquartered in the Tampa Bay area. 2025 HMDA data shows multi-thousand Florida originations.',
    website: 'https://www.suncoastcreditunion.com',
  },
  {
    ...BASE,
    id: 'nat-space-coast-cu',
    slug: 'space-coast-credit-union',
    name: 'Space Coast Credit Union',
    nmlsId: '403370',
    type: 'Credit Union',
    city: 'Melbourne',
    state: 'Florida',
    stateSlug: 'florida',
    county: 'Brevard',
    countySlug: 'brevard',
    zipCodes: ['32940'],
    nationalVolumeRank: 33,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Florida credit union mortgage', 'Member lending', 'Florida HMDA activity'],
    shortDescription:
      'Space Coast Credit Union (NMLS #403370), based in Melbourne, Florida, is a large Florida credit union with multi-thousand mortgage originations in 2025 HMDA filings.',
    website: 'https://www.sccu.com',
  },
  {
    ...BASE,
    id: 'nat-lakeview',
    slug: 'lakeview-loan-servicing',
    name: 'Lakeview Loan Servicing',
    nmlsId: '4095',
    type: 'Lender',
    city: 'Coral Gables',
    state: 'Florida',
    stateSlug: 'florida',
    county: 'Miami-Dade',
    countySlug: 'miami-dade',
    zipCodes: ['33134'],
    nationalVolumeRank: 34,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Origination and servicing', 'National multi-state originator', 'Florida HMDA activity'],
    shortDescription:
      'Lakeview Loan Servicing, LLC (NMLS #4095) is a national mortgage company with Florida-based operations. 2025 HMDA data includes multi-thousand Florida originations.',
    website: 'https://www.lakeviewloanservicing.com',
  },
  {
    ...BASE,
    id: 'nat-homebridge',
    slug: 'homebridge-financial',
    name: 'Homebridge Financial Services',
    nmlsId: '6521',
    type: 'Lender',
    city: 'Iselin',
    state: 'New Jersey',
    stateSlug: 'new-jersey',
    county: 'Middlesex',
    countySlug: 'middlesex',
    zipCodes: ['08830'],
    nationalVolumeRank: 35,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Retail multi-state originator', 'National multi-state originator', 'Florida HMDA activity'],
    shortDescription:
      'Homebridge Financial Services, Inc. (NMLS #6521) is a national mortgage lender with multi-state retail production, including multi-thousand Florida HMDA originations in 2025.',
    website: 'https://www.homebridge.com',
  },
  {
    ...BASE,
    id: 'nat-21st-mortgage',
    slug: '21st-mortgage',
    name: '21st Mortgage',
    nmlsId: '2280',
    type: 'Lender',
    city: 'Knoxville',
    state: 'Tennessee',
    stateSlug: 'tennessee',
    county: 'Knox',
    countySlug: 'knox',
    zipCodes: ['37932'],
    nationalVolumeRank: 36,
    loanTypes: ['Conventional', 'FHA', 'Refinance'],
    specialties: ['Manufactured / specialty housing finance', 'National multi-state originator', 'Florida HMDA activity'],
    shortDescription:
      '21st Mortgage Corporation (NMLS #2280) specializes in manufactured and specialty housing finance nationwide, with multi-thousand Florida originations in 2025 HMDA data.',
    website: 'https://www.21stmortgage.com',
  },
  {
    ...BASE,
    id: 'nat-synovus',
    slug: 'synovus-bank',
    name: 'Synovus Bank',
    nmlsId: '480004',
    type: 'Bank',
    city: 'Columbus',
    state: 'Georgia',
    stateSlug: 'georgia',
    county: 'Muscogee',
    countySlug: 'muscogee',
    zipCodes: ['31901'],
    nationalVolumeRank: 37,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: [
      'Southeast regional bank',
      'Georgia HMDA activity',
      'National multi-state originator',
    ],
    shortDescription:
      'Synovus Bank (NMLS #480004) is a Southeast regional bank headquartered in Columbus, Georgia. Public HMDA filings include multi-thousand Georgia originations among major metro and secondary markets.',
    website: 'https://www.synovus.com',
  },
  {
    ...BASE,
    id: 'nat-planet-home',
    slug: 'planet-home-lending',
    name: 'Planet Home Lending',
    nmlsId: '17022',
    type: 'Lender',
    city: 'Meriden',
    state: 'Connecticut',
    stateSlug: 'connecticut',
    county: 'New Haven',
    countySlug: 'new-haven',
    zipCodes: ['06450'],
    nationalVolumeRank: 38,
    loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Refinance'],
    specialties: ['Retail multi-state originator', 'Georgia HMDA activity'],
    shortDescription:
      'Planet Home Lending, LLC (NMLS #17022) is a multi-state mortgage company with meaningful Georgia originations in 2025 public HMDA data.',
    website: 'https://www.planethomelending.com',
  },
  {
    ...BASE,
    id: 'nat-mutual-omaha',
    slug: 'mutual-of-omaha-mortgage',
    name: 'Mutual of Omaha Mortgage',
    nmlsId: '1025894',
    type: 'Lender',
    city: 'San Diego',
    state: 'California',
    stateSlug: 'california',
    county: 'San Diego',
    countySlug: 'san-diego',
    zipCodes: ['92121'],
    nationalVolumeRank: 39,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Retail multi-state originator', 'Georgia HMDA activity'],
    shortDescription:
      'Mutual of Omaha Mortgage, Inc. (NMLS #1025894) originates residential mortgages in multiple states; Georgia HMDA filings show multi-hundred to thousand-scale originations.',
    website: 'https://www.mutualmortgage.com',
  },
  {
    ...BASE,
    id: 'nat-zillow-home-loans',
    slug: 'zillow-home-loans',
    name: 'Zillow Home Loans',
    nmlsId: '1027871',
    type: 'Lender',
    city: 'Seattle',
    state: 'Washington',
    stateSlug: 'washington',
    county: 'King',
    countySlug: 'king',
    zipCodes: ['98101'],
    nationalVolumeRank: 40,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Direct-to-consumer digital origination', 'Georgia HMDA activity'],
    shortDescription:
      'Zillow Home Loans, LLC (NMLS #1027871) is a multi-state retail mortgage lender affiliated with the Zillow brand. Georgia HMDA data includes substantial statewide originations.',
    website: 'https://www.zillow.com/homeloans',
  },
  {
    ...BASE,
    id: 'nat-sun-west',
    slug: 'sun-west-mortgage',
    name: 'Sun West Mortgage',
    nmlsId: '3277',
    type: 'Lender',
    city: 'Cerritos',
    state: 'California',
    stateSlug: 'california',
    county: 'Los Angeles',
    countySlug: 'los-angeles',
    zipCodes: ['90703'],
    nationalVolumeRank: 41,
    loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Refinance'],
    specialties: ['Multi-state mortgage banker', 'California HMDA activity'],
    shortDescription:
      'Sun West Mortgage Company, Inc. (NMLS #3277) is a multi-state mortgage company headquartered in Cerritos, California. Public HMDA filings include multi-thousand California originations.',
    website: 'https://www.swmc.com',
  },
  {
    ...BASE,
    id: 'nat-afn',
    slug: 'american-financial-network',
    name: 'American Financial Network',
    nmlsId: '237341',
    type: 'Lender',
    city: 'Brea',
    state: 'California',
    stateSlug: 'california',
    county: 'Orange',
    countySlug: 'orange',
    zipCodes: ['92821'],
    nationalVolumeRank: 42,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Multi-state mortgage banker', 'California HMDA activity'],
    shortDescription:
      'American Financial Network, Inc. (NMLS #237341) is a multi-state mortgage banker based in Brea, California, with substantial California HMDA originations in public 2025 data.',
    website: 'https://www.afncorp.com',
  },
  {
    ...BASE,
    id: 'nat-kind-lending',
    slug: 'kind-lending',
    name: 'Kind Lending',
    nmlsId: '3925',
    type: 'Lender',
    city: 'Irvine',
    state: 'California',
    stateSlug: 'california',
    county: 'Orange',
    countySlug: 'orange',
    zipCodes: ['92614'],
    nationalVolumeRank: 43,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Multi-state retail mortgage', 'California HMDA activity'],
    shortDescription:
      'Kind Lending, LLC (NMLS #3925) is a multi-state mortgage lender headquartered in Irvine, California. California HMDA data reports multi-thousand originations.',
    website: 'https://www.kindlending.com',
  },
  {
    ...BASE,
    id: 'nat-amwest',
    slug: 'amwest-funding',
    name: 'AmWest Funding',
    nmlsId: '167441',
    type: 'Lender',
    city: 'Brea',
    state: 'California',
    stateSlug: 'california',
    county: 'Orange',
    countySlug: 'orange',
    zipCodes: ['92821'],
    nationalVolumeRank: 44,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Multi-state mortgage banker', 'California HMDA activity'],
    shortDescription:
      'AmWest Funding Corp. (NMLS #167441) is a multi-state mortgage company based in Brea, California, with multi-thousand California originations in 2025 public HMDA data.',
    website: 'https://amwestfunding.com',
  },
  // ── South Carolina deepen — high-confidence HMDA LEI maps ─────────────────
  {
    ...BASE,
    id: 'nat-first-citizens',
    slug: 'first-citizens-bank',
    name: 'First Citizens Bank',
    nmlsId: '503941',
    type: 'Bank',
    city: 'Raleigh',
    state: 'North Carolina',
    stateSlug: 'north-carolina',
    county: 'Wake',
    countySlug: 'wake',
    zipCodes: ['27603'],
    nationalVolumeRank: 45,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Southeast regional bank', 'South Carolina HMDA activity'],
    shortDescription:
      'First-Citizens Bank & Trust Company (NMLS #503941) is a multi-state bank with deep Southeast mortgage activity, including multi-thousand South Carolina originations in public HMDA data.',
    website: 'https://www.firstcitizens.com/personal/mortgages',
  },
  {
    ...BASE,
    id: 'nat-lower',
    slug: 'lower',
    name: 'Lower',
    nmlsId: '1124061',
    type: 'Lender',
    city: 'Fort Mill',
    state: 'South Carolina',
    stateSlug: 'south-carolina',
    county: 'York',
    countySlug: 'york',
    zipCodes: ['29707'],
    nationalVolumeRank: 46,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Direct-to-consumer digital mortgage', 'South Carolina HQ'],
    shortDescription:
      'Lower, LLC (NMLS #1124061) is a multi-state retail mortgage lender headquartered in Fort Mill, South Carolina, with substantial South Carolina HMDA originations.',
    website: 'https://www.lower.com',
  },
  {
    ...BASE,
    id: 'nat-nvr-mortgage',
    slug: 'nvr-mortgage',
    name: 'NVR Mortgage',
    nmlsId: '1127',
    type: 'Lender',
    city: 'Pittsburgh',
    state: 'Pennsylvania',
    stateSlug: 'pennsylvania',
    county: 'Allegheny',
    countySlug: 'allegheny',
    zipCodes: ['15276'],
    nationalVolumeRank: 47,
    loanTypes: ['Conventional', 'FHA', 'VA', 'USDA', 'Refinance'],
    specialties: ['Builder-affiliated new construction', 'South Carolina HMDA activity'],
    shortDescription:
      'NVR Mortgage Finance, Inc. (NMLS #1127) finances purchases of NVR-affiliated new homes (including Ryan Homes) and reports multi-thousand South Carolina HMDA originations.',
    website: 'https://www.nvrmortgage.com',
  },
  {
    ...BASE,
    id: 'nat-first-heritage',
    slug: 'first-heritage-mortgage',
    name: 'First Heritage Mortgage',
    nmlsId: '86548',
    type: 'Lender',
    city: 'Fairfax',
    state: 'Virginia',
    stateSlug: 'virginia',
    county: 'Fairfax',
    countySlug: 'fairfax',
    zipCodes: ['22030'],
    nationalVolumeRank: 48,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Multi-state retail mortgage', 'South Carolina HMDA activity'],
    shortDescription:
      'First Heritage Mortgage, LLC (NMLS #86548) is a multi-state mortgage lender with material South Carolina HMDA originations in public filings.',
    website: 'https://fhmtg.com',
  },
  {
    ...BASE,
    id: 'nat-new-day',
    slug: 'new-day-financial',
    name: 'New Day Financial',
    nmlsId: '1043',
    type: 'Lender',
    city: 'West Palm Beach',
    state: 'Florida',
    stateSlug: 'florida',
    county: 'Palm Beach',
    countySlug: 'palm-beach',
    zipCodes: ['33401'],
    nationalVolumeRank: 49,
    loanTypes: ['VA', 'Refinance'],
    specialties: ['VA-focused retail mortgage', 'South Carolina HMDA activity'],
    shortDescription:
      'New Day Financial, LLC (NewDay USA, NMLS #1043) specializes in VA mortgage products and appears in multi-state HMDA filings including South Carolina.',
    website: 'https://www.newdayusa.com',
  },
  {
    ...BASE,
    id: 'nat-united-community',
    slug: 'united-community-bank',
    name: 'United Community Bank',
    nmlsId: '421841',
    type: 'Bank',
    city: 'Greenville',
    state: 'South Carolina',
    stateSlug: 'south-carolina',
    county: 'Greenville',
    countySlug: 'greenville',
    zipCodes: ['29601'],
    nationalVolumeRank: 50,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Southeast community bank', 'South Carolina HMDA activity'],
    shortDescription:
      'United Community Bank (NMLS #421841) is a Southeast regional bank with material South Carolina mortgage originations in public HMDA data.',
    website: 'https://www.ucbi.com/mortgages',
  },
  {
    ...BASE,
    id: 'nat-southern-first',
    slug: 'southern-first-bank',
    name: 'Southern First Bank',
    nmlsId: '754127',
    type: 'Bank',
    city: 'Greenville',
    state: 'South Carolina',
    stateSlug: 'south-carolina',
    county: 'Greenville',
    countySlug: 'greenville',
    zipCodes: ['29601'],
    nationalVolumeRank: 51,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Carolinas community bank', 'South Carolina HMDA activity'],
    shortDescription:
      'Southern First Bank (NMLS #754127) is a Carolinas community bank with multi-hundred South Carolina HMDA originations in public filings.',
    website: 'https://www.southernfirst.com/personal/mortgages',
  },
  {
    ...BASE,
    id: 'nat-gra',
    slug: 'guaranteed-rate-affinity',
    name: 'Guaranteed Rate Affinity',
    nmlsId: '1598647',
    type: 'Lender',
    city: 'Chicago',
    state: 'Illinois',
    stateSlug: 'illinois',
    county: 'Cook',
    countySlug: 'cook',
    zipCodes: ['60613'],
    nationalVolumeRank: 52,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Multi-state retail mortgage', 'South Carolina HMDA activity'],
    shortDescription:
      'Guaranteed Rate Affinity, LLC (NMLS #1598647) is a multi-state mortgage lender with South Carolina HMDA originations in public data (distinct entity from Guaranteed Rate, Inc.).',
    website: 'https://www.grarate.com',
  },
  // ── New Jersey deepen — high-confidence HMDA LEI maps ─────────────────────
  {
    ...BASE,
    id: 'nat-anniemac',
    slug: 'anniemac-home-mortgage',
    name: 'AnnieMac Home Mortgage',
    nmlsId: '338923',
    type: 'Lender',
    city: 'Mount Laurel',
    state: 'New Jersey',
    stateSlug: 'new-jersey',
    county: 'Burlington',
    countySlug: 'burlington',
    zipCodes: ['08054'],
    nationalVolumeRank: 53,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['New Jersey HQ lender', 'Multi-state retail mortgage'],
    shortDescription:
      'American Neighborhood Mortgage Acceptance Company LLC, dba AnnieMac Home Mortgage (NMLS #338923), is headquartered in Mount Laurel, New Jersey, with multi-thousand New Jersey HMDA originations.',
    website: 'https://annie-mac.com',
  },
  {
    ...BASE,
    id: 'nat-oceanfirst',
    slug: 'oceanfirst-bank',
    name: 'OceanFirst Bank',
    nmlsId: '409701',
    type: 'Bank',
    city: 'Toms River',
    state: 'New Jersey',
    stateSlug: 'new-jersey',
    county: 'Ocean',
    countySlug: 'ocean',
    zipCodes: ['08753'],
    nationalVolumeRank: 54,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['New Jersey community bank', 'Shore markets'],
    shortDescription:
      'OceanFirst Bank, National Association (NMLS #409701) is a New Jersey community bank with material statewide HMDA originations in public filings.',
    website: 'https://oceanfirst.com',
  },
  {
    ...BASE,
    id: 'nat-valley-national',
    slug: 'valley-national-bank',
    name: 'Valley National Bank',
    nmlsId: '411254',
    type: 'Bank',
    city: 'Wayne',
    state: 'New Jersey',
    stateSlug: 'new-jersey',
    county: 'Passaic',
    countySlug: 'passaic',
    zipCodes: ['07470'],
    nationalVolumeRank: 55,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['New Jersey regional bank', 'Northeast footprint'],
    shortDescription:
      'Valley National Bank (NMLS #411254) is a multi-state regional bank with substantial New Jersey mortgage originations in public HMDA data.',
    website: 'https://www.valley.com',
  },
  {
    ...BASE,
    id: 'nat-mt-bank',
    slug: 'mt-bank',
    name: 'M&T Bank',
    nmlsId: '381076',
    type: 'Bank',
    city: 'Buffalo',
    state: 'New York',
    stateSlug: 'new-york',
    county: 'Erie',
    countySlug: 'erie',
    zipCodes: ['14203'],
    nationalVolumeRank: 56,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Northeast regional bank', 'New Jersey HMDA activity'],
    shortDescription:
      'Manufacturers and Traders Trust Company (M&T Bank, NMLS #381076) is a multi-state bank with multi-thousand New Jersey HMDA originations in public data.',
    website: 'https://www.mtb.com/personal/mortgages-and-loans/mortgages',
  },
  {
    ...BASE,
    id: 'nat-embrace',
    slug: 'embrace-home-loans',
    name: 'Embrace Home Loans',
    nmlsId: '2184',
    type: 'Lender',
    city: 'Middletown',
    state: 'Rhode Island',
    stateSlug: 'rhode-island',
    county: 'Newport',
    countySlug: 'newport',
    zipCodes: ['02842'],
    nationalVolumeRank: 57,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Multi-state retail mortgage', 'New Jersey HMDA activity'],
    shortDescription:
      'Embrace Home Loans, Inc. (NMLS #2184) is a multi-state mortgage lender with material New Jersey HMDA originations (and an OceanFirst referral partnership in NJ markets).',
    website: 'https://www.embracehomeloans.com',
  },
  {
    ...BASE,
    id: 'nat-nfm',
    slug: 'nfm-lending',
    name: 'NFM Lending',
    nmlsId: '2893',
    type: 'Lender',
    city: 'Linthicum Heights',
    state: 'Maryland',
    stateSlug: 'maryland',
    county: 'Anne Arundel',
    countySlug: 'anne-arundel',
    zipCodes: ['21090'],
    nationalVolumeRank: 58,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Multi-state retail mortgage', 'New Jersey HMDA activity'],
    shortDescription:
      'NFM, Inc., dba NFM Lending (NMLS #2893), is a multi-state residential mortgage lender with multi-thousand New Jersey originations in public HMDA filings.',
    website: 'https://nfmlending.com',
  },
  {
    ...BASE,
    id: 'nat-citibank',
    slug: 'citibank',
    name: 'Citibank',
    nmlsId: '412915',
    type: 'Bank',
    city: 'New York',
    state: 'New York',
    stateSlug: 'new-york',
    county: 'New York',
    countySlug: 'new-york',
    zipCodes: ['10013'],
    nationalVolumeRank: 59,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['National bank mortgage', 'New Jersey HMDA activity'],
    shortDescription:
      'Citibank, National Association (NMLS #412915) is a national bank with residential mortgage originations including multi-hundred New Jersey HMDA volume in public data.',
    website: 'https://www.citi.com/mortgage',
  },
  {
    ...BASE,
    id: 'nat-advisors-mtg',
    slug: 'advisors-mortgage-group',
    name: 'Advisors Mortgage Group',
    nmlsId: '33041',
    type: 'Lender',
    city: 'Ocean',
    state: 'New Jersey',
    stateSlug: 'new-jersey',
    county: 'Monmouth',
    countySlug: 'monmouth',
    zipCodes: ['07712'],
    nationalVolumeRank: 60,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['New Jersey HQ lender', 'Multi-state mortgage banker'],
    shortDescription:
      'Advisors Mortgage Group, L.L.C. (NMLS #33041) is a multi-state mortgage banker headquartered in Ocean, New Jersey, with multi-thousand New Jersey HMDA originations.',
    website: 'https://advisorsmortgage.com',
  },
  {
    ...BASE,
    id: 'nat-absolute-home',
    slug: 'absolute-home-mortgage',
    name: 'Absolute Home Mortgage',
    nmlsId: '176743',
    type: 'Lender',
    city: 'Fairfield',
    state: 'New Jersey',
    stateSlug: 'new-jersey',
    county: 'Essex',
    countySlug: 'essex',
    zipCodes: ['07004'],
    nationalVolumeRank: 61,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['New Jersey HQ lender', 'Multi-state mortgage banker'],
    shortDescription:
      'Absolute Home Mortgage Corporation (NMLS #176743) is headquartered in Fairfield, New Jersey, with multi-thousand New Jersey HMDA originations in public filings.',
    website: 'https://ahmcloans.com',
  },
  {
    ...BASE,
    id: 'nat-prosperity-hm',
    slug: 'prosperity-home-mortgage',
    name: 'Prosperity Home Mortgage',
    nmlsId: '75164',
    type: 'Lender',
    city: 'Fairfax',
    state: 'Virginia',
    stateSlug: 'virginia',
    county: 'Fairfax',
    countySlug: 'fairfax',
    zipCodes: ['22031'],
    nationalVolumeRank: 62,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Multi-state retail mortgage', 'New Jersey HMDA activity'],
    shortDescription:
      'Prosperity Home Mortgage, LLC (NMLS #75164) is a multi-state mortgage banker with multi-thousand New Jersey HMDA originations in public data.',
    website: 'https://www.phmloans.com',
  },
  {
    ...BASE,
    id: 'nat-columbia-bank-nj',
    slug: 'columbia-bank-nj',
    name: 'Columbia Bank',
    nmlsId: '504284',
    type: 'Bank',
    city: 'Fair Lawn',
    state: 'New Jersey',
    stateSlug: 'new-jersey',
    county: 'Bergen',
    countySlug: 'bergen',
    zipCodes: ['07410'],
    nationalVolumeRank: 63,
    loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['New Jersey community bank', 'North Jersey markets'],
    shortDescription:
      'Columbia Bank (NMLS #504284) is a New Jersey community bank with multi-hundred statewide HMDA originations in public filings.',
    website: 'https://www.columbiabankonline.com',
  },
];
