import type { Lender } from '@/lib/mockData';

export const WASHINGTON_LENDERS: Lender[] = [
  // ── Snohomish County Transit Corridor (Lynnwood & Everett) ───────────────────
  {
    id: 'wa-01', slug: 'summit-mortgage-snohomish', name: 'Summit Mortgage (Snohomish)', nmlsId: '2561', type: 'Broker',
    city: 'Lynnwood', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98036', '98037', '98201'], rating: 4.9, reviewCount: 890, trustScore: 95, countyExperienceScore: 96,
    nationalVolumeRank: 32, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Light Rail Commuter Financing', 'Aerospace Buyers', 'Transit-Driven Demand'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 2, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Pacific Northwest independent broker — deep expertise in light rail commuter and Boeing-area financing across Snohomish County.',
    website: 'https://summitmortgage.com', phone: '(425) 555-9701',
  },
  {
    id: 'wa-02', slug: 'guild-mortgage-snohomish', name: 'Guild Mortgage (Snohomish)', nmlsId: '3274', type: 'Lender',
    city: 'Lynnwood', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98036', '98201', '98203'], rating: 4.8, reviewCount: 485, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 20, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Full Residential Spectrum', 'Commuter & Aerospace Expertise', 'North Corridor Branches'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 5, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 94,
    shortDescription: 'National Guild lender with Lynnwood and Everett branches — comprehensive financing for light rail commuters and aerospace professionals.',
    website: 'https://guildmortgage.com', phone: '(425) 555-9702',
  },
  {
    id: 'wa-03', slug: 'new-american-funding-snohomish', name: 'New American Funding (Snohomish)', nmlsId: '6606', type: 'Lender',
    city: 'Lynnwood', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98037', '98201', '98208'], rating: 4.9, reviewCount: 420, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 24, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['High-Volume Purchase/Refinance', 'Commuter Buyers', 'Boeing-Area Transactions'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 4, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 26, onTimeCloseRate: 95,
    shortDescription: 'NAF Lynnwood team — excellent ratings for commuter and Boeing-area buyers in the north Sound corridor.',
    website: 'https://newamericanfunding.com', phone: '(425) 555-9703',
  },
  {
    id: 'wa-04', slug: 'crosscountry-mortgage-snohomish', name: 'CrossCountry Mortgage (Snohomish)', nmlsId: '3029', type: 'Lender',
    city: 'Everett', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98201', '98203', '98036'], rating: 4.8, reviewCount: 365, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 22, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Tech & Aerospace Professionals', 'Light Rail Corridor', 'Broad Product Menu'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 6, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 28, onTimeCloseRate: 93,
    shortDescription: 'CrossCountry Everett-Lynnwood teams — experienced support for light rail proximity demand and Boeing job corridor buyers.',
    website: 'https://crosscountrymortgage.com', phone: '(425) 555-9704',
  },
  {
    id: 'wa-05', slug: 'pierpoint-mortgage-north-sound', name: 'PierPoint Mortgage (North Sound)', nmlsId: '112844', type: 'Broker',
    city: 'Lynnwood', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98036', '98201', '98208'], rating: 4.9, reviewCount: 195, trustScore: 93, countyExperienceScore: 94,
    nationalVolumeRank: 58, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['First-Time Buyers', 'Fast Closings', 'Transit-Station Proximity'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 22, onTimeCloseRate: 97,
    shortDescription: 'Wholesale broker — speed suited to Lynnwood and Everett transit-station proximity demand and rapid absorption.',
    website: 'https://pierpointmortgage.com', phone: '(425) 555-9705',
  },
  {
    id: 'wa-06', slug: 'silverton-mortgage-snohomish', name: 'Silverton Mortgage — Snohomish', nmlsId: '1561', type: 'Lender',
    city: 'Everett', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98201', '98203', '98037'], rating: 4.8, reviewCount: 155, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 52, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Retail Lending', 'Water Views & Single-Family', 'Snohomish Expertise'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 0, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 27, onTimeCloseRate: 95,
    shortDescription: 'Silverton Everett retail lending — professional service for water views and single-family options below Seattle medians.',
    website: 'https://silvertonmortgage.com', phone: '(425) 555-9706',
  },
  {
    id: 'wa-07', slug: 'veterans-united-snohomish', name: 'Veterans United (Snohomish)', nmlsId: '1907', type: 'Lender',
    city: 'Everett', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98201', '98208', '98036'], rating: 4.9, reviewCount: 720, trustScore: 92, countyExperienceScore: 93,
    nationalVolumeRank: 8, loanTypes: ['VA', 'FHA', 'Refinance'],
    specialties: ['VA Loans', 'Boeing Relocation Programs', 'Aerospace Job Market'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 15, bbbRating: 'A',
    googleRating: 4.9, trustpilotRating: 4.7, avgCloseDays: 30, onTimeCloseRate: 94,
    shortDescription: 'VA and Boeing-related relocation programs — tailored for Everett\'s robust aerospace job market and defense-adjacent buyers.',
    website: 'https://veteransunited.com', phone: '(425) 555-9707',
  },
  {
    id: 'wa-08', slug: 'becu-snohomish', name: 'BECU (Boeing Employees Credit Union)', nmlsId: '409610', type: 'Credit Union',
    city: 'Lynnwood', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98036', '98201', '98203'], rating: 4.9, reviewCount: 1120, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 55, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Member Rates', 'Commuter Financing', 'Aerospace Community CU'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 28, onTimeCloseRate: 95,
    shortDescription: 'Washington credit union — community-focused member rates for commuters and aerospace professionals near light rail stations.',
    website: 'https://becu.org', phone: '(800) 233-2328',
  },
  {
    id: 'wa-09', slug: 'lennar-mortgage-snohomish', name: 'Lennar Mortgage (Snohomish)', nmlsId: '1058', type: 'Lender',
    city: 'Lynnwood', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98037', '98208', '98036'], rating: 4.7, reviewCount: 380, trustScore: 90, countyExperienceScore: 92,
    nationalVolumeRank: 35, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Transit-Oriented Development', 'Station-Area Housing', 'New Construction'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 8, bbbRating: 'A',
    googleRating: 4.7, trustpilotRating: 4.5, avgCloseDays: 30, onTimeCloseRate: 92,
    shortDescription: 'Builder-affiliated lender — expertise in Lynnwood transit-adjacent new construction with rapidly absorbing station-area demand.',
    website: 'https://lennar.com/mortgage', phone: '(425) 555-9709',
  },
  {
    id: 'wa-10', slug: 'anchor-home-mortgage-snohomish', name: 'Anchor Home Mortgage (Snohomish)', nmlsId: '136890', type: 'Broker',
    city: 'Everett', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98201', '98036', '98203'], rating: 4.9, reviewCount: 245, trustScore: 94, countyExperienceScore: 95,
    nationalVolumeRank: 48, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['North Corridor Buyers', 'Single-Family Below Seattle', 'Personalized Brokerage'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 1, bbbRating: 'A+',
    googleRating: 4.9, trustpilotRating: 4.8, avgCloseDays: 23, onTimeCloseRate: 96,
    shortDescription: 'Independent broker — strong focus on single-family options below Seattle medians in the Lynnwood-Everett north corridor.',
    website: 'https://anchorhomemortgage.com', phone: '(425) 555-9710',
  },
  {
    id: 'wa-11', slug: 'bank-of-america-mortgage-snohomish', name: 'Bank of America Mortgage (Snohomish)', nmlsId: '399802', type: 'Bank',
    city: 'Lynnwood', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98036', '98201', '98208'], rating: 4.6, reviewCount: 620, trustScore: 88, countyExperienceScore: 90,
    nationalVolumeRank: 5, loanTypes: ['Conventional', 'FHA', 'VA', 'Jumbo', 'Refinance'],
    specialties: ['Tech/Aerospace Relocation', 'Full-Service Banking', 'Commuter Financing'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 18, bbbRating: 'A',
    googleRating: 4.6, trustpilotRating: 4.4, avgCloseDays: 32, onTimeCloseRate: 90,
    shortDescription: 'Full-service bank mortgages convenient for tech and aerospace commuters relocating to Lynnwood and Everett.',
    website: 'https://bankofamerica.com/mortgage', phone: '(425) 555-9711',
  },
  {
    id: 'wa-12', slug: 'nova-home-loans-snohomish', name: 'Nova Home Loans (Snohomish)', nmlsId: '3089', type: 'Lender',
    city: 'Everett', state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish',
    zipCodes: ['98201', '98203', '98037'], rating: 4.8, reviewCount: 310, trustScore: 91, countyExperienceScore: 92,
    nationalVolumeRank: 42, loanTypes: ['Conventional', 'FHA', 'VA', 'Refinance'],
    specialties: ['Investor Financing', 'Family Transit Corridor', 'Light Rail Effect'],
    creditTiers: ['Excellent', 'Good', 'Fair'], nmlsVerified: true, cfpbComplaints: 3, bbbRating: 'A',
    googleRating: 4.8, trustpilotRating: 4.7, avgCloseDays: 25, onTimeCloseRate: 94,
    shortDescription: 'Washington lender — localized knowledge of Snohomish light rail effect and steady north corridor family demand.',
    website: 'https://novahomeloans.com', phone: '(425) 555-9712',
  },
];

export const SNOHOMISH_TRANSIT_CORRIDOR_LENDER_SLUGS = [
  'summit-mortgage-snohomish',
  'guild-mortgage-snohomish',
  'new-american-funding-snohomish',
  'crosscountry-mortgage-snohomish',
  'pierpoint-mortgage-north-sound',
  'silverton-mortgage-snohomish',
  'veterans-united-snohomish',
  'becu-snohomish',
  'lennar-mortgage-snohomish',
  'anchor-home-mortgage-snohomish',
  'bank-of-america-mortgage-snohomish',
  'nova-home-loans-snohomish',
] as const;

export const WASHINGTON_COUNTY_SUPPLEMENTS: Record<string, string[]> = {
  snohomish: [],
};

export const SNOHOMISH_TRANSIT_CORRIDOR_HUB_COUNTIES = [
  { name: 'Snohomish', slug: 'snohomish', highlight: 'Lynnwood & Everett light rail commuter corridor' },
] as const;

export const SNOHOMISH_TRANSIT_CORRIDOR_HUB_AREAS = [
  { name: 'Lynnwood', slug: 'snohomish', highlight: 'Link light rail stations, transit-oriented absorption' },
  { name: 'Everett', slug: 'snohomish', highlight: 'Boeing aerospace hub, water views & single-family' },
  { name: 'Mountlake Terrace', slug: 'snohomish', highlight: 'Light rail effect, below-Seattle pricing' },
  { name: 'Mukilteo', slug: 'snohomish', highlight: 'Ferry corridor, steady commuter demand' },
] as const;