import { readFileSync } from 'node:fs';
import { executeSpecialistV2 } from '../lib/specialist-execution/v2';
import { SPECIALIST_CONTRACT_FINGERPRINT, SPECIALIST_SCHEMA_FINGERPRINT } from '../lib/specialist-execution/contract';

const checks: Array<[string, boolean, string]> = [];
const check = (id: string, pass: boolean, detail = '') => checks.push([id, pass, detail]);
const body = (q: string) => executeSpecialistV2(q).body;

const broward = body('FHA lenders in Broward County');
const palm = body('mortgage lenders reporting originations in Palm Beach County');
const texas = body('mortgage originations in Texas');
const appsFl = body('mortgage applications in Florida');
const denial = body('mortgage denials in Broward County');
const page2 = executeSpecialistV2({ query: 'FHA lenders in Broward County', page: 2, limit: 25 }).body;
const deep = executeSpecialistV2({ query: 'FHA lenders in Broward County', page: 999, limit: 500 }).body;

check('1-contract', broward.contract === 'trusthub-specialist-execution-v2');
check('2-version', broward.contractVersion === '2.1.0');
check('3-schema-fp', broward.schemaFingerprint === SPECIALIST_SCHEMA_FINGERPRINT && SPECIALIST_SCHEMA_FINGERPRINT.length === 64);
check('4-contract-fp', broward.contractFingerprint === SPECIALIST_CONTRACT_FINGERPRINT && SPECIALIST_CONTRACT_FINGERPRINT.length === 64);
check('5-institution-branch', body('lender branches in Texas').resultState !== 'SUPPORTED_RESULTS');
check('6-institution-mlo', body('loan officers in Florida').resultState === 'PUBLICATION_RESTRICTED');
check('7-lei-grain', String(broward.queryInterpretation.rowGrain).includes('LEI'));
check('8-nmls-not-inferred', broward.rows.every((r: { nmls: string | null }) => r.nmls === null || /^\d+$/.test(r.nmls)));
check('9-app-not-orig', appsFl.rows.every((r: { action: string }) => r.action === 'application'));
check('10-orig-not-denial', denial.rows.every((r: { action: string }) => r.action === 'denial'));
check('11-fha-broward', broward.resultState === 'SUPPORTED_RESULTS' && broward.total === 214, String(broward.total));
check('12-fips', broward.appliedFilters.geography.countyFips === '12011');
check('13-no-geo-leak', broward.rows.every((r: { propertyGeography: { countyFips: string } }) => r.propertyGeography.countyFips === '12011'));
check('14-palm', palm.resultState === 'SUPPORTED_RESULTS' && palm.appliedFilters.geography.countyFips === '12099');
check('15-state', texas.resultState === 'SUPPORTED_RESULTS' && texas.appliedFilters.geography.stateCode === 'TX');
check('16-loan-type', broward.rows.every((r: { loanType: string }) => r.loanType === 'FHA'));
check('17-action', palm.rows.every((r: { action: string }) => r.action === 'origination'));
check('18-total', broward.total >= broward.rows.length);
check('19-period', String(broward.provenance.reportingPeriod).includes('2025'));
check('20-property-market', broward.queryInterpretation.geographyIntent === 'PROPERTY_MARKET');
check('21-not-hq', body('lenders headquartered in Texas').resultState === 'UNSUPPORTED_CAPABILITY');
check('22-not-branch', body('lender branches in Texas').resultState === 'PUBLICATION_RESTRICTED');
check('23-not-territory', body('lenders serving Florida').resultState === 'UNSUPPORTED_CAPABILITY');
check('24-texas-clarify', body('lenders in Texas').resultState === 'CLARIFICATION_REQUIRED');
check('25-hq-unsupported', body('lenders headquartered in Texas').resultState === 'UNSUPPORTED_CAPABILITY');
check('26-branch-restricted', body('lender branches in Texas').resultState === 'PUBLICATION_RESTRICTED');
check('27-service-unsupported', body('mortgage companies available in Florida').resultState === 'UNSUPPORTED_CAPABILITY');
check('28-volume-not-rec', !/recommended|best lender/i.test(JSON.stringify(broward.rows)));
check('29-denial-reason', denial.limitations.some((x: string) => /not denial reasons/i.test(x)));
check('30-denial-finding', denial.limitations.some((x: string) => /not a discrimination finding/i.test(x)));
check('31-rate', body('mortgage denial rate in Broward County').resultState === 'UNSUPPORTED_CAPABILITY');
check('32-purpose', body('purchase originations in Florida').resultState === 'UNSUPPORTED_CAPABILITY');
check('33-grains', !String(broward.provenance.queryGrain).includes('state + county'));
check('34-null-destination', broward.rows.some((r: { destination: unknown }) => r.destination === null));
check('35-null-preserved', broward.rows.filter((r: { destination: unknown }) => r.destination === null).length > 0);
check('36-profile-gate', broward.rows.filter((r: { destination: { type: string } | null }) => r.destination).every((r: { destination: { type: string } }) => r.destination.type === 'PUBLIC_LENDER_PROFILE'));
check('37-no-profile-mint', broward.diagnostics.dbWrites === 0);
check('38-no-branch-route', !JSON.stringify(broward).includes('/branches/'));
check('39-no-mlo-route', !JSON.stringify(broward).includes('/mlo/'));
check('40-hold', broward.rows.filter((r: { identityStatus: string }) => r.identityStatus === 'identity_hold').every((r: { destination: unknown }) => r.destination === null));
check('41-nmls-no-cohort', body('NMLS 170008').resultState === 'UNSUPPORTED_CAPABILITY');
check('42-lei-no-cohort', body('LEI 549300FGXN1K3HLB1R50').resultState === 'UNSUPPORTED_CAPABILITY');
check('43-identifier-truth', body('NMLS 170008').limitations.some((x: string) => x.includes('LEND-CAP-002')));
check('44-rocket', body('complaints about Rocket Mortgage').resultState === 'UNSUPPORTED_CAPABILITY');
check('45-rocket-next', body('complaints about Rocket Mortgage').limitations.some((x: string) => x.includes('LEND-CAP-002')));
check('46-supported-zero', executeSpecialistV2({ queryType: 'market_cohort', entityClass: 'hmda_reporting_institution', geography: { intent: 'PROPERTY_MARKET', stateCode: 'AK' }, action: 'origination', loanType: 'other', page: 1, limit: 25 }).body.resultState !== 'UNSUPPORTED_CAPABILITY');
check('47-zero-not-unsupported', deep.resultState !== 'UNSUPPORTED_CAPABILITY');
check('48-unsupported-not-backend', body('NMLS 170008').resultState !== 'BACKEND_UNAVAILABLE');
check('49-clarify-not-invalid', body('lenders in Texas').resultState !== 'INVALID_QUERY');
check('50-states-distinct', ['TIMEOUT', 'NO_CONFIDENT_MATCH'].every((x) => x !== body('NMLS 170008').resultState));
check('51-page', page2.pagination.page === 2);
check('52-no-overlap', !new Set(broward.rows.map((r: { lei: string }) => r.lei)).has(page2.rows[0]?.lei));
check('53-out-range', deep.pagination.outOfRangeNormalized === true);
check('54-limit', deep.pagination.limit <= 50);
check('55-reset', executeSpecialistV2({ query: 'mortgage originations in Texas', page: 1 }).body.pagination.page === 1);
check('56-ordering', /raw reported HMDA activity/i.test(broward.diagnostics.orderingMeaning));
check('57-no-quality-rank', !/quality rank/i.test(JSON.stringify(broward)));
check('58-no-paid', !/paid ordering/i.test(JSON.stringify(broward)));
check('59-no-internal-id', !JSON.stringify(broward.rows).includes('institutionId'));
check('60-no-private', !/email|phone/i.test(JSON.stringify(broward.rows)));
check('61-no-person', !JSON.stringify(broward.rows).includes('person_public_candidate'));
check('62-no-branch', !JSON.stringify(broward.rows).includes('branch_manager'));
check('63-no-score', !/trust score/i.test(JSON.stringify(broward)));
check('64-no-recommendation', broward.limitations.some((x: string) => /not a recommendation/i.test(x)));
check('65-no-db-writes', broward.diagnostics.dbWrites === 0);
check('66-publication-zero', !readFileSync('lib/specialist-execution/v2.ts', 'utf8').includes('insert('));
check('67-sitemap-zero', !readFileSync('app/sitemap.ts', 'utf8').includes('specialist-execution'));
check('68-v1', readFileSync('app/api/ask/route.ts', 'utf8').includes('LENDER_ASK_CONTRACT'));
check('69-home', readFileSync('app/page.tsx', 'utf8').length > 0);
check('70-florida', readFileSync('app/florida/page.tsx', 'utf8').length > 0);
check('71-fingerprint', readFileSync('scripts/fl-lend-002f.py', 'utf8').includes('FL_OFR_NMLS_PRR_141437'));
check('72-lint-script', JSON.parse(readFileSync('package.json', 'utf8')).scripts.lint === 'eslint');
check('73-tests-script', JSON.parse(readFileSync('package.json', 'utf8')).scripts.test.includes('assert:ask-lender'));

for (const [id, pass, detail] of checks) {
  if (!pass) throw new Error(`FAIL ${id}${detail ? `: ${detail}` : ''}`);
  console.log(`PASS ${id}${detail ? ` ${detail}` : ''}`);
}
console.log(`PASS LEND-CAP-001 ${checks.length} checks`);
