import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import rosters from '../lib/connecticut-intelligence/rosters.json';
import { CONNECTICUT_SNAPSHOT as ct } from '../lib/connecticut-intelligence/snapshot';
import { parseLenderAsk } from '../lib/ask-lender/parse';
import { normalizedPublishedStatePath } from '../lib/seo/published-state-path';

const expected = { lender: [1567, 448, 1119], broker: [345, 290, 55], correspondent_lender: [25, 22, 3], servicer: [95, 75, 20] } as const;
assert.equal(rosters.records.length, 2032);
for (const [family, [total, companies, branches]] of Object.entries(expected)) {
  const rows = rosters.records.filter(row => row.family === family);
  assert.equal(rows.length, total, family);
  assert.equal(new Set(rows.map(row => row.licenseNumber)).size, total, `${family} distinct licenses`);
  assert.equal(rows.filter(row => row.holderGrain === 'company').length, companies, family);
  assert.equal(rows.filter(row => row.holderGrain === 'branch').length, branches, family);
  assert.ok(rows.every(row => row.licenseName && row.sourceStatus === 'LISTED_AS_LICENSED'));
}
assert.ok(rosters.files.every(file => file.asOf === '2026-09-02' && file.sha256.length === 64));
assert.equal(ct.licensing.nmlsPrintedRows, 0);
assert.equal(ct.licensing.exactRosterNmlsBridges, 0);
assert.equal(rosters.streetAddressesPublished, 0);
const lines = readFileSync('data/hmda/by-state/CT/county_market_summary.csv', 'utf8').trim().split(/\r?\n/);
const fields = lines[0].split(',');
const data = lines.slice(1).map(line => Object.fromEntries(line.split(',').map((value, i) => [fields[i], value])));
const sum = (field: string) => data.reduce((n, row) => n + Number(row[field]), 0);
assert.equal(data.length, ct.hmda.countyEquivalents);
for (const [field, expectedValue] of Object.entries({ total_applications: ct.hmda.applications, total_originations: ct.hmda.originations, denial_count: ct.hmda.denials, purchase_count: ct.hmda.purchase, refinance_count: ct.hmda.refinance, purpose_other_count: ct.hmda.otherPurpose, apps_conventional: ct.hmda.conventional, apps_fha: ct.hmda.fha, apps_va: ct.hmda.va, apps_usda_other: ct.hmda.usdaOther })) assert.equal(sum(field), expectedValue, field);
assert.equal(Math.round(ct.hmda.denials / ct.hmda.applications * 10000) / 100, ct.hmda.denialApplicationPct);
assert.equal(readFileSync('data/hmda/by-state/CT/lender_state_summary.csv', 'utf8').trim().split(/\r?\n/).length - 1, ct.hmda.distinctLeis);
assert.equal(ct.enforcement.rows.length, 11);
assert.equal(ct.enforcement.rows.filter(row => row.grain === 'company').length, 8);
assert.equal(ct.enforcement.rows.filter(row => row.grain === 'person/MLO').length, 3);
assert.ok(ct.enforcement.rows.every(row => /^\d{4}-\d{2}-\d{2}$/.test(row.date) && /^\d+$/.test(row.nmls) && row.url.startsWith('https://portal.ct.gov/')));
assert.equal(ct.enforcement.existingCanonicalAttachments, 1);
assert.equal(ct.enforcement.rows.find(row => row.existingSlug)?.nmls, '2212');
assert.equal(ct.enforcement.nameOnlyAttachments, 0);
assert.equal(ct.enforcement.exactStateLicenseRespondentRows, 0);
assert.equal(ct.graph.writes, 0);
assert.equal(ct.graph.netNewCanonicalOrganizations, 0);
assert.equal(ct.graph.claimEligibilityChanged, false);
assert.equal(normalizedPublishedStatePath('/Connecticut'), '/connecticut');
assert.equal(normalizedPublishedStatePath('/CONNECTICUT'), '/connecticut');
assert.equal(normalizedPublishedStatePath('/connecticut/hartford'), null);
for (const q of ['mortgage lender Connecticut', 'mortgage broker Connecticut', 'mortgage servicer Connecticut', 'correspondent lender Connecticut', 'Connecticut mortgage license', 'Connecticut Department of Banking mortgage', 'mortgage enforcement Connecticut', 'mortgage complaints Connecticut', 'lender Hartford', 'lender New Haven', 'lender Stamford', 'lender Bridgeport']) assert.equal(parseLenderAsk(q).mode, 'fail_closed', q);
for (const q of ['HMDA Connecticut', 'mortgage applications Connecticut', 'mortgage originations Connecticut', 'mortgage denials Connecticut']) assert.notEqual(parseLenderAsk(q).failClosedKind, 'ct-dob-licensing', q);
assert.equal(parseLenderAsk('NMLS 2229 Connecticut mover insurance contractor senior investor').identifier?.value, '2229');
assert.notEqual(parseLenderAsk('2229').mode, 'entity');
for (const q of ['best Connecticut lender', 'safest Connecticut lender', 'recommended Connecticut lender', 'recommend Connecticut lender', 'top-rated Connecticut lender', 'highest-rated Connecticut lender', '#1 Connecticut lender', 'number one Connecticut lender', 'most trustworthy Connecticut lender', 'most trusted Connecticut lender', 'Trust Score Connecticut lender', 'AggregateRating Connecticut lender', 'ratingValue Connecticut lender', 'paid ranking Connecticut lender', 'sponsored ranking Connecticut lender']) assert.equal(parseLenderAsk(q).mode, 'fail_closed', q);
assert.equal((readFileSync('app/sitemap.ts', 'utf8').match(/path: '\/connecticut'/g) ?? []).length, 1);
assert.equal((readFileSync('public/sitemaps/mortgage-lenders.xml', 'utf8').match(/<loc>https:\/\/www\.lendertrusthub\.com\/connecticut<\/loc>/g) ?? []).length, 1);
const page = readFileSync('app/connecticut/page.tsx', 'utf8');
assert.ok(page.includes('index: true, follow: true') && page.includes('canonical: `${SITE_URL}/connecticut`'));
assert.ok(!/AggregateRating|ratingValue|Trust Score/.test(page));
console.log('CT-LEND-001 assertions passed');
