import assert from 'node:assert/strict';
import { readdirSync, readFileSync } from 'node:fs';
import { parseLenderAsk } from '../lib/ask-lender/parse';
import { executeScalarCount } from '../lib/ask-lender/scalar-count';
import { KENTUCKY_SNAPSHOT as ky } from '../lib/kentucky-intelligence/snapshot';
import { normalizedPublishedStatePath } from '../lib/seo/published-state-path';

const lic = ky.licensing;
const csv = readFileSync(ky.hmda.source, 'utf8').trim().split(/\r?\n/);
const keys = csv[0]!.split(',');
const records = csv.slice(1).map(line => Object.fromEntries(line.split(',').map((v, i) => [keys[i], v])));
const sum = (key: string) => records.reduce((n, row) => n + Number(row[key]), 0);
assert.equal(records.length, ky.hmda.counties);
assert.equal(ky.hmda.counties, 120);
assert.equal(new Set(records.map(row => row.county_fips)).size, 120);
for (const [field, expected] of Object.entries({ total_applications: ky.hmda.applications, total_originations: ky.hmda.originations, denial_count: ky.hmda.denials, purchase_count: ky.hmda.purchase, refinance_count: ky.hmda.refinance, purpose_other_count: ky.hmda.otherPurpose, apps_conventional: ky.hmda.conventional, apps_fha: ky.hmda.fha, apps_va: ky.hmda.va, apps_usda_other: ky.hmda.usdaOther })) assert.equal(sum(field), expected, field);
assert.equal(ky.hmda.purchase + ky.hmda.refinance + ky.hmda.otherPurpose, ky.hmda.applications);
assert.equal(ky.hmda.conventional + ky.hmda.fha + ky.hmda.va + ky.hmda.usdaOther, ky.hmda.applications);
assert.equal(Math.round(ky.hmda.denials / ky.hmda.applications * 10000) / 100, ky.hmda.denialApplicationPct);
assert.equal(readFileSync(ky.hmda.leiSummarySource, 'utf8').trim().split(/\r?\n/).length - 1, ky.hmda.leiSummaryRows);
assert.equal(lic.mortgageCompanies + lic.mortgageBrokers, lic.companiesAndBrokersPrintedSum);
assert.equal(lic.companiesAndBrokersPrintedSum, 2158);
assert.equal(lic.checkCashersOrDeferredDeposit + lic.limitedCheckCashers + lic.consumerLoanCompanies + lic.federalStudentLoanServicers + lic.studentLoanServicers + lic.moneyTransmitters + lic.companiesAndBrokersPrintedSum, lic.licenseTypeTotal);
assert.equal(lic.licenseTypeTotal + lic.originatorRegistrations, lic.grandTotal);
assert.equal(lic.grandTotalIsLenderCensus, false);
assert.equal(lic.distinctCompanies, null);
assert.equal(lic.mortgageBankerCount, null);
assert.equal(lic.servicerCount, null);
assert.equal(lic.nmlsBulkRoster, 'NOT_ACQUIRED');
assert.equal(lic.licenseeRosterRows, null);
assert.equal(ky.examinations.mortgageCompanies + ky.examinations.mortgageBrokers + ky.examinations.studentLoanServicers, ky.examinations.total);
assert.equal(ky.examinations.findings, null);
assert.equal(ky.complaints.mortgageCompaniesAndBrokers + ky.complaints.checkCashersOrDeferredDeposit + ky.complaints.consumerLoanCompanies + ky.complaints.moneyTransmitters + ky.complaints.studentLoanServicers, ky.complaints.licensedTypeTotal);
assert.equal(ky.complaints.unlicensedInternetPaydayOrInstallment + ky.complaints.otherUnlicensed, ky.complaints.unlicensedTotal);
assert.equal(ky.complaints.licensedTypeTotal + ky.complaints.unlicensedTotal, ky.complaints.grandTotal);
assert.equal(ky.complaints.outcomes, 'NOT_ACQUIRED');
assert.equal(ky.complaints.mortgageClassesSplit, false);
assert.equal(Object.values(ky.enforcement.yearLinks).reduce((n, v) => n + v, 0), ky.enforcement.indexLinks);
assert.equal(ky.enforcement.indexLinks, 1025);
assert.equal(ky.enforcement.distinctDocumentHrefs, 1019);
assert.equal(ky.enforcement.exactCanonicalAttachments, 0);
assert.equal(ky.enforcement.nameOnlyAdverseJoins, 0);
assert.notEqual(ky.hmda.applications, lic.mortgageCompanies);
assert.notEqual(ky.hmda.applications, lic.originatorRegistrations);
assert.notEqual(ky.hmda.applications, lic.grandTotal);
assert.notEqual(ky.hmda.leiSummaryRows, lic.mortgageCompanies);
assert.equal(ky.depository.isMortgageLicense, false);
assert.equal(ky.newCanonicalOrganizations, 0);
assert.equal(ky.graphWrites, 0);
assert.equal(ky.claimEligibilityChanges, 0);
assert.equal(ky.sources.annualReportSha256, '363f98955759406ba34f83ee0323d7cae5792330e30c91c969ca6e9231fa5b84');
assert.equal(normalizedPublishedStatePath('/Kentucky'), '/kentucky');
assert.equal(normalizedPublishedStatePath('/KENTUCKY'), '/kentucky');
assert.equal(normalizedPublishedStatePath('/kentucky'), null);
assert.equal(normalizedPublishedStatePath('/kentucky/louisville'), null);
assert.equal(normalizedPublishedStatePath('/kentucky/lexington'), null);
for (const q of ['how many mortgage lenders in Kentucky', 'mortgage broker Kentucky', 'mortgage servicer Kentucky', 'mortgage company Kentucky', 'Kentucky mortgage license', 'how many mortgage originators in Kentucky', 'mortgage lender in KY', 'Kentucky DFI licensees', 'how many banks in Kentucky', 'Kentucky credit unions', 'licensed institutions Kentucky', 'mortgage enforcement Kentucky', 'mortgage complaints Kentucky', 'mortgage lender Louisville', 'mortgage lender Lexington', 'HMDA Louisville', 'mortgage applications Lexington']) assert.equal(parseLenderAsk(q).mode, 'fail_closed', q);
assert.match(parseLenderAsk('how many mortgage lenders in Kentucky').failReason ?? '', /not a license count|NOT_ACQUIRED/);
assert.match(parseLenderAsk('mortgage broker Kentucky').failReason ?? '', /229/);
assert.match(parseLenderAsk('how many mortgage originators in Kentucky').failReason ?? '', /10,097/);
assert.match(parseLenderAsk('mortgage servicer Kentucky').failReason ?? '', /NOT_ACQUIRED/);
assert.match(parseLenderAsk('licensed institutions Kentucky').failReason ?? '', /13,081/);
assert.match(parseLenderAsk('licensed institutions Kentucky').failReason ?? '', /not a Kentucky lender census/);
assert.match(parseLenderAsk('mortgage complaints Kentucky').failReason ?? '', /164/);
assert.match(parseLenderAsk('mortgage enforcement Kentucky').failReason ?? '', /1,025/);
assert.notEqual(parseLenderAsk('mortgage lender Louisville Alabama').failClosedKind, 'ky-city-context');
assert.equal(parseLenderAsk('mortgage lender Louisville Alabama').failClosedKind, 'al-no-mortgage-lender-class');
for (const q of ['HMDA Kentucky', 'mortgage applications Kentucky', 'mortgage originations Kentucky', 'mortgage denials Kentucky']) assert.equal(parseLenderAsk(q).mode, 'count', q);
assert.equal(executeScalarCount(parseLenderAsk('mortgage applications Kentucky')).facts[0]?.value, '172,675');
assert.equal(executeScalarCount(parseLenderAsk('mortgage originations Kentucky')).facts[0]?.value, '100,355');
assert.equal(executeScalarCount(parseLenderAsk('mortgage denials Kentucky')).facts[0]?.value, '32,254');
assert.equal(parseLenderAsk('NMLS 3013 Kentucky').mode, 'entity');
assert.notEqual(parseLenderAsk('3013').mode, 'entity');
assert.match(parseLenderAsk('mortgage lender 123456 Kentucky').failReason ?? '', /number has no label/);
for (const q of ['best lender', 'safest lender', 'recommended lender', 'most trustworthy lender', 'highest-rated lender', 'top-rated lender', '#1 lender', 'number one lender', 'Trust Score lender', 'AggregateRating lender', 'ratingValue lender', 'paid ranking lender', 'sponsored ranking lender']) assert.equal(parseLenderAsk(`${q} Kentucky`).mode, 'fail_closed', q);
assert.equal(parseLenderAsk('how many mortgage lenders in Alabama').failClosedKind, 'al-no-mortgage-lender-class');
assert.equal(parseLenderAsk('how many mortgage lenders in Louisiana').failClosedKind, 'la-ofi-licensing');
const page = readFileSync('app/kentucky/page.tsx', 'utf8');
assert.doesNotMatch(page, /AggregateRating|ratingValue|Trust Score/);
assert.match(page, /NOT_ACQUIRED/);
assert.match(page, /lic\.mortgageCompanies/);
assert.match(page, /lic\.originatorRegistrations/);
assert.match(page, /lic\.mortgageBrokers/);
assert.match(page, /includes companies and branches/i);
assert.match(page, /ky\.hmda\.applications/);
assert.match(page, /canonical: `\$\{SITE_URL\}\/kentucky`/);
assert.match(page, /robots: \{ index: true, follow: true \}/);
assert.equal(readFileSync('app/sitemap.ts', 'utf8').match(/path: '\/kentucky'/g)?.length, 1);
assert.deepEqual(readdirSync('app/kentucky').sort(), ['page.tsx']);
console.log('KY-LEND-001 PASS');
