import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { MARYLAND_SNAPSHOT as md } from '../lib/maryland-intelligence/snapshot';
import { parseLenderAsk } from '../lib/ask-lender/parse';
import { normalizedPublishedStatePath } from '../lib/seo/published-state-path';

const csv = readFileSync(md.hmda.source, 'utf8').trim().split(/\r?\n/);
const keys = csv[0]!.split(',');
const records = csv.slice(1).map(line => Object.fromEntries(line.split(',').map((v, i) => [keys[i], v])));
const sum = (key: string) => records.reduce((n, row) => n + Number(row[key]), 0);
assert.equal(records.length, 24);
for (const [field, expected] of Object.entries({ total_applications: md.hmda.applications, total_originations: md.hmda.originations, denial_count: md.hmda.denials, purchase_count: md.hmda.purchase, refinance_count: md.hmda.refinance, purpose_other_count: md.hmda.otherPurpose, apps_conventional: md.hmda.conventional, apps_fha: md.hmda.fha, apps_va: md.hmda.va, apps_usda_other: md.hmda.usdaOther })) assert.equal(sum(field), expected, field);
assert.equal(Math.round(md.hmda.denials / md.hmda.applications * 10000) / 100, md.hmda.denialApplicationPct);
assert.equal(readFileSync('data/hmda/by-state/MD/lender_state_summary.csv', 'utf8').trim().split(/\r?\n/).length - 1, md.hmda.distinctLeis);
assert.equal(md.licensing.rows, null);
assert.equal(md.licensing.rowsWithPrintedNmls, null);
assert.equal(md.licensing.branchLocations, 'REQUEST_ONLY');
assert.ok(!md.licensing.classes.includes('branch' as never));
assert.equal(md.enforcement.rows.length, 8);
assert.deepEqual(md.enforcement.rows.filter(row => row.nmls).map(row => row.nmls), ['51106']);
assert.equal(md.enforcement.exactCanonicalAttachments, 0);
assert.equal(md.enforcement.nameOnlyAdverseJoins, 0);
assert.equal(md.complaints.providerRows, null);
assert.equal(md.newCanonicalOrganizations, 0);
assert.equal(md.graphWrites, 0);
assert.equal(md.claimEligibilityChanges, 0);
assert.equal(normalizedPublishedStatePath('/Maryland'), '/maryland');
assert.equal(normalizedPublishedStatePath('/maryland/baltimore'), null);
for (const q of ['mortgage lender Maryland', 'mortgage broker Maryland', 'mortgage servicer Maryland', 'mortgage company Maryland', 'Maryland mortgage license', 'Maryland OFR mortgage', 'mortgage enforcement Maryland', 'mortgage complaints Maryland', 'mortgage lender Baltimore', 'mortgage lender Annapolis', 'mortgage lender Frederick', 'mortgage lender Rockville']) assert.equal(parseLenderAsk(q).mode, 'fail_closed', q);
for (const q of ['HMDA Maryland', 'mortgage applications Maryland', 'mortgage originations Maryland', 'mortgage denials Maryland']) assert.notEqual(parseLenderAsk(q).failClosedKind, 'md-ofr-licensing', q);
assert.equal(parseLenderAsk('NMLS 123456 Maryland with mover and insurance').mode, 'entity');
assert.notEqual(parseLenderAsk('123456').mode, 'entity');
assert.match(parseLenderAsk('mortgage lender 123456 Maryland').failReason ?? '', /number has no label/);
for (const q of ['best lender', 'safest lender', 'recommended lender', 'most trustworthy lender', 'highest-rated lender', 'top-rated lender', '#1 lender', 'Trust Score lender', 'AggregateRating lender', 'ratingValue lender', 'paid ranking lender', 'sponsored ranking lender']) assert.equal(parseLenderAsk(`${q} Maryland`).mode, 'fail_closed', q);
assert.equal(parseLenderAsk('mortgage lender Connecticut').mode, 'fail_closed');
assert.equal(parseLenderAsk('mortgage lender Michigan').mode, 'entity');
console.log('MD-LEND-001 PASS');
