import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { parseLenderAsk } from '../lib/ask-lender/parse';
import { ILLINOIS_INTELLIGENCE_GATE } from '../lib/illinois-intelligence/publication';
import { assertIllinoisIntelligence, IL_PUBLIC_FINGERPRINT, IL_PUBLIC_PATH } from '../lib/illinois-intelligence/snapshot';
import { buildIllinoisIntelligenceJsonLd, ilJsonLdHasForbiddenRatings } from '../lib/illinois-intelligence/jsonld';

const sitemap = readFileSync('app/sitemap.ts', 'utf8');
const page = readFileSync('app/illinois/page.tsx', 'utf8');
const ui = readFileSync('components/illinois/illinois-state-intelligence.tsx', 'utf8');
const pkg = readFileSync('package.json', 'utf8');
const footer = readFileSync('lib/design/lender-design-system.ts', 'utf8');
const nyUi = readFileSync('components/new-york/new-york-state-intelligence.tsx', 'utf8');
const claim = readFileSync('lib/customer-integration/eligibility.ts', 'utf8');
const searchCaps = readFileSync('lib/specialist-search/capabilities.ts', 'utf8');

const s = assertIllinoisIntelligence();

assert.equal(existsSync('app/illinois/page.tsx'), true);
assert.equal(existsSync('app/illinois/chicago'), false);
assert.equal(existsSync('app/illinois/cook'), false);
assert.equal(ILLINOIS_INTELLIGENCE_GATE.path, '/illinois');
assert.equal(IL_PUBLIC_PATH, '/illinois');
assert.equal(ILLINOIS_INTELLIGENCE_GATE.robotsIndex, true);
assert.match(page, /index:\s*true/);
assert.match(page, /follow:\s*true/);
assert.match(page, /canonical/);
assert.match(sitemap, /\/illinois/);
assert.doesNotMatch(sitemap, /\/illinois\//);
assert.match(footer, /\/illinois/);
assert.match(footer, /Illinois Research/);
assert.match(pkg, /assert:il-lend-001/);
assert.equal(s.fingerprint, IL_PUBLIC_FINGERPRINT);
assert.match(ui, /fmtInt\(H\.applications\)/);
assert.match(ui, /fmtInt\(H\.originations\)/);
assert.match(ui, /fmtInt\(s\.fdic\.institution_rows\)/);
assert.match(ui, /denials_as_pct_of_total_applications/);
assert.match(ui, /denial_pct_denominator_total_applications/);
assert.doesNotMatch(ui, /denial_rate_pct/);
assert.doesNotMatch(ui, /retrieved \{s\.retrieved_at\}/);
assert.equal(s.retrieved_at, null);
assert.equal(s.hmda.retrieved_at, null);
assert.equal(s.fdic.retrieved_at, null);
assert.equal(s.hmda.denials_as_pct_of_total_applications, 16.92);
assert.equal(s.hmda.denial_pct_numerator_denial_observations, 66742);
assert.equal(s.hmda.denial_pct_denominator_total_applications, 394488);
assert.doesNotMatch(ui, /best mortgage lender/i);
assert.doesNotMatch(ui, /AggregateRating|Trust Score schema/i);
assert.match(ui.toLowerCase(), /trust score/);
assert.doesNotMatch(ui, /\/illinois\/chicago|\/illinois\/cook/);
assert.equal(parseLenderAsk('licensed mortgage lenders in Illinois').failClosedKind, 'il-idfpr-nmls-search-only');
assert.equal(parseLenderAsk('how many lenders are in Illinois?').failClosedKind, 'il-no-combined-lenders');
assert.equal(parseLenderAsk('best mortgage lender in Illinois').failClosedKind, 'ranking');
assert.notEqual(parseLenderAsk('mortgage applications in Illinois').mode, 'fail_closed');
assert.equal(parseLenderAsk('complaints against a lender in Illinois').failClosedKind, 'il-cfpb-observations');
assert.equal(parseLenderAsk('Who is serving Chicago in Illinois?').failClosedKind, 'il-mailing-ne-service');
assert.equal(parseLenderAsk('licensed mortgage lenders in New York').failClosedKind, 'ny-dfs-dated-aggregates');
assert.doesNotMatch(claim, /IDFPR|il-idfpr|illinois-roster/);
assert.match(searchCaps, /illinois-roster/);
assert.equal(ilJsonLdHasForbiddenRatings(buildIllinoisIntelligenceJsonLd(s)), false);
assert.match(nyUi, /New York Mortgage Licensing/);
assert.equal(s.expansion_ledger.NET_NEW_CANONICAL_ORGANIZATIONS, 0);
const metrics = JSON.parse(readFileSync('data/home/lender-network-metrics-v1.json', 'utf8'));
assert.ok(metrics.network.publishedStateIntelligencePaths.includes('/illinois'));
assert.ok(metrics.network.publishedStateIntelligencePaths.includes('/new-york'));
assert.equal(metrics.illinois.liveLicensedCompanyUniverse, null);
assert.equal(metrics.illinois.hmdaApplications, 394488);
console.log('assert:il-lend-001 pass', s.fingerprint.slice(0, 12));
