import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { WISCONSIN_SNAPSHOT as wi } from '../lib/wisconsin-intelligence/snapshot';
import { parseLenderAsk } from '../lib/ask-lender/parse';
import { normalizedPublishedStatePath } from '../lib/seo/published-state-path';

const csv = readFileSync(wi.hmda.source, 'utf8').trim().split(/\r?\n/);
const keys = csv[0]!.split(',');
const records = csv.slice(1).map(line => Object.fromEntries(line.split(',').map((v, i) => [keys[i], v])));
const sum = (key: string) => records.reduce((n, row) => n + Number(row[key]), 0);
assert.equal(records.length, wi.hmda.counties);
for (const [field, expected] of Object.entries({ total_applications: wi.hmda.applications, total_originations: wi.hmda.originations, denial_count: wi.hmda.denials, purchase_count: wi.hmda.purchase, refinance_count: wi.hmda.refinance, purpose_other_count: wi.hmda.otherPurpose, apps_conventional: wi.hmda.conventional, apps_fha: wi.hmda.fha, apps_va: wi.hmda.va, apps_usda_other: wi.hmda.usdaOther })) assert.equal(sum(field), expected, field);
assert.equal(Math.round(wi.hmda.denials / wi.hmda.applications * 10000) / 100, wi.hmda.denialApplicationPct);
assert.equal(readFileSync('data/hmda/by-state/WI/lender_state_summary.csv', 'utf8').trim().split(/\r?\n/).length - 1, wi.hmda.distinctLeis);
assert.equal(wi.licensing.verification, 'KNOWN');
assert.equal(wi.licensing.roster, 'NOT_ACQUIRED');
assert.equal(wi.licensing.rows, null);
assert.equal(wi.licensing.classCounts, null);
assert.equal(wi.licensing.rowsWithPrintedNmls, null);
assert.equal(wi.licensing.classes.length, 5);
assert.ok(!wi.licensing.classes.includes('Mortgage Servicer License' as never));
assert.equal(wi.enforcement.rows.length, 2);
assert.deepEqual(wi.enforcement.rows.filter(row => row.nmls).map(row => row.nmls), ['3013']);
assert.equal(wi.enforcement.exactCanonicalAttachments, 0);
assert.equal(wi.enforcement.nameOnlyAdverseJoins, 0);
assert.equal(wi.complaints.providerRows, 'NOT_ACQUIRED');
assert.equal(wi.newCanonicalOrganizations, 0);
assert.equal(wi.graphWrites, 0);
assert.equal(wi.claimEligibilityChanges, 0);
assert.equal(normalizedPublishedStatePath('/Wisconsin'), '/wisconsin');
assert.equal(normalizedPublishedStatePath('/wisconsin/milwaukee'), null);
for (const q of ['mortgage lender Wisconsin', 'mortgage broker Wisconsin', 'mortgage servicer Wisconsin', 'mortgage company Wisconsin', 'Wisconsin mortgage license', 'Wisconsin DFI mortgage', 'mortgage enforcement Wisconsin', 'mortgage complaints Wisconsin', 'mortgage lender Milwaukee', 'mortgage lender Madison', 'mortgage lender Green Bay', 'mortgage lender Kenosha']) assert.equal(parseLenderAsk(q).mode, 'fail_closed', q);
for (const q of ['HMDA Wisconsin', 'mortgage applications Wisconsin', 'mortgage originations Wisconsin', 'mortgage denials Wisconsin']) assert.equal(parseLenderAsk(q).mode, 'count', q);
assert.equal(parseLenderAsk('NMLS 3013 Wisconsin with mover and insurance').mode, 'entity');
assert.notEqual(parseLenderAsk('3013').mode, 'entity');
assert.match(parseLenderAsk('mortgage lender 123456 Wisconsin').failReason ?? '', /number has no label/);
for (const q of ['best lender', 'safest lender', 'recommended lender', 'most trustworthy lender', 'highest-rated lender', 'top-rated lender', '#1 lender', 'number one lender', 'Trust Score lender', 'AggregateRating lender', 'ratingValue lender', 'paid ranking lender', 'sponsored ranking lender']) assert.equal(parseLenderAsk(`${q} Wisconsin`).mode, 'fail_closed', q);
assert.equal(parseLenderAsk('mortgage lender Maryland').mode, 'fail_closed');
assert.equal(parseLenderAsk('mortgage lender Connecticut').mode, 'fail_closed');
assert.equal(parseLenderAsk('mortgage lender Michigan').mode, 'entity');
const page = readFileSync('app/wisconsin/page.tsx', 'utf8');
assert.doesNotMatch(page, /AggregateRating|ratingValue|Trust Score/);
assert.match(page, /NOT_ACQUIRED/);
assert.match(page, /canonical: `\$\{SITE_URL\}\/wisconsin`/);
assert.match(page, /robots: \{ index: true, follow: true \}/);
assert.equal(readFileSync('app/sitemap.ts', 'utf8').match(/path: '\/wisconsin'/g)?.length, 1);
console.log('WI-LEND-001 PASS');
