import assert from 'node:assert/strict';
import { readdirSync, readFileSync } from 'node:fs';
import { LOUISIANA_SNAPSHOT as la } from '../lib/louisiana-intelligence/snapshot';
import { parseLenderAsk } from '../lib/ask-lender/parse';
import { normalizedPublishedStatePath } from '../lib/seo/published-state-path';

const csv = readFileSync(la.hmda.source, 'utf8').trim().split(/\r?\n/);
const keys = csv[0]!.split(',');
const records = csv.slice(1).map(line => Object.fromEntries(line.split(',').map((v, i) => [keys[i], v])));
const sum = (key: string) => records.reduce((n, row) => n + Number(row[key]), 0);
assert.equal(records.length, la.hmda.counties);
for (const [field, expected] of Object.entries({ total_applications: la.hmda.applications, total_originations: la.hmda.originations, denial_count: la.hmda.denials, purchase_count: la.hmda.purchase, refinance_count: la.hmda.refinance, purpose_other_count: la.hmda.otherPurpose, apps_conventional: la.hmda.conventional, apps_fha: la.hmda.fha, apps_va: la.hmda.va, apps_usda_other: la.hmda.usdaOther })) assert.equal(sum(field), expected, field);
assert.equal(Math.round(la.hmda.denials / la.hmda.applications * 10000) / 100, la.hmda.denialApplicationPct);
assert.equal(readFileSync('data/hmda/by-state/LA/lender_state_summary.csv', 'utf8').trim().split(/\r?\n/).length - 1, la.hmda.distinctLeis);
assert.equal(la.licensing.verification, 'KNOWN');
assert.equal(la.licensing.nmlsBulkRoster, 'NOT_ACQUIRED');
assert.equal(la.licensing.originatorUnderLenderRowItems, 9812);
assert.equal(la.licensing.originatorUnderLenderClock, 'October 05, 2026 at 06:26 AM');
assert.equal(la.licensing.originatorUnderLenderGrain, 'ROW_ITEMS');
assert.equal(la.licensing.distinctCompanies, null);
assert.equal(la.licensing.distinctPersons, null);
assert.equal(la.licensing.combinedLenderTotal, null);
assert.equal(la.licensing.classCounts, null);
assert.equal(la.licensing.lenderCount, null);
assert.equal(la.licensing.brokerCount, null);
assert.equal(la.licensing.branchCount, null);
assert.equal(la.licensing.servicerCount, null);
assert.equal(la.licensing.rowsWithPrintedNmls, null);
assert.equal(la.licensing.licenseeExamTable.adoptedAsClassCount, false);
assert.equal(la.licensing.licenseeExamTable.printedItems, 920);
assert.notEqual(la.licensing.licenseeExamTable.printedItems + la.licensing.originatorUnderLenderRowItems, la.licensing.originatorUnderLenderRowItems);
assert.equal(la.hmda.applications === la.licensing.originatorUnderLenderRowItems, false);
assert.equal(la.enforcement.corpus, 'NOT_ACQUIRED');
assert.equal(la.enforcement.exactCanonicalAttachments, 0);
assert.equal(la.enforcement.nameOnlyAdverseJoins, 0);
assert.equal(la.complaints.intake, 'KNOWN');
assert.equal(la.complaints.providerRows, 'NOT_ACQUIRED');
assert.equal(la.newCanonicalOrganizations, 0);
assert.equal(la.graphWrites, 0);
assert.equal(la.claimEligibilityChanges, 0);
assert.equal(normalizedPublishedStatePath('/Louisiana'), '/louisiana');
assert.equal(normalizedPublishedStatePath('/louisiana/new-orleans'), null);
assert.equal(normalizedPublishedStatePath('/louisiana/baton-rouge'), null);
assert.equal(normalizedPublishedStatePath('/louisiana/shreveport'), null);
assert.equal(normalizedPublishedStatePath('/louisiana/lafayette'), null);
for (const q of ['mortgage lender Louisiana', 'mortgage broker Louisiana', 'mortgage servicer Louisiana', 'mortgage company Louisiana', 'Louisiana mortgage license', 'Louisiana OFI mortgage', 'how many mortgage lenders in Louisiana', 'how many mortgage originators in Louisiana', 'mortgage lender in LA', 'mortgage enforcement Louisiana', 'mortgage complaints Louisiana', 'mortgage lender New Orleans', 'mortgage lender Baton Rouge', 'mortgage lender Shreveport', 'mortgage lender Lafayette', 'HMDA New Orleans', 'mortgage applications Baton Rouge', 'mortgage originations Shreveport', 'mortgage denials Lafayette']) assert.equal(parseLenderAsk(q).mode, 'fail_closed', q);
assert.match(parseLenderAsk('how many mortgage lenders in Louisiana').failReason ?? '', /not a lender census|combined Louisiana lender total|not a license count/);
assert.match(parseLenderAsk('mortgage applications Louisiana').failReason ?? '', /^$/);
for (const q of ['HMDA Louisiana', 'mortgage applications Louisiana', 'mortgage originations Louisiana', 'mortgage denials Louisiana']) assert.equal(parseLenderAsk(q).mode, 'count', q);
assert.equal(parseLenderAsk('NMLS 3013 Louisiana with mover and insurance').mode, 'entity');
assert.notEqual(parseLenderAsk('3013').mode, 'entity');
assert.match(parseLenderAsk('mortgage lender 123456 Louisiana').failReason ?? '', /number has no label/);
for (const q of ['best lender', 'safest lender', 'recommended lender', 'most trustworthy lender', 'highest-rated lender', 'top-rated lender', '#1 lender', 'number one lender', 'Trust Score lender', 'AggregateRating lender', 'ratingValue lender', 'paid ranking lender', 'sponsored ranking lender']) assert.equal(parseLenderAsk(`${q} Louisiana`).mode, 'fail_closed', q);
assert.equal(parseLenderAsk('mortgage lender Maryland').mode, 'fail_closed');
assert.equal(parseLenderAsk('mortgage lender Connecticut').mode, 'fail_closed');
assert.equal(parseLenderAsk('mortgage lender Michigan').mode, 'entity');
assert.equal(parseLenderAsk('mortgage lender Wisconsin').mode, 'fail_closed');
const page = readFileSync('app/louisiana/page.tsx', 'utf8');
assert.doesNotMatch(page, /AggregateRating|ratingValue|Trust Score|9290/);
assert.match(page, /NOT_ACQUIRED/);
assert.match(page, /not a lender, broker, or distinct-person census/i);
assert.match(page, /canonical: `\$\{SITE_URL\}\/louisiana`/);
assert.match(page, /robots: \{ index: true, follow: true \}/);
assert.equal(readFileSync('app/sitemap.ts', 'utf8').match(/path: '\/louisiana'/g)?.length, 1);
assert.deepEqual(readdirSync('app/louisiana').sort(), ['page.tsx']);
console.log('LA-LEND-001 PASS');
