import assert from 'node:assert/strict';
import { readdirSync, readFileSync } from 'node:fs';
import { ALABAMA_SNAPSHOT as al } from '../lib/alabama-intelligence/snapshot';
import { parseLenderAsk } from '../lib/ask-lender/parse';
import { normalizedPublishedStatePath } from '../lib/seo/published-state-path';

const loans = al.bureauOfLoans;
const csv = readFileSync(al.hmda.source, 'utf8').trim().split(/\r?\n/);
const keys = csv[0]!.split(',');
const records = csv.slice(1).map(line => Object.fromEntries(line.split(',').map((v, i) => [keys[i], v])));
const sum = (key: string) => records.reduce((n, row) => n + Number(row[key]), 0);
assert.equal(records.length, al.hmda.counties);
for (const [field, expected] of Object.entries({ total_applications: al.hmda.applications, total_originations: al.hmda.originations, denial_count: al.hmda.denials, purchase_count: al.hmda.purchase, refinance_count: al.hmda.refinance, purpose_other_count: al.hmda.otherPurpose, apps_conventional: al.hmda.conventional, apps_fha: al.hmda.fha, apps_va: al.hmda.va, apps_usda_other: al.hmda.usdaOther })) assert.equal(sum(field), expected, field);
assert.equal(al.hmda.purchase + al.hmda.refinance + al.hmda.otherPurpose, al.hmda.applications);
assert.equal(al.hmda.conventional + al.hmda.fha + al.hmda.va + al.hmda.usdaOther, al.hmda.applications);
assert.equal(Math.round(al.hmda.denials / al.hmda.applications * 10000) / 100, al.hmda.denialApplicationPct);
assert.equal(readFileSync('data/hmda/by-state/AL/lender_state_summary.csv', 'utf8').trim().split(/\r?\n/).length - 1, al.hmda.distinctLeis);
assert.equal(loans.smallLoanAct + loans.consumerCreditAct + loans.pawnShopAct + loans.mortgageBrokersLicensingAct + loans.safeActOriginatorLicensees + loans.deferredPresentmentServicesAct, loans.compositionLicensees);
assert.equal(loans.compositionLicensees, 19619);
assert.equal(loans.compositionIsMortgageCensus, false);
assert.equal(loans.mortgageBrokersLicensingAct, 518);
assert.equal(loans.safeActOriginatorLicensees, 14836);
assert.equal(loans.mortgageBrokerBusinessOrPerson, 'NOT_LABELED');
assert.equal(loans.safeActGrain, 'MORTGAGE_LOAN_ORIGINATOR_LICENSEES');
assert.equal(loans.mortgageLenderCount, null);
assert.equal(loans.servicerCount, null);
assert.equal(loans.combinedMortgageTotal, null);
assert.equal(loans.nmlsBulkRoster, 'NOT_ACQUIRED');
assert.equal(loans.licenseeRows, null);
assert.notEqual(loans.mortgageBrokersLicensingAct + loans.safeActOriginatorLicensees, loans.compositionLicensees);
assert.equal(al.hmda.applications === loans.mortgageBrokersLicensingAct, false);
assert.equal(al.hmda.applications === loans.safeActOriginatorLicensees, false);
assert.equal(al.hmda.applications === loans.compositionLicensees, false);
assert.equal(al.mortgageBrokerFinancials2024.adoptedAsCensus, false);
assert.equal(al.mortgageBrokerFinancials2024.totalLoansClosedCount, 3095);
assert.equal(al.bureauOfBanks.commercialBanksSupervised, 88);
assert.equal(al.enforcement.corpus, 'NOT_ACQUIRED');
assert.equal(al.enforcement.exactCanonicalAttachments, 0);
assert.equal(al.enforcement.nameOnlyAdverseJoins, 0);
assert.equal(al.complaints.intake, 'KNOWN');
assert.equal(al.complaints.providerRows, 'NOT_ACQUIRED');
assert.equal(al.newCanonicalOrganizations, 0);
assert.equal(al.graphWrites, 0);
assert.equal(al.claimEligibilityChanges, 0);
assert.equal(al.sources.annualReportSha256, '3ca1f2226b49ce6849181116fc5282acc934afeef48d2dbb3ccc2231f3b5f2fb');
assert.equal(normalizedPublishedStatePath('/Alabama'), '/alabama');
assert.equal(normalizedPublishedStatePath('/ALABAMA'), '/alabama');
assert.equal(normalizedPublishedStatePath('/alabama'), null);
assert.equal(normalizedPublishedStatePath('/alabama/birmingham'), null);
assert.equal(normalizedPublishedStatePath('/alabama/montgomery'), null);
assert.equal(normalizedPublishedStatePath('/alabama/huntsville'), null);
assert.equal(normalizedPublishedStatePath('/alabama/mobile'), null);
assert.equal(normalizedPublishedStatePath('/alabama/tuscaloosa'), null);
for (const q of ['mortgage lender Alabama', 'how many mortgage lenders in Alabama', 'mortgage broker Alabama', 'mortgage servicer Alabama', 'mortgage company Alabama', 'Alabama mortgage license', 'how many mortgage originators in Alabama', 'Alabama SAFE Act originators', 'mortgage lender in AL', 'Alabama small loan licenses', 'Alabama consumer credit licensees', 'Alabama pawn shop licenses', 'Alabama deferred presentment', 'how many banks in Alabama', 'Bureau of Loans licensees Alabama', 'mortgage enforcement Alabama', 'mortgage complaints Alabama', 'mortgage lender Birmingham', 'mortgage lender Montgomery', 'mortgage lender Huntsville', 'mortgage lender Tuscaloosa', 'mortgage lender Mobile Alabama', 'HMDA Birmingham', 'mortgage applications Montgomery']) assert.equal(parseLenderAsk(q).mode, 'fail_closed', q);
assert.match(parseLenderAsk('how many mortgage lenders in Alabama').failReason ?? '', /not a combined Alabama lender total|mortgage-lender census/);
assert.match(parseLenderAsk('mortgage broker Alabama').failReason ?? '', /518/);
assert.match(parseLenderAsk('mortgage broker Alabama').failReason ?? '', /not added|are not added/);
assert.match(parseLenderAsk('how many mortgage originators in Alabama').failReason ?? '', /14,836/);
assert.match(parseLenderAsk('Bureau of Loans licensees Alabama').failReason ?? '', /19,619/);
assert.match(parseLenderAsk('Bureau of Loans licensees Alabama').failReason ?? '', /not a mortgage-lender census/);
assert.notEqual(parseLenderAsk('mortgage lender Mobile').failClosedKind, 'al-city-context');
assert.match(parseLenderAsk('mortgage applications Alabama').failReason ?? '', /^$/);
for (const q of ['HMDA Alabama', 'mortgage applications Alabama', 'mortgage originations Alabama', 'mortgage denials Alabama']) assert.equal(parseLenderAsk(q).mode, 'count', q);
assert.equal(parseLenderAsk('NMLS 3013 Alabama with mover and insurance').mode, 'entity');
assert.notEqual(parseLenderAsk('3013').mode, 'entity');
assert.match(parseLenderAsk('mortgage lender 123456 Alabama').failReason ?? '', /number has no label/);
for (const q of ['best lender', 'safest lender', 'recommended lender', 'most trustworthy lender', 'highest-rated lender', 'top-rated lender', '#1 lender', 'number one lender', 'Trust Score lender', 'AggregateRating lender', 'ratingValue lender', 'paid ranking lender', 'sponsored ranking lender']) assert.equal(parseLenderAsk(`${q} Alabama`).mode, 'fail_closed', q);
assert.equal(parseLenderAsk('mortgage lender Maryland').mode, 'fail_closed');
assert.equal(parseLenderAsk('mortgage lender Connecticut').mode, 'fail_closed');
assert.equal(parseLenderAsk('mortgage lender Michigan').mode, 'entity');
assert.equal(parseLenderAsk('mortgage lender Wisconsin').mode, 'fail_closed');
assert.equal(parseLenderAsk('mortgage lender Louisiana').mode, 'fail_closed');
assert.equal(parseLenderAsk('how many mortgage lenders in Louisiana').failClosedKind, 'la-ofi-licensing');
const page = readFileSync('app/alabama/page.tsx', 'utf8');
assert.doesNotMatch(page, /AggregateRating|ratingValue|Trust Score|15354/);
assert.match(page, /NOT_ACQUIRED/);
assert.match(page, /not a mortgage-lender census/i);
assert.match(page, /518/);
assert.match(page, /14,836/);
assert.match(page, /compositionLicensees/);
assert.match(page, /al\.hmda\.applications/);
assert.match(page, /canonical: `\$\{SITE_URL\}\/alabama`/);
assert.match(page, /robots: \{ index: true, follow: true \}/);
assert.equal(readFileSync('app/sitemap.ts', 'utf8').match(/path: '\/alabama'/g)?.length, 1);
assert.deepEqual(readdirSync('app/alabama').sort(), ['page.tsx']);
console.log('AL-LEND-001 PASS');
