import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { parseLenderAsk } from '../lib/ask-lender/parse';
import { OHIO_INTELLIGENCE_GATE } from '../lib/ohio-intelligence/publication';
import { assertOhioIntelligence, OH_PUBLIC_FINGERPRINT, OH_PUBLIC_PATH } from '../lib/ohio-intelligence/snapshot';
import { buildOhioIntelligenceJsonLd, ohJsonLdHasForbiddenRatings } from '../lib/ohio-intelligence/jsonld';

const sitemap = readFileSync('app/sitemap.ts', 'utf8');
const page = readFileSync('app/ohio/page.tsx', 'utf8');
const ui = readFileSync('components/ohio/ohio-state-intelligence.tsx', 'utf8');
const pkg = readFileSync('package.json', 'utf8');
const footer = readFileSync('lib/design/lender-design-system.ts', 'utf8');
const claim = readFileSync('lib/customer-integration/eligibility.ts', 'utf8');
const searchCaps = readFileSync('lib/specialist-search/capabilities.ts', 'utf8');

const s = assertOhioIntelligence();

assert.equal(existsSync('app/ohio/page.tsx'), true);
assert.equal(existsSync('app/ohio/columbus'), false);
assert.equal(existsSync('app/ohio/cleveland'), false);
assert.equal(existsSync('app/ohio/cincinnati'), false);
assert.equal(existsSync('app/ohio/toledo'), false);
assert.equal(existsSync('app/ohio/dayton'), false);
assert.equal(existsSync('app/ohio/akron'), false);
assert.equal(OHIO_INTELLIGENCE_GATE.path, '/ohio');
assert.equal(OH_PUBLIC_PATH, '/ohio');
assert.equal(OHIO_INTELLIGENCE_GATE.robotsIndex, true);
assert.match(page, /index:\s*true/);
assert.match(page, /follow:\s*true/);
assert.match(page, /canonical/);
assert.match(sitemap, /\/ohio/);
assert.doesNotMatch(sitemap, /\/ohio\//);
assert.match(footer, /\/ohio/);
assert.match(footer, /Ohio Research/);
assert.match(pkg, /assert:oh-lend-001/);
assert.equal(s.fingerprint, OH_PUBLIC_FINGERPRINT);
assert.match(ui, /fmtInt\(H\.applications\)/);
assert.match(ui, /fmtInt\(H\.originations\)/);
assert.match(ui, /denials_as_pct_of_total_applications/);
assert.match(ui, /NMLS Consumer Access/);
assert.match(ui, /OHFA/);
assert.match(ui, /mortgage loan originator|MLO/i);
assert.match(ui, /RMLA/);
assert.doesNotMatch(ui, /denial_rate_pct/);
assert.doesNotMatch(ui, /best mortgage lender/i);
assert.doesNotMatch(ui, /AggregateRating|Trust Score schema/i);
assert.match(ui.toLowerCase(), /trust score/);
assert.doesNotMatch(ui, /\/ohio\/columbus|\/ohio\/cleveland/);
assert.doesNotMatch(ui, /\bNCCOB\b|\bDoBS\b|\bPHFA\b|\bIDFPR\b|\bNYDFS\b/);
assert.equal(parseLenderAsk('how many lenders Ohio').failClosedKind, 'oh-no-combined-lenders');
assert.equal(parseLenderAsk('how many lenders are in Ohio?').failClosedKind, 'oh-no-combined-lenders');
assert.equal(parseLenderAsk('mortgage lenders Ohio').failClosedKind, 'oh-rmla-search-only');
assert.equal(parseLenderAsk('licensed mortgage companies Ohio').failClosedKind, 'oh-rmla-search-only');
assert.equal(parseLenderAsk('best mortgage lender Ohio').failClosedKind, 'ranking');
assert.notEqual(parseLenderAsk('HMDA applications Ohio 2025').mode, 'fail_closed');
assert.equal(parseLenderAsk('mortgage complaints Ohio').failClosedKind, 'oh-cfpb-observations');
assert.equal(parseLenderAsk('CFPB mortgage complaints Ohio').failClosedKind, 'oh-cfpb-observations');
assert.equal(parseLenderAsk('mortgage loan originator Ohio').failClosedKind, 'oh-mlo-search-only');
assert.equal(parseLenderAsk('mortgage servicer Ohio').failClosedKind, 'oh-servicer-activity');
assert.equal(parseLenderAsk('mortgage broker Ohio').failClosedKind, 'oh-broker-activity');
assert.equal(parseLenderAsk('OHFA lenders').failClosedKind, 'oh-ohfa-program');
assert.equal(parseLenderAsk('OHFA lender Cleveland').failClosedKind, 'oh-ohfa-program');
assert.equal(parseLenderAsk('Ohio DFI mortgage enforcement').failClosedKind, 'oh-dfi-enforcement');
assert.equal(parseLenderAsk('mortgage enforcement action Ohio').failClosedKind, 'oh-dfi-enforcement');
assert.equal(parseLenderAsk('Ohio mortgage license RM.804986').failClosedKind, 'oh-dfi-license-identity');
assert.equal(parseLenderAsk('mortgage lender Columbus').failClosedKind, 'oh-no-local');
assert.equal(parseLenderAsk('RMLA Ohio').failClosedKind, 'oh-rmla-search-only');
assert.equal(s.crosswalks.EXACT_OH_DFI_TO_NMLS_CROSSWALKS, 0);
assert.equal(s.crosswalks.EXACT_NMLS_TO_LEI_CROSSWALKS, 0);
assert.equal(s.crosswalks.EXACT_OHFA_NMLS_ATTACHMENTS, 0);
assert.equal(s.ohfa.OH_OHFA_LENDER_OBSERVATION_ROWS, 2095);
assert.equal(s.hero.universe_value, 460825);
assert.notEqual(s.hero.universe_value, 85);
assert.notEqual(s.hero.universe_value, 157);
assert.doesNotMatch(claim, /oh-rmla|oh-dfi-hhg|ohio-rmla/i);
assert.match(searchCaps, /ohio-roster/);
const jsonld = buildOhioIntelligenceJsonLd(s);
assert.equal(ohJsonLdHasForbiddenRatings(jsonld), false);
console.log('OH-LEND-001 publication assert: PASS');
