import type { StateMeta } from './types';

/** All 50 states + DC. Set hasData: true when JSON is added under lib/fdic/data/[slug].json */
export const US_STATES: StateMeta[] = [
  { code: 'AL', fullName: 'Alabama', slug: 'alabama', region: 'Southeast', hasData: true },
  { code: 'AK', fullName: 'Alaska', slug: 'alaska', region: 'West', hasData: false },
  { code: 'AZ', fullName: 'Arizona', slug: 'arizona', region: 'West', hasData: false },
  { code: 'AR', fullName: 'Arkansas', slug: 'arkansas', region: 'South', hasData: false },
  { code: 'CA', fullName: 'California', slug: 'california', region: 'West', hasData: false },
  { code: 'CO', fullName: 'Colorado', slug: 'colorado', region: 'West', hasData: false },
  { code: 'CT', fullName: 'Connecticut', slug: 'connecticut', region: 'Northeast', hasData: false },
  { code: 'DE', fullName: 'Delaware', slug: 'delaware', region: 'Northeast', hasData: false },
  { code: 'DC', fullName: 'District of Columbia', slug: 'district-of-columbia', region: 'Northeast', hasData: false },
  { code: 'FL', fullName: 'Florida', slug: 'florida', region: 'Southeast', hasData: true },
  { code: 'GA', fullName: 'Georgia', slug: 'georgia', region: 'Southeast', hasData: true },
  { code: 'HI', fullName: 'Hawaii', slug: 'hawaii', region: 'West', hasData: false },
  { code: 'ID', fullName: 'Idaho', slug: 'idaho', region: 'West', hasData: false },
  { code: 'IL', fullName: 'Illinois', slug: 'illinois', region: 'Midwest', hasData: false },
  { code: 'IN', fullName: 'Indiana', slug: 'indiana', region: 'Midwest', hasData: false },
  { code: 'IA', fullName: 'Iowa', slug: 'iowa', region: 'Midwest', hasData: false },
  { code: 'KS', fullName: 'Kansas', slug: 'kansas', region: 'Midwest', hasData: false },
  { code: 'KY', fullName: 'Kentucky', slug: 'kentucky', region: 'Southeast', hasData: false },
  { code: 'LA', fullName: 'Louisiana', slug: 'louisiana', region: 'South', hasData: true },
  { code: 'ME', fullName: 'Maine', slug: 'maine', region: 'Northeast', hasData: false },
  { code: 'MD', fullName: 'Maryland', slug: 'maryland', region: 'Northeast', hasData: false },
  { code: 'MA', fullName: 'Massachusetts', slug: 'massachusetts', region: 'Northeast', hasData: false },
  { code: 'MI', fullName: 'Michigan', slug: 'michigan', region: 'Midwest', hasData: false },
  { code: 'MN', fullName: 'Minnesota', slug: 'minnesota', region: 'Midwest', hasData: false },
  { code: 'MS', fullName: 'Mississippi', slug: 'mississippi', region: 'Southeast', hasData: true },
  { code: 'MO', fullName: 'Missouri', slug: 'missouri', region: 'Midwest', hasData: false },
  { code: 'MT', fullName: 'Montana', slug: 'montana', region: 'West', hasData: false },
  { code: 'NE', fullName: 'Nebraska', slug: 'nebraska', region: 'Midwest', hasData: false },
  { code: 'NV', fullName: 'Nevada', slug: 'nevada', region: 'West', hasData: false },
  { code: 'NH', fullName: 'New Hampshire', slug: 'new-hampshire', region: 'Northeast', hasData: false },
  { code: 'NJ', fullName: 'New Jersey', slug: 'new-jersey', region: 'Northeast', hasData: false },
  { code: 'NM', fullName: 'New Mexico', slug: 'new-mexico', region: 'West', hasData: false },
  { code: 'NY', fullName: 'New York', slug: 'new-york', region: 'Northeast', hasData: false },
  { code: 'NC', fullName: 'North Carolina', slug: 'north-carolina', region: 'Southeast', hasData: true },
  { code: 'ND', fullName: 'North Dakota', slug: 'north-dakota', region: 'Midwest', hasData: false },
  { code: 'OH', fullName: 'Ohio', slug: 'ohio', region: 'Midwest', hasData: false },
  { code: 'OK', fullName: 'Oklahoma', slug: 'oklahoma', region: 'South', hasData: false },
  { code: 'OR', fullName: 'Oregon', slug: 'oregon', region: 'West', hasData: false },
  { code: 'PA', fullName: 'Pennsylvania', slug: 'pennsylvania', region: 'Northeast', hasData: false },
  { code: 'RI', fullName: 'Rhode Island', slug: 'rhode-island', region: 'Northeast', hasData: false },
  { code: 'SC', fullName: 'South Carolina', slug: 'south-carolina', region: 'Southeast', hasData: true },
  { code: 'SD', fullName: 'South Dakota', slug: 'south-dakota', region: 'Midwest', hasData: false },
  { code: 'TN', fullName: 'Tennessee', slug: 'tennessee', region: 'Southeast', hasData: false },
  { code: 'TX', fullName: 'Texas', slug: 'texas', region: 'South', hasData: true },
  { code: 'UT', fullName: 'Utah', slug: 'utah', region: 'West', hasData: false },
  { code: 'VT', fullName: 'Vermont', slug: 'vermont', region: 'Northeast', hasData: false },
  { code: 'VA', fullName: 'Virginia', slug: 'virginia', region: 'Southeast', hasData: true },
  { code: 'WA', fullName: 'Washington', slug: 'washington', region: 'West', hasData: false },
  { code: 'WV', fullName: 'West Virginia', slug: 'west-virginia', region: 'Southeast', hasData: true },
  { code: 'WI', fullName: 'Wisconsin', slug: 'wisconsin', region: 'Midwest', hasData: false },
  { code: 'WY', fullName: 'Wyoming', slug: 'wyoming', region: 'West', hasData: false },
];

export const STATE_BY_CODE = new Map(US_STATES.map((s) => [s.code, s]));
export const STATE_BY_SLUG = new Map(US_STATES.map((s) => [s.slug, s]));