import type { SpecialistSearchCapability } from './contract';

export const LENDER_SEARCH_CAPABILITIES: SpecialistSearchCapability[] = [
  { key: 'identity', label: 'Institution identity', supportState: 'KNOWN', coverage: 'Published institution cohort', sourceSystems: ['NMLS institution records', 'GLEIF', 'publication manifests'], limitations: ['Institution is not branch or MLO.'] },
  { key: 'hmda', label: 'HMDA market activity', supportState: 'KNOWN', coverage: 'Committed 2025 state/county observations', sourceSystems: ['CFPB HMDA'], limitations: ['Property geography is not lender location or service territory.'] },
  { key: 'cfpb', label: 'CFPB complaint observations', supportState: 'PARTIAL', coverage: 'Curated confirmed company bridges', sourceSystems: ['CFPB Consumer Complaint Database'], limitations: ['Complaint is not wrongdoing; unattached observations are excluded.'] },
  { key: 'florida-ofr', label: 'Florida OFR evidence', supportState: 'PARTIAL', coverage: 'Published, confirmed institution links only', sourceSystems: ['Florida OFR'], limitations: ['Credential is not institution identity; unresolved links remain held.'] },
  { key: 'new-jersey-rmla', label: 'New Jersey RMLA roster', supportState: 'REQUEST_ONLY', coverage: 'Official request/search workflow', sourceSystems: ['New Jersey DOBI'], limitations: ['No complete acquired bulk universe; missing is not zero.'] },
  { key: 'california-crmla', label: 'California CRMLA roster', supportState: 'NOT_ACQUIRED', coverage: 'No complete current bulk roster', sourceSystems: ['California DFPI'], limitations: ['CalHFA directory rows are not a lender population.'] },
  { key: 'arizona-roster', label: 'Arizona company roster', supportState: 'PARTIAL', coverage: 'Open Search/source-specific evidence', sourceSystems: ['Arizona DIFI'], limitations: ['Open-search evidence is not a complete acquired company universe.'] },
  { key: 'colorado-roster', label: 'Colorado company roster', supportState: 'NOT_ACQUIRED', coverage: 'NMLS Consumer Access search-only; DRE MLO bulk is person-grain', sourceSystems: ['Colorado DRE', 'NMLS'], limitations: ['Search-only company evidence is not a complete acquired company universe. MLO rows are people, not companies.'] },
  { key: 'virginia-roster', label: 'Virginia SCC dated mortgage roster', supportState: 'PARTIAL', coverage: 'SCC 2025-12-31 dated company list with exact MC/NMLS IDs; current 2026 status is NMLS search-only', sourceSystems: ['Virginia SCC BFI', 'NMLS'], limitations: ['Dated 2025 roster is not current license status. Broker, lender, and lender-broker stay separate. MLO persons are not companies.'] },
  { key: 'new-york-roster', label: 'New York DFS dated mortgage aggregates', supportState: 'PARTIAL', coverage: 'DFS 2024 annual-report class aggregates; current 2026 company roster is NMLS/NYDFS search-only', sourceSystems: ['NYDFS', 'NMLS'], limitations: ['Dated 2024 aggregates are not current license status. Banker, broker, servicer, and MLO stay separate. Do not add 151 + 439.'] },
  { key: 'illinois-roster', label: 'Illinois mortgage-company roster', supportState: 'NOT_ACQUIRED', coverage: 'IDFPR/NMLS search-only; HMDA and FDIC overlays are not a company census', sourceSystems: ['IDFPR', 'NMLS'], limitations: ['Search-only is not zero. HMDA applications and FDIC banks are not Illinois mortgage companies.'] },
  { key: 'oregon-roster', label: 'Oregon mortgage-company roster', supportState: 'NOT_ACQUIRED', coverage: 'DFR/NMLS search-only; HMDA, FDIC, and OHCS overlays are not a company census', sourceSystems: ['DFR', 'NMLS'], limitations: ['Search-only is not zero. HMDA applications, HMDA LEIs, FDIC banks, and OHCS Flex lenders are not Oregon mortgage companies.'] },
  { key: 'mlo', label: 'MLO/person directory', supportState: 'UNSUPPORTED', coverage: 'Institution publication only', sourceSystems: [], limitations: ['Person and branch identifiers are not silently treated as institutions.'] },
  { key: 'service-territory', label: 'Service territory', supportState: 'UNSUPPORTED', coverage: 'HMDA property geography only', sourceSystems: ['CFPB HMDA'], limitations: ['Activity tied to properties does not prove availability or service territory.'] },
];
