/**
 * ZIP → county map (leaf module).
 * Kept separate from mockData so catalog sanitize / research scoring cannot circular-import lenders.
 */
export const ZIP_TO_COUNTY: Record<string, { state: string; stateSlug: string; county: string; countySlug: string }> = {
  '33301': { state: 'Florida', stateSlug: 'florida', county: 'Broward', countySlug: 'broward' },
  '33330': { state: 'Florida', stateSlug: 'florida', county: 'Broward', countySlug: 'broward' },
  '33331': { state: 'Florida', stateSlug: 'florida', county: 'Broward', countySlug: 'broward' },
  '33101': { state: 'Florida', stateSlug: 'florida', county: 'Miami-Dade', countySlug: 'miami-dade' },
  '33130': { state: 'Florida', stateSlug: 'florida', county: 'Miami-Dade', countySlug: 'miami-dade' },
  '33431': { state: 'Florida', stateSlug: 'florida', county: 'Palm Beach', countySlug: 'palm-beach' },
  '32801': { state: 'Florida', stateSlug: 'florida', county: 'Orange', countySlug: 'orange' },
  '32819': { state: 'Florida', stateSlug: 'florida', county: 'Orange', countySlug: 'orange' },
  '32811': { state: 'Florida', stateSlug: 'florida', county: 'Orange', countySlug: 'orange' },
  '34786': { state: 'Florida', stateSlug: 'florida', county: 'Orange', countySlug: 'orange' },
  '32827': { state: 'Florida', stateSlug: 'florida', county: 'Orange', countySlug: 'orange' },
  '33602': { state: 'Florida', stateSlug: 'florida', county: 'Hillsborough', countySlug: 'hillsborough' },
  '33609': { state: 'Florida', stateSlug: 'florida', county: 'Hillsborough', countySlug: 'hillsborough' },
  '33544': { state: 'Florida', stateSlug: 'florida', county: 'Hillsborough', countySlug: 'hillsborough' },
  '33619': { state: 'Florida', stateSlug: 'florida', county: 'Hillsborough', countySlug: 'hillsborough' },
  '32202': { state: 'Florida', stateSlug: 'florida', county: 'Duval', countySlug: 'duval' },
  '32256': { state: 'Florida', stateSlug: 'florida', county: 'Duval', countySlug: 'duval' },
  '32073': { state: 'Florida', stateSlug: 'florida', county: 'Duval', countySlug: 'duval' },
  '32223': { state: 'Florida', stateSlug: 'florida', county: 'Duval', countySlug: 'duval' },
  '32401': { state: 'Florida', stateSlug: 'florida', county: 'Bay', countySlug: 'bay' },
  '32407': { state: 'Florida', stateSlug: 'florida', county: 'Bay', countySlug: 'bay' },
  '32547': { state: 'Florida', stateSlug: 'florida', county: 'Okaloosa', countySlug: 'okaloosa' },
  '32504': { state: 'Florida', stateSlug: 'florida', county: 'Escambia', countySlug: 'escambia' },
  '90210': { state: 'California', stateSlug: 'california', county: 'Los Angeles', countySlug: 'los-angeles' },
  '10001': { state: 'New York', stateSlug: 'new-york', county: 'New York', countySlug: 'new-york-county' },
  '77001': { state: 'Texas', stateSlug: 'texas', county: 'Harris', countySlug: 'harris' },
  '75034': { state: 'Texas', stateSlug: 'texas', county: 'Collin', countySlug: 'collin' },
  '75070': { state: 'Texas', stateSlug: 'texas', county: 'Collin', countySlug: 'collin' },
  '75078': { state: 'Texas', stateSlug: 'texas', county: 'Denton', countySlug: 'denton' },
  '75090': { state: 'Texas', stateSlug: 'texas', county: 'Grayson', countySlug: 'grayson' },
  '75020': { state: 'Texas', stateSlug: 'texas', county: 'Grayson', countySlug: 'grayson' },
  '77494': { state: 'Texas', stateSlug: 'texas', county: 'Harris', countySlug: 'harris' },
  '77479': { state: 'Texas', stateSlug: 'texas', county: 'Fort Bend', countySlug: 'fort-bend' },
  '77380': { state: 'Texas', stateSlug: 'texas', county: 'Montgomery', countySlug: 'montgomery' },
  '77304': { state: 'Texas', stateSlug: 'texas', county: 'Montgomery', countySlug: 'montgomery' },
  '78602': { state: 'Texas', stateSlug: 'texas', county: 'Bastrop', countySlug: 'bastrop' },
  '78520': { state: 'Texas', stateSlug: 'texas', county: 'Cameron', countySlug: 'cameron' },
  '78521': { state: 'Texas', stateSlug: 'texas', county: 'Cameron', countySlug: 'cameron' },
  '78201': { state: 'Texas', stateSlug: 'texas', county: 'Bexar', countySlug: 'bexar' },
  '78209': { state: 'Texas', stateSlug: 'texas', county: 'Bexar', countySlug: 'bexar' },
  '78230': { state: 'Texas', stateSlug: 'texas', county: 'Bexar', countySlug: 'bexar' },
  '78249': { state: 'Texas', stateSlug: 'texas', county: 'Bexar', countySlug: 'bexar' },
  '78216': { state: 'Texas', stateSlug: 'texas', county: 'Bexar', countySlug: 'bexar' },
  '78258': { state: 'Texas', stateSlug: 'texas', county: 'Bexar', countySlug: 'bexar' },
  '60601': { state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook' },
  '60614': { state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook' },
  '60622': { state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook' },
  '60647': { state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook' },
  '60657': { state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook' },
  '60004': { state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook' },
  '60056': { state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook' },
  '60201': { state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook' },
  '60302': { state: 'Illinois', stateSlug: 'illinois', county: 'Cook', countySlug: 'cook' },
  '60187': { state: 'Illinois', stateSlug: 'illinois', county: 'DuPage', countySlug: 'dupage' },
  '60137': { state: 'Illinois', stateSlug: 'illinois', county: 'DuPage', countySlug: 'dupage' },
  '60045': { state: 'Illinois', stateSlug: 'illinois', county: 'Lake', countySlug: 'lake' },
  '61101': { state: 'Illinois', stateSlug: 'illinois', county: 'Winnebago', countySlug: 'winnebago' },
  '61602': { state: 'Illinois', stateSlug: 'illinois', county: 'Peoria', countySlug: 'peoria' },
  '61761': { state: 'Illinois', stateSlug: 'illinois', county: 'McLean', countySlug: 'mclean' },
  '48126': { state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne' },
  '48146': { state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne' },
  '48201': { state: 'Michigan', stateSlug: 'michigan', county: 'Wayne', countySlug: 'wayne' },
  '48843': { state: 'Michigan', stateSlug: 'michigan', county: 'Livingston', countySlug: 'livingston' },
  '48933': { state: 'Michigan', stateSlug: 'michigan', county: 'Ingham', countySlug: 'ingham' },
  '48823': { state: 'Michigan', stateSlug: 'michigan', county: 'Ingham', countySlug: 'ingham' },
  '49503': { state: 'Michigan', stateSlug: 'michigan', county: 'Kent', countySlug: 'kent' },
  '49506': { state: 'Michigan', stateSlug: 'michigan', county: 'Kent', countySlug: 'kent' },
  '49301': { state: 'Michigan', stateSlug: 'michigan', county: 'Kent', countySlug: 'kent' },
  '48104': { state: 'Michigan', stateSlug: 'michigan', county: 'Washtenaw', countySlug: 'washtenaw' },
  '49007': { state: 'Michigan', stateSlug: 'michigan', county: 'Kalamazoo', countySlug: 'kalamazoo' },
  '30301': { state: 'Georgia', stateSlug: 'georgia', county: 'Fulton', countySlug: 'fulton' },
  '30041': { state: 'Georgia', stateSlug: 'georgia', county: 'Forsyth', countySlug: 'forsyth' },
  '30004': { state: 'Georgia', stateSlug: 'georgia', county: 'Forsyth', countySlug: 'forsyth' },
  '30097': { state: 'Georgia', stateSlug: 'georgia', county: 'Forsyth', countySlug: 'forsyth' },
  '30024': { state: 'Georgia', stateSlug: 'georgia', county: 'Forsyth', countySlug: 'forsyth' },
  '30253': { state: 'Georgia', stateSlug: 'georgia', county: 'Henry', countySlug: 'henry' },
  '31406': { state: 'Georgia', stateSlug: 'georgia', county: 'Chatham', countySlug: 'chatham' },
  '31405': { state: 'Georgia', stateSlug: 'georgia', county: 'Chatham', countySlug: 'chatham' },
  '30907': { state: 'Georgia', stateSlug: 'georgia', county: 'Richmond', countySlug: 'richmond' },
  '30809': { state: 'Georgia', stateSlug: 'georgia', county: 'Richmond', countySlug: 'richmond' },
  '31909': { state: 'Georgia', stateSlug: 'georgia', county: 'Muscogee', countySlug: 'muscogee' },
  '31904': { state: 'Georgia', stateSlug: 'georgia', county: 'Muscogee', countySlug: 'muscogee' },
  '30043': { state: 'Georgia', stateSlug: 'georgia', county: 'Gwinnett', countySlug: 'gwinnett' },
  '30096': { state: 'Georgia', stateSlug: 'georgia', county: 'Gwinnett', countySlug: 'gwinnett' },
  '30080': { state: 'Georgia', stateSlug: 'georgia', county: 'Cobb', countySlug: 'cobb' },
  '30062': { state: 'Georgia', stateSlug: 'georgia', county: 'Cobb', countySlug: 'cobb' },
  '30033': { state: 'Georgia', stateSlug: 'georgia', county: 'DeKalb', countySlug: 'dekalb' },
  '30083': { state: 'Georgia', stateSlug: 'georgia', county: 'DeKalb', countySlug: 'dekalb' },
  '30188': { state: 'Georgia', stateSlug: 'georgia', county: 'Cherokee', countySlug: 'cherokee' },
  '30114': { state: 'Georgia', stateSlug: 'georgia', county: 'Cherokee', countySlug: 'cherokee' },
  '30052': { state: 'Georgia', stateSlug: 'georgia', county: 'Walton', countySlug: 'walton' },
  '30012': { state: 'Georgia', stateSlug: 'georgia', county: 'Rockdale', countySlug: 'rockdale' },
  '30606': { state: 'Georgia', stateSlug: 'georgia', county: 'Clarke', countySlug: 'clarke' },
  '31602': { state: 'Georgia', stateSlug: 'georgia', county: 'Lowndes', countySlug: 'lowndes' },
  '31525': { state: 'Georgia', stateSlug: 'georgia', county: 'Glynn', countySlug: 'glynn' },
  '31322': { state: 'Georgia', stateSlug: 'georgia', county: 'Effingham', countySlug: 'effingham' },
  '31324': { state: 'Georgia', stateSlug: 'georgia', county: 'Bryan', countySlug: 'bryan' },
  '90012': { state: 'California', stateSlug: 'california', county: 'Los Angeles', countySlug: 'los-angeles' },
  '90017': { state: 'California', stateSlug: 'california', county: 'Los Angeles', countySlug: 'los-angeles' },
  '92101': { state: 'California', stateSlug: 'california', county: 'San Diego', countySlug: 'san-diego' },
  '92602': { state: 'California', stateSlug: 'california', county: 'Orange', countySlug: 'orange' },
  '92401': { state: 'California', stateSlug: 'california', county: 'San Bernardino', countySlug: 'san-bernardino' },
  '95814': { state: 'California', stateSlug: 'california', county: 'Sacramento', countySlug: 'sacramento' },
  '94612': { state: 'California', stateSlug: 'california', county: 'Alameda', countySlug: 'alameda' },
  '94520': { state: 'California', stateSlug: 'california', county: 'Contra Costa', countySlug: 'contra-costa' },
  '94102': { state: 'California', stateSlug: 'california', county: 'San Francisco', countySlug: 'san-francisco' },
  '95060': { state: 'California', stateSlug: 'california', county: 'Santa Cruz', countySlug: 'santa-cruz' },
  '95667': { state: 'California', stateSlug: 'california', county: 'El Dorado', countySlug: 'el-dorado' },
  '95340': { state: 'California', stateSlug: 'california', county: 'Merced', countySlug: 'merced' },
  '96001': { state: 'California', stateSlug: 'california', county: 'Shasta', countySlug: 'shasta' },
  '95901': { state: 'California', stateSlug: 'california', county: 'Butte', countySlug: 'butte' },
  '94558': { state: 'California', stateSlug: 'california', county: 'Napa', countySlug: 'napa' },
  '29577': { state: 'South Carolina', stateSlug: 'south-carolina', county: 'Horry', countySlug: 'horry' },
  '29615': { state: 'South Carolina', stateSlug: 'south-carolina', county: 'Greenville', countySlug: 'greenville' },
  '29464': { state: 'South Carolina', stateSlug: 'south-carolina', county: 'Charleston', countySlug: 'charleston' },
  '29483': { state: 'South Carolina', stateSlug: 'south-carolina', county: 'Berkeley', countySlug: 'berkeley' },
  // SC deepen / major market ZIP hints
  '29201': { state: 'South Carolina', stateSlug: 'south-carolina', county: 'Richland', countySlug: 'richland' },
  '29301': { state: 'South Carolina', stateSlug: 'south-carolina', county: 'Spartanburg', countySlug: 'spartanburg' },
  '29730': { state: 'South Carolina', stateSlug: 'south-carolina', county: 'York', countySlug: 'york' },
  '29072': { state: 'South Carolina', stateSlug: 'south-carolina', county: 'Lexington', countySlug: 'lexington' },
  '29928': { state: 'South Carolina', stateSlug: 'south-carolina', county: 'Beaufort', countySlug: 'beaufort' },
  '29485': { state: 'South Carolina', stateSlug: 'south-carolina', county: 'Dorchester', countySlug: 'dorchester' },
  '29621': { state: 'South Carolina', stateSlug: 'south-carolina', county: 'Anderson', countySlug: 'anderson' },
  '29803': { state: 'South Carolina', stateSlug: 'south-carolina', county: 'Aiken', countySlug: 'aiken' },
  '29150': { state: 'South Carolina', stateSlug: 'south-carolina', county: 'Sumter', countySlug: 'sumter' },
  '29501': { state: 'South Carolina', stateSlug: 'south-carolina', county: 'Florence', countySlug: 'florence' },
  '29671': { state: 'South Carolina', stateSlug: 'south-carolina', county: 'Pickens', countySlug: 'pickens' },
  '29678': { state: 'South Carolina', stateSlug: 'south-carolina', county: 'Oconee', countySlug: 'oconee' },
  '29115': { state: 'South Carolina', stateSlug: 'south-carolina', county: 'Orangeburg', countySlug: 'orangeburg' },
  '29646': { state: 'South Carolina', stateSlug: 'south-carolina', county: 'Greenwood', countySlug: 'greenwood' },
  '29440': { state: 'South Carolina', stateSlug: 'south-carolina', county: 'Georgetown', countySlug: 'georgetown' },
  '29936': { state: 'South Carolina', stateSlug: 'south-carolina', county: 'Jasper', countySlug: 'jasper' },
  '27601': { state: 'North Carolina', stateSlug: 'north-carolina', county: 'Wake', countySlug: 'wake' },
  '27401': { state: 'North Carolina', stateSlug: 'north-carolina', county: 'Guilford', countySlug: 'guilford' },
  '27101': { state: 'North Carolina', stateSlug: 'north-carolina', county: 'Forsyth', countySlug: 'forsyth' },
  '37201': { state: 'Tennessee', stateSlug: 'tennessee', county: 'Davidson', countySlug: 'davidson' },
  '37203': { state: 'Tennessee', stateSlug: 'tennessee', county: 'Davidson', countySlug: 'davidson' },
  '37027': { state: 'Tennessee', stateSlug: 'tennessee', county: 'Williamson', countySlug: 'williamson' },
  '37064': { state: 'Tennessee', stateSlug: 'tennessee', county: 'Williamson', countySlug: 'williamson' },
  '37129': { state: 'Tennessee', stateSlug: 'tennessee', county: 'Rutherford', countySlug: 'rutherford' },
  '37902': { state: 'Tennessee', stateSlug: 'tennessee', county: 'Knox', countySlug: 'knox' },
  '37934': { state: 'Tennessee', stateSlug: 'tennessee', county: 'Knox', countySlug: 'knox' },
  '37804': { state: 'Tennessee', stateSlug: 'tennessee', county: 'Blount', countySlug: 'blount' },
  '37862': { state: 'Tennessee', stateSlug: 'tennessee', county: 'Sevier', countySlug: 'sevier' },
  '37738': { state: 'Tennessee', stateSlug: 'tennessee', county: 'Sevier', countySlug: 'sevier' },
  '85001': { state: 'Arizona', stateSlug: 'arizona', county: 'Maricopa', countySlug: 'maricopa' },
  '85326': { state: 'Arizona', stateSlug: 'arizona', county: 'Maricopa', countySlug: 'maricopa' },
  '85396': { state: 'Arizona', stateSlug: 'arizona', county: 'Maricopa', countySlug: 'maricopa' },
  '85338': { state: 'Arizona', stateSlug: 'arizona', county: 'Maricopa', countySlug: 'maricopa' },
  '85395': { state: 'Arizona', stateSlug: 'arizona', county: 'Maricopa', countySlug: 'maricopa' },
  '85142': { state: 'Arizona', stateSlug: 'arizona', county: 'Maricopa', countySlug: 'maricopa' },
  '85143': { state: 'Arizona', stateSlug: 'arizona', county: 'Maricopa', countySlug: 'maricopa' },
  '85140': { state: 'Arizona', stateSlug: 'arizona', county: 'Pinal', countySlug: 'pinal' },
  '95110': { state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara' },
  '95113': { state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara' },
  '95014': { state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara' },
  '95050': { state: 'California', stateSlug: 'california', county: 'Santa Clara', countySlug: 'santa-clara' },
  '92501': { state: 'California', stateSlug: 'california', county: 'Riverside', countySlug: 'riverside' },
  '92503': { state: 'California', stateSlug: 'california', county: 'Riverside', countySlug: 'riverside' },
  '92551': { state: 'California', stateSlug: 'california', county: 'Riverside', countySlug: 'riverside' },
  '92553': { state: 'California', stateSlug: 'california', county: 'Riverside', countySlug: 'riverside' },
  '93611': { state: 'California', stateSlug: 'california', county: 'Fresno', countySlug: 'fresno' },
  '93612': { state: 'California', stateSlug: 'california', county: 'Fresno', countySlug: 'fresno' },
  '93710': { state: 'California', stateSlug: 'california', county: 'Fresno', countySlug: 'fresno' },
  '93301': { state: 'California', stateSlug: 'california', county: 'Kern', countySlug: 'kern' },
  '93309': { state: 'California', stateSlug: 'california', county: 'Kern', countySlug: 'kern' },
  '98101': { state: 'Washington', stateSlug: 'washington', county: 'King', countySlug: 'king' },
  '98036': { state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish' },
  '98037': { state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish' },
  '98201': { state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish' },
  '98203': { state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish' },
  '98208': { state: 'Washington', stateSlug: 'washington', county: 'Snohomish', countySlug: 'snohomish' },
  '98403': { state: 'Washington', stateSlug: 'washington', county: 'Pierce', countySlug: 'pierce' },
  '98405': { state: 'Washington', stateSlug: 'washington', county: 'Pierce', countySlug: 'pierce' },
  '98418': { state: 'Washington', stateSlug: 'washington', county: 'Pierce', countySlug: 'pierce' },
  '98373': { state: 'Washington', stateSlug: 'washington', county: 'Pierce', countySlug: 'pierce' },
  '98374': { state: 'Washington', stateSlug: 'washington', county: 'Pierce', countySlug: 'pierce' },
  '98660': { state: 'Washington', stateSlug: 'washington', county: 'Clark', countySlug: 'clark' },
  '98661': { state: 'Washington', stateSlug: 'washington', county: 'Clark', countySlug: 'clark' },
  '98662': { state: 'Washington', stateSlug: 'washington', county: 'Clark', countySlug: 'clark' },
  '98663': { state: 'Washington', stateSlug: 'washington', county: 'Clark', countySlug: 'clark' },
  '98664': { state: 'Washington', stateSlug: 'washington', county: 'Clark', countySlug: 'clark' },
  '20001': { state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia' },
  '20005': { state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia' },
  '20009': { state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia' },
  '20012': { state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia' },
  '20011': { state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia' },
  '20017': { state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia' },
  '20003': { state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia' },
  '20018': { state: 'District of Columbia', stateSlug: 'district-of-columbia', county: 'District of Columbia', countySlug: 'district-of-columbia' },
  '01608': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester' },
  '01609': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester' },
  '01610': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester' },
  '01602': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester' },
  '01604': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Worcester', countySlug: 'worcester' },
  '02138': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex' },
  '02139': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex' },
  '02140': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex' },
  '02141': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex' },
  '02142': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex' },
  '02143': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex' },
  '02144': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex' },
  '02145': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex' },
  '02128': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk' },
  '02129': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk' },
  '02121': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk' },
  '02122': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk' },
  '02124': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk' },
  '02125': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk' },
  '02130': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk' },
  '02151': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Suffolk', countySlug: 'suffolk' },
  '02148': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex' },
  '01852': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex' },
  '01901': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Essex', countySlug: 'essex' },
  '01902': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Essex', countySlug: 'essex' },
  '01904': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Essex', countySlug: 'essex' },
  '01701': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex' },
  '01702': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex' },
  '01749': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex' },
  '01760': { state: 'Massachusetts', stateSlug: 'massachusetts', county: 'Middlesex', countySlug: 'middlesex' },
  '14201': { state: 'New York', stateSlug: 'new-york', county: 'Erie', countySlug: 'erie' },
  '14202': { state: 'New York', stateSlug: 'new-york', county: 'Erie', countySlug: 'erie' },
  '14203': { state: 'New York', stateSlug: 'new-york', county: 'Erie', countySlug: 'erie' },
  '14214': { state: 'New York', stateSlug: 'new-york', county: 'Erie', countySlug: 'erie' },
  '14216': { state: 'New York', stateSlug: 'new-york', county: 'Erie', countySlug: 'erie' },
  '14220': { state: 'New York', stateSlug: 'new-york', county: 'Erie', countySlug: 'erie' },
  '12203': { state: 'New York', stateSlug: 'new-york', county: 'Albany', countySlug: 'albany' },
  '12205': { state: 'New York', stateSlug: 'new-york', county: 'Albany', countySlug: 'albany' },
  '12208': { state: 'New York', stateSlug: 'new-york', county: 'Albany', countySlug: 'albany' },
  '12210': { state: 'New York', stateSlug: 'new-york', county: 'Albany', countySlug: 'albany' },
  '10601': { state: 'New York', stateSlug: 'new-york', county: 'Westchester', countySlug: 'westchester' },
  '10605': { state: 'New York', stateSlug: 'new-york', county: 'Westchester', countySlug: 'westchester' },
  '10801': { state: 'New York', stateSlug: 'new-york', county: 'Westchester', countySlug: 'westchester' },
  '10805': { state: 'New York', stateSlug: 'new-york', county: 'Westchester', countySlug: 'westchester' },
  '10512': { state: 'New York', stateSlug: 'new-york', county: 'Putnam', countySlug: 'putnam' },
  '10509': { state: 'New York', stateSlug: 'new-york', county: 'Putnam', countySlug: 'putnam' },
  '11201': { state: 'New York', stateSlug: 'new-york', county: 'Kings', countySlug: 'kings' },
  '11215': { state: 'New York', stateSlug: 'new-york', county: 'Kings', countySlug: 'kings' },
  '11234': { state: 'New York', stateSlug: 'new-york', county: 'Kings', countySlug: 'kings' },
  '11101': { state: 'New York', stateSlug: 'new-york', county: 'Queens', countySlug: 'queens' },
  '11106': { state: 'New York', stateSlug: 'new-york', county: 'Queens', countySlug: 'queens' },
  '11354': { state: 'New York', stateSlug: 'new-york', county: 'Queens', countySlug: 'queens' },
  '10014': { state: 'New York', stateSlug: 'new-york', county: 'New York', countySlug: 'new-york-county' },
  '10021': { state: 'New York', stateSlug: 'new-york', county: 'New York', countySlug: 'new-york-county' },
  '19102': { state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Philadelphia', countySlug: 'philadelphia' },
  '19103': { state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Philadelphia', countySlug: 'philadelphia' },
  '19107': { state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Philadelphia', countySlug: 'philadelphia' },
  '19406': { state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Montgomery', countySlug: 'montgomery' },
  '19380': { state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Chester', countySlug: 'chester' },
  '18940': { state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Bucks', countySlug: 'bucks' },
  '15222': { state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Allegheny', countySlug: 'allegheny' },
  '15005': { state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Beaver', countySlug: 'beaver' },
  '17101': { state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Dauphin', countySlug: 'dauphin' },
  '18101': { state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'Lehigh', countySlug: 'lehigh' },
  '17368': { state: 'Pennsylvania', stateSlug: 'pennsylvania', county: 'York', countySlug: 'york' },
  '80201': { state: 'Colorado', stateSlug: 'colorado', county: 'Denver', countySlug: 'denver' },
  '80516': { state: 'Colorado', stateSlug: 'colorado', county: 'Adams', countySlug: 'adams' },
  '80026': { state: 'Colorado', stateSlug: 'colorado', county: 'Boulder', countySlug: 'boulder' },
  '80027': { state: 'Colorado', stateSlug: 'colorado', county: 'Boulder', countySlug: 'boulder' },
  '80134': { state: 'Colorado', stateSlug: 'colorado', county: 'Douglas', countySlug: 'douglas' },
  '80112': { state: 'Colorado', stateSlug: 'colorado', county: 'Douglas', countySlug: 'douglas' },
  '80903': { state: 'Colorado', stateSlug: 'colorado', county: 'El Paso', countySlug: 'el-paso' },
  '80920': { state: 'Colorado', stateSlug: 'colorado', county: 'El Paso', countySlug: 'el-paso' },
  '80817': { state: 'Colorado', stateSlug: 'colorado', county: 'El Paso', countySlug: 'el-paso' },
  '80831': { state: 'Colorado', stateSlug: 'colorado', county: 'El Paso', countySlug: 'el-paso' },
  '80439': { state: 'Colorado', stateSlug: 'colorado', county: 'Jefferson', countySlug: 'jefferson' },
  '80401': { state: 'Colorado', stateSlug: 'colorado', county: 'Jefferson', countySlug: 'jefferson' },
  '80433': { state: 'Colorado', stateSlug: 'colorado', county: 'Jefferson', countySlug: 'jefferson' },
  '80487': { state: 'Colorado', stateSlug: 'colorado', county: 'Routt', countySlug: 'routt' },
  '08053': { state: 'New Jersey', stateSlug: 'new-jersey', county: 'Burlington', countySlug: 'burlington' },
  '07470': { state: 'New Jersey', stateSlug: 'new-jersey', county: 'Passaic', countySlug: 'passaic' },
  '08260': { state: 'New Jersey', stateSlug: 'new-jersey', county: 'Cape May', countySlug: 'cape-may' },
  '08226': { state: 'New Jersey', stateSlug: 'new-jersey', county: 'Cape May', countySlug: 'cape-may' },
  '08406': { state: 'New Jersey', stateSlug: 'new-jersey', county: 'Cape May', countySlug: 'cape-may' },
  '07016': { state: 'New Jersey', stateSlug: 'new-jersey', county: 'Union', countySlug: 'union' },
  '07065': { state: 'New Jersey', stateSlug: 'new-jersey', county: 'Union', countySlug: 'union' },
  '08817': { state: 'New Jersey', stateSlug: 'new-jersey', county: 'Middlesex', countySlug: 'middlesex' },
  '08901': { state: 'New Jersey', stateSlug: 'new-jersey', county: 'Middlesex', countySlug: 'middlesex' },
  '07042': { state: 'New Jersey', stateSlug: 'new-jersey', county: 'Essex', countySlug: 'essex' },
  '07040': { state: 'New Jersey', stateSlug: 'new-jersey', county: 'Essex', countySlug: 'essex' },
  '07302': { state: 'New Jersey', stateSlug: 'new-jersey', county: 'Hudson', countySlug: 'hudson' },
  '07030': { state: 'New Jersey', stateSlug: 'new-jersey', county: 'Hudson', countySlug: 'hudson' },
};
