/** MI-LEND-001. Bounded, non-census Michigan evidence. No graph or claim writes. */
export const MICHIGAN_SNAPSHOT = {
  contract_name: 'lender-mi-state-intel-v1',
  path: '/michigan',
  retrieved_at: '2026-09-28T15:27:56Z',
  regulator: 'Michigan Department of Insurance and Financial Services (DIFS)',
  sources: {
    licensing: 'https://www.michigan.gov/difs/industry/licensing-cf/mortgage',
    locator: 'https://www.michigan.gov/difs/online-services',
    annualReport: 'https://www.michigan.gov/difs/-/media/Project/Websites/difs/Annual_Report/DIFS_Annual_Report_2025.pdf',
    decisions: 'https://www.michigan.gov/difs/legal/hearings-decisions/final-decisions',
    orders: 'https://www.michigan.gov/difs/legal/hearings-decisions/directors-orders',
    complaints: 'https://www.michigan.gov/difs/consumers/complaint/file-a-paper-complaint',
  },
  licensing: {
    verification: 'KNOWN', roster: 'NOT_ACQUIRED', rows: null,
    classes: ['mortgage broker', 'mortgage lender', 'mortgage servicer', 'mortgage company', 'MLO/person', 'branch', 'exempt entity'],
    note: 'DIFS licenses or registers first- and second-mortgage broker, lender, and servicer activity. The DIFS locator verifies current status; no official bulk roster/export was acquired. NMLS is identity infrastructure, not the regulator.',
    annualReportAsOf: '2025-12-31',
    annualReportGrains: { firstMortgageLicensees: 1186, firstMortgageRegistrants: 261, secondMortgageLicensees: 16, secondMortgageRegistrants: 734, mloPersons: 19025 },
  },
  hmda: {
    year: 2025, source: 'data/hmda/by-state/MI/county_market_summary.csv',
    applications: 381619, originations: 228503, denials: 69927,
    denialApplicationPct: 18.32, distinctLeis: 857, counties: 83,
    purchase: 158983, refinance: 127275, otherPurpose: 95361,
    conventional: 315341, fha: 44639, va: 20524, usdaOther: 1115,
    note: 'Michigan-property HMDA activity, not a DIFS license census or lender quality measure.',
  },
  enforcement: {
    window: ['2022-01-01', '2026-09-28'],
    scope: 'Selected, document-reviewed mortgage-related DIFS final orders; not a complete count of the decisions index.',
    rows: [
      { caseId: '22-17026', date: '2023-05-08', respondent: 'Homesite Mortgage, LLC', type: 'company', order: 'Order accepting stipulation; internal audit and fines', status: 'stipulated', law: 'MBLSLA; SMLA', licenses: ['FL-0017591', 'SR-0018833'], nmls: '136037', url: 'https://www.michigan.gov/difs/-/media/Project/Websites/difs/DO/2023/May/Homesite_Mortgage_22-17026.pdf' },
      { caseId: '24-17825', date: '2024-11-18', respondent: 'Superior Mortgage Services LLC', type: 'company', order: 'Order accepting stipulation', status: 'stipulated; some alleged violations neither admitted nor denied', law: 'MBLSLA', licenses: ['FL-0022413'], nmls: '1873323', url: 'https://www.michigan.gov/difs/-/media/Project/Websites/difs/DO/2024/November/Superior_Mortgage_24-17825.pdf' },
      { caseId: '24-17825', date: '2025-08-20', respondent: 'Superior Mortgage Services LLC', type: 'company', order: 'Order revoking license for failure to comply with consent order', status: 'final revocation', law: 'MBLSLA', licenses: ['FL-0022413'], nmls: '1873323', url: 'https://www.michigan.gov/difs/-/media/Project/Websites/difs/DO/2025/August/Superior_Mortgage_Services_24-17825.pdf' },
      { caseId: '25-18149', date: '2025-06-18', respondent: null, type: 'person', order: 'Order accepting stipulation and requiring compliance', status: 'stipulated', law: 'MLOLA', licenses: [], nmls: '112201', url: 'https://www.michigan.gov/difs/-/media/Project/Websites/difs/DO/2025/June/Glenn_Nimmo_25-18149.pdf' },
      { caseId: '25-18140', date: '2025-09-08', respondent: 'Security Mortgage Corporation', type: 'company', order: 'Order accepting stipulation and civil fine', status: 'stipulated', law: 'MBLSLA', licenses: ['FL-0108', 'SR-0024796'], nmls: '135633', url: 'https://www.michigan.gov/difs/-/media/Project/Websites/difs/DO/2025/September/Security_Mortgage_25-18140.pdf' },
      { caseId: '25-18206', date: '2025-10-06', respondent: 'Priority 1 Lending, LLC', type: 'company', order: 'Order accepting stipulation; compliance and civil fine', status: 'stipulated; allegations neither admitted nor denied', law: 'MBLSLA; SMLA; MLPA', licenses: ['FL-0019884', 'SR-0019885'], nmls: '1375378', url: 'https://www.michigan.gov/difs/-/media/Project/Websites/difs/DO/2025/October/Priority_1_Lending_25-18206.pdf' },
      { caseId: '25-18509', date: '2026-07-20', respondent: 'Ross Mortgage Corporation', type: 'company', order: 'Order accepting stipulation', status: 'stipulated; allegations neither admitted nor denied', law: 'MBLSLA; SMLA', licenses: ['FL-0022828', 'SR-0205'], nmls: '107716', url: 'https://www.michigan.gov/difs/-/media/Project/Websites/difs/DO/2026/July/Ross_Mortgage_Corporation_25-18509.pdf' },
      { caseId: '26-19168', date: '2026-08-12', respondent: 'Taxes and Loans Inc.', type: 'company', order: 'Order accepting stipulation', status: 'stipulated; allegations neither admitted nor denied', law: 'MBLSLA', licenses: ['FL-0023309'], nmls: '2084643', url: 'https://www.michigan.gov/difs/-/media/Project/Websites/difs/DO/2026/August/Taxes_and_Loans_Inc_26-19168.pdf' },
    ],
    nameOnlyAttachments: 0,
    existingCanonicalAttachments: 0,
    note: 'Printed NMLS and Michigan license IDs identify the order respondent only. No adverse event is attached to an existing hub identity without an independently verified exact identifier match.',
  },
  complaints: { intake: 'KNOWN', providerRows: 'NOT_ACQUIRED', outcomes: 'REQUEST_ONLY' },
  graph: { netNewCanonicalOrganizations: 0, writes: 0, claimEligibilityChanged: false },
} as const;
