/** LA-LEND-001: OFI originator-under-lender row items, null class counts, accepted HMDA 2025 property activity. */
export const LOUISIANA_SNAPSHOT = {
  path: '/louisiana',
  generatedAt: '2026-10-05T13:17:22Z',
  retrievedAt: '2026-10-05',
  regulator: 'Louisiana Office of Financial Institutions, Residential Mortgage Lending',
  sources: {
    licensing: 'https://ofi.la.gov/non-depository/residential-mortgage-lending/',
    originatorsByLender: 'https://ofi.la.gov/non-depository/residential-mortgage-lending/originators/',
    originatorsByLenderAlias: 'https://ofi.la.gov/non-depository/residential-mortgage-lending/originators-by-lender/',
    licenseesWithExamDates: 'https://ofi.la.gov/non-depository/residential-mortgage-lending/licensees-w-exam-dates/',
    fees: 'https://ofi.la.gov/non-depository/residential-mortgage-lending/fees/',
    nmls: 'https://nmlsconsumeraccess.org/',
    complaints: 'https://ofi.la.gov/non-depository/residential-mortgage-lending/complaints/',
    administrativeActions: 'https://ofi.la.gov/non-depository/residential-mortgage-lending/administrative-actions/',
  },
  licensing: {
    verification: 'KNOWN',
    nmlsBulkRoster: 'NOT_ACQUIRED',
    originatorUnderLenderRowItems: 9812,
    originatorUnderLenderClock: 'October 05, 2026 at 06:26 AM',
    originatorUnderLenderGrain: 'ROW_ITEMS',
    distinctCompanies: null,
    distinctPersons: null,
    combinedLenderTotal: null,
    classCounts: null,
    lenderCount: null,
    brokerCount: null,
    branchCount: null,
    servicerCount: null,
    rowsWithPrintedNmls: null,
    distinctNmls: null,
    exactExistingCanonicalMatches: null,
    unmatchedRows: null,
    licenseeExamTable: {
      adoptedAsClassCount: false,
      printedItems: 920,
      clock: 'October 05, 2026 at 06:26 AM',
      classColumn: false,
    },
  },
  hmda: {
    year: 2025, source: 'data/hmda/by-state/LA/county_market_summary.csv',
    applications: 132458, originations: 69035, denials: 29012, denialApplicationPct: 21.9,
    distinctLeis: 605, counties: 64,
    purchase: 73405, refinance: 39371, otherPurpose: 19682,
    conventional: 90502, fha: 25739, va: 12560, usdaOther: 3657,
  },
  enforcement: {
    corpus: 'NOT_ACQUIRED',
    exactCanonicalAttachments: 0,
    nameOnlyAdverseJoins: 0,
    scope: 'No bounded OFI residential-mortgage enforcement corpus was acquired. Missing orders are not zero orders.',
  },
  complaints: { intake: 'KNOWN', providerRows: 'NOT_ACQUIRED', outcomes: 'REQUEST_ONLY/NOT_ACQUIRED' },
  newCanonicalOrganizations: 0, graphWrites: 0, claimEligibilityChanges: 0,
} as const;
