/** IN-LEND-001: split Indiana regulators (DFI mortgage lenders vs Securities Division loan brokers), accepted HMDA 2025. */
// Counts are literals verified against ./evidence.json by scripts/assert-in-lend-001.mts (keeps the roster out of client bundles).
export const INDIANA_SNAPSHOT = {
  contract_name: 'lender-in-state-intel-v1',
  path: '/indiana',
  generatedAt: '2026-09-29T19:20:00Z',
  evidenceFingerprint: '457d96fd39db234bf79e2425df00a9ba88f705d21d910185c4a43cd2f2cec903',
  sources: {
    dfiListing: 'https://extranet.dfi.in.gov/ConsumerCredit/CompanyListing/13?handler=CompaniesInLicenseType',
    dfiDivision: 'https://www.in.gov/dfi/general-information/consumer-credit-division',
    dfiLicensing: 'https://www.in.gov/dfi/licensing-and-applications/consumer-credit-licensing',
    dfiMloFaq: 'https://www.in.gov/dfi/licensing-and-applications/consumer-credit-licensing/mlo-faq',
    dfiComplaints: 'https://www.in.gov/dfi/file-a-complaint',
    sosLoanBrokers: 'https://securities.sos.in.gov/loan-brokers/',
    sosRegistrationSearch: 'https://securities.sos.in.gov/public-portfolio-search/',
    sosAdminActions: 'https://lcm.securities.sos.in.gov/admin-actions-search',
    sosComplaints: 'https://lcm.securities.sos.in.gov/file-a-complaint',
    nmls: 'https://www.nmlsconsumeraccess.org/',
    newrez: 'https://www.csbs.org/sites/default/files/external-link-files/NewRez%20Final%20Agreement%20with%20attachments%20-%20redacted.pdf',
  },
  dfi: {
    regulator: 'Indiana Department of Financial Institutions, Consumer Credit Division',
    roster: 'ACQUIRED',
    rosterClock: { retrievedAt: '2026-09-29T19:01:27Z', sourceAsOf: null },
    mortgageLenderListingRows: 490,
    mortgageLenderActiveLicenses: 489,
    indianaAddressed: 23,
    rowsWithPrintedNmls: 0,
    distinctPrintedNmls: 0,
    exactNmlsBridges: 0,
    unmatchedRows: 489,
    mloPersonRoster: 'NOT_ACQUIRED',
    servicerClass: 'The DFI licensee listing has no separate mortgage-servicer class; Subordinate Lien Mortgage Lending appears only as terminated history on lender detail pages.',
    examinationCapability: 'KNOWN',
    providerExamRows: 'NOT_ACQUIRED',
    enforcementOrderIndex: 'NOT_ACQUIRED',
  },
  sos: {
    regulator: 'Indiana Secretary of State, Securities Division',
    loanBrokerRoster: 'NOT_ACQUIRED',
    branchRoster: 'NOT_ACQUIRED',
    mloPersonRoster: 'NOT_ACQUIRED',
    verification: 'KNOWN',
    examinationCapability: 'KNOWN',
    providerExamRows: 'NOT_ACQUIRED',
  },
  hmda: {
    year: 2025, source: 'data/hmda/by-state/IN/county_market_summary.csv',
    applications: 285688, originations: 177798, denials: 46696, denialApplicationPct: 16.35,
    distinctLeis: 907, counties: 92,
    purchase: 122902, refinance: 99009, otherPurpose: 63777,
    conventional: 217545, fha: 45715, va: 19974, usdaOther: 2454,
  },
  loanBrokerEnforcement: {
    indexRows: 1747,
    taggedLoanBroker2022to2026: 14,
    taggedButSecuritiesActOnly: 2,
    loanBrokerActRows: 12,
    rowsWithPrintedCompanyNmls: 12,
    exactExistingResearchIdentities: 7,
    publicProfileAdverseAttachments: 0,
    nameOnlyAdverseJoins: 0,
    individualRespondentsWithheld: 1,
    retrievedAt: '2026-09-29T19:05:36Z',
  },
  dfiEnforcement: {
    dfiOrderRows: 'NOT_ACQUIRED',
    multistateRows: 1,
    exactCanonicalAttachments: 0,
    nameOnlyAdverseJoins: 0,
  },
  complaints: { dfiIntake: 'KNOWN', sosIntake: 'KNOWN', providerRows: 'NOT_ACQUIRED', outcomes: 'REQUEST_ONLY/NOT_ACQUIRED' },
  newCanonicalOrganizations: 0, graphWrites: 0, claimEligibilityChanges: 0,
} as const;
