export {
  HMDA_VINTAGE_YEAR,
  HMDA_SOURCE_LABEL,
  HMDA_SOURCE_NOTE,
  type HmdaLenderEvidence,
  type HmdaCountyEvidence,
  type HmdaLoanTypeMix,
  type HmdaLeiMapping,
  type HmdaLenderStateSummary,
  type HmdaLenderCountyActivity,
  type HmdaCountyMarketSummary,
  type HmdaLenderStateSlice,
} from './types';

export {
  hmdaDataAvailable,
  loadHmdaFloridaData,
  loadHmdaStateData,
  loadAllHmdaStateData,
  countyNameToSlug,
  type HmdaStateBundle,
} from './load';

export {
  HMDA_STATE_CONFIGS,
  HMDA_ACTIVE_STATE_CODES,
  hmdaStateFromSlug,
  type HmdaStateCode,
  type HmdaStateConfig,
} from './states';

export {
  getHmdaLenderEvidenceBySlug,
  getHmdaCountyEvidence,
  getMatchedHmdaSlugs,
  getHmdaCountySlugsForState,
  getHmdaProductStates,
  MAJOR_FLORIDA_COUNTY_SLUGS,
  MAJOR_TEXAS_COUNTY_SLUGS,
  MAJOR_GEORGIA_COUNTY_SLUGS,
  MAJOR_CALIFORNIA_COUNTY_SLUGS,
  MAJOR_NORTH_CAROLINA_COUNTY_SLUGS,
  MAJOR_SOUTH_CAROLINA_COUNTY_SLUGS,
  MAJOR_NEW_JERSEY_COUNTY_SLUGS,
  MAJOR_NEW_YORK_COUNTY_SLUGS,
  MAJOR_PENNSYLVANIA_COUNTY_SLUGS,
  MAJOR_MASSACHUSETTS_COUNTY_SLUGS,
  MAJOR_RHODE_ISLAND_COUNTY_SLUGS,
  MAJOR_VERMONT_COUNTY_SLUGS,
  MAJOR_MAINE_COUNTY_SLUGS,
  MAJOR_CONNECTICUT_COUNTY_SLUGS,
  MAJOR_NEW_HAMPSHIRE_COUNTY_SLUGS,
  MAJOR_VIRGINIA_COUNTY_SLUGS,
  MAJOR_MARYLAND_COUNTY_SLUGS,
  MAJOR_DELAWARE_COUNTY_SLUGS,
  MAJOR_DISTRICT_OF_COLUMBIA_COUNTY_SLUGS,
  MAJOR_TENNESSEE_COUNTY_SLUGS,
  MAJOR_ILLINOIS_COUNTY_SLUGS,
  MAJOR_OHIO_COUNTY_SLUGS,
  MAJOR_MICHIGAN_COUNTY_SLUGS,
  MAJOR_INDIANA_COUNTY_SLUGS,
} from './queries';
