/** HMDA product states with cleaned slices under data/hmda/{folder}/ */

export type HmdaStateCode =
  | 'FL'
  | 'TX'
  | 'GA'
  | 'CA'
  | 'NC'
  | 'SC'
  | 'NJ'
  | 'NY'
  | 'PA'
  | 'MA';

export type HmdaStateConfig = {
  code: HmdaStateCode;
  /** Directory / URL state slug */
  stateSlug: string;
  name: string;
  /** data/hmda/{dataFolder}/ */
  dataFolder: string;
  /** File name suffixes (e.g. _fl, _tx, _ny, _pa, _ma) for summary CSVs */
  fileSuffix: string;
  /** Mapping CSV column for state originations */
  originationsColumn:
    | 'florida_originations'
    | 'texas_originations'
    | 'georgia_originations'
    | 'california_originations'
    | 'north_carolina_originations'
    | 'south_carolina_originations'
    | 'new_jersey_originations'
    | 'new_york_originations'
    | 'pennsylvania_originations'
    | 'massachusetts_originations';
  /** Major county slugs for market intelligence panels */
  majorCountySlugs: ReadonlySet<string>;
};

export const HMDA_STATE_CONFIGS: Record<HmdaStateCode, HmdaStateConfig> = {
  FL: {
    code: 'FL',
    stateSlug: 'florida',
    name: 'Florida',
    dataFolder: 'florida',
    fileSuffix: '_fl',
    originationsColumn: 'florida_originations',
    majorCountySlugs: new Set([
      'miami-dade',
      'broward',
      'palm-beach',
      'hillsborough',
      'orange',
      'duval',
      'pinellas',
      'lee',
      'polk',
      'brevard',
      'volusia',
      'pasco',
      'seminole',
      'sarasota',
      'manatee',
      'collier',
      'osceola',
      'lake',
      'marion',
      'st-johns',
      'st-lucie',
    ]),
  },
  TX: {
    code: 'TX',
    stateSlug: 'texas',
    name: 'Texas',
    dataFolder: 'texas',
    fileSuffix: '_tx',
    originationsColumn: 'texas_originations',
    majorCountySlugs: new Set([
      'harris',
      'dallas',
      'tarrant',
      'bexar',
      'collin',
      'travis',
      'denton',
      'montgomery',
      'fort-bend',
      'williamson',
      'el-paso',
      'bell',
      'hidalgo',
      'brazoria',
      'galveston',
      'hays',
      'lubbock',
      'nueces',
      'cameron',
      'webb',
    ]),
  },
  GA: {
    code: 'GA',
    stateSlug: 'georgia',
    name: 'Georgia',
    dataFolder: 'georgia',
    fileSuffix: '_ga',
    originationsColumn: 'georgia_originations',
    majorCountySlugs: new Set([
      // Core metro Atlanta
      'fulton',
      'gwinnett',
      'cobb',
      'dekalb',
      'cherokee',
      'forsyth',
      'henry',
      'paulding',
      'clayton',
      'douglas',
      'coweta',
      'fayette',
      'bartow',
      'jackson',
      'carroll',
      'barrow',
      'newton',
      'walton',
      'rockdale',
      // Secondary / regional metros
      'chatham',
      'effingham',
      'bryan',
      'glynn',
      'hall',
      'houston',
      'columbia',
      'richmond',
      'muscogee',
      'bibb',
      'lowndes',
      'floyd',
      'clarke',
      'catoosa',
      'whitfield',
      'spalding',
    ]),
  },
  CA: {
    code: 'CA',
    stateSlug: 'california',
    name: 'California',
    dataFolder: 'california',
    fileSuffix: '_ca',
    originationsColumn: 'california_originations',
    majorCountySlugs: new Set([
      // Wave 1 metros
      'los-angeles',
      'san-diego',
      'riverside',
      'orange',
      'san-bernardino',
      'sacramento',
      'santa-clara',
      'alameda',
      'contra-costa',
      'kern',
      'fresno',
      'san-joaquin',
      'ventura',
      'placer',
      'san-mateo',
      'solano',
      'san-francisco',
      'sonoma',
      'stanislaus',
      'tulare',
      'santa-barbara',
      'san-luis-obispo',
      'monterey',
      'marin',
      // Deepen — SoCal spillover, Central Valley, NorCal growth
      'el-dorado',
      'merced',
      'shasta',
      'butte',
      'madera',
      'santa-cruz',
      'yolo',
      'nevada',
      'kings',
      'napa',
      'imperial',
      'humboldt',
    ]),
  },
  NC: {
    code: 'NC',
    stateSlug: 'north-carolina',
    name: 'North Carolina',
    dataFolder: 'north-carolina',
    fileSuffix: '_nc',
    originationsColumn: 'north_carolina_originations',
    majorCountySlugs: new Set([
      'wake',
      'mecklenburg',
      'guilford',
      'forsyth',
      'durham',
      'cumberland',
      'union',
      'brunswick',
      'johnston',
      'cabarrus',
      'onslow',
      'gaston',
      'new-hanover',
      'iredell',
      'buncombe',
      'harnett',
      'catawba',
      'alamance',
      'davidson',
      'rowan',
      'pitt',
      'moore',
      'randolph',
      'henderson',
      'craven',
      'lincoln',
      'orange',
      'wayne',
      'pender',
      'franklin',
    ]),
  },
  SC: {
    code: 'SC',
    stateSlug: 'south-carolina',
    name: 'South Carolina',
    dataFolder: 'south-carolina',
    fileSuffix: '_sc',
    originationsColumn: 'south_carolina_originations',
    majorCountySlugs: new Set([
      // Wave 1
      'horry',
      'greenville',
      'charleston',
      'spartanburg',
      'richland',
      'berkeley',
      'york',
      'lexington',
      'beaufort',
      'dorchester',
      'anderson',
      'aiken',
      'lancaster',
      'sumter',
      'florence',
      'pickens',
      'kershaw',
      'laurens',
      'jasper',
      'georgetown',
      // Deepen
      'oconee',
      'orangeburg',
      'greenwood',
      'cherokee',
      'darlington',
      'chester',
      'colleton',
      'chesterfield',
      'edgefield',
      'newberry',
    ]),
  },
  NJ: {
    code: 'NJ',
    stateSlug: 'new-jersey',
    name: 'New Jersey',
    dataFolder: 'new-jersey',
    fileSuffix: '_nj',
    originationsColumn: 'new_jersey_originations',
    majorCountySlugs: new Set([
      'ocean',
      'bergen',
      'monmouth',
      'middlesex',
      'burlington',
      'camden',
      'essex',
      'morris',
      'union',
      'gloucester',
      'mercer',
      'hudson',
      'passaic',
      'somerset',
      'atlantic',
      'cape-may',
      'sussex',
      'hunterdon',
      // Deepen — full NJ extract
      'cumberland',
      'warren',
      'salem',
    ]),
  },
  NY: {
    code: 'NY',
    stateSlug: 'new-york',
    name: 'New York',
    dataFolder: 'new-york',
    fileSuffix: '_ny',
    originationsColumn: 'new_york_originations',
    majorCountySlugs: new Set([
      // Wave 1 — highest volume + metros
      'suffolk',
      'nassau',
      'erie',
      'monroe',
      'queens',
      'kings',
      'westchester',
      'onondaga',
      'new-york-county', // Manhattan (directory slug; HMDA name is "New York")
      'orange',
      'albany',
      'richmond',
      'dutchess',
      'saratoga',
      'rockland',
      'bronx',
      'niagara',
      'oneida',
      'schenectady',
      'rensselaer',
      'ulster',
      'broome',
      // Deepen — Hudson Valley / downstate spillover
      'putnam',
      'sullivan',
      'columbia',
      'greene',
      // Deepen — Finger Lakes / Central / North Country / Southern Tier
      'ontario',
      'oswego',
      'wayne',
      'jefferson',
      'steuben',
      'chautauqua',
      'chemung',
      'warren',
      'madison',
      'cayuga',
      'tompkins',
      'livingston',
      'herkimer',
      'washington',
      'genesee',
      'st-lawrence',
      'fulton',
      'clinton',
      'cattaraugus',
      'montgomery',
      'tioga',
      'otsego',
    ]),
  },
  PA: {
    code: 'PA',
    stateSlug: 'pennsylvania',
    name: 'Pennsylvania',
    dataFolder: 'pennsylvania',
    fileSuffix: '_pa',
    originationsColumn: 'pennsylvania_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Philly / Pittsburgh / mid-state
      'philadelphia',
      'montgomery',
      'bucks',
      'delaware',
      'chester',
      'allegheny',
      'westmoreland',
      'butler',
      'washington',
      'beaver',
      'lancaster',
      'york',
      'berks',
      'lehigh',
      'northampton',
      'dauphin',
      'cumberland',
      'lebanon',
      'lackawanna',
      'luzerne',
      'erie',
      'monroe',
      'franklin',
      'centre',
      'fayette',
      'adams',
      'cambria',
      'lycoming',
      'schuylkill',
      'mercer',
      // Deepen — next volume / regional
      'blair',
      'pike',
      'carbon',
      'lawrence',
      'northumberland',
      'clearfield',
      'wayne',
      'somerset',
      'crawford',
      'indiana',
      'columbia',
      'armstrong',
      'perry',
      'bedford',
    ]),
  },
  MA: {
    code: 'MA',
    stateSlug: 'massachusetts',
    name: 'Massachusetts',
    dataFolder: 'massachusetts',
    fileSuffix: '_ma',
    originationsColumn: 'massachusetts_originations',
    majorCountySlugs: new Set([
      // Wave 1 — highest volume metros
      'middlesex',
      'worcester',
      'essex',
      'norfolk',
      'plymouth',
      'bristol',
      'suffolk',
      'hampden',
      'barnstable',
      'berkshire',
      'hampshire',
      'franklin',
      // Deepen — remaining counties (full state)
      'dukes',
      'nantucket',
    ]),
  },
};

export const HMDA_ACTIVE_STATE_CODES: HmdaStateCode[] = [
  'FL',
  'TX',
  'GA',
  'CA',
  'NC',
  'SC',
  'NJ',
  'NY',
  'PA',
  'MA',
];

export function hmdaStateFromSlug(stateSlug: string): HmdaStateConfig | null {
  const s = stateSlug.toLowerCase();
  for (const cfg of Object.values(HMDA_STATE_CONFIGS)) {
    if (cfg.stateSlug === s || cfg.code.toLowerCase() === s) return cfg;
  }
  return null;
}
