/** HMDA product states with cleaned slices under data/hmda/{folder}/ */

export type HmdaStateCode =
  | 'FL'
  | 'TX'
  | 'GA'
  | 'CA'
  | 'NC'
  | 'SC'
  | 'NJ'
  | 'NY'
  | 'PA'
  | 'MA'
  | 'RI'
  | 'VT'
  | 'ME'
  | 'CT'
  | 'NH'
  | 'VA'
  | 'MD'
  | 'DE'
  | 'DC';

export type HmdaStateConfig = {
  code: HmdaStateCode;
  /** Directory / URL state slug */
  stateSlug: string;
  name: string;
  /** data/hmda/{dataFolder}/ */
  dataFolder: string;
  /** File name suffixes (e.g. _fl, _va, _md) for summary CSVs */
  fileSuffix: string;
  /** Mapping CSV column for state originations */
  originationsColumn:
    | 'florida_originations'
    | 'texas_originations'
    | 'georgia_originations'
    | 'california_originations'
    | 'north_carolina_originations'
    | 'south_carolina_originations'
    | 'new_jersey_originations'
    | 'new_york_originations'
    | 'pennsylvania_originations'
    | 'massachusetts_originations'
    | 'rhode_island_originations'
    | 'vermont_originations'
    | 'maine_originations'
    | 'connecticut_originations'
    | 'new_hampshire_originations'
    | 'virginia_originations'
    | 'maryland_originations'
    | 'delaware_originations'
    | 'district_of_columbia_originations';
  /** Major county slugs for market intelligence panels */
  majorCountySlugs: ReadonlySet<string>;
};

export const HMDA_STATE_CONFIGS: Record<HmdaStateCode, HmdaStateConfig> = {
  FL: {
    code: 'FL',
    stateSlug: 'florida',
    name: 'Florida',
    dataFolder: 'florida',
    fileSuffix: '_fl',
    originationsColumn: 'florida_originations',
    majorCountySlugs: new Set([
      'miami-dade',
      'broward',
      'palm-beach',
      'hillsborough',
      'orange',
      'duval',
      'pinellas',
      'lee',
      'polk',
      'brevard',
      'volusia',
      'pasco',
      'seminole',
      'sarasota',
      'manatee',
      'collier',
      'osceola',
      'lake',
      'marion',
      'st-johns',
      'st-lucie',
    ]),
  },
  TX: {
    code: 'TX',
    stateSlug: 'texas',
    name: 'Texas',
    dataFolder: 'texas',
    fileSuffix: '_tx',
    originationsColumn: 'texas_originations',
    majorCountySlugs: new Set([
      'harris',
      'dallas',
      'tarrant',
      'bexar',
      'collin',
      'travis',
      'denton',
      'montgomery',
      'fort-bend',
      'williamson',
      'el-paso',
      'bell',
      'hidalgo',
      'brazoria',
      'galveston',
      'hays',
      'lubbock',
      'nueces',
      'cameron',
      'webb',
    ]),
  },
  GA: {
    code: 'GA',
    stateSlug: 'georgia',
    name: 'Georgia',
    dataFolder: 'georgia',
    fileSuffix: '_ga',
    originationsColumn: 'georgia_originations',
    majorCountySlugs: new Set([
      // Core metro Atlanta
      'fulton',
      'gwinnett',
      'cobb',
      'dekalb',
      'cherokee',
      'forsyth',
      'henry',
      'paulding',
      'clayton',
      'douglas',
      'coweta',
      'fayette',
      'bartow',
      'jackson',
      'carroll',
      'barrow',
      'newton',
      'walton',
      'rockdale',
      // Secondary / regional metros
      'chatham',
      'effingham',
      'bryan',
      'glynn',
      'hall',
      'houston',
      'columbia',
      'richmond',
      'muscogee',
      'bibb',
      'lowndes',
      'floyd',
      'clarke',
      'catoosa',
      'whitfield',
      'spalding',
    ]),
  },
  CA: {
    code: 'CA',
    stateSlug: 'california',
    name: 'California',
    dataFolder: 'california',
    fileSuffix: '_ca',
    originationsColumn: 'california_originations',
    majorCountySlugs: new Set([
      // Wave 1 metros
      'los-angeles',
      'san-diego',
      'riverside',
      'orange',
      'san-bernardino',
      'sacramento',
      'santa-clara',
      'alameda',
      'contra-costa',
      'kern',
      'fresno',
      'san-joaquin',
      'ventura',
      'placer',
      'san-mateo',
      'solano',
      'san-francisco',
      'sonoma',
      'stanislaus',
      'tulare',
      'santa-barbara',
      'san-luis-obispo',
      'monterey',
      'marin',
      // Deepen — SoCal spillover, Central Valley, NorCal growth
      'el-dorado',
      'merced',
      'shasta',
      'butte',
      'madera',
      'santa-cruz',
      'yolo',
      'nevada',
      'kings',
      'napa',
      'imperial',
      'humboldt',
    ]),
  },
  NC: {
    code: 'NC',
    stateSlug: 'north-carolina',
    name: 'North Carolina',
    dataFolder: 'north-carolina',
    fileSuffix: '_nc',
    originationsColumn: 'north_carolina_originations',
    majorCountySlugs: new Set([
      'wake',
      'mecklenburg',
      'guilford',
      'forsyth',
      'durham',
      'cumberland',
      'union',
      'brunswick',
      'johnston',
      'cabarrus',
      'onslow',
      'gaston',
      'new-hanover',
      'iredell',
      'buncombe',
      'harnett',
      'catawba',
      'alamance',
      'davidson',
      'rowan',
      'pitt',
      'moore',
      'randolph',
      'henderson',
      'craven',
      'lincoln',
      'orange',
      'wayne',
      'pender',
      'franklin',
    ]),
  },
  SC: {
    code: 'SC',
    stateSlug: 'south-carolina',
    name: 'South Carolina',
    dataFolder: 'south-carolina',
    fileSuffix: '_sc',
    originationsColumn: 'south_carolina_originations',
    majorCountySlugs: new Set([
      // Wave 1
      'horry',
      'greenville',
      'charleston',
      'spartanburg',
      'richland',
      'berkeley',
      'york',
      'lexington',
      'beaufort',
      'dorchester',
      'anderson',
      'aiken',
      'lancaster',
      'sumter',
      'florence',
      'pickens',
      'kershaw',
      'laurens',
      'jasper',
      'georgetown',
      // Deepen
      'oconee',
      'orangeburg',
      'greenwood',
      'cherokee',
      'darlington',
      'chester',
      'colleton',
      'chesterfield',
      'edgefield',
      'newberry',
    ]),
  },
  NJ: {
    code: 'NJ',
    stateSlug: 'new-jersey',
    name: 'New Jersey',
    dataFolder: 'new-jersey',
    fileSuffix: '_nj',
    originationsColumn: 'new_jersey_originations',
    majorCountySlugs: new Set([
      'ocean',
      'bergen',
      'monmouth',
      'middlesex',
      'burlington',
      'camden',
      'essex',
      'morris',
      'union',
      'gloucester',
      'mercer',
      'hudson',
      'passaic',
      'somerset',
      'atlantic',
      'cape-may',
      'sussex',
      'hunterdon',
      // Deepen — full NJ extract
      'cumberland',
      'warren',
      'salem',
    ]),
  },
  NY: {
    code: 'NY',
    stateSlug: 'new-york',
    name: 'New York',
    dataFolder: 'new-york',
    fileSuffix: '_ny',
    originationsColumn: 'new_york_originations',
    majorCountySlugs: new Set([
      // Wave 1 — highest volume + metros
      'suffolk',
      'nassau',
      'erie',
      'monroe',
      'queens',
      'kings',
      'westchester',
      'onondaga',
      'new-york-county', // Manhattan (directory slug; HMDA name is "New York")
      'orange',
      'albany',
      'richmond',
      'dutchess',
      'saratoga',
      'rockland',
      'bronx',
      'niagara',
      'oneida',
      'schenectady',
      'rensselaer',
      'ulster',
      'broome',
      // Deepen — Hudson Valley / downstate spillover
      'putnam',
      'sullivan',
      'columbia',
      'greene',
      // Deepen — Finger Lakes / Central / North Country / Southern Tier
      'ontario',
      'oswego',
      'wayne',
      'jefferson',
      'steuben',
      'chautauqua',
      'chemung',
      'warren',
      'madison',
      'cayuga',
      'tompkins',
      'livingston',
      'herkimer',
      'washington',
      'genesee',
      'st-lawrence',
      'fulton',
      'clinton',
      'cattaraugus',
      'montgomery',
      'tioga',
      'otsego',
    ]),
  },
  PA: {
    code: 'PA',
    stateSlug: 'pennsylvania',
    name: 'Pennsylvania',
    dataFolder: 'pennsylvania',
    fileSuffix: '_pa',
    originationsColumn: 'pennsylvania_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Philly / Pittsburgh / mid-state
      'philadelphia',
      'montgomery',
      'bucks',
      'delaware',
      'chester',
      'allegheny',
      'westmoreland',
      'butler',
      'washington',
      'beaver',
      'lancaster',
      'york',
      'berks',
      'lehigh',
      'northampton',
      'dauphin',
      'cumberland',
      'lebanon',
      'lackawanna',
      'luzerne',
      'erie',
      'monroe',
      'franklin',
      'centre',
      'fayette',
      'adams',
      'cambria',
      'lycoming',
      'schuylkill',
      'mercer',
      // Deepen — next volume / regional
      'blair',
      'pike',
      'carbon',
      'lawrence',
      'northumberland',
      'clearfield',
      'wayne',
      'somerset',
      'crawford',
      'indiana',
      'columbia',
      'armstrong',
      'perry',
      'bedford',
    ]),
  },
  MA: {
    code: 'MA',
    stateSlug: 'massachusetts',
    name: 'Massachusetts',
    dataFolder: 'massachusetts',
    fileSuffix: '_ma',
    originationsColumn: 'massachusetts_originations',
    majorCountySlugs: new Set([
      // Wave 1 — highest volume metros
      'middlesex',
      'worcester',
      'essex',
      'norfolk',
      'plymouth',
      'bristol',
      'suffolk',
      'hampden',
      'barnstable',
      'berkshire',
      'hampshire',
      'franklin',
      // Deepen — remaining counties (full state)
      'dukes',
      'nantucket',
    ]),
  },
  RI: {
    code: 'RI',
    stateSlug: 'rhode-island',
    name: 'Rhode Island',
    dataFolder: 'rhode-island',
    fileSuffix: '_ri',
    originationsColumn: 'rhode_island_originations',
    majorCountySlugs: new Set([
      'providence',
      'kent',
      'washington',
      'newport',
      'bristol',
    ]),
  },
  VT: {
    code: 'VT',
    stateSlug: 'vermont',
    name: 'Vermont',
    dataFolder: 'vermont',
    fileSuffix: '_vt',
    originationsColumn: 'vermont_originations',
    majorCountySlugs: new Set([
      'chittenden',
      'washington',
      'franklin',
      'windsor',
      'rutland',
      'windham',
      'lamoille',
      'addison',
      'orleans',
      'bennington',
      'caledonia',
      'orange',
    ]),
  },
  ME: {
    code: 'ME',
    stateSlug: 'maine',
    name: 'Maine',
    dataFolder: 'maine',
    fileSuffix: '_me',
    originationsColumn: 'maine_originations',
    majorCountySlugs: new Set([
      'cumberland',
      'york',
      'penobscot',
      'kennebec',
      'androscoggin',
      'oxford',
      'hancock',
      'somerset',
      'aroostook',
      'waldo',
      'knox',
      'lincoln',
      'sagadahoc',
      'washington',
      'franklin',
      'piscataquis',
    ]),
  },
  CT: {
    code: 'CT',
    stateSlug: 'connecticut',
    name: 'Connecticut',
    dataFolder: 'connecticut',
    fileSuffix: '_ct',
    originationsColumn: 'connecticut_originations',
    // HMDA uses Census planning-region county-equivalents (not legacy counties)
    majorCountySlugs: new Set([
      'capitol', // Hartford-area (09110)
      'western-connecticut', // Fairfield-area (09190)
      'south-central-connecticut', // New Haven-area (09170)
      'naugatuck-valley',
      'southeastern-connecticut', // New London-area
      'greater-bridgeport',
      'lower-connecticut-river-valley',
      'northeastern-connecticut',
      'northwest-hills',
    ]),
  },
  NH: {
    code: 'NH',
    stateSlug: 'new-hampshire',
    name: 'New Hampshire',
    dataFolder: 'new-hampshire',
    fileSuffix: '_nh',
    originationsColumn: 'new_hampshire_originations',
    majorCountySlugs: new Set([
      'hillsborough',
      'rockingham',
      'merrimack',
      'strafford',
      'grafton',
      'belknap',
      'carroll',
      'cheshire',
      'sullivan',
      'coos',
    ]),
  },
  VA: {
    code: 'VA',
    stateSlug: 'virginia',
    name: 'Virginia',
    dataFolder: 'virginia',
    fileSuffix: '_va',
    originationsColumn: 'virginia_originations',
    majorCountySlugs: new Set([
      // Wave 1 — NOVA / Richmond / Hampton Roads core
      'fairfax',
      'virginia-beach',
      'loudoun',
      'chesterfield',
      'prince-william',
      'henrico',
      'chesapeake',
      'norfolk',
      'spotsylvania',
      'stafford',
      'richmond',
      'newport-news',
      'hampton',
      'suffolk',
      'arlington',
      'hanover',
      'portsmouth',
      'frederick',
      'alexandria',
      'roanoke',
      'albemarle',
      'james-city',
      'roanoke-city',
      'bedford',
      'augusta',
      'fauquier',
      'rockingham',
      'york',
      'montgomery',
      'lynchburg',
      'louisa',
      'isle-of-wight',
      // Deepen — next volume counties / independent cities (min ~700 orig)
      'orange',
      'franklin',
      'shenandoah',
      'caroline',
      'campbell',
      'warren',
      'gloucester',
      'new-kent',
      'washington',
      'pittsylvania',
      'powhatan',
      'botetourt',
      'fluvanna',
      'petersburg',
      'goochland',
      'king-george',
      'henry',
      'prince-george',
      'pulaski',
      'westmoreland',
      'dinwiddie',
      'manassas',
      'staunton',
      'waynesboro',
      'amherst',
      'danville',
      'king-william',
      'mecklenburg',
      'accomack',
      'hopewell',
      'charlottesville',
      'salem',
      'carroll',
    ]),
  },
  MD: {
    code: 'MD',
    stateSlug: 'maryland',
    name: 'Maryland',
    dataFolder: 'maryland',
    fileSuffix: '_md',
    originationsColumn: 'maryland_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Baltimore–Washington corridor + mid-tier
      'prince-georges',
      'montgomery',
      'baltimore',
      'anne-arundel',
      'baltimore-city',
      'frederick',
      'howard',
      'harford',
      'charles',
      'carroll',
      'washington',
      'st-marys',
      'calvert',
      'cecil',
      'worcester',
      'wicomico',
      'queen-annes',
      'allegany',
      'talbot',
      'dorchester',
      'caroline',
      'garrett',
      // Deepen — remaining meaningful counties (full 24-county panel set)
      'kent',
      'somerset',
    ]),
  },
  DE: {
    code: 'DE',
    stateSlug: 'delaware',
    name: 'Delaware',
    dataFolder: 'delaware',
    fileSuffix: '_de',
    originationsColumn: 'delaware_originations',
    majorCountySlugs: new Set([
      // Full 3-county state
      'new-castle',
      'sussex',
      'kent',
    ]),
  },
  DC: {
    code: 'DC',
    stateSlug: 'district-of-columbia',
    name: 'District of Columbia',
    dataFolder: 'district-of-columbia',
    fileSuffix: '_dc',
    originationsColumn: 'district_of_columbia_originations',
    // Single county-equivalent FIPS 11001 → slug district-of-columbia
    majorCountySlugs: new Set(['district-of-columbia']),
  },
};

export const HMDA_ACTIVE_STATE_CODES: HmdaStateCode[] = [
  'FL',
  'TX',
  'GA',
  'CA',
  'NC',
  'SC',
  'NJ',
  'NY',
  'PA',
  'MA',
  'RI',
  'VT',
  'ME',
  'CT',
  'NH',
  'VA',
  'MD',
  'DE',
  'DC',
];

export function hmdaStateFromSlug(stateSlug: string): HmdaStateConfig | null {
  const s = stateSlug.toLowerCase();
  for (const cfg of Object.values(HMDA_STATE_CONFIGS)) {
    if (cfg.stateSlug === s || cfg.code.toLowerCase() === s) return cfg;
  }
  return null;
}
