/** HMDA product states with cleaned slices under data/hmda/{folder}/ */

export type HmdaStateCode =
  | 'FL'
  | 'TX'
  | 'GA'
  | 'CA'
  | 'NC'
  | 'SC'
  | 'NJ'
  | 'NY'
  | 'PA'
  | 'MA'
  | 'RI'
  | 'VT'
  | 'ME'
  | 'CT'
  | 'NH'
  | 'VA'
  | 'MD'
  | 'DE'
  | 'DC'
  | 'TN'
  | 'IL'
  | 'OH'
  | 'MI'
  | 'IN'
  | 'AZ'
  | 'CO'
  | 'WI'
  | 'MN'
  | 'MO'
  | 'KY'
  | 'UT'
  | 'NV'
  | 'OR'
  | 'WA'
  | 'AL'
  | 'LA'
  | 'IA'
  | 'KS'
  | 'NE'
  | 'AR'
  | 'MS'
  | 'OK';

export type HmdaStateConfig = {
  code: HmdaStateCode;
  /** Directory / URL state slug */
  stateSlug: string;
  name: string;
  /** data/hmda/{dataFolder}/ */
  dataFolder: string;
  /** File name suffixes (e.g. _fl, _va, _md) for summary CSVs */
  fileSuffix: string;
  /** Mapping CSV column for state originations */
  originationsColumn:
    | 'florida_originations'
    | 'texas_originations'
    | 'georgia_originations'
    | 'california_originations'
    | 'north_carolina_originations'
    | 'south_carolina_originations'
    | 'new_jersey_originations'
    | 'new_york_originations'
    | 'pennsylvania_originations'
    | 'massachusetts_originations'
    | 'rhode_island_originations'
    | 'vermont_originations'
    | 'maine_originations'
    | 'connecticut_originations'
    | 'new_hampshire_originations'
    | 'virginia_originations'
    | 'maryland_originations'
    | 'delaware_originations'
    | 'district_of_columbia_originations'
    | 'tennessee_originations'
    | 'illinois_originations'
    | 'ohio_originations'
    | 'michigan_originations'
    | 'indiana_originations'
    | 'arizona_originations'
    | 'colorado_originations'
    | 'wisconsin_originations'
    | 'minnesota_originations'
    | 'missouri_originations'
    | 'kentucky_originations'
    | 'utah_originations'
    | 'nevada_originations'
    | 'oregon_originations'
    | 'washington_originations'
    | 'alabama_originations'
    | 'louisiana_originations'
    | 'iowa_originations'
    | 'kansas_originations'
    | 'nebraska_originations'
    | 'arkansas_originations'
    | 'mississippi_originations'
    | 'oklahoma_originations';
  /** Major county slugs for market intelligence panels */
  majorCountySlugs: ReadonlySet<string>;
};

export const HMDA_STATE_CONFIGS: Record<HmdaStateCode, HmdaStateConfig> = {
  FL: {
    code: 'FL',
    stateSlug: 'florida',
    name: 'Florida',
    dataFolder: 'florida',
    fileSuffix: '_fl',
    originationsColumn: 'florida_originations',
    majorCountySlugs: new Set([
      'miami-dade',
      'broward',
      'palm-beach',
      'hillsborough',
      'orange',
      'duval',
      'pinellas',
      'lee',
      'polk',
      'brevard',
      'volusia',
      'pasco',
      'seminole',
      'sarasota',
      'manatee',
      'collier',
      'osceola',
      'lake',
      'marion',
      'st-johns',
      'st-lucie',
    ]),
  },
  TX: {
    code: 'TX',
    stateSlug: 'texas',
    name: 'Texas',
    dataFolder: 'texas',
    fileSuffix: '_tx',
    originationsColumn: 'texas_originations',
    majorCountySlugs: new Set([
      'harris',
      'dallas',
      'tarrant',
      'bexar',
      'collin',
      'travis',
      'denton',
      'montgomery',
      'fort-bend',
      'williamson',
      'el-paso',
      'bell',
      'hidalgo',
      'brazoria',
      'galveston',
      'hays',
      'lubbock',
      'nueces',
      'cameron',
      'webb',
    ]),
  },
  GA: {
    code: 'GA',
    stateSlug: 'georgia',
    name: 'Georgia',
    dataFolder: 'georgia',
    fileSuffix: '_ga',
    originationsColumn: 'georgia_originations',
    majorCountySlugs: new Set([
      // Core metro Atlanta
      'fulton',
      'gwinnett',
      'cobb',
      'dekalb',
      'cherokee',
      'forsyth',
      'henry',
      'paulding',
      'clayton',
      'douglas',
      'coweta',
      'fayette',
      'bartow',
      'jackson',
      'carroll',
      'barrow',
      'newton',
      'walton',
      'rockdale',
      // Secondary / regional metros
      'chatham',
      'effingham',
      'bryan',
      'glynn',
      'hall',
      'houston',
      'columbia',
      'richmond',
      'muscogee',
      'bibb',
      'lowndes',
      'floyd',
      'clarke',
      'catoosa',
      'whitfield',
      'spalding',
    ]),
  },
  CA: {
    code: 'CA',
    stateSlug: 'california',
    name: 'California',
    dataFolder: 'california',
    fileSuffix: '_ca',
    originationsColumn: 'california_originations',
    majorCountySlugs: new Set([
      // Wave 1 metros
      'los-angeles',
      'san-diego',
      'riverside',
      'orange',
      'san-bernardino',
      'sacramento',
      'santa-clara',
      'alameda',
      'contra-costa',
      'kern',
      'fresno',
      'san-joaquin',
      'ventura',
      'placer',
      'san-mateo',
      'solano',
      'san-francisco',
      'sonoma',
      'stanislaus',
      'tulare',
      'santa-barbara',
      'san-luis-obispo',
      'monterey',
      'marin',
      // Deepen — SoCal spillover, Central Valley, NorCal growth
      'el-dorado',
      'merced',
      'shasta',
      'butte',
      'madera',
      'santa-cruz',
      'yolo',
      'nevada',
      'kings',
      'napa',
      'imperial',
      'humboldt',
    ]),
  },
  NC: {
    code: 'NC',
    stateSlug: 'north-carolina',
    name: 'North Carolina',
    dataFolder: 'north-carolina',
    fileSuffix: '_nc',
    originationsColumn: 'north_carolina_originations',
    majorCountySlugs: new Set([
      'wake',
      'mecklenburg',
      'guilford',
      'forsyth',
      'durham',
      'cumberland',
      'union',
      'brunswick',
      'johnston',
      'cabarrus',
      'onslow',
      'gaston',
      'new-hanover',
      'iredell',
      'buncombe',
      'harnett',
      'catawba',
      'alamance',
      'davidson',
      'rowan',
      'pitt',
      'moore',
      'randolph',
      'henderson',
      'craven',
      'lincoln',
      'orange',
      'wayne',
      'pender',
      'franklin',
    ]),
  },
  SC: {
    code: 'SC',
    stateSlug: 'south-carolina',
    name: 'South Carolina',
    dataFolder: 'south-carolina',
    fileSuffix: '_sc',
    originationsColumn: 'south_carolina_originations',
    majorCountySlugs: new Set([
      // Wave 1
      'horry',
      'greenville',
      'charleston',
      'spartanburg',
      'richland',
      'berkeley',
      'york',
      'lexington',
      'beaufort',
      'dorchester',
      'anderson',
      'aiken',
      'lancaster',
      'sumter',
      'florence',
      'pickens',
      'kershaw',
      'laurens',
      'jasper',
      'georgetown',
      // Deepen
      'oconee',
      'orangeburg',
      'greenwood',
      'cherokee',
      'darlington',
      'chester',
      'colleton',
      'chesterfield',
      'edgefield',
      'newberry',
    ]),
  },
  NJ: {
    code: 'NJ',
    stateSlug: 'new-jersey',
    name: 'New Jersey',
    dataFolder: 'new-jersey',
    fileSuffix: '_nj',
    originationsColumn: 'new_jersey_originations',
    majorCountySlugs: new Set([
      'ocean',
      'bergen',
      'monmouth',
      'middlesex',
      'burlington',
      'camden',
      'essex',
      'morris',
      'union',
      'gloucester',
      'mercer',
      'hudson',
      'passaic',
      'somerset',
      'atlantic',
      'cape-may',
      'sussex',
      'hunterdon',
      // Deepen — full NJ extract
      'cumberland',
      'warren',
      'salem',
    ]),
  },
  NY: {
    code: 'NY',
    stateSlug: 'new-york',
    name: 'New York',
    dataFolder: 'new-york',
    fileSuffix: '_ny',
    originationsColumn: 'new_york_originations',
    majorCountySlugs: new Set([
      // Wave 1 — highest volume + metros
      'suffolk',
      'nassau',
      'erie',
      'monroe',
      'queens',
      'kings',
      'westchester',
      'onondaga',
      'new-york-county', // Manhattan (directory slug; HMDA name is "New York")
      'orange',
      'albany',
      'richmond',
      'dutchess',
      'saratoga',
      'rockland',
      'bronx',
      'niagara',
      'oneida',
      'schenectady',
      'rensselaer',
      'ulster',
      'broome',
      // Deepen — Hudson Valley / downstate spillover
      'putnam',
      'sullivan',
      'columbia',
      'greene',
      // Deepen — Finger Lakes / Central / North Country / Southern Tier
      'ontario',
      'oswego',
      'wayne',
      'jefferson',
      'steuben',
      'chautauqua',
      'chemung',
      'warren',
      'madison',
      'cayuga',
      'tompkins',
      'livingston',
      'herkimer',
      'washington',
      'genesee',
      'st-lawrence',
      'fulton',
      'clinton',
      'cattaraugus',
      'montgomery',
      'tioga',
      'otsego',
    ]),
  },
  PA: {
    code: 'PA',
    stateSlug: 'pennsylvania',
    name: 'Pennsylvania',
    dataFolder: 'pennsylvania',
    fileSuffix: '_pa',
    originationsColumn: 'pennsylvania_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Philly / Pittsburgh / mid-state
      'philadelphia',
      'montgomery',
      'bucks',
      'delaware',
      'chester',
      'allegheny',
      'westmoreland',
      'butler',
      'washington',
      'beaver',
      'lancaster',
      'york',
      'berks',
      'lehigh',
      'northampton',
      'dauphin',
      'cumberland',
      'lebanon',
      'lackawanna',
      'luzerne',
      'erie',
      'monroe',
      'franklin',
      'centre',
      'fayette',
      'adams',
      'cambria',
      'lycoming',
      'schuylkill',
      'mercer',
      // Deepen — next volume / regional
      'blair',
      'pike',
      'carbon',
      'lawrence',
      'northumberland',
      'clearfield',
      'wayne',
      'somerset',
      'crawford',
      'indiana',
      'columbia',
      'armstrong',
      'perry',
      'bedford',
    ]),
  },
  MA: {
    code: 'MA',
    stateSlug: 'massachusetts',
    name: 'Massachusetts',
    dataFolder: 'massachusetts',
    fileSuffix: '_ma',
    originationsColumn: 'massachusetts_originations',
    majorCountySlugs: new Set([
      // Wave 1 — highest volume metros
      'middlesex',
      'worcester',
      'essex',
      'norfolk',
      'plymouth',
      'bristol',
      'suffolk',
      'hampden',
      'barnstable',
      'berkshire',
      'hampshire',
      'franklin',
      // Deepen — remaining counties (full state)
      'dukes',
      'nantucket',
    ]),
  },
  RI: {
    code: 'RI',
    stateSlug: 'rhode-island',
    name: 'Rhode Island',
    dataFolder: 'rhode-island',
    fileSuffix: '_ri',
    originationsColumn: 'rhode_island_originations',
    majorCountySlugs: new Set([
      'providence',
      'kent',
      'washington',
      'newport',
      'bristol',
    ]),
  },
  VT: {
    code: 'VT',
    stateSlug: 'vermont',
    name: 'Vermont',
    dataFolder: 'vermont',
    fileSuffix: '_vt',
    originationsColumn: 'vermont_originations',
    majorCountySlugs: new Set([
      'chittenden',
      'washington',
      'franklin',
      'windsor',
      'rutland',
      'windham',
      'lamoille',
      'addison',
      'orleans',
      'bennington',
      'caledonia',
      'orange',
    ]),
  },
  ME: {
    code: 'ME',
    stateSlug: 'maine',
    name: 'Maine',
    dataFolder: 'maine',
    fileSuffix: '_me',
    originationsColumn: 'maine_originations',
    majorCountySlugs: new Set([
      'cumberland',
      'york',
      'penobscot',
      'kennebec',
      'androscoggin',
      'oxford',
      'hancock',
      'somerset',
      'aroostook',
      'waldo',
      'knox',
      'lincoln',
      'sagadahoc',
      'washington',
      'franklin',
      'piscataquis',
    ]),
  },
  CT: {
    code: 'CT',
    stateSlug: 'connecticut',
    name: 'Connecticut',
    dataFolder: 'connecticut',
    fileSuffix: '_ct',
    originationsColumn: 'connecticut_originations',
    // HMDA uses Census planning-region county-equivalents (not legacy counties)
    majorCountySlugs: new Set([
      'capitol', // Hartford-area (09110)
      'western-connecticut', // Fairfield-area (09190)
      'south-central-connecticut', // New Haven-area (09170)
      'naugatuck-valley',
      'southeastern-connecticut', // New London-area
      'greater-bridgeport',
      'lower-connecticut-river-valley',
      'northeastern-connecticut',
      'northwest-hills',
    ]),
  },
  NH: {
    code: 'NH',
    stateSlug: 'new-hampshire',
    name: 'New Hampshire',
    dataFolder: 'new-hampshire',
    fileSuffix: '_nh',
    originationsColumn: 'new_hampshire_originations',
    majorCountySlugs: new Set([
      'hillsborough',
      'rockingham',
      'merrimack',
      'strafford',
      'grafton',
      'belknap',
      'carroll',
      'cheshire',
      'sullivan',
      'coos',
    ]),
  },
  VA: {
    code: 'VA',
    stateSlug: 'virginia',
    name: 'Virginia',
    dataFolder: 'virginia',
    fileSuffix: '_va',
    originationsColumn: 'virginia_originations',
    majorCountySlugs: new Set([
      // Wave 1 — NOVA / Richmond / Hampton Roads core
      'fairfax',
      'virginia-beach',
      'loudoun',
      'chesterfield',
      'prince-william',
      'henrico',
      'chesapeake',
      'norfolk',
      'spotsylvania',
      'stafford',
      'richmond',
      'newport-news',
      'hampton',
      'suffolk',
      'arlington',
      'hanover',
      'portsmouth',
      'frederick',
      'alexandria',
      'roanoke',
      'albemarle',
      'james-city',
      'roanoke-city',
      'bedford',
      'augusta',
      'fauquier',
      'rockingham',
      'york',
      'montgomery',
      'lynchburg',
      'louisa',
      'isle-of-wight',
      // Deepen — next volume counties / independent cities (min ~700 orig)
      'orange',
      'franklin',
      'shenandoah',
      'caroline',
      'campbell',
      'warren',
      'gloucester',
      'new-kent',
      'washington',
      'pittsylvania',
      'powhatan',
      'botetourt',
      'fluvanna',
      'petersburg',
      'goochland',
      'king-george',
      'henry',
      'prince-george',
      'pulaski',
      'westmoreland',
      'dinwiddie',
      'manassas',
      'staunton',
      'waynesboro',
      'amherst',
      'danville',
      'king-william',
      'mecklenburg',
      'accomack',
      'hopewell',
      'charlottesville',
      'salem',
      'carroll',
    ]),
  },
  MD: {
    code: 'MD',
    stateSlug: 'maryland',
    name: 'Maryland',
    dataFolder: 'maryland',
    fileSuffix: '_md',
    originationsColumn: 'maryland_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Baltimore–Washington corridor + mid-tier
      'prince-georges',
      'montgomery',
      'baltimore',
      'anne-arundel',
      'baltimore-city',
      'frederick',
      'howard',
      'harford',
      'charles',
      'carroll',
      'washington',
      'st-marys',
      'calvert',
      'cecil',
      'worcester',
      'wicomico',
      'queen-annes',
      'allegany',
      'talbot',
      'dorchester',
      'caroline',
      'garrett',
      // Deepen — remaining meaningful counties (full 24-county panel set)
      'kent',
      'somerset',
    ]),
  },
  DE: {
    code: 'DE',
    stateSlug: 'delaware',
    name: 'Delaware',
    dataFolder: 'delaware',
    fileSuffix: '_de',
    originationsColumn: 'delaware_originations',
    majorCountySlugs: new Set([
      // Full 3-county state
      'new-castle',
      'sussex',
      'kent',
    ]),
  },
  DC: {
    code: 'DC',
    stateSlug: 'district-of-columbia',
    name: 'District of Columbia',
    dataFolder: 'district-of-columbia',
    fileSuffix: '_dc',
    originationsColumn: 'district_of_columbia_originations',
    // Single county-equivalent FIPS 11001 → slug district-of-columbia
    majorCountySlugs: new Set(['district-of-columbia']),
  },
  TN: {
    code: 'TN',
    stateSlug: 'tennessee',
    name: 'Tennessee',
    dataFolder: 'tennessee',
    fileSuffix: '_tn',
    originationsColumn: 'tennessee_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Nashville / Memphis / Knoxville / Chattanooga core
      'davidson',
      'shelby',
      'knox',
      'hamilton',
      'rutherford',
      'montgomery',
      'williamson',
      'sumner',
      'wilson',
      // Next volume / regional metros
      'sullivan',
      'blount',
      'maury',
      'washington',
      'sevier',
      'bradley',
      'robertson',
      'madison',
      'anderson',
      'loudon',
      'putnam',
    ]),
  },
  IL: {
    code: 'IL',
    stateSlug: 'illinois',
    name: 'Illinois',
    dataFolder: 'illinois',
    fileSuffix: '_il',
    originationsColumn: 'illinois_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Chicago metro + secondary metros
      'cook',
      'dupage',
      'will',
      'lake',
      'kane',
      'mchenry',
      'kendall',
      'madison',
      'winnebago',
      'st-clair',
      'sangamon',
      'peoria',
      'mclean',
      'champaign',
      'tazewell',
      'rock-island',
      'dekalb',
      'kankakee',
      'lasalle',
      'macon',
      // Deepen — next volume / collar / downstate
      'grundy',
      'williamson',
      'vermilion',
      'boone',
      'ogle',
      'henry',
      'woodford',
      'monroe',
      'macoupin',
      'whiteside',
      'knox',
      'adams',
    ]),
  },
  OH: {
    code: 'OH',
    stateSlug: 'ohio',
    name: 'Ohio',
    dataFolder: 'ohio',
    fileSuffix: '_oh',
    originationsColumn: 'ohio_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Columbus / Cleveland / Cincinnati / Dayton / Akron
      'franklin',
      'cuyahoga',
      'hamilton',
      'summit',
      'montgomery',
      'butler',
      'stark',
      'lucas',
      'lorain',
      'warren',
      'delaware',
      'lake',
      'clermont',
      'mahoning',
      'licking',
      'medina',
      'fairfield',
      'trumbull',
      'greene',
      'portage',
      // Deepen — next volume / regional
      'clark',
      'wood',
      'miami',
      'richland',
      'union',
      'geauga',
      'allen',
      'wayne',
      'muskingum',
      'ashtabula',
      'columbiana',
      'pickaway',
      'hancock',
      'knox',
      'erie',
      'ross',
      'marion',
      'tuscarawas',
      'madison',
      'sandusky',
    ]),
  },
  MI: {
    code: 'MI',
    stateSlug: 'michigan',
    name: 'Michigan',
    dataFolder: 'michigan',
    fileSuffix: '_mi',
    originationsColumn: 'michigan_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Detroit metro + Grand Rapids / West MI + secondary
      'wayne',
      'oakland',
      'macomb',
      'kent',
      'genesee',
      'ottawa',
      'washtenaw',
      'kalamazoo',
      'livingston',
      'ingham',
      'muskegon',
      'st-clair',
      'monroe',
      'berrien',
      'jackson',
      'saginaw',
      'allegan',
      'calhoun',
      'grand-traverse',
      'eaton',
      // Deepen — next volume / regional
      'lenawee',
      'lapeer',
      'bay',
      'van-buren',
      'clinton',
      'barry',
      'midland',
      'shiawassee',
      'ionia',
      'st-joseph',
      'cass',
      'isabella',
      'mecosta',
      'montcalm',
      'newaygo',
    ]),
  },
  IN: {
    code: 'IN',
    stateSlug: 'indiana',
    name: 'Indiana',
    dataFolder: 'indiana',
    fileSuffix: '_in',
    originationsColumn: 'indiana_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Indianapolis metro + NW IN / Fort Wayne / secondary
      'marion',
      'hamilton',
      'lake',
      'allen',
      'st-joseph',
      'hendricks',
      'johnson',
      'elkhart',
      'porter',
      'vanderburgh',
      'tippecanoe',
      'clark',
      'madison',
      'hancock',
      'boone',
      'monroe',
      'delaware',
      'laporte',
      'morgan',
      'floyd',
      // Deepen — next volume / regional
      'howard',
      'kosciusko',
      'bartholomew',
      'vigo',
      'warrick',
      'dearborn',
      'wayne',
      'dekalb',
      'shelby',
      'grant',
      'noble',
      'lawrence',
      'harrison',
      'henry',
      'marshall',
    ]),
  },
  AZ: {
    code: 'AZ',
    stateSlug: 'arizona',
    name: 'Arizona',
    dataFolder: 'arizona',
    fileSuffix: '_az',
    originationsColumn: 'arizona_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Phoenix / Tucson / growth corridors + secondary volume
      'maricopa',
      'pima',
      'pinal',
      'yavapai',
      'mohave',
      'yuma',
      'coconino',
      'cochise',
      'navajo',
      'gila',
      'santa-cruz',
      'graham',
      // Deepen — remaining AZ counties with HMDA volume
      'apache',
      'la-paz',
      'greenlee',
    ]),
  },
  CO: {
    code: 'CO',
    stateSlug: 'colorado',
    name: 'Colorado',
    dataFolder: 'colorado',
    fileSuffix: '_co',
    originationsColumn: 'colorado_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Front Range metros + mountain / western secondary
      'el-paso',
      'jefferson',
      'arapahoe',
      'denver',
      'adams',
      'douglas',
      'weld',
      'larimer',
      'boulder',
      'mesa',
      'pueblo',
      'broomfield',
      'garfield',
      'eagle',
      'summit',
      'la-plata',
      'elbert',
      'fremont',
      'teller',
      'montrose',
      // Deepen — next volume mountain / western / plains
      'grand',
      'park',
      'delta',
      'routt',
      'chaffee',
      'morgan',
      'archuleta',
      'gunnison',
      'pitkin',
      'montezuma',
    ]),
  },
  WI: {
    code: 'WI',
    stateSlug: 'wisconsin',
    name: 'Wisconsin',
    dataFolder: 'wisconsin',
    fileSuffix: '_wi',
    originationsColumn: 'wisconsin_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Milwaukee / Madison / Fox Valley / secondary volume
      'milwaukee',
      'dane',
      'waukesha',
      'brown',
      'outagamie',
      'racine',
      'rock',
      'winnebago',
      'kenosha',
      'washington',
      'marathon',
      'sheboygan',
      'la-crosse',
      'walworth',
      'st-croix',
      'fond-du-lac',
      'ozaukee',
      'eau-claire',
      'dodge',
      'manitowoc',
      // Deepen — next volume / regional
      'jefferson',
      'columbia',
      'sauk',
      'calumet',
      'chippewa',
      'wood',
      'waupaca',
      'polk',
      'portage',
      'oconto',
      'barron',
      'marinette',
      'shawano',
      'douglas',
      'oneida',
      'monroe',
      'door',
      'pierce',
      'green',
      'dunn',
    ]),
  },
  MN: {
    code: 'MN',
    stateSlug: 'minnesota',
    name: 'Minnesota',
    dataFolder: 'minnesota',
    fileSuffix: '_mn',
    originationsColumn: 'minnesota_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Twin Cities core + Duluth / Rochester / secondary
      'hennepin',
      'dakota',
      'ramsey',
      'anoka',
      'washington',
      'wright',
      'st-louis',
      'scott',
      'olmsted',
      'stearns',
      'carver',
      'sherburne',
      'crow-wing',
      'chisago',
      'clay',
      'rice',
      'blue-earth',
      'otter-tail',
      'isanti',
      'winona',
      // Deepen — next volume / regional
      'goodhue',
      'itasca',
      'carlton',
      'benton',
      'mille-lacs',
      'douglas',
      'mcleod',
      'cass',
      'becker',
      'mower',
      'pine',
      'kandiyohi',
      'steele',
      'le-sueur',
      'morrison',
      'nicollet',
    ]),
  },
  MO: {
    code: 'MO',
    stateSlug: 'missouri',
    name: 'Missouri',
    dataFolder: 'missouri',
    fileSuffix: '_mo',
    originationsColumn: 'missouri_originations',
    majorCountySlugs: new Set([
      // Wave 1 — St. Louis / Kansas City / Springfield / mid-state
      'st-louis',
      'jackson',
      'st-charles',
      'greene',
      'clay',
      'jefferson',
      'st-louis-city',
      'boone',
      'cass',
      'jasper',
      'christian',
      'platte',
      'franklin',
      'cole',
      'buchanan',
      'cape-girardeau',
      'lincoln',
      'camden',
    ]),
  },
  KY: {
    code: 'KY',
    stateSlug: 'kentucky',
    name: 'Kentucky',
    dataFolder: 'kentucky',
    fileSuffix: '_ky',
    originationsColumn: 'kentucky_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Louisville / Lexington / NKY / secondary volume
      'jefferson',
      'fayette',
      'kenton',
      'boone',
      'warren',
      'hardin',
      'campbell',
      'bullitt',
      'madison',
      'daviess',
      'oldham',
      'scott',
      'jessamine',
      'shelby',
      'christian',
      'mccracken',
      'franklin',
      'nelson',
    ]),
  },
  UT: {
    code: 'UT',
    stateSlug: 'utah',
    name: 'Utah',
    dataFolder: 'utah',
    fileSuffix: '_ut',
    originationsColumn: 'utah_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Wasatch Front + secondary high-volume markets
      'salt-lake',
      'utah',
      'davis',
      'weber',
      'washington',
      'cache',
      'tooele',
      'iron',
      'box-elder',
      'wasatch',
      'summit',
      'uintah',
      'sanpete',
      'sevier',
      'carbon',
      'morgan',
    ]),
  },
  NV: {
    code: 'NV',
    stateSlug: 'nevada',
    name: 'Nevada',
    dataFolder: 'nevada',
    fileSuffix: '_nv',
    originationsColumn: 'nevada_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Las Vegas / Reno + secondary high-volume markets
      'clark',
      'washoe',
      'lyon',
      'nye',
      'douglas',
      'elko',
      'carson-city',
      'churchill',
      'humboldt',
    ]),
  },
  OR: {
    code: 'OR',
    stateSlug: 'oregon',
    name: 'Oregon',
    dataFolder: 'oregon',
    fileSuffix: '_or',
    originationsColumn: 'oregon_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Portland metro / Willamette Valley / secondary volume
      'multnomah',
      'washington',
      'clackamas',
      'lane',
      'marion',
      'deschutes',
      'jackson',
      'linn',
      'yamhill',
      'douglas',
      'polk',
      'josephine',
      'umatilla',
      'klamath',
      'benton',
      'coos',
      'lincoln',
      'columbia',
    ]),
  },
  WA: {
    code: 'WA',
    stateSlug: 'washington',
    name: 'Washington',
    dataFolder: 'washington',
    fileSuffix: '_wa',
    originationsColumn: 'washington_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Puget Sound / Spokane / southwest WA / secondary volume
      'king',
      'pierce',
      'snohomish',
      'spokane',
      'clark',
      'thurston',
      'kitsap',
      'whatcom',
      'benton',
      'yakima',
      'cowlitz',
      'skagit',
      'island',
      'lewis',
      'mason',
      'grant',
      'grays-harbor',
      'franklin',
    ]),
  },
  AL: {
    code: 'AL',
    stateSlug: 'alabama',
    name: 'Alabama',
    dataFolder: 'alabama',
    fileSuffix: '_al',
    originationsColumn: 'alabama_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Birmingham / Huntsville / Mobile / coastal + secondary volume
      'jefferson',
      'madison',
      'baldwin',
      'mobile',
      'shelby',
      'lee',
      'tuscaloosa',
      'montgomery',
      'limestone',
      'morgan',
      'st-clair',
      'houston',
      'elmore',
      'lauderdale',
      'marshall',
      'calhoun',
      'etowah',
      'cullman',
      'autauga',
      'coffee',
    ]),
  },
  LA: {
    code: 'LA',
    stateSlug: 'louisiana',
    name: 'Louisiana',
    dataFolder: 'louisiana',
    fileSuffix: '_la',
    originationsColumn: 'louisiana_originations',
    majorCountySlugs: new Set([
      // Wave 1 — major parishes (URL slugs use county naming convention)
      'east-baton-rouge',
      'st-tammany',
      'jefferson',
      'lafayette',
      'orleans',
      'caddo',
      'livingston',
      'calcasieu',
      'ascension',
      'bossier',
      'ouachita',
      'tangipahoa',
      'rapides',
      'terrebonne',
      'lafourche',
      'st-landry',
      'st-charles',
      'vermilion',
    ]),
  },
  IA: {
    code: 'IA',
    stateSlug: 'iowa',
    name: 'Iowa',
    dataFolder: 'iowa',
    fileSuffix: '_ia',
    originationsColumn: 'iowa_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Des Moines / Cedar Rapids / Quad Cities / secondary volume
      'polk',
      'linn',
      'scott',
      'johnson',
      'black-hawk',
      'woodbury',
      'dallas',
      'dubuque',
      'pottawattamie',
      'warren',
      'story',
      'jasper',
      'clinton',
      'muscatine',
      'bremer',
    ]),
  },
  KS: {
    code: 'KS',
    stateSlug: 'kansas',
    name: 'Kansas',
    dataFolder: 'kansas',
    fileSuffix: '_ks',
    originationsColumn: 'kansas_originations',
    majorCountySlugs: new Set([
      // Wave 1 — KC metro / Wichita / Topeka / secondary volume
      'johnson',
      'sedgwick',
      'shawnee',
      'douglas',
      'wyandotte',
      'leavenworth',
      'butler',
      'reno',
      'riley',
      'miami',
      'geary',
      'harvey',
      'saline',
      'pottawatomie',
    ]),
  },
  NE: {
    code: 'NE',
    stateSlug: 'nebraska',
    name: 'Nebraska',
    dataFolder: 'nebraska',
    fileSuffix: '_ne',
    originationsColumn: 'nebraska_originations',
    majorCountySlugs: new Set([
      // Wave 1 — Omaha / Lincoln / secondary volume
      'douglas',
      'lancaster',
      'sarpy',
      'hall',
      'buffalo',
      'dodge',
      'cass',
      'lincoln',
      'platte',
      'saunders',
      'washington',
      'madison',
      'adams',
      'scotts-bluff',
    ]),
  },
  AR: {
    code: 'AR',
    stateSlug: 'arkansas',
    name: 'Arkansas',
    dataFolder: 'arkansas',
    fileSuffix: '_ar',
    originationsColumn: 'arkansas_originations',
    majorCountySlugs: new Set([
      // Wave 1 — NWA / Little Rock / secondary volume
      'benton',
      'pulaski',
      'washington',
      'saline',
      'faulkner',
      'craighead',
      'sebastian',
      'garland',
      'lonoke',
      'white',
      'crawford',
      'pope',
      'baxter',
      'greene',
      'boone',
      'jefferson',
      'crittenden',
      'independence',
    ]),
  },
  MS: {
    code: 'MS',
    stateSlug: 'mississippi',
    name: 'Mississippi',
    dataFolder: 'mississippi',
    fileSuffix: '_ms',
    originationsColumn: 'mississippi_originations',
    majorCountySlugs: new Set([
      // Wave 1 — DeSoto / Coast / Jackson metro / secondary volume
      'desoto',
      'harrison',
      'rankin',
      'hinds',
      'jackson',
      'madison',
      'lee',
      'lafayette',
      'lamar',
      'forrest',
      'jones',
      'hancock',
      'pearl-river',
      'lowndes',
      'lauderdale',
      'marshall',
      'oktibbeha',
      'warren',
    ]),
  },
  OK: {
    code: 'OK',
    stateSlug: 'oklahoma',
    name: 'Oklahoma',
    dataFolder: 'oklahoma',
    fileSuffix: '_ok',
    originationsColumn: 'oklahoma_originations',
    majorCountySlugs: new Set([
      // Wave 1 — OKC / Tulsa / secondary volume
      'oklahoma',
      'tulsa',
      'cleveland',
      'canadian',
      'wagoner',
      'comanche',
      'rogers',
      'logan',
      'pottawatomie',
      'creek',
      'grady',
      'mcclain',
      'payne',
      'muskogee',
      'garfield',
      'washington',
      'bryan',
      'carter',
    ]),
  },
};

export const HMDA_ACTIVE_STATE_CODES: HmdaStateCode[] = [
  'FL',
  'TX',
  'GA',
  'CA',
  'NC',
  'SC',
  'NJ',
  'NY',
  'PA',
  'MA',
  'RI',
  'VT',
  'ME',
  'CT',
  'NH',
  'VA',
  'MD',
  'DE',
  'DC',
  'TN',
  'IL',
  'OH',
  'MI',
  'IN',
  'AZ',
  'CO',
  'WI',
  'MN',
  'MO',
  'KY',
  'UT',
  'NV',
  'OR',
  'WA',
  'AL',
  'LA',
  'IA',
  'KS',
  'NE',
  'AR',
  'MS',
  'OK',
];

export function hmdaStateFromSlug(stateSlug: string): HmdaStateConfig | null {
  const s = stateSlug.toLowerCase();
  for (const cfg of Object.values(HMDA_STATE_CONFIGS)) {
    if (cfg.stateSlug === s || cfg.code.toLowerCase() === s) return cfg;
  }
  return null;
}
